### ISSUE TITLE
[rush] Allow `init` command to work with existing folders that are not overwritten

### ISSUE THREAD

**Issue by KevinGrandon** [microsoft/rushstack#1073]
Currently rush is not very user-friendly for folks migrating from an existing monorepo to one managed by rush. I believe there are migration tools that rush could provide to make this a lot easier, but for the time being, allowing the `init` command to work with an existing repo would be ideal.

Currently I get the output like:
```
rush init

Rush Multi-Project Build Tool 5.5.4 (unmanaged) - https://rushjs.io

Starting "rush init"

ERROR: Found a subdirectory: "<some local dir name>"

The "rush init" command must be run in a new folder with no projects added yet.
```

**Comment by octogonz** [comment]
Did you try `rush init --overwrite-existing`?

**Comment by octogonz** [comment]
People sometimes ask for a feature that would suck up all the existing monorepo projects into rush.json.

**Comment by KevinGrandon** [comment]
I did not, but I don't think I should have to do that, I only had a subfolder which did not match any generated rush files. IMO rush should ignore folders during the init process. 

Potentially the error message can include something about using `--overwrite-existing` as well.

**Comment by KevinTCoughlin** [comment]
> Potentially the error message can include something about using `--overwrite-existing` as well.

I think this would be useful with the appropriate warning text. I also had no idea that flag existed when trying to add rush to existing projects via `rush init`.

**Comment by octogonz** [comment]
Sounds good to me.

**Comment by KevinGrandon** [comment]
I think a warning message is a good start, but really it should not warn about directories that it is not going to overwrite.

**Comment by octogonz** [comment]
> I think a warning message is a good start, but really it should not warn about directories that it is not going to overwrite.

When we originally designed it, the concern was to protect against accidents like this:

1. I install Rush
2. I type `mkdir my-repo`
3. I run `rush init` which accidentally dumps a ton of files into my home directory, because I forgot to do `cd my-repo`

Whereas if you are in an already existing monorepo folder, `--overwrite-existing` is pretty safe, because whatever gets blown away is most likely already tracked by Git, and the diff is often very interesting.  For example, when upgrading Rush, you can use `--overwrite-existing` to update the config templates, and then revert parts of the Git diff to bring back your customizations.

**Comment by KevinGrandon** [comment]
I appreciate the thought process that went into safeguarding users from their own mistakes. I would argue that this would probably apply to more junior engineers, and at the same time hurt them from easily being able to consume the tool.

For me, as a newcomer to rush I was very frustrated that it was difficult to get started as I could not easily implement this in an existing repository. I had to delete folders and then restore them later.

I think that a better thing to prevent the specific case of people forgetting to `cd my-repo`, would be to analyze the git information for the current folder, then possibly warn them if they are `init`ing into a non-repository.

**Comment by octogonz** [comment]
That sounds fine to me. I'm happy with any design that makes the overall experience more intuitive.

**Comment by octogonz** [comment]
Someone should create a PR and then we'll have something more concrete to agree on.

**Comment by charlex** [comment]
Just an idea for this:

Could Rust generate a manifest of the files/folders it will create? Could this manifest then be used to check if any files will be replaced? Then if there are replacements, warn the user and exit. Or warn the user and provide some type of resolution/reconcilation.

**Comment by CoderK** [comment]
I had the same issue like this during my tutorial.

```
hunmin.kim@MB-hunminkim  ~/Workspace/CoderK/rush-example   master  rush init

Rush version 5.26.0 is not currently installed. Installing...
Trying to acquire lock for rush-5.26.0
Deleting old files from /Users/hunmin.kim/.rush/node-v12.13.0/rush-5.26.0
Copying /Users/hunmin.kim/Workspace/CoderK/rush-example/common/config/rush/.npmrc --> /Users/hunmin.kim/.rush/node-v12.13.0/rush-5.26.0/.npmrc

Running "npm install" in /Users/hunmin.kim/.rush/node-v12.13.0/rush-5.26.0
Successfully installed Rush version 5.26.0 in /Users/hunmin.kim/.rush/node-v12.13.0/rush-5.26.0.

Rush Multi-Project Build Tool 5.26.0 - https://rushjs.io
Node.js version is 12.13.0 (LTS)


Starting "rush init"

ERROR: Found an existing configuration in: /Users/hunmin.kim/Workspace/CoderK/rush-example/rush.json

The "rush init" command must be run in a new folder without an existing Rush configuration.
```

At first, I cloned rush-example repository on my local and then tried to initiate rush project.

It would have been nice if the document instructed a developer to use rush init --overwrite-existing command instead of rush init.

**Comment by octogonz** [comment]
This is essentially the same discussion as https://github.com/microsoft/rushstack/issues/1475 which proposed the `myrush` command.  

#1073 has an additional detail, of asking for the `rush init` error message to be more intuitive, but we can tackle the problem in the existing PR https://github.com/microsoft/rushstack/pull/1771
