### ISSUE TITLE
[rush] Incremental build is not working for partial success builds.

### ISSUE THREAD

**Issue by dzearing** [microsoft/rushstack#1103]
Run `rush build`
A few packages succeed
A package fails and stops the build.

Expected:
Running `rush build` again skips the packages that succeeded

Resulted:
Rebuilds everything. Packages seem to only be skipped when the full build passes.

I am guessing that the package-deps.json files are only written after a successful full build. Was looking for the culprit in the code here but things have changed a lot since I've last looked.

**Comment by nickpape-msft** [comment]
Is one of your builds not doing anything (i.e. an empty string in package.json). I think that the package-deps doesn’t get written in that case, which would invalidate all the downstream dependencies.

**Comment by octogonz** [comment]
> I think that the package-deps doesn’t get written in that case, which would invalidate all the downstream dependencies.

@nickpape-msft The **web-build-tools** repo has a project [rush-stack-compiler-shared](https://github.com/Microsoft/web-build-tools/blob/master/stack/rush-stack-compiler-shared/package.json) with an empty `"build"` script.  When I run `rush rebuild`, a **package-deps.json** file does NOT get written for that project.  However afterwards `rush build` completes instantly without rebuilding anything as expected.  So at least for this case the empty build script scenario is working correctly.

@dzearing Next I tried introducing an error for **api-documenter** which is fairly far down the build graph (49/51).  I ran `rush build` twice, and each time it skipped the first 48 projects as expected.  Then I reverted the change and ran `rush build` again, which rebuilt 3 things.  Thereafter `rush build` completed as expected without doing anything.

So... I'm not able to repro this issue, nor does it seem to be explained by an empty build script.  @dzearing could you provide a repro?

**Comment by elliot-nelson** [comment]
Closing due to no repro, please feel free to open a new ticket if this is still an issue.

(As an aside: the _symptom_ is exactly what would happen if Rush cannot find git. On recent Rush versions, running with `rush --debug build --verbose` will flush that out if it's the case.)
