### ISSUE TITLE
[load-theme-styles] Load theme styles package contains only commonjs output

### ISSUE THREAD

**Issue by christiango** [microsoft/rushstack#1292]
We'd love if this package included ESM in addition to (or instead of) the commonjs output so that it is eligible for webpack optimizations like tree shaking or module concatenation

**Comment by octogonz** [comment]
@iclanton @dzearing FYI

**Comment by Silic0nS0ldier** [comment]
I noticed that there appears to already be ESM (and AMD) in the published package. Adding a `module` entrypoint to `package.json` would address this, as is already done in https://developer.microsoft.com/en-us/fabric#/ web modules.
