### ISSUE TITLE
[rush] Provide an "install-run-rushx.js" script similar to "install-run-rush.js"

### ISSUE THREAD

**Issue by poelstra** [microsoft/rushstack#1311]
It can be useful to run `rushx start something` in a CI environment.

There already is `common/scripts/install-run-rush.js`, but there's e.g. no `rush run` as an alias for `rushx` that would allow using rush to e.g. prepare bin paths.

Suggestion from @octogonz was to create `common/scripts/install-run-rushx.js`.

**Comment by octogonz** [comment]
This should be pretty easy to implement.  I think it's a good idea.

@iclanton maybe you could give it to someone as an onboarding exercise. :-)

**Comment by bsiegel** [comment]
Completed in #1440, this issue can be closed 🎉

**Comment by apostolisms** [comment]
Closing since this completed [here](https://github.com/microsoft/rushstack/pull/1440)
