### ISSUE TITLE
[rush] rush version bump types inconsistent in code, starter files, and docs

### ISSUE THREAD

**Issue by adrw** [microsoft/rushstack#1335]
In the starter files for `common/config/version-policies.json` and [docs](https://rushjs.io/pages/configs/version_policies_json/), allowed bump types are: `"prerelease", "release", "minor", "patch", "major"`.

https://github.com/microsoft/web-build-tools/blob/9406ac71d40afa5807975a0d7dbd0315f9f84501/apps/rush-lib/assets/rush-init/common/config/rush/version-policies.json#L39-L46

In the code, `release` is not a valid bump type and `preminor` is included: 

https://github.com/microsoft/web-build-tools/blob/9406ac71d40afa5807975a0d7dbd0315f9f84501/apps/rush-lib/src/api/VersionPolicy.ts#L24-L37

Testing which options are correct and unified version bump types across code, starter files, and docs will bring clarity.

**Comment by octogonz** [comment]
My understanding is that a given release type won't work correctly unless it's defined in the `BumpType` enum.

And it cannot be specified in the config file at all, unless it appears in [version-policies.schema.json](https://github.com/microsoft/web-build-tools/blob/d5c1756c805f2f9a231fc648c9d50ae142c7abe9/apps/rush-lib/src/schemas/version-policies.schema.json#L81), which defines these options:
```json
        "nextBump": {
          "description": "Type of next version bump",
          "enum": ["prerelease", "release", "minor", "patch", "major"]
        },
```

If we consider the intersection of those two sets, then:
- `release` can be specified but probably doesn't work right
- `preminor` cannot be specified, although it is in the enum (and even has a unit test)

The option names also get printed for help output in a couple places in [VersionAction.ts](https://github.com/microsoft/web-build-tools/blob/0474edd2335a12983b5cb451b5d6e043101a6a18/apps/rush-lib/src/cli/actions/VersionAction.ts#L85).  That should be made consistent with the other noted places as well.

I suppose the simplest and safest solution would be to remove both `release` and `preminor` from the code base, and then make everything else consistent.  Some justification for removal:  In the usage I'm familiar with, `prerelease` assumes that the minor/major version bump was already manually assigned when the branch was created, thus `preminor` wouldn't be useful.  Similarly, the `minor`/`major` version options are types of "releases", so I'm not sure what `release` would do differently.

If you'd like to create the PR, that would be appreciated.  :-)

**Comment by alber70g** [comment]
FYI The "release" is still shown in the comments in `version-policies.json` docs https://rushjs.io/pages/configs/version-policies_json/#:~:text=nextBump%22%3A%20%22prerelease
