### ISSUE TITLE
[gulp-core-build-serve] Option to launch custom browser

### ISSUE THREAD

**Issue by timdw** [microsoft/rushstack#1338]
I recently started using the SharePoint Framework and ran into a small annoyance: the gulp serve task launches the OS default browser with no option to change it. I figured out that you can add something like this in the gulpfile:

```typescript
...

const gulpOpen = require('gulp-open');

 // Create a subtask to launch a browser session using gulp-open
 let launchBrowserSubTask = build.subTask('launch-browser-subtask', function(gulp, buildOptions, done) {
   // Check if the serve task was invoked by checking args, hope there's a better way to do this!
   if (buildOptions.args._[0] === 'serve') {
     return gulp.src('')
       .pipe(gulpOpen({
         app: 'chrome',
         uri: "https://localhost:5432/workbench"
       }));
   }
   done();
 })
 // add the subtask as a post build task
 build.rig.addPostBuildTask(launchBrowserSubTask);

 build.initialize(gulp);
 ```

 but I think adding the option to the serve.json file would be better, including a no browser option too while we're at it. This means changing the serve.schema.json and unfortunately also spfx-serve.schema.json which is not open as far as I can see. Is it possible to get this updated?
I have made the changes locally, should I create a draft pull request for it?

**Comment by octogonz** [comment]
> I have made the changes locally, should I create a draft pull request for it?

Sure.  This seems like a useful feature.  

You're right that a corresponding change would be needed in **spfx-serve.schema.json**, but I believe the **gulp-core-build** settings are simply passed through, so it would be a very trivial change.

**Comment by iclanton** [comment]
We'll need to make a change for the SPFx release that this ships in, but that shouldn't be too complicated.

**Comment by timdw** [comment]
The schemas are in [Microsoft/json-schemas](https://github.com/microsoft/json-schemas) too. You probably know that though!

**Comment by octogonz** [comment]
Those are the public copies for the website that serves the `"$schema"` URL. The master copy is shipped as part of the NPM package (so you don't need an internet connection to use it).

**Comment by iclanton** [comment]
GCB is no longer under active development.
