### ISSUE TITLE
[rush] "Rush add" is not working for Yarn

### ISSUE THREAD

**Issue by bruk1977** [microsoft/rushstack#1343]
When I'm using the following command with Yarn package manager

rush add -p react-dom@16.8.0 -m

I"m getting the following error:

ERROR: The Yarn package manager is not currently supported by the "rush add" command.

Updating lots of packages manually is a pain... really appreciate if you make 'rush add' working for 'yarn' as it's working for 'pnpm'

**Comment by iclanton** [comment]
I suspect this won't be too difficult to fix.

**Comment by bruk1977** [comment]
@iclanton wondering if team has any timeline when this could be fixed?

**Comment by octogonz** [comment]
Looks like there's only two operations we need to implement:

- `npm view <packageName> versions --json` from [this code](https://github.com/microsoft/web-build-tools/blob/9ca224456be192286190d8bee25fe33088b61190/apps/rush-lib/src/logic/PackageJsonUpdater.ts#L313)
- `npm view <packageName>@latest version` from [this code](https://github.com/microsoft/web-build-tools/blob/9ca224456be192286190d8bee25fe33088b61190/apps/rush-lib/src/logic/PackageJsonUpdater.ts#L342)

@bruk1977 If you could figure out the Yarn CLI equivalents, that's probably all we need to complete the implementation.

**Comment by tbrannam** [comment]
I think these are closest 

yarn info react versions
yarn info react dist-tags.latest

**Comment by bruk1977** [comment]
@octogonz any progress on this one using @tbrannam suggestions?

**Comment by ron4ex** [comment]
I took a shot at this #1585. I'm not a regular open-source contributor. In fact, this is my very first PR on an OSS project. So let me know if something needs to be done differently.

**Comment by octogonz** [comment]
This was fixed in #1585, and the fix was published with Rush 5.16.0
