### ISSUE TITLE
[rush] 'rush change' bulk update

### ISSUE THREAD

**Issue by bruk1977** [microsoft/rushstack#1383]
It would be nice 'rush change' supported bulk update. 

For example, when we update the version of an underlying package that is used by 100 other packages, using the interactive window of 'rush change' to update all the packages that depend on the underlying package is very time consuming.

Proposal:

rush change --bulk --message 'Update utility package to add feature x' --version patch

**Comment by octogonz** [comment]
Good idea! I would use this.

**Comment by iclanton** [comment]
I took a stab at this: https://github.com/microsoft/web-build-tools/pull/1389

**Comment by iclanton** [comment]
This was released a few months ago in Rush 5.14.0. Closing this issue.
