### ISSUE TITLE
[rush] Add option to run bulk command in only specified project

### ISSUE THREAD

**Issue by mikeharder** [microsoft/rushstack#1399]
- [x] Feature

Currently, Rush has two options for running bulk commands:

```
  -t PROJECT1, --to PROJECT1
                        Run command in the specified project and all of its
                        dependencies
  -f PROJECT2, --from PROJECT2
                        Run command in all projects that directly or
                        indirectly depend on the specified project
```

These cover most of our needs, but sometimes we want to run a command in **only** a single project, and neither its dependencies nor projects which depend on it.  It would be great if Rush could add an option for this, like:

```
  --only PROJECT1
                        Run command in only the specified project
```

It might be better to use a different name for the parameter to avoid confusion with the existing option:

```
  -o, --changed-projects-only
                        If specified, the incremental build will only rebuild
                        projects that have changed, but not any projects that
                        directly or indirectly depend on the changed package.
```

**Comment by apostolisms** [comment]
@mikeharder Do you envision this to be an option primarily for rush build or all commands? Can you give an example use case ?
Thanks

**Comment by mikeharder** [comment]
All commands.  For example:

* You have 3 projects in a dependency chain `A -> B -> C`
* You have 3 command `build`, `test`  and `lint`
* You want to validate a pull request which changes `B`

You would run these commands:

* `rush build --to B --from B`
  * Before you can build `B`, you need to build all its dependencies
  * You also want to build everything which depends on `B`, to ensure there are no breaking changes in `B`.
* `rush test --from B`
  * You should test `B` and everything which depends on it, again to ensure there are no breaking changes in `B`.
  * However, you do not need to run tests for the dependencies of `B`, since they are not changed in the pull request.
* `rush lint --only B`
  * You only need to run a static analysis tool like `lint` on code which has actually changed, not dependencies in either direction.

**Comment by octogonz** [comment]
Suppose there was also a project `D`, and someone did this:

`rush build --to B --only D`

I think I would expect it to build `A`+`B`+`D`.  I wouldn't expect it to build "only" `D`.

Here are some other possible names to compare with:
`rush build --to B --include D`
`rush build --to B --select D`
`rush build --to B --with D`
`rush build --to B --project D`

BTW https://github.com/microsoft/web-build-tools/issues/1241 has a related discussion about project selection.

**Comment by mikeharder** [comment]
@octogonz: I agree the name `--only` is confusing if this option is composed with `--to` or `--from`.  My favorite of the alternative names you proposed is `--project`, since it seems the clearest when using by itself:

`rush build --include D`
`rush build --select D`
`rush build --with D`
`rush build --project D`

**Comment by octogonz** [comment]
Currently the short name  `-p` is used by `--parallelism`.  

If we call it `--project`, I would definitely to use `-p` for that instead.

**Comment by mikeharder** [comment]
My favorite is still `--project`.  If you want to avoid conflict with `-p`, you could use `-j, --project`.

**Comment by octogonz** [comment]
I agree `--project` is the best name.  (That's why I removed the `needs design` tag heheh.)

**Comment by scamden** [comment]
i'd add a little suggestion to make `--project` take more than one. my use case would be a command to start up a certain constellation of dev servers. i.e `rush servers --project backend-api frontend-ui` or similar

**Comment by mikeharder** [comment]
Closing since I believe this issues has been fixed by https://github.com/microsoft/rushstack/pull/2422.

@octogonz: Feel free to re-open if you disagree.
