### ISSUE TITLE
[rush] [add] Feature request: Allow "rush add" to add a dependency for all packages

### ISSUE THREAD

**Issue by sadasant** [microsoft/rushstack#1411]
`rush add` is only limited to the current package the user is located at. It would be wonderful if there was an option to add a dependency to all packages.

* **Tool:** Rush Multi-Project Build Tool
* **Tool Version:** 5.10.1
* **Node Version:** v10.16.0

**Comment by bsiegel** [comment]
For context, `--make-consistent` can be used to *update* all projects which use a given dependency, however there is no way to add a new dependency across all projects in the Rush workspace.

For what it’s worth, there’s also no `rush rm` to remove a dependency from one (or all) projects in the workspace. That would be a nice complement to this feature, but should be its own issue if it’s not already filed.

**Comment by sadasant** [comment]
I would like to implement this feature! I will try to come up with a PR myself as soon as possible. But, of course, that's prior to any feedback on the request itself. If you don't agree with this request, please comment about it! Also: If you'd like a specific API, please say so. I'll be happy to oblige.

**Comment by rakeshpatnaik** [comment]
Thanks for the suggestion. This seems to be a useful feature. This can be a new flag parameter --all to the command line. Looking forward to see the PR on this.

**Comment by sadasant** [comment]
@rakeshpatnaik hi! I'm glad you like it! What do you mean by a new parameter? This PR adds it as a flag. Is that what you're referring?
