### ISSUE TITLE
[api-extractor] Ability to bundle types into .d.ts rollup.

### ISSUE THREAD

**Issue by DylanVann** [microsoft/rushstack#1532]
- [x] Feature
- [ ] Bug

## Example

- `@company/main` depends on `@company/utils`.
- `@company/utils` is not published and is bundled into `@company/main` using a bundler like Rollup.
- Currently `import {x} from '@company/utils'` will appear in the declaration file for `@company/main`, which won't work for consumers.
- It would be useful to be able to specify that types of `@company/utils` should be rolled up into the `.d.ts` rollup for `@company/main`.

The settings should go in the `dtsRollup` section. Naming options:

- `bundledPackages`
- `internalPackages`
- `internals`/`internal`, the opposite of Webpack/Rollups `externals`/`external` option.

**Comment by octogonz** [comment]
@DylanVann Here is an initial sketch of this idea: PR https://github.com/microsoft/web-build-tools/pull/1533

This initial sketch handles `import {x} from '@company/utils';` but is missing the logic for handling `import {x} from '@company/utils/some/path';`.

Could you give it a try and let me know if it solves your problem?

To use it, you would add a line like this to your api-extractor.json:

```ts
"bundledPackages": [ "api-extractor-test-01" ],
```

For instructions on running a PR build, see [Building the code
](https://api-extractor.com/pages/contributing/building/) and [Debugging](https://api-extractor.com/pages/contributing/debugging/).

**Comment by octogonz** [comment]
@wanderwang FYI

**Comment by octogonz** [comment]
This feature was published as with API Extractor 7.5.0
