### ISSUE TITLE
[api-extractor] packageJson option is ignored

### ISSUE THREAD

**Issue by bgotink** [microsoft/rushstack#1559]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

The `packageJson` configuration property is ignored. If the option isn't set, the package manifest gets read by `@microsoft/api-extractor` but if the `packageJson` option is passed in, an empty `packageJson` will be used by the program. That leads to runtime errors.

**What is the expected behavior?**

The `packageJson` option should be respected.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** `@microsoft/api-extractor`
* **Tool Version:** latest
* **Node Version:** any
* **OS:** any

**Comment by octogonz** [comment]
Oops. 😇  I guess this was overlooked since in most cases it re-loads the right data.
