### ISSUE TITLE
[api-extractor] using any types defined in the "react" package causes "api-extractor" to fail

### ISSUE THREAD

**Issue by thealjey** [microsoft/rushstack#1562]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

```typescript
import { ReactNode } from "react";

export function foo(value: ReactNode): void {
  ...
}
```
```
$ api-extractor run

Error: Cannot read property 'externalModuleIndicator' of undefined
```

**What is the expected behavior?**

successful api extraction

**If this is a bug, please provide the tool version, Node.js version, and OS.**

- api-extractor version ^7.4.6
- nodejs version v12.11.1
- yarn version 1.19.0
- MacOS Mojave 10.14.6
- yarn workspaces and yarn PnP

**Comment by octogonz** [comment]
I can't repro this; the `foo()` function is analyzed successfully.  As far as I can tell, `@types/react` version `16.9.4` doesn't declare any symbol `externalModuleIndicator`, nor does API Extractor.

@thealjey Could you share a GitHub branch that repros this error?

**Comment by thealjey** [comment]
sure, will try to do that over the weekend

**Comment by thealjey** [comment]
had the time to do it today
https://github.com/thealjey/api-extractor-error

**Comment by thealjey** [comment]
lol, only after making the repo did I figure out what the problem/solution was
typescript does not support yarn PnP completely
it seems like api-extractor doesn't either
the strange thing is that it works perfectly until you reference the "react" module
and I could've sworn that it used to work before, like a week ago (I have no idea what changed)

anyway, `pnpify` makes it work just fine, and that is good enough for me
issue closed :)
