### ISSUE TITLE
'@microsoft/ts-command-line' cannot be found/imported when TS module generation is set to es2015 or esnext

### ISSUE THREAD

**Issue by toolness** [microsoft/rushstack#1569]
Hello!  I wanted to use `@microsoft/ts-command-line` in my project and after running `yarn add @microsoft/ts-command-line` and adding an `import` statement to one of my files, received error `TS2307` claiming that `@microsoft/ts-command-line` couldn't be found.

After starting a new project from scratch, I narrowed the error down to the `module` setting in `tsconfig.json`: if it's set to `commonjs`, everything works fine, but once I change it to `es2015` or `esnext`, suddenly the module can't be found, for some reason.

Any thoughts on why this is happening?  I'm attaching the example project below.  Running `yarn` followed by `yarn build` should result in `TS2307`, but changing the `tsconfig.json` to use `commonjs` module generation should make everything work.

[ts-module-not-found-example.zip](https://github.com/microsoft/rushstack/files/3686331/ts-module-not-found-example.zip)

**Comment by octogonz** [comment]
Hmmm...  My understanding was that `es2015` is not very well supported yet for NodeJS projects.  Here's a recent article that seems to support this view:

https://medium.com/@iamstan/typescript-es-modules-micheal-jackson-2040216be793

Why are you wanting to use `es2015`?  Could you share a link to a serious NodeJS project that uses TypeScript+ES2015?  I'd be interested to see how they set it up.

**Comment by toolness** [comment]
Ah, no worries, I ended up just switching my project to use `commonjs` after running into all kinds of roadblocks!  I'll close this issue now.
