### ISSUE TITLE
[Rush] Allow empty parameter defaults

### ISSUE THREAD

**Issue by danwbyrne** [microsoft/rushstack#1574]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

If I have a global command:
```json
{
      "commandKind": "global",
      "name": "test",
      "summary": "test",
      "description": "test",
      "safeForSimultaneousRushProcesses": false,
      "shellCommand": "jest --config ./packages/<test-script-directory>/jest/unit.js"
    }
```

I am unable to pass a non-defined argument to jest:
```bash
rush jest <testPattern>
```

Since the `choice` I would define as a parameter is not pre-defined.

**What is the expected behavior?**

I am able to inform rush of initial arguments that are not pre-defined for commands like `jest`.

edit: I had a few of the semantics wrong, I think my issue is more clear now.

**Comment by danwbyrne** [comment]
It seems like `jest` also accepts dashed-arg format so I could use `--test-path-pattern`. 

Still,

**Comment by iclanton** [comment]
Unfortunately, our command-line parser doesn't yet support arguments that aren't attached to a named parameter.

Supporting this is something we've wanted to do for a while, but it hasn't been a high priority.

**Comment by danwbyrne** [comment]
@iclanton thanks I went ahead and closed this issue since I found the `string` parameter in the json schema not listed in the docs :)
