### ISSUE TITLE
[rush] rush link throws error after upgrade to PNPM 4

### ISSUE THREAD

**Issue by sadsa** [microsoft/rushstack#1587]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

After specifying in the `rush.json` upgrade to `"rushVersion": "5.15.1"` and "pnpmVersion": "4.0.1", the `rush link` stage fails with the following error:

```
ERROR: Internal Error: Cannot find installed dependency "@bugsnag/js" in
"C:\Users\___\Projects\___\arc-mono\common\temp\node_modules\.local\C%3A%2FUsers%2F___%2FProjects%2F___%2Farc-mono%2Fcommon%2Ftemp%2Fprojects%2Fapp-shell.tgz_react-dom@16.9.0\node_modules"
You have encountered a software defect. Please consider reporting the issue to
the maintainers of this application.
```

**What is the expected behavior?**

I expect the `rush link` process to pass. It seems that the folder structure for local packages was changed to `common\temp\node_modules\pnpm\.local` with the upgrade to PNPM 4. However, rush maybe still referencing the OLD path. i.e. `common\temp\node_modules\.local`

* **Tool:** 
* **Tool Version:** 
* **Node Version:** 
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS:**

**Comment by sadsa** [comment]
Can confirm this issue is resolved by the PR #1577. Once it's merged this error will be resolved.

**Comment by alex-shamshurin** [comment]
The same is here with latest rush 5.15.1 and  pnpm 4.0.2

**Comment by sadsa** [comment]
> The same is here with latest rush 5.15.1 and pnpm 4.0.2
There currently isn't stable support for PNPM 4 until the PR I mentioned #1577 is approved and merged.
