### ISSUE TITLE
[rush] add --json flag for check and list commands

### ISSUE THREAD

**Issue by sdalonzo** [microsoft/rushstack#1597]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**
It would be useful to be able to serialize the output of `rush check` and `rush list` into a json format. My immediate use case is to send this data to splunk or a similar service to create a dashboard representing our common dependency usage across projects.

**What is the expected behavior?**
Output would be serialized to JSON or similar format.

**Comment by sdalonzo** [comment]
@octogonz added this based on our gitter conversation

**Comment by Claudiazhaoya** [comment]
#1668

**Comment by Claudiazhaoya** [comment]
#1757

**Comment by Claudiazhaoya** [comment]
All features have already been implemented. Check the feature by adding --json to 'rush check' and 'rush list' to see the output.
