### ISSUE TITLE
[rush] Unknown option 'resolution-strategy'

### ISSUE THREAD

**Issue by wbern** [microsoft/rushstack#1598]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [X] Bug

**Please describe the actual behavior.**
Repro: 1. `git clone --single-branch --branch rush-issue-1598 https://github.com/wbern/rush-pnpm-issues.git` 2. `rush update`

It seems latest pnpm doesn't like the strategyOption

![image](https://user-images.githubusercontent.com/25477382/67240219-52314600-f451-11e9-95b4-cdbfa66ad553.png)

**What is the expected behavior?**
rush should work with latest version of pnpm 4.

pnpm 4.0.0 actually works, so something happened later on.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:**
Rush 
* **Tool Version:**
rush 5.16.0 / pnpm 4.1.5
* **Node Version:**
10.15.3
  * **Is this a LTS version?**
Yes
  * **Have you tested on a LTS version?**
Yes 
* **OS:**
Windows 10

**Comment by christiango** [comment]
Seeing the same issue when trying to upgrade to rush 5.16.0 + pnpm 4.1.5 for one of the Office web repos.

**Comment by Claudiazhaoya** [comment]
Thanks for finding this issue. This issue only happens in pnpm 4.1+. It will be no problem if you switch the pnpm version to previous ones. Thanks!

**Comment by christiango** [comment]
Thanks! We're actually blocked from taking new versions of rush due to https://github.com/microsoft/rushstack/issues/1589. I'll see if I can just update pnpm without updating rush.

**Comment by apostolisms** [comment]
@christiango support for pnpm 4.x was added to rush 5.16.0

**Comment by christiango** [comment]
Ah, bummer. We can't update to 5.16 until https://github.com/microsoft/rushstack/issues/1589 is fixed.

**Comment by apostolisms** [comment]
@wbern @christiango this should be fixed now with pnpm 4.1.6. Can you please verify it is resolved?

**Comment by christiango** [comment]
Will do, just waiting for a fix for #1589 to be able to upgrade to a rush version compatible with pnpm 4

**Comment by apostolisms** [comment]
Thanks @christiango the [fix](https://github.com/microsoft/rushstack/pull/1604) for #1589 is getting released today.

**Comment by apostolisms** [comment]
Closing this since it doesn't seem to be an issue anymore with pnpm v4.1.6 release.
