### ISSUE TITLE
[api-extractor] blank exports created

### ISSUE THREAD

**Issue by kenotron** [microsoft/rushstack#1601]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**
When run, api-extractor creates an extra blank `export { }` in the d.ts (untrimmed)

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

I have a repro github repo: https://github.com/kenotron/repro-api-extractor

just do this in that repo:

```
git clone https://github.com/kenotron/repro-api-extractor.git
npm i
npm run build
```
The input file looks like this
```ts
/** @public */
export const a = 5;
```

Resultant d.ts rolled up to this:
```ts
export declare const a = 5;
export { }
```

**What is the expected behavior?**

I expect it to only have valid declarations:

```ts
export declare const a = 5;
```

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** api-extractor
* **Tool Version:** 7.5.2
* **Node Version:** 10.15.1
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** macos mojave

**Comment by octogonz** [comment]
This is by design. There is a design flaw in the TypeScript language, where non-exported declarations will sometimes be treated as if they had an `export` modifier.  In other words, unexported APIs in a .d.ts rollup will incorrectly show up in your IntelliSense.  The empty `export { }` is a top secret compiler directive that prevents this problem.

See https://github.com/microsoft/rushstack/pull/1000 for details.

**Comment by kenotron** [comment]
Oh does this interfere consumers from using the dts file?

**Comment by octogonz** [comment]
How do you mean?

**Comment by octogonz** [comment]
@kenotron Try creating a file like this:

**index.d.ts**
```ts
export declare const a = 5;
declare const b = 5;
```

You will find that `import { b } from 'your-lib';` does not produce any compiler errors, but of course fails at runtime.

Whereas if you do this:

**index.d.ts**
```ts
export declare const a = 5;
declare const b = 5;
export { }
```

...then `import { b } from 'your-lib';` is correctly reported as a compile error `Module ___ has no exported member 'b'.`

That's the concept here.

**Comment by kenotron** [comment]
A gap in knowledge for me it seems. I didn’t know that blank export is legal syntax

**Comment by kenotron** [comment]
I’m closing this issue because this is by design

**Comment by octogonz** [comment]
>  I didn’t know that blank export is legal syntax

Me neither!  I only learned about it from chatting with someone who works on the compiler. 😋

@kenotron Maybe API Extractor should emit a code comment to avoid confusion?  It could be like this:

```
export { }; // prevents accidental imports of local declarations
```

BTW I found that the TypeScript compiler does the same thing as API Extractor.  For example, if you compile this input:

**foo.ts**
```ts
class A { }
export function f(): A {
  return new A();
}
```
...you get this output:

**foo.d.ts**
```ts
declare class A {
}
export declare function f(): A;
export {};
```

**Comment by JimiC** [comment]
The `export { }` was driving me crazy. Couldn't figure out why it's being generated. Glad I have found the thread that explains it all.
