### ISSUE TITLE
[rush] Could not find preferred package /@typescript-eslint/eslint-plugin/2.5.0 in lockfile

### ISSUE THREAD

**Issue by samcolby** [microsoft/rushstack#1609]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [X] Bug

**Please describe the actual behavior.**

We've added a new eslint-config shareable module to the monorepo, with the following dependencies, that were added with the following command `rush add -p eslint-plugin-prettier --dev --exact -m`

```
"dependencies": {
    "eslint-config-prettier": "6.4.0",
    "@typescript-eslint/parser": "2.5.0",
    "prettier": "1.17.0"
  },
  "peerDependencies": {
    "eslint": ">=6.5",
    "eslint-plugin-prettier": "3.1.1",
    "eslint-plugin-react": "7.16.0",
    "eslint-plugin-react-hooks": "2.2.0",
    "@typescript-eslint/eslint-plugin": "2.5.0"
  },
  "devDependencies": {
    "jest": "24.8.0",
    "typescript": "3.5.3"
  },
```

When trying to add the necessary devDependencies to other projects in the repo, we  get the following errors.

```
 WARN  Could not find preferred package /@typescript-eslint/eslint-plugin/2.5.0 in lockfile
 WARN  Could not find preferred package /eslint-plugin-prettier/3.1.1 in lockfile
 WARN  Could not find preferred package /@typescript-eslint/eslint-plugin/2.5.0 in lockfile
 WARN  Could not find preferred package /eslint-plugin-prettier/3.1.1 in lockfile
```

pnpm-lock.yaml contains some of the following entries
```
  '@typescript-eslint/eslint-plugin': 2.5.0_aebcf8b8a2528ed8adbfe1a5c3bbd8fc
...
...
   eslint-plugin-prettier: 3.1.1_prettier@1.17.0
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

See above, we can't share this unfortunately

**What is the expected behavior?**

That we can add these dependencies to other projects in the repo.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:**  Rush and pnpm
* **Tool Version:**  rush 5.11.1, pnpm 3.6.2
* **Node Version:**  v10.16.0
  * **Is this a LTS version?**  yes, or it was when this error started
  * **Have you tested on a LTS version?** yes
* **OS:** macos mojave

**Comment by rakeshpatnaik** [comment]
Can you please upgrade to the latest version of Rush (5.16.1) and try to repro this?

**Comment by samcolby** [comment]
Hi @rakeshpatnaik.

We have tried upgrading both rush and pnpm, with the same results. 

```
 WARN  Could not find preferred package /@typescript-eslint/eslint-plugin/2.5.0 in lockfile
 WARN  Could not find preferred package /eslint-plugin-prettier/3.1.1 in lockfile
 WARN  Could not find preferred package /@typescript-eslint/eslint-plugin/2.5.0 in lockfile
 WARN  Could not find preferred package /eslint-plugin-prettier/3.1.1 in lockfile
```
 

And we also get the following errors when linking each project, even in projects that don't have eslint enabled in them yet.
```
Could not find peer dependency 'eslint' that satisfies version '^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0', skipping...
Could not find peer dependency 'stylis' that satisfies version '^3.5.0', skipping...
```

Is there anything else I need to do to upgrade?  We changed the values in`rush.json`, ran `rush purge` etc. ?

**Comment by iclanton** [comment]
Your global version of Rush doesn't matter, as long as you have it installed. The global installation automatically installs the version that repos request.

We generally suggest people run `rush update --full` after updating their version of Rush or their version of their package manager. Can you try that?

**Comment by iclanton** [comment]
@sachinjoseph - 3.6.2 is a known good version of pnpm, right?

**Comment by samcolby** [comment]
Thanks @iclanton .

Just tried that again with `"rushVersion": "5.16.1",` and `"pnpmVersion": "4.1.7",` but with the same results.  

However the second error `Could not find peer dependency 'eslint' that satisfies version '^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0', skipping...` is now gone.


Is there a list somewhere of the known good versions of pnpm ?

My current fix is to revert `pnpm-lock.yaml` to an earlier version before eslint was installed in the monorepo and let it rebuild.  Otherwise we get the same 2 errors for every project, we have installed our eslint config into

```
WARN  Could not find preferred package /@typescript-eslint/eslint-plugin/2.5.0 in lockfile
 WARN  Could not find preferred package /eslint-plugin-prettier/3.1.1 in lockfile
 WARN  Could not find preferred package /@typescript-eslint/eslint-plugin/2.5.0 in lockfile
 WARN  Could not find preferred package /eslint-plugin-prettier/3.1.1 in lockfile
```

**Comment by octogonz** [comment]
@samcolby Are you able to share a branch that repros these errors?  That would help us investigate faster.

**Comment by octogonz** [comment]
Closing because we can't proceed with this investigation. Please open a new issue if you want to revisit it. Thanks!
