### ISSUE TITLE
[api-extractor] Error: "import * as ___ from ___;" is not supported yet for local files.

### ISSUE THREAD

**Issue by wandyezj** [microsoft/rushstack#1610]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [x] Feature
- [] Bug

**Please describe the actual behavior.**

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

**What is the expected behavior?**

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 
* **Tool Version:** 
* **Node Version:** 
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS:**

**Comment by octogonz** [comment]
This is a duplicate of https://github.com/microsoft/rushstack/issues/1029
