### ISSUE TITLE
[rush] New rush-stack-compiler-3.7!

### ISSUE THREAD

**Issue by qianghuang94** [microsoft/rushstack#1630]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**
Typescript 3.7 contains a lot of exciting features.

Any plan to upgrade the compiler to support 3.7?

**Comment by iclanton** [comment]
These have been released :)
