### ISSUE TITLE
[api-extractor] Support `@throws` tag

### ISSUE THREAD

**Issue by vidartf** [microsoft/rushstack#1631]
**Is this a feature or a bug?**

- [X] Feature
- [ ] Bug

Tsdoc supports `@throws` (https://github.com/microsoft/tsdoc/pull/175), but api-extractor still does not support it:

https://github.com/microsoft/rushstack/blob/e5bccece4fa5f40a1a3a482da387afa553cd7d27/apps/api-extractor-model/src/aedoc/AedocDefinitions.ts#L39-L60

I have no idea how much work it would be to add this, but it would be useful to have 😃

**Comment by octogonz** [comment]
It's pretty easy. :-) I think the implementation would be similar to `@example`.

Would you be interested to implement it?

**Comment by vidartf** [comment]
> Would you be interested to implement it?

Yes, I would need to some guidance:
- Is the list I added the right place to add it?
- What are other key code locations to look at?

**Comment by octogonz** [comment]
> - Is the list I added the right place to add it?

Yup

> - What are other key code locations to look at?

The intended `@throws` usage is here: https://github.com/microsoft/tsdoc/pull/175

Note that the class name is (optionally) specified as a `{@link}` on a separate line.

The code that renders `@example` is [here](https://github.com/microsoft/rushstack/blob/4de6fe10f1cc8ced95580d6aba9b826d9510f789/apps/api-documenter/src/documenters/MarkdownDocumenter.ts#L304)

If you need to visualize the AST, use this tool: https://microsoft.github.io/tsdoc/

Instructions for debugging API Extractor are here: https://api-extractor.com/pages/contributing/building/

For testing your change, use this project: https://github.com/microsoft/rushstack/tree/master/build-tests/api-documenter-test

**Comment by vidartf** [comment]
So, as far as I am reading you:
- The warning that was previously issued from `api-extractor` was a hint that the default renderer of api-documenter does not support the `@throws` tag.
- The main work for a PR would be to add support for the tag in `api-documenter`.

Correct?

**Comment by octogonz** [comment]
Yup!
