### ISSUE TITLE
[api-extractor] Error: Cannot read property 'externalModuleIndicator' of undefined

### ISSUE THREAD

**Issue by acalvo** [microsoft/rushstack#1652]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**
If you are rolling up a `d.ts` file that references a dependency that is not found, a generic non-intuitive `Error: Cannot read property 'externalModuleIndicator' of undefined` is shown.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**
Clone https://github.com/acalvo/api-extractor-dependency and `npm install && npx api-extractor run` over it.

**What is the expected behavior?**
I'd expect to say something like `Error: 'rxjs' dependency not found` or even a more generic `Error: dependency not found`. Something that points the user in the right direction.

**Comment by halfnibble** [comment]
I received this error too. Thank you for the explanation!

**Comment by octogonz** [comment]
But doesn't API Extractor normally run after a successful invocation of the TypeScript compiler?  Whereas if the TypeScript compiler failed and reported errors, then its .d.ts output may be incomplete, and it may be challenging for the rollup logic to analyze it correctly.

I'm not objecting to fixing this issue. But rather trying to clarify the usage scenarios that we want to invest in supporting.

**Comment by octogonz** [comment]
The bug itself turned to be pretty simple. Here's a PR: https://github.com/microsoft/rushstack/pull/1680

**Comment by octogonz** [comment]
@acalvo  Thank you for preparing a repro.  It was very helpful!

**Comment by acalvo** [comment]
The new output is great!

Before (api-extractor 7.7.1-):
```
Error: Cannot read property 'externalModuleIndicator' of undefined
```

Now (api-extractor 7.7.2+):
```
Warning: example.d.ts:1:28 - (TS2307) Cannot find module 'rxjs'.

API Extractor completed with warnings
```

Thanks, @octogonz 🥳

**Comment by octogonz** [comment]
Awesome!
