### ISSUE TITLE
Unable to join Gitter

### ISSUE THREAD

**Issue by xmclark** [microsoft/rushstack#1654]
I can't seem to join the public gitter that is linked on the readme. I always get a page like this:

![image](https://user-images.githubusercontent.com/1364747/70269137-a1f47400-1756-11ea-87e7-be3e0d813211.png)

**Comment by octogonz** [comment]
What is the specific URL you are trying to visit?

**Comment by octogonz** [comment]
The README.md URL is apparently outdated.  It should be `https://gitter.im/rushstack/rushstack` instead of `https://gitter.im/web-build-tools/web-build-tools`.  But for me the old URL redirects successfully to the new one.

**Comment by octogonz** [comment]
Here's a PR: https://github.com/microsoft/rushstack/pull/1655
