### ISSUE TITLE
[rush] bug. A project in rush.json is not added to rush-link.json

### ISSUE THREAD

**Issue by beejones** [microsoft/rushstack#1658]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**
- [x] Bug

**Please describe the actual behavior.**
https://github.com/beejones/rush-test-environment
use branch beejones/show-package-not-found-problem
This repository contains three projects.

"projects": [

{
  "packageName": "@beejones/calculator-interface",
  "projectFolder": "libs/calculator-interface"
},
{
  "packageName": "@beejones/fancy-calculator",
  "projectFolder": "libs/fancy-calculator"
},
{
  "packageName": "@beejones/sample-package",
  "projectFolder": "libs/sample-package"
}
]

PS C:\did1\rush-test-environment> rush update --full

Rush Multi-Project Build Tool 5.13.0 - https://rushjs.io Node.js version is 12.13.1 (LTS)

Starting "rush update"

Trying to acquire lock for pnpm-2.15.1 Acquired lock for pnpm-2.15.1 Found pnpm version 2.15.1 in C:\Users\ronny.rush\node-v12.13.1\pnpm-2.15.1

Symlinking "C:\did1\rush-test-environment\common\temp\pnpm-local" --> "C:\Users\ronny.rush\node-v12.13.1\pnpm-2.15.1"

Updating temp projects in C:\did1\rush-test-environment\common\temp\projects Finished creating temporary modules (0.05 seconds)

Checking node_modules in C:\did1\rush-test-environment\common\temp

Deleting: C:\did1\rush-test-environment\common\temp\rush-link.json

Running "pnpm install" in C:\did1\rush-test-environment\common\temp

Packages: +177 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ Resolving: total 174, reused 174, downloaded 0, done Updating C:\did1\rush-test-environment\common\config\rush\shrinkwrap.yaml

Linking projects together...

LINKING: @beejones/calculator-interface
Purging C:\did1\rush-test-environment\libs\calculator-interface\node_modules

LINKING: @beejones/fancy-calculator Purging C:\did1\rush-test-environment\libs\fancy-calculator\node_modules

LINKING: @beejones/sample-package Purging C:\did1\rush-test-environment\libs\sample-package\node_modules Writing "C:\did1\rush-test-environment\common\temp\rush-link.json"

Linking finished successfully. (1.24 seconds)

Next you should probably run "rush build" or "rush rebuild"

Rush update finished successfully. (8.71 seconds) PS C:\did1\rush-test-environment>

rush build will fail in FancyCalculator because calculator-interface is not found.
calculator-interface is missing from rush-link.json
{ "localLinks": 
 { "@beejones/fancy-calculator": [ "@beejones/calculator-interface" ],
   "@beejones/sample-package": [ "@beejones/calculator-interface", "@beejones/fancy-calculator" ] } }

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**
I've setup a repo.
https://github.com/beejones/rush-test-environment
use branch beejones/show-package-not-found-problem

**What is the expected behavior?**
rush install
rush build 
All local packages can be used in the repo but @beejones/calculator-interface is not linked. As such the build fails.
See rush-link.json file and @beejones/calculator-interface is not there as a project.

**If this is a bug, please provide the tool version, Node.js version, and OS.**
Visual code 1.40.2 
Rush Multi-Project Build Tool 5.13.0 - https://rushjs.io 
Node.js version is 12.13.1 (LTS)
Windows 10 build 1809

Comment:
The reason for posting this repo is because  @beejones/calculator-interface is not found during the build. This is  a problem I encountered in my other project I am working on. It is my assumption that the root cause build cannot find the package is because it is not in the rush-link.json. This is totally an assumption from my side.

**Comment by beejones** [comment]
Hi is anybody investigating this issue?
Thanks

**Comment by octogonz** [comment]
I'll see if I can take a look tomorrow - we all just got back from the holiday.

**Comment by octogonz** [comment]
Hi @beejones,

The reason that the TypeScript compiler cannot import `@beejones/calculator-interface` is that your `package.json` has an incorrect ["main" entry](https://github.com/beejones/rush-test-environment/blob/f9259ee51017de6d38db468be8618d40c14b5f1a/libs/calculator-interface/package.json#L11):

```js
{
  "name": "@beejones/calculator-interface",
  "version": "1.0.0",
  "description": "Simple interface for calculator.",
  "repository": {
    "type": "git",
    "url": "https://msazure.visualstudio.com/DefaultCollection/One/_git/AD-DID-Services-Enterprise-Agent.git"
  },
  "author": "beejones",
  "license": "MIT",
  "main": "./dist/lib/index.js",  // <========= INCORRECT
```

If you change it to `"./dist/index.js"` then `rush build` completes successfully.

The issue isn't caused by Rush.  The `rush-link.json` file that you mentioned is an internal data structure, and not the complete picture. If you look in `rush-test-environment\libs\fancy-calculator\node_modules\@beejones`, you'll see that the symlinks are created properly.

Let me know if we can close this issue. Thanks for using Rush!

**Comment by beejones** [comment]
You nailed it. Thanks you very much.
