### ISSUE TITLE
[load-themed-styles] unnecessary type attribute on style tags leads to HTML validator warning

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/rushstack#1673]
Our team uses load-themed-styles via office-ui-fabric-react, please feel free to redirect if needed - thanks!

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

`loadTheme()` creates style elements with a type attribute:
https://github.com/microsoft/rushstack/blob/667e22f332988f57e77ec4651ab8f22a3ec08eba/libraries/load-themed-styles/src/index.ts#L398

When running the resulting HTML through the "[Nu HTML Checker](https://validator.w3.org/nu/)", we see the following warning:

> The type attribute for the style element is not needed and should be omitted.

This occurs because the WHATWG HTML spec treats this as "[obsolete but conforming behavior](https://html.spec.whatwg.org/multipage/obsolete.html#warnings-for-obsolete-but-conforming-features)":

> Authors should not specify a type attribute on a style element. ([link](https://html.spec.whatwg.org/multipage/obsolete.html#obsolete-but-conforming-features:attr-style-type))

The Mozilla docs say:

> **type**
This attribute defines the styling language as a MIME type (charset should not be specified). This attribute is optional and defaults to text/css if it is not specified — there is very little reason to include this in modern web documents. ([link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style
))

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

This [codepen](https://codepen.io/anon/pen/jjEVjw) uses office-fabric theming - inspecting the iframe head style tags shows text/css types. Running the nu validator on this page or any page with text/css types produces the warning.

This [branch](https://github.com/karanbirsingh/rushstack/tree/notype) removes the line above. When testing locally via office-fabric theming, the functionality seemed identical & the warning disappeared. PR [here](https://github.com/microsoft/rushstack/issues/1673) if the change seems appropriate.

**What is the expected behavior?**

Generated style tags should not have the text/css type set - this will help clients of the library when testing for HTML validation

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 
* **Tool Version:** 1.10.26
* **Node Version:** 
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS:**

**Comment by octogonz** [comment]
Fixed by PR https://github.com/microsoft/rushstack/pull/1674
