### ISSUE TITLE
[api-extractor] ae-missing-getter is a breaking change

### ISSUE THREAD

**Issue by pmconne** [microsoft/rushstack#1678]
**Is this a feature or a bug?**

- [ ] Feature
- [X] Bug (or, potentially undesirable change in behavior)

**Please describe the actual behavior.**

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

```ts
/** @public */
export class Thing {
  private _thing = 0;
  /** @public */
  public set thing(thing: number) { this._thing = thing; }
}
```

Run this code through api-extractor 7.6.2. No errors are produced.
Run it through api-extractor 7.7.0. It produces the following errors:

`(ae-missing-getter) The property "thing" has a setter but no getter.`
`(ae-setter-with-docs) The doc comment for the property "thing" must appear on the getter, not the setter.`

Introduced in #1646 

**What is the expected behavior?**

Exposing a setter without a getter is valid and sometimes useful. I would expect that if only a setter is present, the documentation should be taken from the setter and no errors produced.

I'd also expect these two new errors to be documented here: https://api-extractor.com/pages/setup/invoking/

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** api-extractor
* **Tool Version:** 7.7.0
* **Node Version:** 10.15.0
  * **Is this a LTS version?** Yes
  * **Have you tested on a LTS version?** 
* **OS:** Windows 10

**Comment by octogonz** [comment]
> Run this code through api-extractor 7.6.2. No errors are produced.
> Run it through api-extractor 7.7.0. It produces the following errors:

True, but this validation was present in API Extractor 6.  It was punted from the API Extractor 7.0 initial releae, and we finally got around to restoring it in 7.7.  So it's not entirely new.

> Exposing a setter without a getter is valid and sometimes useful.

Could you elaborate on this?  In our original design discussion, people unanimously considered the setter-without-getter to be an incorrect usage.  If there are legitimate usage cases for this (e.g. where it's the only possible API representation), we can reconsider it.  

But note that while TypeScript aims to represent _every possible_ JavaScript construct (no matter how ill-advised), API Extractor's focus is to help people ship _high quality_ APIs.  We sometimes make design decisions that completely disregard the needs of outdated coding practices. 😊

From this perspective, an API "property" is conventionally used to indicate an operation similar to reading/writing a variable.  For example, people often recommend against:
- property getters that cause nontrivial side-effects (e.g. incrementing a counter each time it is read)
- property getters that perform expensive/complex operations
- property getters that throw exceptions
All of these practices diverge from a person's intuition about reading a variable.  They are signs that the API should be a method/function, not a property.

Thus, if I shouldn't be allowed to access `Thing._thing` after it has been assigned, then it seems that maybe it would be more natural to represent the API like this:

```ts
export class Thing {
  private _thing = 0;

  /** @public */
  public initialize(thing: number): void { 
    this._thing = thing; 
  }
}
```

**Comment by octogonz** [comment]
> I'd also expect these two new errors to be documented here: https://api-extractor.com/pages/setup/invoking/

We'll definitely fix that.  Thanks for pointing it out!

**Comment by pmconne** [comment]
Thanks for providing that context. I'll throw a couple of examples below, but I'm not presenting these as "good" APIs - multiple alternative (probably preferable) ways to model them exist that don't require a write-only property. Also, unlike some other languages, TypeScript doesn't provide any way to define an `interface` with a write-only property. I'm fine with closing this issue.

```ts
enum GraphicsQuality {
  Low,
  High,
  // ...
}

class GraphicsSettings {
  public constructor(
    public antiAliasingFactor: number = 4,
    public shadowsEnabled: boolean = false,
    public lightingMode = "HDR") { }

  public set quality(quality: GraphicsQuality) {
    switch (quality) {
      case GraphicsQuality.Low:
        this.antiAliasingFactor = 2;
        this.shadowsEnabled = false;
        this.lightingMode = "bloom";
        break;
      case GraphicsQuality.High:
        this.antiAliasingFactor = 8;
        this.shadowsEnabled = true;
        this.lightingMode = "HDR";
        break;
      // ...
      }
  }
}

const settings = new GraphicsSettings();
settings.quality = GraphicsQuality.High;
settings.shadowsEnabled = false;
// settings no longer matches any default graphics quality.
// A `GraphicsQuality` getter could not return anything meaningful, unless we add a
// `Custom` enum member and update `settings` internally whenever an individual property is modified.
```

```ts
class ByteRgba {
    public constructor(
        public red: number = 0xff,
        public green: number = 0xff,
        public blue: number = 0xff,
        public alpha: number = 0xff
    ) { }
}

class FloatPreMultipliedRgba {
    public constructor(
        public red: number = 1.0,
        public green: number = 1.0,
        public blue: number = 1.0,
        public alpha: number = 1.0
    ) { }

    public set bytes(bytes: ByteRgba) {
        this.red = bytes.red * bytes.alpha;
        this.green = bytes.green * bytes.alpha;
        this.blue = bytes.blue * bytes.alpha;
        this.alpha = bytes.alpha;
    }
}

const b = new ByteRgba(20, 30, 40, 0);
const f = new FloatPreMultipliedRgba();
f.bytes = b;
// red green and blue components are irretrievable from f (division by zero).
```

**Comment by octogonz** [comment]
> > I'd also expect these two new errors to be documented here: https://api-extractor.com/pages/setup/invoking/
> 
> We'll definitely fix that. Thanks for pointing it out!

I have updated the docs:
- https://api-extractor.com/pages/messages/ae-missing-getter/
- https://api-extractor.com/pages/messages/ae-setter-with-docs/

The code example in [ae-missing-getter](https://api-extractor.com/pages/messages/ae-missing-getter/) made me even more convinced  that omitting the setter isn't a good practice.  In your example it might happen like this:

```ts
const settings = new GraphicsSettings();

// Mysteriously prints "The quality is: undefined" -- 🤔
settings.quality = GraphicsQuality.High;
console.log("The quality is: " + settings.quality);

settings.quality = GraphicsQuality.High;
if (settings.quality === GraphicsQuality.High) {
   // This code mysteriously never executes 😮
}
```

The TypeScript compiler doesn't issue any warning for the above code.
