### ISSUE TITLE
[rush] Enable `rush list` to accept `--to` and `--from` params

### ISSUE THREAD

**Issue by sdalonzo** [microsoft/rushstack#1687]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

My needs would be satisfied by @wbern's proposal here: https://github.com/microsoft/rushstack/issues/1202

We are looking to create a dev/watch workflow based partially around a `build:watch` bulk task, but we need to be able to scope the run to specific projects in our monorepo.

In the meantime, the ability to apply `--to` and `--from` flags to the rush list command would enable us to spawn watch processes for the required projects from a Node script. JSON output would be a bonus.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

n/a

**What is the expected behavior?**

`rush list` output can be filtered by `--to` and `--from`, and possibly output JSON

**If this is a bug, please provide the tool version, Node.js version, and OS.**

Not a bug

**Comment by sdalonzo** [comment]
@octogonz ☝️ as discussed on Gitter.

**Comment by octogonz** [comment]
Have you considered using the `rush-lib` API for this problem?

For example, in NodeJS:

```ts
const rushLib = require("@microsoft/rush-lib");
const RushConfiguration = rushLib.RushConfiguration;
const config = RushConfiguration.loadFromDefaultLocation();
const exampleProject = config.projects[0];

// Prints "@microsoft/api-documenter"
console.log(exampleProject.packageName);

// Prints "[ 'api-documenter-test', 'doc-plugin-rush-stack', 'generate-api-docs' ]"
console.log(exampleProject.downstreamDependencyProjects);

const dependencyName = exampleProject.downstreamDependencyProjects[0];

// Prints "api-documenter-test"
console.log(dependencyName);
const dependencyProject = config.projectsByName.get(dependencyName);

// Prints normalized package.json contents
console.log(JSON.stringify(dependencyProject.packageJson));
```

If this API is awkward to use for the problem that you're solving, we could make it better.

**Comment by sdalonzo** [comment]
@octogonz `rush-lib` did end up serving this purpose well.
