### ISSUE TITLE
[GCB] Allow configuration of autoprefixer browser list (or drop IE10 support EOM)

### ISSUE THREAD

**Issue by KevinTCoughlin** [microsoft/rushstack#1689]
Currently, `gulp-core-build-sass` passes a hard-coded browser range including IE10 to `autoprefixer`:

https://github.com/microsoft/rushstack/blob/4cf4bdd0738e4cadbb198f6c0112a8eedc4aea54/core-build/gulp-core-build-sass/src/SassTask.ts#L90

Officially, IE10 reaches end of support on January 31, 2020:

>Internet Explorer (IE) 10 will reach end of support on January 31, 2020. From this point forward, IE 11 will be the only supported version of Internet Explorer on Windows Server 2012 and Windows Embedded 8 Standard. IE 11 is available via Microsoft Update Catalog, Windows Update and Windows Server Update Service (WSUS). Go here to learn more.
>https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer

IE10 requires a number of vendor specific prefixes, particularly with flex & grid. Dropping IE10 from the supported browser range will reduce emitted CSS size. This change would impact both first and third-party SharePoint developers.

We may consider making the browser list configurable if devs require that level of configuration.

I'm happy to raise the PR. The above change may need to be a `major` bump to `gulp-core-build-sass`.

cc: @iclanton @lijunle @patmill

**Comment by KevinTCoughlin** [comment]
IIRC `load-themed-styles` is no longer compatible with IE < 11. In case that influences the above.

**Comment by lijunle** [comment]
> IIRC load-themed-styles is no longer compatible with IE < 11. In case that influences the above.

When did `load-themed-styles` drop off the IE10 support? I don't see it is mentioned in its [`CHANGELOG`](https://github.com/microsoft/rushstack/blob/master/libraries/load-themed-styles/CHANGELOG.md)? 

> We may consider making the browser list configurable if devs require that level of configuration. I'm happy to raise the PR. The above change may need to be a major bump to gulp-core-build-sass.

Sounds reasonable for the layer of `gulp-core-build-sass`. Each end product has the choice to decide if support IE10. Also, reasonable to be a major bump and mention int the CHANGELOG.

One more thing from SharePoint aspect, we should have something like `browsers: '> 1% of SharePoint'`. It pushes the end user experience to the dev end.

**Comment by KevinTCoughlin** [comment]
I may have misspoke re: IE10 compat; I need to verify locally. I had assumed this change used an incompatible API, specifically `createEvent`: https://github.com/microsoft/rushstack/pull/1570/files#diff-dff79cdef78744eea24f892dfabcd55bR405

As you suggest, the better forward fix here is to make browsers list configurable for devs to adjust to their needs.
