### ISSUE TITLE
[rushstack] git user information validator broken

### ISSUE THREAD

**Issue by mandric** [microsoft/rushstack#1694]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

Totally new to rush and started by following the getting started docs here https://rushjs.io/pages/intro/get_started/.

When I run `rush update` I get an error that not following policy, yet my git config is valid:

```

Checking Git policy for tmandric in ~/dev/scratch/rushstack (master=)
$ rush update

Rush version 5.17.2 is not currently installed. Installing...
Trying to acquire lock for rush-5.17.2
Deleting old files from /Users/mandric/.rush/node-v10.17.0/rush-5.17.2
Copying /Users/mandric/dev/scratch/rushstack/common/config/rush/.npmrc --> /Users/mandric/.rush/node-v10.17.0/rush-5.17.2/.npmrc

Running "npm install" in /Users/mandric/.rush/node-v10.17.0/rush-5.17.2
Successfully installed Rush version 5.17.2 in /Users/mandric/.rush/node-v10.17.0/rush-5.17.2.

Rush Multi-Project Build Tool 5.17.2 - https://rushjs.io
Node.js version is 10.17.0 (LTS)


Starting "rush update"

Checking Git policy for this repository.

Hey there!  To keep things tidy, this repo asks you to submit your Git commits using an email like one of these patterns:

    [^@]+@users\.noreply\.github\.com
    travis@example\.org

...but yours is configured like this:

    Milan Andric <mandric@gmail.com>

To fix it, you can use commands like this:

    git config --local user.name "Mr. Example"
    git config --local user.email "mrexample@users.noreply.github.com"

Aborting, so you can go fix your settings.  (Or use --bypass-policy to skip.)

mandric in ~/dev/scratch/rushstack (master=)
$ cat ~/.gitconfig 
[user]
	email = mandric@gmail.com
	name = Milan Andric
...
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

**What is the expected behavior?**

My git config looks like it should be valid.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 
rush

* **Tool Version:** 
rush-5.17.2

* **Node Version:** 

node-v10.17.0

  * **Is this a LTS version?** 

yes

  * **Have you tested on a LTS version?** 

yes

* **OS:** 

OSX

**Comment by iclanton** [comment]
Your `rush.json` looks like it has the `gitPolicy.allowedEmailRegExps` property set to only allow the Git `user.email` config option to be set to something that matches the regular expression `[^@]+@users\.noreply\.github\.com` or `travis@example\.org`.

If you don't want any restrictions on what Git email addresses are allowed, remove (or comment out) that field in `rush.json`.
