### ISSUE TITLE
[Maintainers] feedback & development is slow

### ISSUE THREAD

**Issue by Jabher** [microsoft/rushstack#1696]
Hello guys!
I appreciate a lot what you are doing here.
I love and use Rush in production in its current state and I'm already having better experience in comparison to what I had without Rush. You are way much better than Lerna or workspaces or any other solution for large repos on nodejs.

But I see that support and development is kinda slow; average response time is days and weeks, and requested features are coming extremely slowly.

I'm feeling sorry I cannot participate more that just making bug reports and feature requests - Rush saved me significant amount of time, but not enough to participate as a committer yet :)

I understand that probably this is a side project of some teams inside a Microsoft.
What can I do to help you to make it an open-source project on full-time inside a MS?
Spread a word, advice to friends, write on some magic email with words "this project of your company is great, please support it", something else?

Rush is already good, but has a great potential, and it will be very sad if another challenger will just copy ideas and make something rush-alike, but with all the stuff missing. Also, I do not want to migrate to another framework :)

**Comment by apostolisms** [comment]
Thank you for your feedback. We as well feel that we could be faster and try to push for quicker turnaround times for bug and feature requests. We try to have new releases every week and we have managed to do so (December aside, holidays have pushed us outside our normal routine) as well as issue triage 3 times a week. We usually try to respond to issues and review PRs within 2 days. Rush is not a side project as a lot of teams rely on it, inside and outside of Microsoft, and we are committed to its success.  As any open source project we also rely on the community to help us move faster. Picking up open issues and spreading the word is very helpful and very much appreciated.

**Comment by Jabher** [comment]
I will try to help, then :)

Also, did not want to insult by naming rush a "side project" - I just had a strong feeling that there is a sub-team inside Office or Sharepoint that supports all the tooling including Rush. Sorry if accidentally offended the team

**Comment by rnarayana** [comment]
Totally agree with @Jabher here. I will also try to pitch in if I can.. Love this project!

**Comment by octogonz** [comment]
This year there has been a noticeable increase in development activity here. PNPM workspaces got implemented, the Heft project is almost ready for first release, "rush deploy" got implemented, API Extractor is trying to keep up with all the new language features from TypeScript. For the relatively small group of maintainers, pushing to get a feature shipped sometimes makes it challenging to keep on top of everything else.  If your issue/PR isn't getting any attention, it might help to reply with a comment asking if anyone has followed up, or to ping someone in the [Gitter chat room](https://gitter.im/rushstack/rushstack). There might not be resources to implement every idea or fix every bug, but usually people can at least give an opinion about the issue and its priority.

**Comment by iclanton** [comment]
Closing this out. Since this was opened, we've formalized a biweekly triage and brought on more people to help push things through.
