### ISSUE TITLE
[rush] install-run scripts are autogenerated. Should they be ignored by git?

### ISSUE THREAD

**Issue by trusktr** [microsoft/rushstack#1700]
I ran `rush update` which generated three `install-run*.js` scripts. Should these be added to .gitignore? If not, why not?

EDIT: After investigating, in my case I don't really need those scripts. I have my own way to install dependencies reliably, so I'll just add those scripts to `.gitignore`.

**Comment by trusktr** [comment]
Based on the comments in the files, where it says I may need those scripts if `rush` is not installed in a CI build environment, then I can safely ignore them as I can guarantee that `rush` is available. I always build projects with all build dependencies as dev dependencies, not global dependencies.

**Comment by trusktr** [comment]
Seems like the same with `.rush` folders. Those aren't ignored by default either, except for `.rush/temp`.

**Comment by trusktr** [comment]
Ah, nvm, I see for some reason my VS Code is not ignoring `.rush/temp` folder in sub directories, which was confusing me.

**Comment by trusktr** [comment]
Hmm, it seems like a git problem. I have

```
.rush/temp/**
```

in my `.gitignore`, but it does not ignore, for example, anything in `packages/foo/.rush/temp/`.

I can fix the problem if I change the line to

```
.rush
```

**Comment by octogonz** [comment]
@trusktr  Are you saying [this line](https://github.com/microsoft/rushstack/blob/a67691a6ad6c7eb681ce9d31d90ce1c363bb02ed/apps/rush-lib/assets/rush-init/%5Bdot%5Dgitignore#L63) doesn't work?

If so, let's make a PR to fix it.

**Comment by iclanton** [comment]
The `install-run*.js` scripts should be committed to Git. The idea behind those scripts is that, generally, you get a CI agent that doesn't have Rush installed, so you can use `install-run-rush.js` to automatically install the version of Rush that the repo is using in a folder under `/common/temp/` and run a Rush command. The `install-run.js` script is just an extension of that same concept, but you can use it to install any NPM package and invoke a `.bin` script on it.

**Comment by trusktr** [comment]
@octogonz Yeah, that line's not working for me. I'm not sure what the fix is though.

@iclanton In my case I have ways to get the packages I need, plus I don't see a need for those scripts yet.

[Buddy CI](http://buddy.works) for example sets the environment up via Dockerfiles, so system dependencies are part of the image I then use for testing. As for `rush`, I install it into the repo's `devDependencies`, then the CI runs `npm test` which calls any commands, including `rush` commands, and the binary from the local `node_modules`.

**Comment by octogonz** [comment]
> This is strange. I don't understand why `common/temp/**` works while `.rush/temp/**` doesn't.

From the [Git docs](https://git-scm.com/docs/gitignore):

> - If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.

**Comment by octogonz** [comment]
So maybe something like `**/.rush/temp/`?

**Comment by trusktr** [comment]
Looks like that works! I didn't realize the `common/temp/**` has the same issue because there's only one of those at the root.

**Comment by octogonz** [comment]
> In my case I don't see a need for those scripts yet. [Buddy CI](http://buddy.works) for example sets the environment up via Dockerfiles, so system dependencies are part of the image I then use for testing. As for `rush`, I install it into the repo's `devDependencies`, then the CI runs `npm test` which calls any commands, including `rush` commands, and the binary from the repo's local `node_modules/.bin` is used.

This solves the problem for CI, but what about scripts that are run locally by developers?  For example, you might have a Git hook that needs to run an NPM tool.  In this case, the `install-run.js` script provides a way to install and run a deterministic version, using appropriate .npmrc settings.  If the `common/scripts` files really bother you, we could provide a `rush.json` setting to suppress them.  But it seems reasonable to treat these scripts as useful utilities that are always available in a Rush repo, which you can ignore if you don't need them.

They are documented [here](https://rushjs.io/pages/maintainer/enabling_ci_builds/) -- if you think those docs could be improved to make this more clear, let us know.

**Comment by octogonz** [comment]
@trusktr Here's a fix for the incorrect `.gitignore` pattern: PR https://github.com/microsoft/rushstack/pull/1707

**Comment by trusktr** [comment]
Thanks for the insights!

The doc says

> But there’s one hitch – what if your CI environment doesn’t come with Rush preinstalled? 

These scripts _might_ be useful for some people in that case. But I already have my own mechanisms in place to specify dependencies for my build environment. I ended up deleting the `.travis.yml` file too, as I don't use travis. But yeah, it'd be great to have an option to disable the parts we don't need. I like how the default rush.json has very helpful comments for each option. :+1:

**Comment by trusktr** [comment]
@octogonz Just curious, is there stuff in `.rush` that we should not ignore? What if we ignore `**/.rush/` instead of `**/.rush/temp/`?

**Comment by octogonz** [comment]
I wasn't part of the design discussion, but I believe the plan was to eventually store project-specific Rush configuration in that folder.  That's why the temporary files were stored under an explicit `./rush/temp` subfolder.

CC @iclanton @sachinjoseph
