### ISSUE TITLE
[rush] [bug] rush modifies package.json format.

### ISSUE THREAD

**Issue by trusktr** [microsoft/rushstack#1701]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

Or maybe this is a feature request. :)

**Please describe the actual behavior.**

`rush` destroys `package.json`  format.

**What is the expected behavior?**

It should leave formatting intact, like `npm` does.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** `rush`
* **Tool Version:** 5.17.2
* **Node Version:** 12.13.0
  * **Is this a LTS version?** Yes 
  * **Have you tested on a LTS version?** ^ 
* **OS:** NixOS Linux

**Comment by trusktr** [comment]
I just discovered that `rush` also changes the order of fields in package.json, which is unwanted (compared to `npm`). I guess `npm` does custom manipulation, whereas probably `JSON.stringify` will output undefined order.

**Comment by iclanton** [comment]
This is a known issue. The `JsonFile` API that we use to modify `.json` files in Rush supports modifying a file without restructuring it. I started a branch working on this a few months ago, but never finished testing it.

I just opened a PR with this: https://github.com/microsoft/rushstack/pull/1710

**Comment by iclanton** [comment]
This will be fixed in the next release of Rush. I'd like to get 5.19.0 out today, and that'll contain this fix.

**Comment by iclanton** [comment]
This has been fixed in Rush 5.19.0
