### ISSUE TITLE
[rush] Required custom parameters

### ISSUE THREAD

**Issue by boardend** [microsoft/rushstack#1762]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

Currently there is no way to make a custom parameter required. (For some cases it might be sufficient to provide a default value (which is allready supportet), but for other cases it would be nice to mark a parameter as required).

It seems that the underlying ts-command-line engine allready does support required parameters.

**Comment by octogonz** [comment]
Here's a PR: https://github.com/microsoft/rushstack/pull/1764

**Comment by octogonz** [comment]
@boardend This was published with Rush 5.21.0

**Comment by boardend** [comment]
@octogonz Thanks for your amazingly quick implementation!
