### ISSUE TITLE
[rush] How to handle more elaborate testing

### ISSUE THREAD

**Issue by patwhite** [microsoft/rushstack#1773]
**Is this a feature or a bug?**

- [X] Feature
- [ ] Bug

**Please describe the actual behavior.**
Our projects tend to have different levels of testing, from unit to integration. How should we handle that with rush? The examples seem to just do unit testing as part of the build, but some of our tests require stand-up, and are potentially long running, so I'd like to keep them as a separate process.

**Comment by iclanton** [comment]
We run quick unit tests as part of our builds and then run integration tests as a separate build phase after the build (separate from Rush). @D4N14L is working on a feature to not block dependent projects' builds on their dependencies' tests (here https://github.com/microsoft/rushstack/pull/1777).

How are you doing your integration tests?

**Comment by shawnmclean** [comment]
@iclanton any idea if this is possible yet?

**Comment by D4N14L** [comment]
The work that I was performing was nix'd in favor of a more holistic approach which is currently in progress, see #2300

**Comment by elliot-nelson** [comment]
I'm going to close this issue, as I don't think there are any testing scenarios that Rush is blocking today.

For the question in OP: I think there are at least 3 good options here (and as a monorepo grows, it's not necessarily a choice between the 3, you can mix and match them for different projects).

### PHASES

If you have various types of tests (unit, integration, etc.), and all of them are "reasonably runnable" by any developer in the repo, you can create a phased build that supports a different _phase_ for each type of test, allow projects to define commands for the phases they support, and Rush will automatically schedule all your unit and integration tests for you during the build (e.g. `rush full-test` might run `_phase:build`, `_phase:test`, and `_phase:test-integration` on each project).

### "INTEGRATION TEST" PROJECTS

Sometimes, your "integration tests" look nothing like your source code, and might be written in a framework (e.g. Playwright) that requires a specific organization for your tests. A great way to handle this is to define project `apps/my-app`, and also project `sandbox/my-app-integration-tests`.

The `test` script for `my-app` runs unit tests (e.g. Jest), whereas the `test` script for `my-app-integration-tests` runs your custom command for setting up, running, and tearing down your test framework (e.g. Playwright or Cypress). For local developers hammering away on `my-app`, the integration tests can be ignored; but in CI, affecting `my-app` will automatically count as affecting `my-app-integration-tests` too, and it'll run the test suite for you.

### SEPARATE JOBS

The last and most extreme option is defining totally different jobs (in an Azure DevOps pipeline, GHA workflow, Jenkins pipeline, etc.). The reason you'd do this is your integration tests required access to locked-down backend environments, and had to be run on runners in a specific IP pool or even self-hosted runners (in an AWS account, or on-prem, etc.). Another reason might be that you need to launch e.g. iOs/tvOS simulators on a Mac box, or build and run a set of Windows tests, so you can't just do it inline in your normal "rush build" command.

In this case, you'll usually define a totally separate _script_ in a specific project (e.g. `rushx test:integration-staging`), which does not have a Rush equivalent. Then, in your workflow, you'll determine in a small, early job whether that project has been affected by this PR:

```console
rush list --impacted-by git:origin/main | grep '@acme/my-app'
if [ $? -eq 0 ]; then
  echo "impacted-my-app=true" >> $GITHUB_OUTPUT
else
  echo "impacted-my-app=false" >> $GITHUB_OUTPUT
fi
```

And then you'll have an entirely separate job, which will check out the monorepo, run `rush install`, and then run `rushx test:integration-staging` in your `my-app` project, only if it is impacted:

```console
  my-app-integration:
    needs: changeset
    if: always() && needs.changeset.outputs.impacted-my-app == 'true'
    steps:
      - ...
```
