### ISSUE TITLE
[rush] tgz files in common/temp/projects different based on platform 

### ISSUE THREAD

**Issue by joshughes** [microsoft/rushstack#1804]
[RUSH]
**Is this a feature or a bug?**

- [ ] Feature
- [ x] Bug

On MacOS the tgz files produced are different than the tgz files produced on Linux. This leads to PNPM throwing an error because the sha512 is different when you push a commit from MacOS and then the project starts in a Linux based CI system. 

https://github.com/microsoft/rushstack/blob/82476f4983b7bbd0ed56c7acce4ebbf450a9bad9/apps/rush-lib/src/logic/InstallManager.ts#L743

The portable option is used, but in a later release in the tar package, it is updated to ensure that when gzip is used it also is safe across platforms. 

https://github.com/npm/node-tar/blob/master/CHANGELOG.md#50

Gzip needs to have this option set in order to create portable tgz files. 

**Reproduction:**
If using pnpm 4.12.1 as I am
To reproduce you need a rush repo and two platforms. MacOS and Linux. 

If using pnpm 4.12.1 as I am
1) Run `rush update --full` on one platform and make sure all files are committed. 
2) Run `rush update --full` on the other platform on the same commit SHA as Step 1. 
3) Run `git diff` and you will see that only the sha512 of the files in common/temp/projects has changed in `config/rush/pnpm-lock.yaml`, even though no package.json has changed. 

If not using pnpm... 
1) Run `rush update --full` on one platform
2) Get the MD5 or SHA hash of a tgz file in common/temp/projects
3) Run `rush update -full` on the same commit SHA on the other platform
4) Get the MD5 or SHA hash of a tgz file in common/temp/projects from the second platform. 

The MD5 or SHA hash of the tgz files should be the same... but will be different. 

**Expected Behavior: **
If I am on any platform and run `rush update --full` and I have not changed a package.json, then the sha512 sum for the local package should not change. 

* **Tool: RUSH** 
* **Tool Version: 5.22.0** 
* **Node Version: 12.16.1** 
* **OS: MacOS Catalina / Linux Ubuntu 18.04**

**Comment by sachinjoseph** [comment]
@joshughes Workaround - downgrade pnpm. Verified that this does not reproduce on pnpm <= `4.10.0-3`. It does reproduce on pnpm >= `4.10.0`.

**Comment by sachinjoseph** [comment]
The file mode in .tar header is different on different OSes even with "portable: true". On Windows I see 0644, on Ubuntu I see 0755. Not sure what has changed in pnpm > `4.9.3` that it now treats this as an error.

**Comment by sachinjoseph** [comment]
node-tar@5.05 with [this](https://github.com/npm/node-tar/blob/0691c4f7bd0f011b1bc57ca44073e620bd823632/lib/write-entry.js#L130) line commented out produces identical tarballs on Windows and Ubuntu when "portable: true" is set.

**Comment by sachinjoseph** [comment]
Hmm, in a CI environment, pnpm >= 4.10.0 by default throws if the lockfile needs an update: https://github.com/pnpm/pnpm/issues/1994#issuecomment-596211620.

**Comment by sachinjoseph** [comment]
Hmm, I am curious as to how pnpm's default CI behavior of using `--frozen-lockfile` would affect rush install on CI machines. Rush's shrinkwrap-churn-optimization might be affected - rush install does pass '--no-prefer-frozen-lockfile' flag to pnpm, but this could potentially cause problems. https://github.com/pnpm/pnpm/issues/1994. FYI @octogonz @iclanton @apostolisms.

**Comment by sachinjoseph** [comment]
Update: On pnpm 4.12.5+, rush install should work without running into errors when developer and CI platforms are different.

**Comment by sachinjoseph** [comment]
The tgz sha mismatch is still open - though it should not cause any problems for rush install at the moment.

**Comment by octogonz** [comment]
> Hmm, I am curious as to how pnpm's default CI behavior of using `--frozen-lockfile` would affect rush install on CI machines. Rush's shrinkwrap-churn-optimization might be affected - rush install does pass '--no-prefer-frozen-lockfile' flag to pnpm, but this could potentially cause problems.

@sachinjoseph That's right.  To avoid shrinkwrap churn, Rush did permit `common/temp/pnpm-lock.yaml` to deviate from `common/temp/pnpm-lock-preinstall.yaml` in small ways. This is why `--frozen-lockfile`  was disabled.
