### ISSUE TITLE
[Rush] Rush install does not run pnpm install if common-versions.json changed and shrinkwrap not changed

### ISSUE THREAD

**Issue by sunilsurana** [microsoft/rushstack#1834]
- [-] Bug

**Issue description**
We use dedicated build agents for our PR pipeline jobs so we don't clean the repo so that we save time doing npm install.

There are cases when shrinkwrap present on machine is not changed so rush skips running pnpm install command.

We had a case where common-versions.json was changed so rush skipped install and pr went thru fine. But the official build started failing because version specified in common-versions.json was not existing.

**Expected Behaviour**
Rush should include a way to check change in common-versions.json file also before skipping pnpm install

**Extra note**
This seems to be coming from [here ](https://github.com/microsoft/rushstack/blob/0584b2100d61a208276f49d2343580fd5e2485d9/apps/rush-lib/src/logic/InstallManager.ts#L884)

**Comment by octogonz** [comment]
> **Extra note**
> This seems to be coming from [here](https://github.com/microsoft/rushstack/blob/0584b2100d61a208276f49d2343580fd5e2485d9/apps/rush-lib/src/logic/InstallManager.ts#L884)

That does look like a bug.  I agree that we should add the `common-versions.json` path to the `potentiallyChangedFiles` list in that algorithm.

**Comment by octogonz** [comment]
@sunilsurana  are you able to make a PR?  Should be a fairly easy fix.

**Comment by sunilsurana** [comment]
PR for review @octogonz @iclanton 
https://github.com/microsoft/rushstack/pull/1838

**Comment by iclanton** [comment]
This has been released in Rush 5.23.2.
