### ISSUE TITLE
[api-extractor] Missing docs in generated markdown

### ISSUE THREAD

**Issue by frederikvanhevel** [microsoft/rushstack#1835]
I have the following interface:
```
/**
 * Verify email parameters
 */
export interface VerifyEmailParams {
    /**
     * Link to verify email
     */
    link: string
}
```

And this is what is generated:
```
// @public
export interface VerifyEmailParams {
    link: string;
}
```

Why is the generated markdown not containing my comments? Am i missing something here or is this a bug?

**Comment by octogonz** [comment]
Please take a look at the documentation:

https://api-extractor.com/pages/overview/intro/

The `.api.md` file is the "API Report", whose purpose is for detecting changes to API signatures.

If you want to generate markdown documentation for consumers of your API, that uses the `.api.json` "Doc Model" files which are processed by API Documenter.
