### ISSUE TITLE
[rush] git already dryrun when I publish

### ISSUE THREAD

**Issue by kamontat** [microsoft/rushstack#1848]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [X] Bug

**Please describe the actual behavior.**
the log shows that git always be `DRYRUN`

```
* DRYRUN: git tag -a @nmsys/dev-cli_v1.0.1 -m @nmsys/dev-cli v1.0.1

* DRYRUN: git tag -a @nmsys/dev-linter_v1.0.1 -m @nmsys/dev-linter v1.0.1

* DRYRUN: git tag -a @nmsys/dev-generator_v1.0.2 -m @nmsys/dev-generator v1.0.2

* DRYRUN: git tag -a @nmsys/dev-testbox_v1.0.1 -m @nmsys/dev-testbox v1.0.1

* DRYRUN: git tag -a @nmsys/dev-graph_v1.0.1 -m @nmsys/dev-graph v1.0.1

* DRYRUN: git tag -a @nmsys/dev-utils_v1.0.1 -m @nmsys/dev-utils v1.0.1

* DRYRUN: git tag -a @nmsys/cli_v1.0.1 -m @nmsys/cli v1.0.1

* DRYRUN: git tag -a @nmsys/lib-error_v1.0.1 -m @nmsys/lib-error v1.0.1

* DRYRUN: git tag -a @nmsys/lib-logger_v1.0.1 -m @nmsys/lib-logger v1.0.1

* DRYRUN: git push origin HEAD:publish-1588076204815 --follow-tags --verbose --no-verify

* DRYRUN: git checkout undefined

* DRYRUN: git pull origin undefined

* DRYRUN: git merge publish-1588076204815 --no-edit

* DRYRUN: git push origin HEAD:undefined --follow-tags --verbose --no-verify

* DRYRUN: git branch -d publish-1588076204815

* DRYRUN: git push origin --delete publish-1588076204815
```

My repository is [kamontat/nmsys](https://github.com/kamontat/nmsys)

Steps:
1. Run `rush change`
2. Run `rush publish --add-commit-details --apply --publish`

**What is the expected behavior?**

perform git action like tag, push etc.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** rushjs
* **Tool Version:** v5.23.2
* **Node Version:** v12.16.1
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** MacOS `10.15.4 (19E287)`

**Comment by iclanton** [comment]
I think you're missing the `--target-branch` CLI parameter.

[This](https://github.com/microsoft/rushstack/blob/master/common/config/azure-pipelines/templates/buildAndPublish.yaml) is the script that the pipelines in this repo use to publish. Can you give that a shot?

**Comment by kamontat** [comment]
What is difference between target brach and default brach that I set in rush.json file?

**Comment by knownasilya** [comment]
Worked for me. Should maybe default to current branch?
