### ISSUE TITLE
[rush] Rush list --json contains non json information

### ISSUE THREAD

**Issue by paulmowat** [microsoft/rushstack#1855]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [X] Bug

**Please describe the actual behavior.**

If I run "rush list --json" it outputs the following 

[1mRush Multi-Project Build Tool 5.23.2[22m[36m - https://rushjs.io[39m
Node.js version is 10.15.1 (LTS)

Starting "rush list"

{
  "projects": [{...},{...}]
}

**What is the expected behavior?**

When using the --json I'd expect to just receive the json information so that I can then easily pipe the output into a JSON parsing tool like JQ to easily use as part of a github action for CI/CD.

There needs to be a way to just get the JSON data. 

It's been mentioned before against https://github.com/microsoft/rushstack/pull/1668#issuecomment-572754895

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** Rush
* **Tool Version:** 5.23.2
* **Node Version:**  Node.js version is 10.15.1 (LTS)
* **OS:** Windows

**Comment by iclanton** [comment]
This is true. Right now, the way Rush actions are structured, the header information is printed before the individual action starts executing, so we don't know if the console output is expected to be machine-readable.

I don't think this would be too hard to fix.

**Comment by dmichon-msft** [comment]
Mainly this means we need to run the command line parser before we print the header information, instead of after. This will allow individual actions to opt out of printing it.
