### ISSUE TITLE
[rush] Docs request - comparison with lerna

### ISSUE THREAD

**Issue by mmkal** [microsoft/rushstack#1859]
I just had a read through https://github.com/microsoft/rushstack/issues/673, which was a wild ride. It is focused more on copyright infringement than technical documentation, and is now locked, so I'm opening a new issue.

I work on a few medium-sized projects that use lerna and yarn workspaces extensively. Rush is obviously of interest, but something I couldn't find anywhere in the docs or the website, was a comparison with lerna (feature-wise - I'm _not_ talking about whether any code was taken from lerna years ago - I just want to know what the pros and cons of switching a medium-sized project are).

There are obviously many similarities `rush version` vs `lerna version`, `rush publish` vs `lerna publish` etc. It'd be great to have a page called `rush vs lerna`, similar to the [npm vs pnpm vs yarn](https://rushjs.io/pages/maintainer/package_managers/) page, at least documenting at a high level:

- what safety do you gain?
- what features do you gain?
- what features do you lose?
- what flexibility do you lose?
- can/should rush and lerna be used together?

Even better would be a migration guide for simple lerna setups, maybe with a PR in an example project.

**Comment by octogonz** [comment]
@mmkal Good idea.  Could you reopen this issue on https://github.com/microsoft/rushjs.io-website/issues ? That's where we track documentation requests.
