### ISSUE TITLE
[rush] Support for PNPM Workspaces

### ISSUE THREAD

**Issue by D4N14L** [microsoft/rushstack#1887]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

Currently, Rush uses it's own logic to generate a temporary project for each Rush monorepo project, and adds this project to a single temporary project. Rush then runs install on this temporary project, and then manually links the resulting node_modules folders for each project into the related Rush project.

**What is the expected behavior?**

Rush should use the existing [PNPM workspaces](https://pnpm.js.org/en/workspaces) feature to support monorepo package install. This will allow Rush to get out of the business of generating temporary projects within `/common/temp` folders and manually linking to Rush projects, as the workspaces feature does all of this in-place. It will also allow the shrinkwrap file checked in with a Rush-managed repository to actually reflect how the install is performed, instead of containing placeholder projects for each repository project. Additionally, workspaces can be used with the `--filter` argument to create filtered installs which target a specific subset of monorepo projects, much in the way that `rush build -to ...` operates.

**Comment by wbern** [comment]
Filtered installs! Omg!

**Comment by arri-cc** [comment]
@D4N14L does #1938 close this issue?

**Comment by D4N14L** [comment]
> @D4N14L does #1938 close this issue?

I’ve been leaving it open for while we look for bugs in the implementation, but do plan on closing it soon

**Comment by arri-cc** [comment]
@D4N14L workspaces seems to work great with `pnpm v 5.3.0` and it solves my problem described in #1990. I actually no longer see the point making rush link work without workspaces, for the edge case I presented.

**Comment by D4N14L** [comment]
Given that it's been a bit since this was released and no major bugs have been reported, I'm going to close this one out :)
