### ISSUE TITLE
[eslint-config] Outdated dependencies leading to errors while linting

### ISSUE THREAD

**Issue by terehov** [microsoft/rushstack#1895]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**
Running eslint leads to errors related to an outdated version of `@typescript-eslint/typescript-estree`
Error: 
```
  0:0  error  Parsing error: Cannot read property 'parent' of null
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Its really hard to reproduce it and I wasn't able to set up an example repo. It is somehow related to comments inside the AST tree analyzed by eslint.
https://github.com/typescript-eslint/typescript-eslint/issues/1114

Another problem is that this version does not officially support current TypeScript versions: 
```
SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.7.0

YOUR TYPESCRIPT VERSION: 3.9.3
```

**What is the expected behavior?**
`eslint` should finish without internal errors. 

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 
eslint-config
* **Tool Version:** 
0.5.8 
* **Node Version:** 
v12.16.3  
* **Is this a LTS version?** 
yes
* **Have you tested on a LTS version?** 
yes
* **OS:** 
macOS 10.15.5

This error is not present when updating `@typescript-eslint/typescript-estree` to the latest 2.x (`2.34.0`) version.

Additional Question: Do you plan to upgrade to eslint 7 and @typescript-eslint 3?

From my tests version `2.34.0` seems to be working fine.

**Comment by octogonz** [comment]
Fixed by https://github.com/microsoft/rushstack/pull/1936
