### ISSUE TITLE
[rush] Support for Node >= v13

### ISSUE THREAD

**Issue by aeisenberg** [microsoft/rushstack#1896]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

Currently, rush does not support any version of node greater than 12. v12 is getting old. It would be great to support newer versions so we can all upgrade our projects.

If you let me know what needs to be done and it's not too complex, I can look into this.

**Comment by octogonz** [comment]
Node 12 is the [latest LTS release](https://nodejs.org/en/download/releases/) of Node. 

For professional usage, we only recommend/support LTS releases.  Node 14 will not graduate to LTS until [October 2020](https://nodejs.org/en/about/releases/).

That said, people who ship libraries often do want to test out experimental releases of Node.js to anticipate possible incompatibilities.  There are various mechanisms for that such as the `RUSH_ALLOW_CUSTOM_NODE_VERSION` variable, and `suppressNodeLtsWarning` in rush.json.

Hmm... Looks like [UPCOMING_NODE_LTS_VERSION](https://github.com/microsoft/rushstack/blob/58beb83a82f0eef8b3ac3f6b0be4ff234c9e25b2/apps/rush-lib/src/logic/NodeJsCompatibility.ts#L13) is currently set to 12.  Want to make an PR to update it to 14?

See  https://github.com/microsoft/rushstack/issues/1373 and https://github.com/microsoft/rushstack/pull/1388 for background.

**Comment by aeisenberg** [comment]
Thanks. I wasn't aware of the extra parameters I can set.
