### ISSUE TITLE
[rush] Rush deploy hard fails on missing optionalDependencies

### ISSUE THREAD

**Issue by jlsjonas** [microsoft/rushstack#1908]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

Considering this a bug as optionalDependencies of dependencies of dependencies shouldn't be required.

`ERROR: Cannot find module 'fsevents/' from '/path/to/common/temp/node_modules/.pnpm/registry.npmjs.org/chokidar/2.1.8/node_modules/chokidar'`

**What is the expected behavior?**
optionalDependencies to be included if available, skipped otherwise

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** Rush (using pnpm)
* **Tool Version:** 5.24.1
* **Node Version:** 10.20.1 (LTS)
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** Ubuntu 20.04

Related to #1078

**Comment by jlsjonas** [comment]
Failure is happening on line 228 of the new `deployManager.ts`
https://github.com/microsoft/rushstack/blob/b9d87052535e3e0ec5237c2046ec8d75d7d48bdb/apps/rush-lib/src/logic/deploy/DeployManager.ts#L228

**Comment by octogonz** [comment]
This fix was released with Rush `5.24.2`.
