### ISSUE TITLE
[rush] paths are broken after a no-op rush install

### ISSUE THREAD

**Issue by jlsjonas** [microsoft/rushstack#1925]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**
```
ERROR: Internal Error: Cannot find installed dependency ...
"/<path/to/repo>/common/temp/node_modules/.pnpm/local/%2F<path%2Fto%2Frepo>%2Fcommon%2Ftemp%2Fprojects%2F<projectname>.tgz/node_modules
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**
`rush install`
`rush install` (_doing nothing_)
`rush link -f`

**What is the expected behavior?**
command to work

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** rush using pnpm
* **Tool Version:** 5.24.4 (pnpm 4.9.3, currently running new tests with 4.14.4)
* **Node Version:** 10.20.1 (LTS)
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** Ubuntu 20.04 LTS

Current workaround: `rush purge`

**Comment by apostolisms** [comment]
@jlsjonas can you please provide a repro for this ?

**Comment by jlsjonas** [comment]
We can no longer reproduce this, likely due to a subtle change in our config and/or pnpm version update
