### ISSUE TITLE
[rush] apps & tabs crash when running rush update on macOS

### ISSUE THREAD

**Issue by qin-guan** [microsoft/rushstack#1934]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

When running `rush update`, apps (WhatsApp, Discord) and tabs open in Microsoft Edge crashes on macOS

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Run `rush update` while having WhatsApp/Edge open on macOS

**What is the expected behavior?**

No apps/tabs crash

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 

Rush Multi-Project Build Tool 5.23.4 (unmanaged) - https://rushjs.io

* **Tool Version:** 

Rush Multi-Project Build Tool 5.23.4 (unmanaged) - https://rushjs.io

* **Node Version:** 

Node.js version is 10.20.1 (LTS)

  * **Is this a LTS version?** 

Yes

  * **Have you tested on a LTS version?** 

Yes

* **OS:** 

macOS 10.15.6 Beta

**Comment by octogonz** [comment]
That is very strange.  Could you try some experiments:

- Try using `--network-concurrency=1` with `rush update`
- Try with Node 12 and Node 10; does it affect all versions?
- Try the latest Rush (5.26.0) and a somewhat older version (5.17.2)

Your OS appears to be an unsupported version: "macOS 10.15.6 Beta"  If possible, maybe you could also try with a non-beta version of macOS.

I'm somewhat skeptical that this is a Rush bug.  A crashing browser tab can be a potential security vulnerability for the web browser; if you have a reliable repro, you might consider reporting your issue to the [Edge support channels](https://developer.microsoft.com/en-us/microsoft-edge/support/).

**Comment by qin-guan** [comment]
managed to figure out the issue, it was actually due to the 256 maxfiles limit on macOS, increasing the limit fixes the problem

**Comment by octogonz** [comment]
>  it was actually due to the 256 maxfiles limit on macOS, increasing the limit fixes the problem

@qin-guan Is this a common problem on macOS? Would it be useful for Rush detect and warn about it?  (Or, is there some valid situation where `maxfiles` /should/ be 256 when using Rush?)

Maybe `rush install` could invoke `launchctl` or `ulimit` and report a warning if `maxfiles` is too small. What do you think?

**Comment by qin-guan** [comment]
sorry for the late reply,
i'm not really sure how common it is, since different sized projects and running apps would have different number of open files, 256 for maxfiles seems unusually low nonetheless. 
i think it is a good idea if rush could warn about it, or if it was in the documentation, however this might just be an isolated case for me, since i can't seem to find anything online about it.

**Comment by octogonz** [comment]
[This article](https://krypted.com/mac-os-x/maximum-files-in-mac-os-x/) says *"By default, the maximum number of files that Mac OS X can open is set to 12,288 and the maximum number of files a given process can open is 10,240."*  

So maybe your laptop was not in the default configuration?

[This article](https://wilsonmar.github.io/maximum-limits/) implies that the reading/writing of the setting varies a lot between OS versions, so maybe there is not a reliable straightforward way for Rush to validate it.

Maybe we should wait and see if other people encounter the same problem.

**Comment by qin-guan** [comment]
if i am not wrong, for macOS Catalina and Big Sur, the defualt is 256. Yeah we should probably wait and see for now
