### ISSUE TITLE
[rush] "You are not on master branch, do you want to continue?"

### ISSUE THREAD

**Issue by slavafomin** [microsoft/rushstack#1940]
Hello! Thank you for your hard work.

After updating the Rush and pnpm to the latest versions I've started to get the following prompts during release: `You are not on master branch, do you want to continue? [y/N]`

I'm running the following command in master branch to start the releasing process: `rush publish --apply --publish --target-branch master`

What could be the issue? Thanks.

* **Tool:** Rush
* **Tool Version:** 5.26.0
* **Node Version:** 12.16.1 (LTS)
* **OS:** Ubuntu 18.04.4 LTS

**Comment by apostolisms** [comment]
@slavafomin Rush shouldn't generate this prompt, are you sure it is coming from Rush ?

**Comment by jcao219** [comment]
It's coming from here:

https://github.com/pnpm/pnpm/blob/f00dabd2d109e8b24e1794e057ed539643f9e3ec/packages/plugin-commands-publishing/src/publish.ts#L101

I think you should add `git-checks=false` to your `common/config/rush/.npmrc` file

**Comment by octogonz** [comment]
`rush publish` is a CI automation command. It seems wrong for it to be showing interactive prompts on the console.

We should look at the Git history and determine why this was introduced. Can we simply remove it?  

Or should we convert it to a hard error, with a `--yes-i-know-what-i-am-doing` type parameter to disable the validation?

**Comment by jcao219** [comment]
Results from pnpm version 5 defaulting its 'gitChecks' option to true by default.
Should Rush by default put `git-checks=false` in `common/config/rush/.npmrc-publish` then?

**Comment by iclanton** [comment]
@jcao219 - we could maybe put that in `.npmrc`, commented-out by default with a note about this issue.

@octogonz, what do you think?

**Comment by octogonz** [comment]
@jcao219 @zkochan Could somewhat clarify what `git-checks` does? From [the docs](https://pnpm.js.org/en/next/npmrc#git-checks) I see only this description:

> When true, `pnpm publish` checks if current branch is your publish branch (master by default), clean, and up-to-date.

If this means that `pnpm publish` will interrupt the operation and wait for interactive input from the command line, that is inappropriate for `rush publish`, which is designed for CI jobs.  (If so I'd suggest for Rush to somehow override PNPM's defaults and force `git-checks=false`.)

I suppose that everyday PNPM users might invoke `pnpm publish` manually. But in Rush's world, manual publishing is generally a security concern (and/or compliance violation) for any shipping package.

**Comment by zkochan** [comment]
If there are uncommitted changes, or you did not pull some new changes from remote, or the branch name is not master, you'll be asked to confirm that you want to proceed.

**Comment by octogonz** [comment]
Can this be switched off via a command-line parameter or environment variable? Or is `.npmrc` the only way to specify `git-checks=false`?

**Comment by zkochan** [comment]
it can be switched off through CLI and env variable

**Comment by octogonz** [comment]
Here's a PR: https://github.com/microsoft/rushstack/pull/2056

@jcao219 @slavafomin  Could someone test this and confirms that it resolves the problem?  Some instructions for testing Rush builds are here: https://rushjs.io/pages/contributing/

**Comment by slavafomin** [comment]
Thanks Pete! I will test this on first occasion.

**Comment by jcao219** [comment]
Yep, I can test it now.
