### ISSUE TITLE
[eslint-config] patch-eslint does not work with eslintv7

### ISSUE THREAD

**Issue by qin-guan** [microsoft/rushstack#1945]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

`eslint-config` does not work with eslintv7

might be due to `require("@rushstack/eslint-config/patch-eslint6");` being for v6 and not v7?

.eslintrc.js
```
require("@rushstack/eslint-config/patch-eslint6");

module.exports = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "tsconfig.json",
    sourceType: "module",
    tsconfigRootDir: __dirname
  },
  plugins: ["@typescript-eslint/eslint-plugin"],
  extends: [
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier",
    "prettier/@typescript-eslint",
    "@rushstack/eslint-config"
  ],
  root: true,
  env: {
    node: true,
    jest: true
  },
  rules: {
    "@typescript-eslint/interface-name-prefix": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-parameter-properties": "off"
  }
};
```

error

```
TypeError [ERR_INVALID_ARG_VALUE]: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js': The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received {
  filePath: '/Users/qinguan/Desktop/path-to-proj/.eslintrc.js',
  matchBasePath: '/Users/qinguan/Desktop/path-to-proj/api...
Referenced from: /Users/qinguan/Desktop/path-to-proj/.eslintrc.js
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

**What is the expected behavior?**

should not cause error 

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 

`@rushstack/eslint-config`

* **Tool Version:** 

`    "@rushstack/eslint-config": "^0.5.8"`

* **Node Version:** 

`v12.18.0`

  * **Is this a LTS version?** 

Yes

  * **Have you tested on a LTS version?** 

Yes

* **OS:** 
macOS 10.15.6 Beta

**Comment by octogonz** [comment]
This will be fixed with PR https://github.com/microsoft/rushstack/pull/1936

The PR is code complete, but I've been testing it on several repos and there are still some regressions that need to be addressed before we can merge it.
