### ISSUE TITLE
.npmrc is ignored during `rush publish`

### ISSUE THREAD

**Issue by mpiroc** [microsoft/rushstack#1951]
Rush copies `common/config/rush/.npmrc` to `common/temp/.npmrc` during `rush update`. However, `rush publish` invokes the package manager in each individual package folder, not in `common/temp`. Therefore, the `.npmrc` is ignored.

I can work around this by making a copy of `.npmrc` in each individual package folder. But this is cumbersome, could easily become out of sync, and contradicts the [Rush docs](https://rushjs.io/pages/configs/npmrc/): 

> Prior to **invoking the package manager**, Rush will always copy this file to the folder where installation is performed.

This is currently preventing me from upgrading `pnpm` from `4.x` to `5.x`. PNPM `5.x` changes the default of the `git-checks` setting from `false` to `true`. This causes `pnpm publish` to fail if the repository is in detached head mode (i.e., on a CI machine).

Therefore, I need to override the setting, either by passing `--no-git-checks` to `pnpm` (not possible because Rush invokes `pnpm` for me), or through `.npmrc`.

## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

Rush invokes `pnpm publish` without copying `.npmrc` to the working directory.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

1. Create an empty rush repo and add a hello world-type package. Set your package manager to pnpm 5.x.
2. Add the line `git-checks=false` to `common/config/rush/.npmrc`.
3. Do any of the following: Enter detached HEAD mode, check out a branch other than master, or make some changes in your working directory (and do not commit them).
4. Run `rush publish`

**What is the expected behavior?**

Rush successfully publishes each package using pnpm.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** `rush`
* **Tool Version:** `5.26.0`
* **Node Version:** `12.16.3`
  * **Is this a LTS version?** Yes
  * **Have you tested on a LTS version?** Yes
* **OS:** Ubuntu (in WSL2 under Windows 10)

**Comment by iclanton** [comment]
Sounds like you're hitting an issue similar to this one: https://github.com/microsoft/rushstack/issues/1940

Rush uses another `.npmrc` file ([`common/config/rush/.npmrc-publish`](https://github.com/microsoft/rushstack/blob/master/common/config/rush/.npmrc-publish)) for publishing (introduced here: https://github.com/microsoft/rushstack/pull/1602). It does this by creating a `common/temp/publish-home` folder, copying that file (as `common/temp/publish-home/.npmrc`) and setting that folder's path to the `HOME` (or `USERPROFILE` on Windows) env variable during publish.

The primary purpose here is to allow credentials to be passed to the package manager differently when publishing than when installing dependencies, but there's no reason you can't put other options in that file.

Give that a shot?

**Comment by octogonz** [comment]
There was some more conversation about this [on Gitter](https://gitter.im/rushstack/rushstack?at=5eefbbe9613d3b3394fdb8bc).  

**.npmrc-publish** is a relatively new feature, so it seems like we need to update our docs.

**Comment by octogonz** [comment]
@mpiroc Sorry about the trouble you encountered.

Here is a PR that adds a "rush init" template for **.npmrc-publish** with some more detailed documentation:

PR https://github.com/microsoft/rushstack/pull/1956

Please let us know:
1. Would these file comments have been sufficient to prevent the trouble that you encountered? (If not, what should we explain better?)
2. Do these docs correctly describe Rush's behavior, as far as your experience?

After merging this PR, we'll also add the same info to the website.
