### ISSUE TITLE
[rush] How are you supposed to share configs between projects?

### ISSUE THREAD

**Issue by rdeusser** [microsoft/rushstack#1952]
I'm not seeing any sort of documentation or issue on it, but is there a way to share something like a `tsconfig.json` or a `jest.config.js` with every project in the monorepo? I'd prefer an approach such as how the `node_modules` folder is symlinked to each project, but I just can't find any information.

**Comment by iclanton** [comment]
Rush currently doesn't have an automatic way to do this, but you can create a project containing your configurations and use the `extends` and `preset` fields of `tsconfig.json` and `jest.config.js[on]` to point individual projects' configs at the base configs in your configuration project.

This is actually how `tsconfig.json` files work in this repo. See here: https://github.com/microsoft/rushstack/blob/master/apps/rush/tsconfig.json#L2

Would that solve your problem?

**Comment by rdeusser** [comment]
Yeah that seems like a pretty good solution. Thanks @iclanton!
