### ISSUE TITLE
[rush] Rush integration with vsts-npm-auth/better-vsts-npm-auth

### ISSUE THREAD

**Issue by iclanton** [microsoft/rushstack#1954]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

I'm finding myself needing to run [`better-vsts-npm-auth`](https://www.npmjs.com/package/better-vsts-npm-auth) in my `common/config/rush` folder several times per day to regenerate package feed credentials. It'd be really useful if Rush could run this automatically. It would ideally be run in the `common/temp` (or `common/config/rush`) folder, and be configurable per-clone.

**Comment by octogonz** [comment]
I'm a little nervous about officially integrating an authentication component that is:

1. Proprietary to Azure DevOps
2. Published by an individual person who is not affiliated with Microsoft
3. Only has 1,000 downloads/week

**Comment by iclanton** [comment]
This may be fixed by parts of https://github.com/microsoft/rushstack/issues/1994. Closing this in favor of that.
