### ISSUE TITLE
rush link is not working.

### ISSUE THREAD

**Issue by jt112** [microsoft/rushstack#1967]
ERROR: Internal Error: Cannot load shrinkwrap at "I:\office-online-ui\common\temp\pnpm-lock.yaml"

**Comment by apostolisms** [comment]
Can you please try `rush update --full` and if the issues continues to happen, send a repro?

**Comment by iclanton** [comment]
Closing this. Please reopen if this is still an issue.

**Comment by futurist** [comment]
I can reproduce this issue with below steps:

1. run `npm config set package-lock false`
2. `rush init` to setup a new repo and add projects(any projects).
3. `rush change --full` always failed.

I think it's a problem when package-lock is disabled, rush seems not compatible with this situation.
