### ISSUE TITLE
rush update / pnpm install incongruence (--strict-peer-dependencies with nextjs demonstration)

### ISSUE THREAD

**Issue by dfee** [microsoft/rushstack#1973]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**
`rush update` fails to install packages, but running the failed `pnpm install` command directly succeeds.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

1. checkout the repo (branch: nextjs): https://github.com/dfee/rush-issues/tree/nextjs
2. run rush update, to get the following error

>  ERROR  @rush-temp/primary > next: @next/react-refresh-utils@9.4.4 requires a peer of react-refresh@0.8.3 but none was installed.
> Resolving: total 718, reused 33, downloaded 0
> 
> The command failed:
>  /Users/dfee/code/rush-issues/common/temp/pnpm-local/node_modules/.bin/pnpm install --store /Users/dfee/code/rush-issues/common/temp/pnpm-store --no-lock --no-prefer-frozen-lockfile --strict-peer-dependencies --resolution-strategy=fewer-dependencies

3. run the failed pnpm command directly:

> /Users/dfee/code/rush-issues/common/temp/pnpm-local/node_modules/.bin/pnpm install --store /Users/dfee/code/rush-issues/common/temp/pnpm-store --no-lock --no-prefer-frozen-lockfile --strict-peer-dependencies --resolution-strategy=fewer-dependencies

**What is the expected behavior?**
...

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** rush
* **Tool Version:** v5.27.0
* **Node Version:** v12.16.3
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** this is lts.
* **OS:** macOS 10.15.3

**Comment by octogonz** [comment]
Will [PNPM workspaces](https://github.com/microsoft/rushstack/pull/1938) fix this issue? That branch is in a testable state now.

**Comment by D4N14L** [comment]
> Will [PNPM workspaces](https://github.com/microsoft/rushstack/pull/1938) fix this issue? That branch is in a testable state now.

Just ran workspaces against this project, looks like it works as expected!
```
Starting "rush update"


Validating package manager shrinkwrap file.

Shrinkwrap file could not be found, skipping validation.

Trying to acquire lock for pnpm-5.2.6
Acquired lock for pnpm-5.2.6
Found pnpm version 5.2.6 in C:\Users\danade\.rush\node-v12.18.1\pnpm-5.2.6

Symlinking "D:\Workspace\Testing\rush-issues\common\temp\pnpm-local"
  --> "C:\Users\danade\.rush\node-v12.18.1\pnpm-5.2.6"
Copying D:\Workspace\Testing\rush-issues\common\config\rush\.npmrc --> D:\Workspace\Testing\rush-issues\common\temp\.npmrc
Updating D:\Workspace\Testing\rush-issues\common\temp\pnpmfile.js

Updating workspace files in D:\Workspace\Testing\rush-issues\common\temp
Finished creating workspace (0.02 seconds)

The shrinkwrap file contains the following issues:
  Preferred versions from common-versions.json have been modified.

Deleting files from D:\Workspace\Testing\rush-issues\common\temp\node_modules

Running "pnpm install" in D:\Workspace\Testing\rush-issues\common\temp

 WARN  Deprecated options: 'lock', 'resolution-strategy'
Scope: all 2 workspace projects
Using hooks from: D:\Workspace\Testing\rush-issues\common\temp\pnpmfile.js
readPackage hook is declared. Manifests of dependencies might get overridden
.                                        | +719 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 725, reused 0, downloaded 725, done
node_modules/.pnpm/@ampproject/toolbox-optimizer@2.4.0/node_modules/@ampproject/toolbox-optimizer: Running postinstall snode_modules/.pnpm/@ampproject/toolbox-optimizer@2.4.0/node_modules/@ampproject/toolbox-optimizer: Running postinstall script, done in 479ms

Updating D:\Workspace\Testing\rush-issues\common\config\rush\pnpm-lock.yaml
repo-state.json has been modified and must be committed to source control.

Linking projects together...
Writing "D:\Workspace\Testing\rush-issues\common\temp\rush-link.json"

Linking finished successfully. (0.04 seconds)

Next you should probably run "rush build" or "rush rebuild"

Rush refreshed some files in the "common/scripts" folder.  Please commit this change to Git.

Rush update finished successfully. (9.80 seconds)
```

**Comment by devin-fee-ah** [comment]
Awesome. Just returned home and tested. It does seem to work.

Just to be clear, I made the following changes:
- add `useWorkspaces: true` to `rush.json` (p.s. i think a new jsonschema file should be uploaded, as VS Code complains about that option)
- upgraded `rush` to 5.28.0
- upgraded `pnpm` to 5.3.0 (not sure what the minimum required version of pnpm is, but figured i'd update it anyway).
- run `rush update --full`

It might be referenced in another issue, but is it expected that pnpm with workspaces becomes the "suggested" path for use with Rush?

**Comment by D4N14L** [comment]
> It might be referenced in another issue, but is it expected that pnpm with workspaces becomes the "suggested" path for use with Rush?

I can see a future where this becomes the default, though I can’t speak for @octogonz ... Currently however it’s experimental and were on the lookout for bugs. If you would like to use it and report back on any issues though, that would be great!

**Comment by devin-fee-ah** [comment]
I'll definitely use it on my non-primary repo, and report any issues I find.

I'd like to find some convergence point in the future where this feature moves form "experimental" to "stable" (or whatever) and flip over then. I'm tracking a few of these features now, but haven't seen the full lifecycle for an experimental feature to know what the criteria for that promotion... (not even asking for some formally hard-defined criteria, just the general understanding for when an experiment is baked).

@D4N14L thanks for your work 😄

**Comment by D4N14L** [comment]
Closing this out because workspaces resolves this issue, and has been available for a bit now with no major (reported) blocking bugs :)
