### ISSUE TITLE
[rush] when using pnpm `rush link` fails to match peer dependencies installed via tarballs from arbitrary URLs

### ISSUE THREAD

**Issue by arri-cc** [microsoft/rushstack#1990]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

This issue is likely solved with support for pnpm workspaces here #1938, but for now it's an issue.

For example, I'm building a project that references expo.io's custom version of `react-native`, with an dependencies like this in it's `package.json`:

```
"dependencies": {
  "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz",
  "@react-native-community/masked-view": "0.1.6"
 }
 ```
 
The `@react-native-community/masked-vew` has a `peerDependency` on `react-native` and the `react-native` package that we installed is a customized version provided by [expo.io](https://expo.io), with it's `package.json` providing the following values:

```js
{
  "name": "react-native",
  "version": "0.62.2",
  "bin": "./cli.js",
  "description": "A framework for building native apps using React",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git@github.com:facebook/react-native.git"
  },
  "engines": {
    "node": ">=8.3"
  },
  "jest-junit": {
    // redacted for brevity
  },
  "files": [
    // redacted for brevity
  ],
  "scripts": {
  	// redacted for brevity
  },
  "peerDependencies": {
    "react": "16.11.0"
  },
  "dependencies": {
  // redacted for brevity
  }
}
```

 pnpm installs this fine and recognizes it as `react-native@0.62.2`, yet if any other packages list `react-native` as a peer dependency, when `rush link` is run during a `rush update`, it throws the following error:

 ```
 ERROR: Internal Error: The version
'0.62.2' of peer dependency 'react-native' is invalid
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

The `react-native` package appears in the `pnpm-lock.yaml` shrinkwrap file like so:

```yaml
dependencies:
  react-native: github.com/expo/react-native/archive/sdk-38.0.0.tar.gz_686ec919160581136b28b7fe63160a42
lockfileVersion: 5.1
packages:
  github.com/expo/react-native/archive/sdk-38.0.0.tar.gz_686ec919160581136b28b7fe63160a42:
    dependencies:
      # redacted for brevity
    dev: false
    engines:
      node: '>=8.3'
    hasBin: true
    id: github.com/expo/react-native/archive/sdk-38.0.0.tar.gz
    name: react-native
    peerDependencies:
      react: 16.11.0
      react-native: '*'
    resolution:
      tarball: 'https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz'
    version: 0.62.2
specifiers:
  react-native: 'https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz'
```

If I swap the expo `react-native` package for the version hosted via the npm registry everything works fine. I believe the problem is with how the `rush link` process performs look ups for existing packages.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

1. create a new repo and initialize with `rush` and setup `pnpm v4.14.4` _pnpm v4.14.4 is required to avoid a separate issue with tarball packages fixed here #1986 
2. add a project that depends on the following packages
   - "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz",
   - "@react-native-community/masked-view": "0.1.6"
3. `rush update`

**What is the expected behavior?**

Peer dependencies are resolved by packages installed via tarball URLs

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool: rush** 
* **Tool Version: 5.27.1** 
* **Node Version: 10.18.1** 
* **pnpm Version: 4.14.4 and 5.2.6**
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS: MacOS**

**Comment by arri-cc** [comment]
I believe with #1887 integrated into `rush v5.28.0` there's no reason to try to make this work without the use of pnpm workspaces.

**Comment by D4N14L** [comment]
Closed out due to comment by @arri-cc referenced above.
