### ISSUE TITLE
[rush] Dependency of dependency not installing

### ISSUE THREAD

**Issue by knownasilya** [microsoft/rushstack#1998]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

Rush repo here: https://github.com/Strider-CD/strider/tree/chore/rush

To reproduce issue, do `rush install && rush build`
An error is returned by the clients/strider-ui build step, that it can't find `clients/strider-ui/node_modules/@fortawesome/fontawesome-svg-core`. The dependency is coming from `@fortawesome/ember-fontawesome` which is a direct dependency of `strider-ui` and the missing dependency is it's direct dependency (defined here https://github.com/FortAwesome/ember-fontawesome/blob/master/package.json#L51).

I tried `purge` and reinstall, but the module isn't there or in common. It does install when using `npm install` directly.

**What is the expected behavior?**

Expect the module to be installed.

* **Tool: rush** 
* **Tool Version: 5.27.3** 
* **Node Version: 14.5.0** 
  * **Is this a LTS version? no** 
  * **Have you tested on a LTS version? no, see https://github.com/microsoft/rushstack/issues/1997** 
* **OS: macos latest**

**Comment by iclanton** [comment]
Your repo is using the PNPM package manager (which is the default in Rush). PNPM installs dependencies in a sandbox such that only dependencies that are declared in `package.json` are resolvable.

In your repo, `clients/strider-ui/node_modules/@fortawesome/ember-fontawesome` is a symlink to `common/temp/node_modules/.pnpm/registry.npmjs.org/@fortawesome/ember-fontawesome/0.2.1/node_modules/@fortawesome/ember-fontawesome`, and `@fortawesome/fontawesome-svg-core` is made available to `@fortawesome/ember-fontawesome` via `common/temp/node_modules/.pnpm/registry.npmjs.org/@fortawesome/ember-fontawesome/0.2.1/node_modules/@fortawesome/fontawesome-svg-core`, which, itself, is a symlink to `common/temp/node_modules/.pnpm/registry.npmjs.org/@fortawesome/fontawesome-svg-core/1.2.29/node_modules/@fortawesome/fontawesome-svg-core`. This structure prevents undeclared dependencies from being available to packages, but it comes with the downside that algorithms that resolve modules must more closely follow the Node spec.

This sounds like an issue with the `@fortawesome/ember-fontawesome` package. You can try changing your package manager to Yarn, or reporting this issue to the owners of that package.

![image](https://user-images.githubusercontent.com/5010588/86571204-ec74e380-bf25-11ea-9e98-c1ce12c89ae5.png)

**Comment by knownasilya** [comment]
You are correct, resolved with https://github.com/FortAwesome/ember-fontawesome/pull/153
