### ISSUE TITLE
[api-extractor] dts rollup cannot handle "export { default } from 'foo';" correctly

### ISSUE THREAD

**Issue by adventure-yunfei** [microsoft/rushstack#2014]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

Using `export { default } from 'foo';` syntax, dts rollup will generate a result with invalid typescript syntax.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

With following entry dts file:
```ts
export { default } from 'foo';
```

api-extractor will generate following dts rollup result:
```ts
import { default } from 'foo';
export default default;

export { }
```

This is not a valid ts syntax. `default` is a reserved keyword.

**What is the expected behavior?**

Generate something like:
```ts
import { default as Foo } from 'foo';
export default Foo;

export { }
```

Or anything that's valid and with correct exports.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool: api-extractor** 
* **Tool Version: 7.9.1** 
* **Node Version: v10.21.0** 
  * **Is this a LTS version? yes** 
  * **Have you tested on a LTS version?** 
* **OS: windows 10**

**Comment by octogonz** [comment]
@adventure-yunfei are you able to make a PR? I have been really busy with Rush lately and have a backlog of API Extractor work to do (including merging one of your own  other PRs :-) ).

**Comment by adventure-yunfei** [comment]
Sure. I would fix them on my own to keep api-extractor working for my project anyway 😄. For this issue it would be a simple fix.
