### ISSUE TITLE
[rush] `rush link` support should be removed from workspace installs

### ISSUE THREAD

**Issue by D4N14L** [microsoft/rushstack#2015]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

`rush link` is still performed by Rush after performing a workspaces install. Since there is no more linking occurring (only generation of a few files used by Rush), support for this command should be removed when using workspaces.

**What is the expected behavior?**

Generation of necessary files by Rush should be done after install completes, as a final step when running `rush install` or `rush update`. `shrinkwrap-deps.json` is still useful to have as a dependency tracking tool (it is also used by `rush build` to determine if the build can be incrementally skipped after an install). `rush-link.json` is also still widely used internally (for example, in the `TaskScheduler` used to schedule build order).

Removing the `rush-link.json` file and replacing with a proper flag file, similar to `last-install.flag` is also something that could be considered, though this would take a bit more work.

`rush link` should error out when run while using workspaces, similarly to how `rush install --no-link` errors out for workspaces. Should the ability to skip linking be available in the future, we could consider adding this support back in.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** rush-lib
* **Tool Version:** 5.28.0

**Comment by octogonz** [comment]
`rush unlink` is a handy command that I often use to clear out the `node_modules` folders for projects.

Does PNPM provide an equivalent of that?

Otherwise +1 for this proposal.

**Comment by iclanton** [comment]
This work was completed in https://github.com/microsoft/rushstack/pull/2023
