### ISSUE TITLE
[rush] ERROR: Internal Error: Target does not exist

### ISSUE THREAD

**Issue by rommik** [microsoft/rushstack#2044]
When I do `rush deploy --overwrite` I get the following error
````
Copying folders...
Writing deploy-metadata.json
Creating symlinks...

ERROR: Internal Error: Target does not exist: {
"kind": "folderLink",
"linkPath":
"D:\\some\\path\\app1\\node_modules\\envsub\\Dockerfiles",
"targetPath": "D:\\some\\path\\common\\temp\\node_modules\\envsub\\Dockerfiles"
}
You have encountered a software defect. Please consider reporting the issue to the maintainers of this
application
````
The link path is good and so it target Path. What could be the problem?

VsCode shows that linkPath is a symlink (if it helps or makes a difference)
There's nothing special about envsub package that I can think of that would cause this error.

**Comment by octogonz** [comment]
@rommik the source code says:

```ts
      for (const linkToCopy of linksToCopy) {
        if (!this._deploySymlink(linkToCopy, deployState)) {
          // TODO: If a symbolic link points to another symbolic link, then we should order the operations
          // so that the intermediary target is created first.  This case was procrastinated because it does
          // not seem to occur in practice.  If you encounter this, please report it.
          throw new InternalError('Target does not exist: ' + JSON.stringify(linkToCopy, undefined, 2));
        }
      }
```
Can you confirm that your case involves a symlink pointing to another symlink?

If so, we know what we need to do to fix this.

**Comment by octogonz** [comment]
(Also if you are able to isolate a repro branch, that would be helpful for validating that we fixed the right problem for your case.)

**Comment by rommik** [comment]
Sorry for the long delay on this. I believe this issue was related to incorrect usage of rush on my part. I tried to reproduce it by recreating my repo from scratch and striping out all other dependencies, and I was not able to reproduce the issue anymore.
