### ISSUE TITLE
[rush] Another rush command is already running in this repository.

### ISSUE THREAD

**Issue by sesteva** [microsoft/rushstack#2058]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x ] Bug

**Please describe the actual behavior.**
Sometimes when I run `rush update` or `rush add -p something` I get "Another rush command is already running in this repository."

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

I can't find the pattern yet on how to reproduce it

**What is the expected behavior?**
To execute the command

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** RUSH
* **Tool Version:**  Rush Multi-Project Build Tool 5.30.1 
* **Node Version:**  v12.18.3
  * **Is this a LTS version?** YES
  * **Have you tested on a LTS version?**  Yes
* **OS:** macOS 10.15.6

**Comment by octogonz** [comment]
> I can't find the pattern yet on how to reproduce it

Rush uses transactional locks to protect against accidentally executing simultaneous commands that could interfere with each other.

For example, invoking `rush add` during `rush update` could create to a race condition that might corrupt the installation.

Whereas invoking `rush scan` and `rush update` is safe, so `rush scan` runs without a lock.

For [custom commands](https://rushjs.io/pages/configs/command-line_json/), you can can use the `safeForSimultaneousRushProcesses` setting to specify whether to lock or not.

**Comment by GiriB** [comment]
I `Ctrl + C`d my `rush update` command in the middle of the run. Now when I run it again I see this message `Another rush command is already running in this repository`. What do I need to cleanup so that this goes away? @octogonz

**Comment by GiriB** [comment]
Worked around this by deleting the `rush#1234.lock` file in `common/temp`.

**Comment by octogonz** [comment]
> Worked around this by deleting the `rush#1234.lock` file in `common/temp`.

@GiriB FYI the lock file API is designed such that it should automatically delete this file unless process 1234 is still running.  So the expected workaround would be something like `kill -9 1234` rather than deleting the file.  (If you encounter this again, and that's not the case, maybe it is a bug with the locking -- please let us know.)

**Comment by octogonz** [comment]
Closing because we have no repro for the original issue -- please open a new issue if you can determine some repro steps.
