### ISSUE TITLE
[rush]  ```rush add -p proj``` should fail early when not run at project folder root

### ISSUE THREAD

**Issue by jasonswearingen** [microsoft/rushstack#2079]
**Is this a feature or a bug?**
- [ x] Bug

**Please describe the actual behavior.**

```rush add -p @xlib/eslint-config```  when in a subdir (such as under ```app-proj/src```) goes ahead and creates a ```node_modules``` and eventually errors with something like:

```bash
ERROR: Internal Error: Unable to find dependency @xlib/eslint-config with version link:../../utils/eslint-config in shrinkwrap.
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

```rush add``` a project from a dependent project ```./src``` folder

**What is the expected behavior?**

should fail early saying to run the command from the project root folder.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:**  Rush 
* **Tool Version:**  Rush 5.30.2
* **Node Version:** 14.7.0 pre-LTS
  * **Is this a LTS version?**  nope
  * **Have you tested on a LTS version?**  nope
* **OS:**  ubuntu 20.04 via WSL2 via Win10 Home
also using ```pnpm``` with ```useWorkspaces:true``` in ```rush.json```

**Comment by iclanton** [comment]
I'm not seeing a repro of this. Can you share a repro repo? This shouldn't be happening.

**Comment by jasonswearingen** [comment]
sorry tried reproing and now I can't (???)  will reopen if this comes up again
