### ISSUE TITLE
[rush] A few questions regarding rush

### ISSUE THREAD

**Issue by zefexdeveloper** [microsoft/rushstack#2083]
I'm totally new to rush and I read the documentation but a few questions still remains and I'd appreciate if anyone answer them for me.

1. Why rush requires the noreply github email when installing?
2. All the files created by rush init are necessary to work or most of them are optional? (which ones)
3. When using yarn workspaces alone with lerna I can easily run any script in a scope, for example, if I have a package with a nodejs server I can call the start script from it, how to handle that using rush as we don't have a centralized package.json? Do I have to browser in each package and run the script?

Thank you very much

**Comment by sachinjoseph** [comment]
hi @zefexdeveloper.
 
1. It's a security measure to prevent accidentally leaking your email (via git commits) and a compliance measure to ensure that all people who contribute have an email ID that follows a specified pattern. The pattern can be specified in rush.json.

2. Keep only the files you need. For example, for rush/yarn combo you won't need pnpmfile.js. If you don't intend to use Travis CI then you don't need .travis.yml. 

3. I don't really understand the question, but will Rush custom commands work for you? https://rushjs.io/pages/maintainer/custom_commands/

**Comment by zefexdeveloper** [comment]
@sachinjoseph Thank you very much for answering the questions. The 3th question is regarding how e usually do monorepo with yarn and lerna, we have a centralized package.json in the root where we can have scripts so we can run right? This way I can create a script that will call a scoped script inside a package. For example. In the root package.json I can have a script called `start:server` this script will call learn run with scope pointing to the server package calling its start script. It allows me to start the server package without the need to browse into the folder to just call the script in the package.json. But it think that custom commands might do the trick.

**Comment by sachinjoseph** [comment]
I am not very familiar with what you are asking. @octogonz @iclanton - will you be able to answer @zefexdeveloper's question?

**Comment by octogonz** [comment]
I answered these same questions in the [Gitter channel](https://gitter.im/rushstack/rushstack?at=5f2e1fd2733c00338ffba01f).

@zefexdeveloper If all your questions have been answered, please close this issue. Thanks!

**Comment by zefexdeveloper** [comment]
@octogonz Yes, they are answered. It helped me a lot, thank you guiys.
