### ISSUE TITLE
rush add -p not inserting in alphabetical order

### ISSUE THREAD

**Issue by matthiasg** [microsoft/rushstack#2115]
rush: 5.32.0
pnpm: 5.5.1

When running `rush add -p package` the package.json is extended, but the dependency is not inserted in alpahabetical order.

This causes issues down the line with other steps in the toolchain where the package.json is reordered which causes unncessary commits and unclean working directories.

I have seen other issues talking about keeping the general order of properties, but this seems not to be mentioned anywhere. If I overlooked it, please close this issue.

**Comment by iclanton** [comment]
This behavior was changed in https://github.com/microsoft/rushstack/pull/1710, which was a response to https://github.com/microsoft/rushstack/issues/1701. People were having issues with merge conflicts because `rush add` would change the `package.json` property order. Adding the new dependency to the end was the least disruptive way to modify the `package.json`.

We could introduce a flag to `rush add` that would disable the `updateExistingFile` option in the call to `JsonFile.save`, but we probably don't want to go back to the sorting-by-default behavior that caused the original issue to be saved.

**Comment by octogonz** [comment]
Maybe this could be controlled by a `rush.json` setting:

- `"normalizePackageJson": true` - Rush comprehensively normalizes **package.json**:  alphabetize the dependency names, reorder the fields into a canonical sequence (e.g. `name`, `version`, `license`, `description`, `dependencies`, `devDependenices`, `optionalDependencies`, `peerDependencies`, then everything else alphabetical), and maybe also deletes cruft.  In other words, automatically keep your monorepo package.json's nice.  I would be very happy to use this setting.
- `"normalizePackageJson": true`  - Rush assumes that some other tool manages package.json, so it tries to make as few changes to it as possible.

**Comment by matthiasg** [comment]
Not sure I quite understand. npm adds in alphabetical order, merging in alpha order ensures that lines are next to each other during merges (the missing comma for the last dependency is an issue of course).

A problem occurs when, during a later stage in rush build/update/publish some other process decides to order alphabetically.

So the question then becomes, why is there another place where the package.json does get sorted alphabetically.

That being said, I would prefer alphabetical order specifically for merging.

**Comment by octogonz** [comment]
> So the question then becomes, why is there another place where the package.json does get sorted alphabetically.

I looked in the code, but all the places I found seem to be preserving order (using [`{ updateExistingFile: true }`](https://github.com/microsoft/rushstack/blob/2b06f26d1f7a67351a58adea2c1bff1f0fbe09cf/apps/rush-lib/src/api/PackageJsonEditor.ts#L220).  If you can narrow down a specific Rush operation that alphabetizes, please let us know. We should keep it consistent.  Perhaps the best way is to start using the `PackageJsonEditor` class more broadly.

> Not sure I quite understand. npm adds in alphabetical order, merging in alpha order ensures that lines are next to each other during merges (the missing comma for the last dependency is an issue of course).

I can't find the other issue, but someone else had complained about this also. They were using some other tool to normalize their package.json files, so when Rush reordered the file, it was interfering with that.  In issue https://github.com/microsoft/rushstack/issues/1701@trusktr didn't give details, but it sounds like his group wanted to manually order the dependencies -- maybe to make them look nicer?

> That being said, I would prefer alphabetical order specifically for merging.

Me, too!

**Comment by octogonz** [comment]
I found [prettier-package-json](https://github.com/cameronhunter/prettier-package-json) which might be useful.

**Comment by matthiasg** [comment]
I believe the sorting happens during rush update on the CI server (pnpm operation). It doesn't happen anymore since we sort now before merge on master.

As for prettier, this only makes sense when used with a hook, but husky cannot be used for multi repos as they overwrite and rush cannot yet execute a script local to each package that is not contained in the package.json. 

We wrote our own sort-package-deps tool which we run on demand for now and will expand using a global rush command to parse the rush.json for packages and auto-sort all deps in each of them for now.

PS: I still do not understand how alphabetical sorting can impact merging in a worse way than appending at the end though :)

**Comment by octogonz** [comment]
Closing this, since it is a special case for the more general issue #2496
