### ISSUE TITLE
[rush] Create a toggle to allow simultaneous `rush deploy`

### ISSUE THREAD

**Issue by VincentSurelle** [microsoft/rushstack#2125]
Hi ! :)

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

For now, only one instance of `rush deploy` is allowed.
Any simultaneously launched command will result with the following error : `Another rush command is already running in this repository.`

So the deploy duration on a 50+ projects monorepo can be really long.

**What is the expected behavior?**

I understand that, with the default `common/deploy` path, it can be dangerous (or impossible?) to run multiple instance of this command.
But in the case where multiple command are launched with multiple paths defined with the `-t` flag, it should work.
A CLI toggle can be a correct answer for this ? `--allow-simultaneous` ?

**Comment by octogonz** [comment]
> I understand that, with the default `common/deploy` path, it can be dangerous (or impossible?) to run multiple instance of this command.

Actually, this protection is mainly intended for commands that a novice user might invoke manually. We're less concerned about commands that run in CI, because they run in a controlled environment, which is normally configured by a somewhat experienced user.

Seems okay to simply disable this check for `rush deploy`.

**Comment by octogonz** [comment]
Here's a PR: https://github.com/microsoft/rushstack/pull/2127

**Comment by octogonz** [comment]
This fix was released with Rush 5.33.1

**Comment by VincentSurelle** [comment]
Wow very quick !

Thanks a lot @octogonz ! 👍
