### ISSUE TITLE
[heft] heft build --watch does not incremental build for additionalModuleKindsToEmit from typescript.json

### ISSUE THREAD

**Issue by jasonswearingen** [microsoft/rushstack#2141]
**Is this a feature or a bug?**

- [X ] Bug

**Please describe the actual behavior.**
the ```heft build --watch``` does incremental building for the ```outDir``` specified in the the project ```tsconfig.json```.   It doesn't perform an incremental build for additional ```additionalModuleKindsToEmit``` from ```typescript.json```

additionally, when the ```--watch``` argument is specified it doesn't emit the additional out folder at all, let alone incremental build it.   

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

open a project with a additionalModuleKindsToEmit set and run ```heft build --watch```

**What is the expected behavior?**

simultaniously ```build --watch ``` 

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:**  heft
* **Tool Version:**  0.4.3
* **Node Version:**  14.8.0
  * **Is this a LTS version?**  no
  * **Have you tested on a LTS version?**  no
* **OS:** Ubuntu 20.04
Typescript:  4.0.2

**Comment by jasonswearingen** [comment]
I think it might be better to come up with a way to easily have multiple projects share the same source folders, not a project having multiple ways of building.

That way every heft task doesn't need to be aware of some "alternate configuration" that has to be worried about

**Comment by jasonswearingen** [comment]
my workaround is to create a sibling project that's empty, with a tsconfig.json that points to the project I want built both for node and browser

```json
//tsconfig.json
{
	"$schema": "http://json.schemastore.org/tsconfig",
	"extends": "./node_modules/@xlib/build-tools/includes/tsconfig-web.json",
	"compilerOptions": {
		"outDir": "../xlib/lib-esm",
		"types": [
			"node",
			"jest"
		],
		"lib": [
			//"es5",
			"scripthost",
			// "es2015.collection",
			// "es2015.promise",
			// "es2015.iterable",
			"dom",
			"ES2017"
		]
	},
	"include": [
		"../xlib/src/**/*.ts",
		"../xlib/src/**/*.tsx"
	],
	"exclude": [
		"node_modules",
		"lib",
		"lib-esm"
	]
}
```

**Comment by jasonswearingen** [comment]
My workaround (above) seems to work with a dependent project "react-browser-test", in that the ```lib-esm``` code is  properly references and ```--watch``` rebuild triggers on code edits.

The only problem is that it feels hacky.  You need to know that the ```project/lib-esm``` folder gets rebuilt by a sibling project, and you need to trigger rebuilds/watch builds by navigating to that sibling and running ```pnpm watch```.   It's okay for me as a one-man show, but for teams... (???)

**Comment by jasonswearingen** [comment]
this seems to be resolved by the latest ```heft``` version.    currently using ```@rushstack/heft": "0.13.1"```  

will leave open a few days in case a contributor wants to chime in.

**Comment by ksjogo** [comment]
I just ran into this missing emit with `"@rushstack/heft": "^0.30.4"`.
@jasonswearingen what as updated with 0.13.1?

**Comment by jasonswearingen** [comment]
try upgrading to the newest version of heft.  Sorry I haven't had a chance to use heft recently so I dont know if the bug is back.  Maybe make a new issue and reference this one.

**Comment by ksjogo** [comment]
0.30.5 seems to be the latest from npm. I did create a new issue.
