### ISSUE TITLE
Request for Comments & suggestions to avoid "Another rush command is already running in this repository."

### ISSUE THREAD

**Issue by rommik** [microsoft/rushstack#2205]
I'm implementing a script to build docker images for 10 projects. Each project has its own `Dockerfile` and two npm scripts in their package.json files

`package.json`

```
    "docker-build":"rm -rf deploy && mkdir deploy && rush deploy -t deploy -s scenario-name && rushx docker",
    "docker": "docker build -t project-name:local .",
```

`command-line.json`

```
    {
      "commandKind": "bulk",
      "name":"docker-build",
      "summary": "Calls 'docker-build' in scripts (if available) of each project.",
      "description":"Each project will execute their 'docker-build' command. ",
      "enableParallelism": false,
      "ignoreMissingScript": true,
      "ignoreDependencyOrder": false,
      "allowWarningsInSuccessfulBuild": false,
      "safeForSimultaneousRushProcesses": false
    }
```

However, I always get `Another rush command is already running in this repository.`

My guess the issue is in `docker-build` and all `&&` . Is this a wrong way to create a `bulk` command?

If executed individually (e.g `rushx docker-build`) There's no issue but a lot of `stdout`. Is the stdout what confuses the bulk command?

**Comment by octogonz** [comment]
@rommik Did you try setting `safeForSimultaneousRushProcesses=true`?

**Comment by rommik** [comment]
I had assumed that by default it is true , that's why I set it to false here. Now, that I set it to true it worked and I was able to execute the script everywhere! Thanks @octogonz

**Comment by octogonz** [comment]
Rush would never assume that something is "safe" if it might not be. 😁
