### ISSUE TITLE
[heft] when `heft test` finds no jest config, tests are silently skipped

### ISSUE THREAD

**Issue by mmkal** [microsoft/rushstack#2209]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

I just spent the best part of an hour trying to figure out why my tests wouldn't run. It mentions in the docs that `config/jest.config.json` is the only supported jest config file (which is good!), but I didn't realise I'd followed that part of the instructions wrongly (I accidentally used `jest.config.json`.

**What is the expected behavior?**

A message (at least when running with `--verbose`) saying something like `[jest] didn't find a config file at "config/jest.config.json", skipping jest task` would have saved me a lot of time.

I'd actually probably prefer to go one step further, and get a hard error when running `heft test` and no config file is found. As far as I can tell it just falls back to being the equivalent of `heft build` right now.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** "@rushstack/heft"
* **Tool Version:** "~0.13.2"
* **Node Version:** v12.18.0
  * **Is this a LTS version?** Yes
  * **Have you tested on a LTS version?** Yes
* **OS:** Windows 10

**Comment by iclanton** [comment]
>I'd actually probably prefer to go one step further, and get a hard error when running heft test and no config file is found. As far as I can tell it just falls back to being the equivalent of heft build right now.

I like this solution. You interested in opening a PR?
