### ISSUE TITLE
[heft] Proposal: Consolidate and reorganize Heft's config files

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#2225]
Today Heft supports the following Heft-specific config files:
- `.heft/api-extractor-task.json`
- `.heft/clean.json`
- `.heft/copy-static-assets.json`
- `.heft/plugins.json`
- `.heft/typescript.json`

...plus the following tool-defined config files:
- `config/api-extractor-task.json`
- `config/jest.config.json`
- Plus the root-level `.eslintrc.js`, `tsconfig.json`, and `tslint.json`

As we add more tasks and plugins, we are accumulating more config files. Some of these files have hardly any settings in them. To make configuration easier for people who are just getting started with Heft, maybe we can reduce the number of files required for a basic project.

Specifically, we should associate config files with "plugin packages" (i.e. opt-in things that would go in their own NPM package), rather than with every object that implement `IHeftPlugin` (but may all live in the same NPM package).  For core settings that everyone will always use, it would be more intuitive to find them in a centralized a `heft.json`.  

As an additional suggestion, I'd like to propose that the `.heft` hidden folder should only be used for unimportant files such as caches and temporary files.  By contrast, the config files are essentially source code. They are arguably just as important to understanding a project as its **package.json** file.

###  `config/api-extractor-task.json`

Moves to a different folder but retains the same schema.  Since this file has only one setting, we could consider merging it into `typescript.json`.  But I think of API Extractor as not being a "core" task, even though it is important. In the future if we want to reduce Heft's install footprint, we might move the API Extractor plugin into a separate NPM package.

BTW it might also be possible to eliminate this file entirely by moving the setting into the real `api-extractor.json`.

### `config/heft.json`

Heft should have its own config file that rolls together all the basic everyday features that everyone will always need, no matter which plugins they use.  "Core" operations include:

- `clean.json` -- deleting files
- `plugins.json` -- loading Heft plugins
- future feature: copying files during specific lifecycle events; we proposed this previously in  https://github.com/microsoft/rushstack/pull/2186#discussion_r487455582 
- future feature: running scripts during specific lifecycle events

here's a proposed layout:

**heft.json**
```js
{
  /**
   * An array of actions. Each action will have a unique "actionId", allowing
   * a config file to replace/remove actions that were inherited via "extends".
   * (Alternatively the "actionId" could be an object key for "eventActions"
   * although I prefer not to put user data in a JSON key.)
   *
   * When/if the specified "heftEvent" occurs, the associated actions run in
   * the order they appear in the array.
   */
  "eventActions": [
    {
      /**
       * I'll leave the "heftEvent" definitions up to you, since they are based
       * on the task engine events.  But I would suggest not to use names like
       * "afterPostBuild" or "beforePostBuild" and instead adopt a simpler convention
       * For example: "build" always happens AFTER Heft's tasks build things,
       * and if we need more granularity invent more names like "prepare" or "initialize".
       * (Instead of "build" and "postBuild", we could also consider using English tense:
       " "building" / "built".)
       */
      "heftEvent": "clean",
      /**
       * A user-defined tag whose purpose is to allow configs to replace/delete
       * handlers that were added by other configs.
       */
      "actionId": "defaultClean",

      /**
       * "actionKind" are built-in operations.  They determine the remaining JSON options
       * for this entry.
       *
       * "deleteFiles" is the clean.json logic.
       */
      "actionKind": "deleteFiles",

      "pathsToDelete": ["dist", "lib", "lib-esnext", "lib-umd", "temp"]
    },

    {
      "heftEvent": "preCompile",
      "actionId": "copyFiles",

      /**
       * "fileCopy" is a new general-purpose file copying feature.  (It is unrelated to
       * copy-static-assets.json, which I propose to roll into typescript.json.)
       */
      "eventActionKind": "fileCopy",

      "sourceGlob": "src/**/*.md",
      "targetFolders": ["dist"],
      "hardlinkInsteadOfCopy": true
    },

    {
      "heftEvent": "postBuild",
      "actionId": "rundown",
      /**
       * "shell" simply runs a shell script. This is a cheap escape hatch that avoids
       * the need to author custom plugins for running one-off scripts.
       */
      "eventActionKind": "shell",

      "command": "rundown",
      "args": ["snapshot", "--script", "./lib/index.js"]
    }
  ],

  /**
   * This is the configuration from plugins.json.
   */
  "heftPlugins": [
    /**
     * The list of Heft plugins to be loaded.
     */
    // {
    //  /**
    //   * The path to the plugin package.
    //   */
    //  "plugin": "path/to/my-plugin",
    //
    //  /**
    //   * An optional object that provides additional settings that may be defined by the plugin.
    //   */
    //  // "options": { }
    // }
    {
      /**
       * The path to the plugin package.
       */
      "plugin": "heft-example-plugin-01"
    },
    {
      /**
       * The path to the plugin package.
       */
      "plugin": "heft-example-plugin-02"
    }
  ]
}
```

## `config/typescript.json`

I'm suggesting to roll **copy-static-assets.json** and **typescript.json** into one file because:
 1. The reason we copy static assets is because transpiled files import them.
 2. They should only be copied when transpilation occurs.
 3. They should honor `additionalModuleKindsToEmit`, which is a TypeScript specific setting.

Here's how it looks:

**typescript.json**
```js
/**
 * Configures the TypeScript plugin for Heft.  This plugin also manages linting.
 */
{
  "$schema": "https://developer.microsoft.com/json-schemas/heft/typescript.schema.json",

  /**
   * Optionally specifies another JSON config file that this file extends from. This provides a way for standard
   * settings to be shared across multiple projects.
   */
  // "extends": "base-project/config/typescript.json",

  /**
   * Can be set to "copy" or "hardlink". If set to "copy", copy files from cache.
   * If set to "hardlink", files will be hardlinked to the cache location.
   * This option is useful when producing a tarball of build output as TAR files don't
   * handle these hardlinks correctly. "hardlink" is the default behavior.
   */
  // "copyFromCacheMode": "copy",

  /**
   * If provided, emit these module kinds in addition to the modules specified in the tsconfig.
   * Note that this option only applies to the main tsconfig.json configuration.
   */
  "additionalModuleKindsToEmit": [
    // {
    //   /**
    //    * (Required) Must be one of "commonjs", "amd", "umd", "system", "es2015", "esnext"
    //    */
    //  "moduleKind": "amd",
    //
    //   /**
    //    * (Required) The name of the folder where the output will be written.
    //    */
    //    "outFolderName": "lib-amd"
    // }
  ],

  /**
   * Specifies the intermediary folder that Jest will use for its input.  Because Jest uses the
   * Node.js runtime to execute tests, the module format must be CommonJS.
   *
   * The default value is "lib".
   */
  // "emitFolderNameForJest": "lib-commonjs",

  /**
   * If set to "true", the TSlint task will not be invoked.
   */
  // "disableTslint": true,

  /**
   * Set this to change the maximum number of file handles that will be opened concurrently for writing.
   * The default is 50.
   */
  // "maxWriteParallelism": 50

  /**
   * These are the settings from copy-static-assets.json.
   */
  "staticAssetsToCopy": {
    /**
     * File extensions that should be copied from the src folder to the destination folder(s).
     */
    "fileExtensions": [".json", ".css"]

    /**
     * Glob patterns that should be explicitly included.
     */
    // "includeGlobs": [
    //   "some/path/*.js"
    // ],

    /**
     * Glob patterns that should be explicitly excluded. This takes precedence over globs listed
     * in "includeGlobs" and files that match the file extensions provided in "fileExtensions".
     */
    // "excludeGlobs": [
    //   "some/path/*.css"
    // ]
  }
}
```

CC @iclanton

**Comment by octogonz** [comment]
We could also consider moving `emitFolderNameForJest` into a new file `config/jest-task.json`.  Jest's installation footprint is massive, so it's likely we will eventually extract it into a plugin package.  Also @hbo-iecheruo has another Jest setting that he was looking to store in a Heft config file.

**Comment by iclanton** [comment]
I've addressed what I believe to be an MVP of this here https://github.com/microsoft/rushstack/pull/2204. This PR moves all of the config files to the `config` folder and consolidates `plugins.json` and `clean.json` into `heft.json`.
