### ISSUE TITLE
[rush] shrinkwrap-deps is not updated on full update with pnpm >= 5.5.8

### ISSUE THREAD

**Issue by atsikov** [microsoft/rushstack#2227]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

With `pnpm > 5.5.5`, while running `rush update --full`, rush stops at linking step with
```
ERROR: Internal Error: Unable to find dependency webpack with version /webpack/4.44.2 in shrinkwrap.
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

In this case ,`webpack@4.44.2` is a dependency of storybook, and is being updated from `4.44.1`. However `shrinkwrap-deps.json`s for both packages with storybook still contain `webpack/4.44.1` entry.

Dependencies:
package in monorepo
```
"devDependencies": {
  ...
  "@storybook/react": "6.0.21",
  ...
}
```

`@storybook/react`
```
"dependencies": {
  ...
  "webpack": "^4.43.0"
}
```

With pnpm <= `5.5.5` everything works as exepcted.

Note: I experienced this issue with `pnpm >= 5.5.7`. With `5.5.6`, I got `boolean false is not iterable (cannot read property Symbol(Symbol.iterator))` at install step, so not sure if it was affected.

**What is the expected behavior?**

rush is able to perform full dependencies update with `pnpm > 5.5.5`, correctly updating `shrinkwrap-deps.json` for each package

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** rush
* **Tool Version:** 5.34.2
* **Node Version:** 12.16.1
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** macOS Catalina 10.15.6

**Comment by iclanton** [comment]
I'm not able to get a repro of this. I just created [this branch](https://github.com/iclanton/rushstack/tree/ianc/update-pnpm) for this repo. Can you share a repro repo?

**Comment by atsikov** [comment]
Thanks for looking into this @iclanton 
This issue happens with our large monorepo, which I cannot share.
I will try to build some repro this week.

**Comment by atsikov** [comment]
Sorry for being so long. Here's a repro https://github.com/atsikov/rushstack-2227
Run `rush install` from main, then try `rush update --full` from branches `pnpm-5.5.5` and `pnpm-5.9.3`
For 5.5.5, everything works as expected.
For 5.9.3, `rush update --full` fails with 
```
LINKING: package-a

ERROR: Internal Error: Unable to find dependency webpack with version /webpack/4.44.2 in shrinkwrap.
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

**Comment by atsikov** [comment]
I updated repro to be less synthetic. I removed `common-versions` and replaced it with `pnpmfile`, which fixes transitive dependency version one patch behind the latest one. I believe it reproduces more real update flow.
It could be that the issue is because of two versions of webpack being installed as transitive dependencies:
- `4.42.0` for `react-scripts`
- `^4.44.1` (which is being bumped `4.44.1` -> `4.44.2` and causes the actual error) for `@storybook/react`

**Comment by atsikov** [comment]
Did some debugging. The issue has nothing to do with two versions of webpack installed, so I made repro repo even smaller.
Issue happens since `pnpm@5.5.8`, and not `5.5.7` as I thought before (not sure why update failed in original monorepo with `5.5.7`). I suppose this RP changed peer deps hoisting: https://github.com/pnpm/pnpm/pull/2821

From what I could see, it was something about pnpm hoisting peer dependencies.
Deps chain is the following:
- dep: `@storybook/react` -> dep: `react-docgen-typescript-loader` -> dep: `@webpack-contrib/schema-utils` -> peerDep: `webpack@^3.0.0 || ^4.0.0`
pnpm hoists `webpack` to `react-docgen-typescript-loader` as peerDep `webpack@*`, but doesn't add it to dependencies. So rush is not able to find `webpack@4.44.2_webpack@4.44.2` (as per shrinkwrap file).
Next, rush tries to parse version from full dependecy name, which is `/react-docgen-typescript-loader/3.7.2_webpack@4.44.2` and then again fails to find `webpack@4.44.2` as it's `webpack@4.44.2_webpack@4.44.2` in shrinkwrap dependencies list.

I'm afraid I'm not aware of all the logic behind pnpm shrinkwrap generation and how rush uses it, so cannot propose a fix.
Hope the above information is helpful.

**Comment by atsikov** [comment]
@iclanton any progress on this issue? I updated rush and pnpm in the repro (`rush@5.35.2`, `pnpm@5.13.7`), and now I cannot even run `install` a regular `update` without `--full` flag.
It fails with ` ERROR  Broken lockfile: no entry for '/webpack/4.44.1_webpack@4.44.1' in pnpm-lock.yaml`
Please check `pnpm-latest` branch.

**Comment by atsikov** [comment]
With `rush@5.35.2`, `pnpm@5.13.7` I was able to perform **full** update on both repro and my monorepo, which fixed the above error. Closing the issue.

**Comment by iclanton** [comment]
Sounds like the scenario is working correctly now? Excellent.

Please open another issue if you continue to have problems.
