### ISSUE TITLE
[rush] Authenticated .npmrc files committed to source control when executing "rush version"

### ISSUE THREAD

**Issue by AndrewCraswell** [microsoft/rushstack#2249]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

Our Azure Pipeline for CD that bumps package versions before publishing uses the `npmAuthenticate` pipeline task to authenticate .npmrc files. This task adds the token to the file which works, but I've hit an issue where the `rush version` command includes the changes to the .npmrc files back into source control. This is a big security risk and I'm not totally sure the best way to prevent it. My preference would have been to add the `authToken` as an environment variable, but this is not an option for the `npmAuthenticate` pipeline task today.

Either way, this seems like a flaw in Rush since the only files that should be committed to git are the files that Rush changed.

Btw, I did open a Feature Request on the `npmAuthenticate` task since this is the recommended way for getting an auth token, but I suspect it won't be taken up for a long time (if ever).

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

**What is the expected behavior?**

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** pnpm
* **Tool Version:**  4.14.4
* **Node Version:** 12.17.0
  * **Is this a LTS version?** Yes
  * **Have you tested on a LTS version?** Yes
* **OS:** Windows

**Comment by dmichon-msft** [comment]
Looks like we have a misconfiguration on this line here:
https://github.com/microsoft/rushstack/blob/7f0ccdf463b044ba0f67a7bd4840197b960d9be1/apps/rush-lib/src/cli/actions/VersionAction.ts#L242
```diff
-      git.addChanges(':/*');
+      git.addChanges(':/**/package.json');
```
