### ISSUE TITLE
[heft] copy-static-assets ignores additionalModuleKindsToEmit

### ISSUE THREAD

**Issue by halfnibble** [microsoft/rushstack#2251]
**Is this a feature or a bug?**

- [ ] Feature
- [X] Bug

**Please describe the actual behavior.**
copy-static-assets in Heft does not consider the additionalModuleKindsToEmit setting in config/typescript.json

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

This can be reproduced within rushstack on current master. Build the test project `heft-sass-test`.
https://github.com/microsoft/rushstack/tree/master/build-tests/heft-sass-test

Note: in the config/typescript.json, commonjs is configured as an additional module to emit and .scss files are listed as static assets to copy.

Observe that the scss files are only copied to the `lib/` directory, but not the `lib-commonjs/` directory.

**What is the expected behavior?**
I expect static assets to be copied into both `lib/` and `lib-commonjs/` when it is configured. 

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** Heft
* **Tool Version:** From today 10/01/2020 AM
* **Node Version:** 12.18.1
  * **Is this a LTS version?**  Yes
  * **Have you tested on a LTS version?** yes
* **OS:** Mac

**Comment by halfnibble** [comment]
@Claudiazhaoya Here is the bug you discovered.

**Comment by octogonz** [comment]
I thought we fixed this already? Does it repro in Heft 0.14.0?

**Comment by halfnibble** [comment]
I just reproed it on master right now, heft-sass-test, which has the dep: `"@rushstack/heft": "workspace:*",`
Git commit: 89d265cc232524a8c0223c39b58bd391f36a8317

I am looking into it.
