### ISSUE TITLE
[api-documenter] Indicate optional members in interface declarations

### ISSUE THREAD

**Issue by hiranya911** [microsoft/rushstack#2269]
- [X] Feature
- [ ] Bug

Markdown generated for interfaces do not contain any information about which members are optional. For example, given the following interface:

```typescript
interface Foo {
  a: string;
  b?: string;
}
```

api-documenter will generate the following markdown:

## Properties (actual)

|  Property | Type | Description |
|  --- | --- | --- |
|  a  | string |  |
|  b | string | |

Note that there's no indication that `b` is optional. It would be nice to include this information in the generated markdown docs. Perhaps the easiest would be to list the optional fields with the `?` sign so that the above property gets listed as `b?`. Alternatively it could be included in the property description too.

## Properties (proposed)

|  Property | Type | Description |
|  --- | --- | --- |
|  a  | string |  |
|  b? | string | **Optional** |

I've noticed that this information is missing in the generated doc model file too. It's only available as part of the excerpt tokens:

```
{
  "kind": "PropertySignature",
  "docComment": "...",
  "excerptTokens": [
    {
      "kind": "Content",
      "text": "b?: "
    },
    {
      "kind": "Content",
      "text": "string"
    },
    {
      "kind": "Content",
      "text": ";"
    }
  ],
  "releaseTag": "Public",
  "name": "b",
  "propertyTypeTokenRange": {
    "startIndex": 1,
    "endIndex": 2
  }
}
```

**Comment by octogonz** [comment]
> |  Property | Type | Description |
> |  --- | --- | --- |
> |  a  | string |  |
> |  b? | string | **Optional** |

Where does the description go?  Maybe we'd use parentheses?

> |  Property | Type | Description |
> |  --- | --- | --- |
> |  a  | string |  The `a` component of the API |
> |  b? | string | _(Optional)_ The `b` component of the API |

**Comment by octogonz** [comment]
@hiranya911 This is a good suggestion. Would you be available/interested to make a PR?

**Comment by hiranya911** [comment]
Thanks @octogonz. I can put together a PR in the next couple of days. Putting "Optional" inside parenthesis sounds good to me.
