### ISSUE TITLE
[api-extractor] Support typescript 4.0

### ISSUE THREAD

**Issue by dotnetjunky** [microsoft/rushstack#2278]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**
`api-extractor` doesn't support new TS 4.0 features, such as labeled tuple. As a result, it fails when verifying the api. 

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

**What is the expected behavior?**

It supports new TS 4.0 features.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 
* **Tool Version:** 
* **Node Version:** 
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS:**

**Comment by iclanton** [comment]
@octogonz

**Comment by octogonz** [comment]
👍 I suspect we just need to upgrade the bundled dependency.

**Comment by octogonz** [comment]
Here's a PR: https://github.com/microsoft/rushstack/pull/2314

@dotnetjunky Are you able to [test this branch](https://api-extractor.com/pages/contributing/debugging/) before we merge it?  I confirmed that labeled tuples work, but didn't test any other features.

**Comment by octogonz** [comment]
The fix was published with API Extractor 7.11.0
