### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by iantruslove** [microsoft/rushstack#2306]
## Rush has no clear license

It's not clear from the usual places what the license for Rush is. This makes adoption a bit tricky.

Looking at the source I guess it's MIT licensed, with Microsoft asserting copyright.

Regardless of what license terms you actually want to use, please could you make this clear with e.g. LICENSE file, a statement on the docs site, a statement in the project README, anything else equally visible, or really any combination of as many of these things as possible.

**Comment by octogonz** [comment]
This repo contains [55 license files](https://github.com/microsoft/rushstack/search?l=Text&q=filename%3ALICENSE).

It is a "monorepo" containing many different projects. Each project has its own license and README.

Also, each source file starts with a banner:
```js
// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.
```

**Comment by iclanton** [comment]
Closing this. Please open a new issue if this is still a problem or is unclear.
