### ISSUE TITLE
[eslint-patch] eslint 7.12.0 breaks eslint-patch

### ISSUE THREAD

**Issue by known-as-bmf** [microsoft/rushstack#2310]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

It looks like configuration loading / merging code has been moved around (to another package) in the latest eslint release (`7.12.0`) and the patch depends on a specific path / file to do its magic.

The reorganization is part of the effort to support relative module / plugin loading natively.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Try to use the patch with eslint `7.12.0`

**What is the expected behavior?**

Support for this new version.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** eslint-patch
* **Tool Version:** 1.0.5
* **Node Version:** v12.18.3
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** Windows 10

**Comment by onigoetz** [comment]
Hi, I forked the version in this repo a few months ago, I use it a bit differently than you but I believe the fix I made can be useful to you as well : 
https://github.com/swissquote/crafty/commit/4aed07e14dd3cfb6c24aa16a77e98d949663729c#diff-1b872c2f06946bfe0b8f31457d876ec624c062e965dd8d836bf8cf083df70dff

**Comment by iclanton** [comment]
@octogonz

**Comment by octogonz** [comment]
Here's a PR: https://github.com/microsoft/rushstack/pull/2320
