### ISSUE TITLE
[rush] Ability to run `rush deploy` in parallel 

### ISSUE THREAD

**Issue by joshughes** [microsoft/rushstack#2321]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**
``` 
rush deploy --create-archive foo-deploy.zip --scenario "foo" -t "/tmp/foo-local-deploy" &
rush deploy --create-archive bar-deploy.zip --scenario "bar" -t "/tmp/bar-local-deploy"
```
The above will fail because rush deploy is using the rush command lock to ensure only one rush command runs at a time. This command should be able to be run in parallel, especially in CI where we can take advantage of multiple cores. 

The end goal here is to craete deploy zips that have just the dependencies for each package. Right now it takes a long time because it is not possible to do it in parallel. 

**What is the expected behavior?**
many rush deploys can run in parallel 

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool**: **rush** 
* **Tool Version**: **5.34.3**
* **Node Version:** 
  * **Is this a LTS version?**:  **yes** 

* **OS**: **Ubuntu 20.04**

**Comment by octogonz** [comment]
Wasn't this already fixed in https://github.com/microsoft/rushstack/pull/2127 ?

**Comment by joshughes** [comment]
Yes your right... it is deploy-init that has this issue. Will close this
