### ISSUE TITLE
[heft] Heft vs lage ?

### ISSUE THREAD

**Issue by gfortaine** [microsoft/rushstack#2328]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

We are in the process of migrating our current front-end architecture and we have chosen Rush + pnpm. However, it looks like that we couldn’t fully leverage the workspaces capabilities of pnpm, by example with —filter. Moreover, it seems that the path taken by Heft is not fully satisfying. What about integrating instead with lage (that provides [Scoped Builds](https://microsoft.github.io/lage/guide/scopes.html#scoped-builds-with-all-its-dependents)) ?  cc @octogonz @kenotron @arcanis @zkochan  @iclanton 

https://github.com/microsoft/lage/blob/master/decks/lage-deck.md

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

**What is the expected behavior?**

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 
* **Tool Version:** 
* **Node Version:** 
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS:**

**Comment by octogonz** [comment]
Rush already has a planned feature called **phased commands** which will enable subtasks to be lagged similar to what Ken's tool does. The phased commands proposal is in [issue #​2300](https://t.co/i0Xo1uqOrh). Those design meetings centered around how this capability will relate to Rush's other features and user experience goals. The actual work of invoking shell commands in the proper order is not difficult, so integrating a separate engine probably won't help much. 

But I see from Ken's website that he [included support for Rush repos](https://microsoft.github.io/lage/):

> "The workspace-agnostic task runner will run npm scripts for all workspace implementations out there: lerna, yarn, pnpm, rush"

So if you need this functionality right away, that might be a pretty good option while waiting for a built-in solution.

**Comment by octogonz** [comment]
> We are in the process of migrating our current front-end architecture and we have chosen Rush + pnpm. However, it looks like that we couldn’t fully leverage the workspaces capabilities of pnpm, by example with —filter.

@gfortaine This is a completely unrelated topic.  Could you open a separate GitHub issue for it?  It has come up a few times already and should be a priority, but there doesn't seem to be an issue tracking it. (?)

**Comment by iclanton** [comment]
Heft is currently under active development, so new features are being added regularly. @gfortaine, what functionality are you missing?

**Comment by gfortaine** [comment]
@iclanton Regarding rush It looks like that the **phased commands** feature would fit the bill for our needs, we are eager to try it 😄 👍 

However, it looks like that we still don't see the point with Heft against other initiatives, even the ones already lead by some other Microsoft teammates. What about just ? https://microsoft.github.io/just/

**Comment by iclanton** [comment]
Just takes a very different approach than Heft takes. Just runs tasks similarly to the way Gulp runs tasks (it actually uses Gulp's task runner under the hood). Our team tried this approach for several years (see gulp-core-build) and concluded that a much more tightly-integrated build pipeline was a better design, which is where Heft came from.

Heft takes design cues from Webpack, and actually uses Webpack's plugin model. It also deeply integrates with the tools it's invoking for a more tightly-managed build process. For example, take a look at the way we invoke the TypeScript compiler in Heft: https://github.com/microsoft/rushstack/blob/master/apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts This approach is far more complex than other alternatives, but it allows us to do things like output multiple module targets and to perform linting after doing a single analysis of the source files.

**Comment by octogonz** [comment]
This thread mixed together a number of unrelated topics. It looks like they have all been addressed:

- The PNPM workspaces question is tracked separately by [Issue #2347](https://t.co/acLfSxFvM8)
- The lag feature for subtasks will be solved by Rush's phased commands with [Issue #​2300](https://t.co/i0Xo1uqOrh)
- @iclanton gave a pretty good explanation of how Heft and Just are optimized for different scenarios (enterprise requirements vs simplicity)

So it seems that we can close this issue.  If want to discuss it further, the [chat room](https://rushstack.zulipchat.com/) might be a better place.  GitHub issues are best for tracking work on a single problem.

BTW I will add that it is healthy to have different tooling options to choose from.  In a way this flexibility characterizes the Node.js community.  It's cool that Microsoft engineers are open minded about exploring different approaches, rather than investing in "one way" only. 🙂
