### ISSUE TITLE
[rush] Custom command parameter type exists for multiple selection (choices)

### ISSUE THREAD

**Issue by colin-valentini** [microsoft/rushstack#2330]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

Currently `flag`, `choice`, and `string` parameter kinds are supported in `command-line.json` for custom rush commands. There does not appear to be any direct way of using one of these to declare a custom command parameter which could be passed multiple values.

For example, **there is no way to run `rush my-custom-command --my-custom-parameter ARG_1 ARG_2 ... ARG_N`**.

It would not be feasible to use the `flag` parameter kind to do this as you would have to declare `N` number of different flag parameters. With the `choice` parameter, only one value among a set of alternatives is allowed.  The only way to do this right now is to declare a `string` parameter and pass it a comma-separated list of values which is a hack.

**What is the expected behavior?**

To be able to declare a custom parameter kind which can be passed one or more values from an optional list of accepted values. For example: `rush my-custom-command --my-custom-parameter ARG_1 ARG_2 ... ARG_N`.

Where my parameter declaration in `command-line.json` looks something like:

```json
{
  "parameterKind": "multiple-selection",
  "longName": "--my-custom-parameter",
  "description": "A multiple selection parameter for the \"my-custom-command\" custom command",
  "associatedCommands": [ "my-custom-command" ],
  "required": false,
  /**
  * (Optional) Provide a predefined list of values which can be provided. Omitting this allows any argument values to be provided
  */
  "allowedValues": [
    {
      "name": "ARG_1",
      "description": "First allowed argument"
    },
    ...
    {
      "name": "ARG_N",
      "description": "Last allowed argument"
    },
  ]
}
```

**Comment by iclanton** [comment]
Our command-line processor (`ts-command-line`) supports this (albeit with slightly different syntax for specifying multiple values) via the [`CommandLineStringListParameter`](https://rushstack.io/pages/api/ts-command-line.commandlinestringlistparameter/).

It would probably be pretty easy to add support for this for custom parameters. @colin-valentini - would you be interested in putting together a change to add this feature?

**Comment by colin-valentini** [comment]
Thanks for taking a look @iclanton, yes I would be interested in adding support though I'll have to prioritize it along with the stuff I'm doing at work. That's a weak way of saying it will take me a bit longer to do so than a Rush veteran, but I'll give it a college try :)
