### ISSUE TITLE
[gulp-core-build] allow customizable coverageReporters for each project

### ISSUE THREAD

**Issue by TisnKu** [microsoft/rushstack#2365]
Currently jest-task in gulp-core-build only uses coverageReporters in JestTaskConfig instead of project jest config.
![image](https://user-images.githubusercontent.com/10512841/99763629-46bdbc00-2b36-11eb-80dd-ae03531a0f3e.png)

## Expected:
coverageReporters in jest.config.json can override that of taskConfig.

**Comment by TisnKu** [comment]
I found a work around though, adding following code to gulpfile can override coverageReporters:
```
const coreBuild = require('@microsoft/gulp-core-build');
coreBuild.jest.mergeConfig({
  coverage: true,
  coverageReporters: ["json", "lcov", "text", "clover"]
});
```

**Comment by octogonz** [comment]
@TisnKu are you happy with this solution?  If so should we close the issue?

FYI most of the current development effort is focused on [Heft](https://rushstack.io/pages/heft/overview/), which is expected to eventually replace `gulp-core-build`.

**Comment by TisnKu** [comment]
I am happy with the workaround, closing this issue.
