### ISSUE TITLE
[rush] Install can't be skipped with useWorkspaces and git checkout

### ISSUE THREAD

**Issue by buffaybu** [microsoft/rushstack#2371]
## Summary

With Gitlab CI, I try to skip install by marking `common/temp` as cache but install still runs. 

## Repro steps

In a rush repo,

1. `git checkout A`
2. `rush install`
3. `git checkout B`
4. `touch some/project/package.json`
4. `git checkout A`
5. `rush install`

  **Expected result:** 

Don't run the second install.

  **Actual result:** 

The second install runs.

## Details

[canSkipInstall](https://github.com/microsoft/rushstack/blob/@microsoft/rush_v5.35.2/apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts#L256) compares mtime of `common/temp/last-install.flag` and each project's `package.json` (#2029).

`common/temp/last-install.flag`'s mtime is preserved because of cache, but mtime of each project's `package.json` [is not preserved by git checkout](https://git.wiki.kernel.org/index.php/GitFaq#Why_isn.27t_Git_preserving_modification_time_on_files.3F) so it can be more recent than flag's even though the file content remains the same, and that the install step won't be skipped.

Although all the packages are reused, the install step still takes tens of seconds.

Maybe keeping MD5 hash of `package.json` in the flag file or somewhere else will fix this.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  5.35.2 |
| `rushVersion` from rush.json? |  5.35.2 |
| `useWorkspaces` from rush.json? |  Yes |
| Operating system? |  Mac |
| Would you consider contributing a PR? |  Yes |
| Node.js version (`node -v`)? |  14.15.0 |

**Comment by iclanton** [comment]
>Maybe keeping MD5 hash of `package.json` in the flag file or somewhere else will fix this.

I like this idea. @D4N14L is the expert on this feature, if he wants to weigh in.

@buffaybu - would you be interested in contributing this feature?

**Comment by D4N14L** [comment]
I'm going to close this out seeing as:
- it appears we are using the modified time as expected according to Git spec
- the Rush build cache feature solves the original issue that you are attempting to resolve by modifying the functionality

Feel free to re-open if you disagree :)
