### ISSUE TITLE
[rush] webpack bundle duplicate module in rush project

### ISSUE THREAD

**Issue by WanderWang** [microsoft/rushstack#2372]
## Repro steps

clone my demo project
```bash
git clone https://github.com/WanderWang/rush-issue.git
cd rush-issue/react-project
npm install
npm run build   ##without rush, dist/bundle.js 194k
rm -rf node_modules
rush update
npm run build ## with rush , dist/bundle.js 308k
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.2.23 |
| `rushVersion` from rush.json? | 5.23.0 |
| `useWorkspaces` from rush.json? | no,I don't know what is rush workspaces |
| Operating system? | Windows |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v10.21.0 |

**Comment by octogonz** [comment]
I did some preliminary investigation and posted my notes in [the Zulip thread](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/.5Brush.5D.20webpack.20bundle.20duplicate.20module.20in.20rush.20project/near/217716295).

Seems like maybe side-by-side versions are getting included in the bundle.
