### ISSUE TITLE
[rush] Can't install @microsoft/rush due to 'publish-please' dep

### ISSUE THREAD

**Issue by gregjacobs** [microsoft/rushstack#2380]
**Update**: bigger problem: can't install `@microsoft/rush` globally anymore. See next comment

## Summary

`install-run-rush.js install` now raises a bunch of interactive prompts from the [publish-please](https://github.com/inikulin/publish-please) package's post-install script, which blocks CI pipelines

```
$ node common/scripts/install-run-rush.js install
The rush.json configuration requests Rush version 5.35.2
Copying /my-project/common/config/rush/.npmrc --> /my-project/common/temp/install-run/@microsoft+rush@5.35.2/.npmrc
Installing @microsoft/rush...

> publish-please@5.5.2 preinstall /my-project/common/temp/install-run/@microsoft+rush@5.35.2/node_modules/publish-please
> node lib/pre-install.js

> publish-please@5.5.2 postinstall /my-project/common/temp/install-run/@microsoft+rush@5.35.2/node_modules/publish-please
> node lib/post-install.js

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! publish-please hooks were successfully setup for the project. !!
!! Now follow few simple steps to configure your publishing...   !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

-- Configuring option "prePublishScript":
? Do you want to run any scripts before publishing (e.g. build steps, tests)? (Y/n)
Error: Unable to install package: Error: "npm install" encountered an error
```

The error probably occurs immediately after the question since there is no interactive shell.

## Repro steps

As of this morning (2020-12-06), simply running the install-run-rush.js script on my local machine causes the issue:

```bash
[11:35:01] /my-project$ node common/scripts/install-run-rush.js install
```

I'm prompted to create all of the configuration options for a `.publishrc` file, which will eventually be placed into the `common/temp/install-run/@microsoft+rush@5.35.2/` directory

## Details

Not sure what changed here all of a sudden as it seems that the 'publish-please' package was last changed months ago. Does rush need to generate a `.publichrc` file before installing itself?

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.34.3 |
| `rushVersion` from rush.json? | 5.35.2 |
| `useWorkspaces` from rush.json? | No |
| Operating system? | Mac |
| Would you consider contributing a PR? | No, not sure what to do |
| Node.js version (`node -v`)? | 12.16.3 |

**Comment by gregjacobs** [comment]
UPDATE: can no longer globally install `@microsoft/rush` either!

```
$ npm i -g @microsoft/rush
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead

> publish-please@5.5.2 preinstall /Users/xxxxxx/lib/node_modules/@microsoft/rush/node_modules/publish-please
> node lib/pre-install.js

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! Starting from v2.0.0 publish-please can't be installed globally.          !!
!! Use local installation instead : 'npm install --save-dev publish-please', !!
!! Or use npx if you do not want to install publish-please as a dependency.  !!
!! (learn more: https://github.com/inikulin/publish-please#readme).          !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! publish-please@5.5.2 preinstall: `node lib/pre-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the publish-please@5.5.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by steffenkrohnstorgaard** [comment]
We're having the same issue.

As a temporary workaround, installing the exact version specified in `rush.json` did the trick in our case (assuming it's an earlier version). E.g. `npm i -g @microsoft/rush@5.34.3`

**Comment by gregjacobs** [comment]
Used this as a temporary workaround on our CI:

```bash
# Workaround for 'publish-please' issue with interactive post-install script
mkdir -p common/temp/install-run/@microsoft+rush@5.34.3
echo '{
  "validations": {
     "vulnerableDependencies": false,
     "uncommittedChanges": false,
     "untrackedFiles": false,
     "sensitiveData": false,
     "branch": false,
     "gitTag": false
  },
  "confirm": false,
  "publishCommand": "npm publish",
  "publishTag": "latest",
  "prePublishScript": false,
  "postPublishScript": false
}' > common/temp/install-run/@microsoft+rush@5.34.3/.publishrc

# rush install
node common/scripts/install-run-rush.js install
```

**Comment by iclanton** [comment]
I'm not able to repro this. Are you using a private package feed that may have a package with an issue cached that may have since been unpublished?

**Comment by iclanton** [comment]
For someone who can repro this: can you try to figure out which dependency chain is pulling in `publish-please`?

**Comment by octogonz** [comment]
Rush doesn't have any dependency on `publish-please`.  This problem seems unrelated to Rush.

```
Installing @microsoft/rush...

> publish-please@5.5.2 preinstall /my-project/common/temp/install-run/@microsoft+rush@5.35.2/node_modules/publish-please
```
The above log seems to indicate that `publish-please` has an NPM `"preinstall"` hook that is getting triggered when Rush invokes `npm install` in the `common/temp/install-run/@microsoft+rush@5.35.2` folder.  If someone can prepare some isolated repro steps, we might be able to give some advice how to solve it. But the solution will most likely require a PR to make `publish-please`  more compatible with monorepos.

If you aren't actually wanting to use `publish-please`, maybe you just need to purge it from everywhere.  

Does this repro on a clean computer?  If so, then search all the files in your Git repo for any references to `publish-please`.

If not:
- `nvm uninstall ...` + `nvm install ...` to clear out your Node.js environment
- `rush purge` to clear out Rush's temporary files
- check for stray package.json and .npmrc files in parent folders
- check environment variables

**Comment by gregjacobs** [comment]
> Are you using a private package feed that may have a package with an issue cached that may have since been unpublished?

@iclanton Yes actually, we're on a corporate network which uses Nexus and proxies out to the real npm repository. I wonder if the issue could be there. Thanks for pointing that out. @steffenkrohnstorgaard, is your situation similar?

Thanks for the replies otherwise guys. I'm not able to reproduce this issue on my home computer, so I have to assume it's a problem within Nexus. Not even sure where that `publish-please` reference came from as you're right: it doesn't seem to be a dependency of Rush in any way.

Will close this out for now, thanks again for taking a look!

**Comment by steffenkrohnstorgaard** [comment]
> @iclanton Yes actually, we're on a corporate network which uses Nexus and proxies out to the real npm repository. I wonder if the issue could be there. Thanks for pointing that out. @steffenkrohnstorgaard, is your situation similar?

@gregjacobs We experienced it in our ci environment on netlify and on a home computer as well.

**Comment by gregjacobs** [comment]
Interesting. Maybe this was something where one of Rush's dependencies temporarily included 'publish-please' as a dependency itself, and has since removed it. I'm not getting the issue anymore on my corporate network now either. I guess all good!
