### ISSUE TITLE
[rush] Passing "unstructured" arguments to a command line command

### ISSUE THREAD

**Issue by chopfitzroy** [microsoft/rushstack#2381]
## Summary

Cannot pass "unstructured" arguments to a Rush command line command, I would like to be able to "pass on" these arguments to binaries called internally by the Rush command line command.

## Repro steps

I have two Rush commands as below:

```jsonc
    {
      // https://rushjs.io/pages/maintainer/enabling_prettier/
      "name": "file-format",
      "commandKind": "global",
      "autoinstallerName": "file-format",
      "shellCommand": "prettier --write",
      "summary": "Used by lint-staged. This command invokes Prettier to reformat staged changes."
    },
```

And 

```jsonc
    {
      "name": "process-staged",
      "commandKind": "global",
      "autoinstallerName": "process-staged",
      "shellCommand": "lint-staged",
      "summary": "Used by the pre-commit Git hook. This command invokes lint-staged."
    }
```

I also have a `lint-staged.config.js` that looks like this:

```js
module.exports = {
  '*.+(js)': ['rush file-format'], // more commands to come, i.e `rush file-lint`
};
```

The idea is to be able to run Rush commands on staged files only, essentially by passing the file list through to the command form `lint-staged` and then invoking whatever internal binaries are needed.

  **Expected result:** 

Prettier runs across the provided file list and the `pre-commit` hook is a success.

  **Actual result:** 

The command fails with the following (prettier) error:

```
rush file-format: error: Unrecognized arguments: applications/default/.eslintrc.js applications/default/app.js
```

Which from what I can tell is Rush failing to pass the additional arguments.

## Details

There is potentially a more 'Rush' way to do this, I am just wanting to only process files that have changed on commit as this is a fairly large repo and processing all of the files is quite time consuming.

From what I can see #1336 may be related.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | `Rush Multi-Project Build Tool 5.35.2` | 
| `rushVersion` from rush.json? | `"rushVersion": "5.35.2",` | 
| `useWorkspaces` from rush.json? | N/A | 
| Operating system? | Windows - WSL 1 - Ubuntu 18.04 | 
| Would you consider contributing a PR? | Yes (although my TS skills are probably lacking) | 
| Node.js version (`node -v`)? | `Node.js version is 15.3.0` |

**Comment by iclanton** [comment]
WRT running Prettier on staged files, [this](https://github.com/microsoft/rushstack/blob/master/common/config/rush/command-line.json#L149-L160) is the command we use in this repo to do that (and [here](https://github.com/microsoft/rushstack/tree/master/common/autoinstallers/rush-prettier) is the autoinstaller). Give that a try?

There is a way to get at the "remaining" arguments in our command-line processing library (ts-command-line), but that isn't exposed to Rush's custom commands. We could add an option for that, but I suspect that the examples I mentioned above may fix your Prettier issue.

**Comment by chopfitzroy** [comment]
Hey @iclanton,

The Prettier example you have sent is actually exactly what I was using before I tried this 😅 (got it directly from the docs) so perhaps that was a bad example to start with, but I would also like to use it for something like ESLint as well (so essentially would run Prettier and ESLint over the staged files.

I did try and find something like `pretty-quick` for ESLint but didn't have a lot of luck.

**Comment by chopfitzroy** [comment]
Hey @iclanton I thought about this some more and managed to come up with the following solution:

```jsonc
  "commands": [
    {
      // https://rushjs.io/pages/maintainer/enabling_prettier/
      "name": "file-format",
      "commandKind": "global",
      "autoinstallerName": "file-format",
      "shellCommand": "echo '{ \"*.+(md|css|js|jsx|json|yaml)\": \"prettier --write\" }' | lint-staged --config -",
      "summary": "Used by the pre-commit git hook. This command invokes Prettier to reformat staged changes."
    },
    {
      "name": "file-lint",
      "commandKind": "global",
      "autoinstallerName": "file-lint",
      "shellCommand": "echo '{ \"*.+(js|jsx)\": \"eslint --fix\" }' | lint-staged --config -",
      "summary": "Used by the pre-commit git hook. This command invokes ESLint to lint staged changes."
    },
]
```

This way I can invoke `lint-staged` as needed and customize the glob pattern per command, posting here incase someone else comes across this. This also quite nicely covers use cases discussed in [#711](https://github.com/microsoft/rushstack/issues/711) and [#821](https://github.com/microsoft/rushstack/issues/821).
