### ISSUE TITLE
[eslint-config] Outdated version of typescript-eslint plugin and parser

### ISSUE THREAD

**Issue by jjnkr** [microsoft/rushstack#2389]
## Summary

I would like to use TypeScript 4.1.2 in a project which is using the rushstack config. When running ESLint, I see the following message:
```
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <3.10.0
YOUR TYPESCRIPT VERSION: 4.1.2
Please only submit bug reports when using the officially supported version.
=============
```

## Details

I don't know whether bumping up to the newest version of `typescript-eslint`'s tools would cause problems, given that these libraries had a major version change, but if it's possible then that would be helpful for me.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/eslint-config` version? | 2.1.1 |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | 4.1.2 |
| Node.js version (`node -v`)? | 12.8.4 |

**Comment by octogonz** [comment]
We should probably upgrade API Extractor in the same PR.

**Comment by octogonz** [comment]
Bumping priority of this.

**Comment by relm923** [comment]
@octogonz are you able to review #2771 ?

**Comment by octogonz** [comment]
@relm923 Thanks for making a PR! I'm back from the holiday and will take a look today

**Comment by octogonz** [comment]
Update: This got stalled because the PR is failing `rush update --full`.  I'm working on it.
