### ISSUE TITLE
[rush] 'rush publish' creates dirty package.json files that fail 'git checkout master'

### ISSUE THREAD

**Issue by daviwil** [microsoft/rushstack#2395]
## Summary

I am trying to set up release automation with `rush publish` and I've run into an issue where CI fails because Rush can't check out `master` after it creates the temporary `publish-*` branch.  It seems the cause for this is that Rush makes changes to the `package.json` files of my projects such that `git checkout master` fails when the publish process is almost complete.

Here is the command I'm using to publish:

```
node common/scripts/install-run-rush.js publish --apply --publish --target-branch master --set-access-level public
```

## Repro steps

  **Expected result:** 

CI run with `rush publish` should complete successfully.

  **Actual result:** 

Publish job manages to publish the packages and push the tags, but it can't check out `master` so that it can merge in the `publish-*` branch and push it back to origin.  *NOTE:* I cannot reproduce this on my local machine!

## Details

Here's a job where it failed: https://github.com/daviwil/rush-deluxe/runs/1534372931?check_suite_focus=true

Here are the relevant logs:

```
Starting "rush publish"

Validating package manager shrinkwrap file.

Copying /home/runner/work/rush-deluxe/rush-deluxe/common/config/rush/.npmrc-publish --> /home/runner/work/rush-deluxe/rush-deluxe/common/temp/publish-home/.npmrc
Finding changes in: /home/runner/work/rush-deluxe/rush-deluxe/common/changes

* EXECUTING: git checkout -b publish-1607647350132 
Switched to a new branch 'publish-1607647350132'

* APPLYING: minor update for @daviwil/rush-deluxe-logic to 1.1.0
 - [minor] Add writeMessage function

* APPLYING: patch update for @daviwil/rush-deluxe to 1.0.1
 - [dependency] Updating dependency "@daviwil/rush-deluxe-logic" from `~1.0.0` to `~1.1.0`

* APPLYING: Changelog update for "@daviwil/rush-deluxe-logic@1.1.0".

* APPLYING: Changelog update for "@daviwil/rush-deluxe@1.0.1".

* DELETING: 1 change file(s).
 - /home/runner/work/rush-deluxe/rush-deluxe/common/changes/@daviwil/rush-deluxe-logic/add-lib-function_2020-12-10-23-45.json
Deleting: /home/runner/work/rush-deluxe/rush-deluxe/common/changes/@daviwil/rush-deluxe-logic/add-lib-function_2020-12-10-23-45.json

* EXECUTING: git add :/* 

* EXECUTING: git commit -m Applying package updates. --no-verify 
[publish-1607647350132 47ad972] Applying package updates.
 7 files changed, 57 insertions(+), 14 deletions(-)
 create mode 100644 apps/cli/CHANGELOG.json
 create mode 100644 apps/cli/CHANGELOG.md
npm notice package size:  870 B                                   
npm notice unpacked size: 1.2 kB                                  
npm notice shasum:        63585b522263e3b863fee495ae487c7193138592
npm notice integrity:     sha512-eeh4n05g2dZNo[...]cStEg+YSNrB8A==
npm notice total files:   6                                       
npm notice 
+ @daviwil/rush-deluxe@1.0.1

* EXECUTING: git tag -a @daviwil/rush-deluxe-logic_v1.1.0 -m @daviwil/rush-deluxe-logic v1.1.0 

* EXECUTING: git tag -a @daviwil/rush-deluxe_v1.0.1 -m @daviwil/rush-deluxe v1.0.1 

* EXECUTING: git push origin HEAD:publish-1607647350132 --follow-tags --verbose --no-verify 
Pushing to https://github.com/daviwil/rush-deluxe
POST git-receive-pack (546 bytes)
To https://github.com/daviwil/rush-deluxe
 = [up to date]      HEAD -> publish-1607647350132
 * [new tag]         @daviwil/rush-deluxe-logic_v1.1.0 -> @daviwil/rush-deluxe-logic_v1.1.0
 * [new tag]         @daviwil/rush-deluxe_v1.0.1 -> @daviwil/rush-deluxe_v1.0.1
updating local tracking ref 'refs/remotes/origin/publish-1607647350132'

* EXECUTING: git checkout master 
error: Your local changes to the following files would be overwritten by checkout:
	apps/cli/package.json
	lib/logic/package.json
Please commit your changes or stash them before you switch branches.
Aborting
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | None |
| `rushVersion` from rush.json? | 5.35.2 |
| `useWorkspaces` from rush.json? | No |
| Operating system? | Linux |
| Would you consider contributing a PR? | Sure |
| Node.js version (`node -v`)? | 12.20.0 |

**Comment by daviwil** [comment]
Turns out this wasn't Rush's fault, I had a spacing issue in my `package.json` files which caused Rush's updated `package.json` output to resolve the spacing issue, creating a change in the file that wasn't there in the `master` branch.

**Comment by octogonz** [comment]
Maybe Rush should normalize package.json files?

**Comment by daviwil** [comment]
It'd definitely be nice if there was a command I could run that would have Rush normalize all project `package.json` files so that I can check in those changes to ensure that we don't end up with unexpected edits after `rush publish`.

**Comment by VipulGarg** [comment]
@daviwil I am also facing the issue in my branch. Can you please elaborate as to what the spacing issue in package.json file was?

**Comment by daviwil** [comment]
@VipulGarg I think I was missing a space between a dependency and its version number, i.e.:

```
  "dependency":"1.0.0",
```

When Rush regenerated the package.json after the changes, the space was added after the colon resulting in a conflict.

**Comment by antony** [comment]
I get this issue too, but it is because rush has reordered my dependencies in package json.

I'm actually now getting it most times I do a publish, which is extremely problematic.
