### ISSUE TITLE
[rush] Expose commandToRun option to command-line.json config

### ISSUE THREAD

**Issue by arikon** [microsoft/rushstack#2410]
## Summary

Let's expose `commandToRun` option from `IBulkScriptActionOptions` to command-line.json config.
So we could define incremental and non-incremental commands (like `build` and `rebuild`), invoking the same script, on the project level.

**Comment by apostolisms** [comment]
This will possibly be covered by this #2300. 

Can you please provide more details?

**Comment by elliot-nelson** [comment]
Closing -- you can now override behavior of incremental and non-incremental command versions, as well as redefine them as phased operations. (Please reopen if there's specific functionality still missing that you were looking for!)
