### ISSUE TITLE
[rush] Add `changeLogUpdateCommitMessage` to docs and schema

### ISSUE THREAD

**Issue by matthias-ccri** [microsoft/rushstack#2445]
## Summary

Today I ran `rush init` to set up my first rush project. In the `rush.json`, there was a `changeLogUpdateCommitMessage` property, commented out by default. When I uncommented it, vscode showed a warning, because the schema lacks the property and has `"additionalProperties": false`. 

This is the schema: https://developer.microsoft.com/json-schemas/rush/v5/rush.schema.json

As for docs, the [rush.json](https://rushjs.io/pages/configs/rush_json/) page does not mention the property.

## Details

The property was introduced by this PR: https://github.com/microsoft/rushstack/pull/2369 where the schema error was mentioned but appears to be unresolved.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.36.2 |
| `rushVersion` from rush.json? | 5.36.2 |
| `useWorkspaces` from rush.json? | undefined |
| Operating system? | Linux, sorry Bill |
| Would you consider contributing a PR? | Maybe |
| Node.js version (`node -v`)? | 12.13.1 |

**Comment by iclanton** [comment]
Sounds like we need to update our published schemas! Here's the update: https://github.com/microsoft/json-schemas/pull/56
