### ISSUE TITLE
[rush] pnpmOptions.strictPeerDependencies checks even disabled projects

### ISSUE THREAD

**Issue by slavafomin** [microsoft/rushstack#2447]
## Summary

When `pnpmOptions.strictPeerDependencies` is enabled in `rush.json` Rush checks projects and report peer dependency issues for projects that are actually disabled (commented out) in the `projects` list of `rush.json`.

## Example error

` ERROR  A > B: C requires a peer of D but none was installed.`

## Expected behavior

Rush shouldn't check disabled projects and report issues for them.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | `5.36.1` |
| `rushVersion` from rush.json? | `5.36.1` |
| `useWorkspaces` from rush.json? | `Not set` |
| Operating system? | `Ubuntu 18.04.5 LTS` |
| Would you consider contributing a PR? | Not at this point |
| Node.js version (`node -v`)? | `14.15.4` |

**Comment by iclanton** [comment]
When Rush loads `rush.json` into a [`RushConfiguration`](https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/src/api/RushConfiguration.ts) object, comments are stripped out. Did you run `rush update` after commenting out the projects in `rush.json`? It's likely that the projects that you've excluded are still listed in the `pnpm-lock.yaml` file, so `pnpm` may be complaining. However, in that case, Rush should complain before `pnpm` is even invoked.

Can you provide a repro?

**Comment by D4N14L** [comment]
Closing out since author never responded, and it appears to have possibly been dev error.
