### ISSUE TITLE
[rush] Feature Request: Option to git add & commit automatically after rush change

### ISSUE THREAD

**Issue by ScriptedAlchemy** [microsoft/rushstack#2470]
## Summary

When running rush change, some files are created. It would be nice to have an additional flag that auto commits and adds the rush change files. that was just added. Otherwise, developers could send PRs out without the rush files actually being in the commit

## Repro steps

none, feature request

  **Expected result:** 

  **Actual result:** 

## Details

It would be more convenient to have rush commit its own files after running the `rush change` command, since rush already throws errors on uncommitted files, it would make sense to offer an option to have rush commit its own files or amend the last commit and include its change files.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
That sounds like a good idea, and would probably be pretty easy to implement. Would you be interested in putting this together?

**Comment by a-mkljajic** [comment]
@iclanton I'd be keen on taking a look at this, could you give me a couple of pointers about where to start looking?
