### ISSUE TITLE
[rush] Provide Current pwd to Custom Commands

### ISSUE THREAD

**Issue by m1heng** [microsoft/rushstack#2497]
## Summary

hi, i was trying to implement a command which expected to act like rush add, where the command can know current path. But it seems for all custom commands are executed in rush project root. 

As Pete suggested in chat room, current pwd can be provided as an environment variable to executed command.

**Comment by octogonz** [comment]
This turned out to be quite easy. Here's a PR: https://github.com/microsoft/rushstack/pull/2498

**Comment by Amour1688** [comment]
@octogonz how's it going
