### ISSUE TITLE
[rush] use verbs in commit messages / provide cfg option

### ISSUE THREAD

**Issue by akaRem** [microsoft/rushstack#2504]
## Summary

It's considered the best practice to start commits with verbs (Add/Fix/Delete/Merge/Apply/..).
However, some of Rush "helper" commits have "-ing", ex: Applying/Deleting.

I agree that using "Delete" vs "Deleting" can be seen as a personal preference and it's possible to configure some commit messages, but not all of them.

I've found 2 directives `versionBumpCommitMessage` and `changeLogUpdateCommitMessage` in rush.json responsible for "Applying".

I didn't find an option responsible for "Deleting". It might be called "gitChangeLogUpdateCommitMessage", but there is no such section in rush.json generated by the latest rush CLI (I use 5.40.2)

Please, verify that all such commit messages are possible to override; please make sure that docs and autogenerated files include such options

## Repro steps

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.40.2 |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  Mac  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
The field you're looking for is `gitPolicy.changeLogUpdateCommitMessage`. The init text is misleading. I raised a PR to fix it: https://github.com/microsoft/rushstack/pull/2509

**Comment by iclanton** [comment]
This was released in 5.40.6
