### ISSUE TITLE
[rush] CacheId not changes when in non-git environment

### ISSUE THREAD

**Issue by xc2** [microsoft/rushstack#2505]
## Summary

Our projects are intergrated/delivery in a non-git environment like this:

1. checkout specific commit in path `A`
2. sync files without `.git` directory to path `B`
3. build projects in path `B`

When I enabled rush build cache and built projects or did incremental build in this environment, rush always told cache found or build skipped even if I modify files.

###  What action did I perform that ran into trouble in this environemnt:

1. Enable rush build cache, build project `X`
2. Modify files of project `X`, build project `X`

### What went wrong

Rush told that cache was found and restored.

###  What action did I perform that ran into trouble in this environemnt:

1. Not enable rush build cache, build project `X`
2. Modify files of project `X`, build project `X`

### What went wrong

Rush told that build was skipped.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.40.2 |
| `rushVersion` from rush.json? | 5.40.2 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v14.15.5 |

**Comment by iclanton** [comment]
Looks like that's a bug when git isn't found. I'll investigate today.

**Comment by iclanton** [comment]
Here's a fix: https://github.com/microsoft/rushstack/pull/2511
