### ISSUE TITLE
[heft] Feature Request: Approach to skip TypeScript plugin for projects with `tsconfig.json`.

### ISSUE THREAD

**Issue by xc2** [microsoft/rushstack#2515]
## Summary

I'm working at a custom heft plugin that build ts files with babel. [I'm requesting an official plugin too.](https://github.com/microsoft/rushstack/issues/2514)

So I don't need the typescript heft plugin or typescript dependency.

But when heft builds project with `tsconfig.json`, it attempts to find typescript runtime and build source with typescript or fail.

So we need a way to skip TypeScript plugin when building projects with `tsconfig.json`.

### Since `@babel/preset-typescript` does not using `tsconfig.json`, why's there still `tsconfig.json` in your project?

Config files like `tsconfig.json` and `.babelrc` help the whole development environment (like VSCode, IDEA, even tsserver, eslint) understanding codes or resolving imports. So it's important to have these files in our projects.

And because most of the development tools (IDEA/tsserver/eslint) do not provide options to specific path to config files, we must have config files with default path like `tsconfig.json` for development tools and sometimes custom path like `tsconfig.build.json` for build. So please prompting #2258.

**Comment by dmichon-msft** [comment]
Using the "project" option in typescript.json introduced in #2844, you can set it to a non-existent file and that will disable the plugin execution.

**Comment by ApolloTang** [comment]
@dmichon-msft I was able to skip typescript compilation after pointing `project` to a non-existent file, but now I don't know how to heft eslint task. What is the work-around?

**Comment by ApolloTang** [comment]
@dmichon-msft forgot to mention, here is the link to my study: https://github.com/ApolloTang/study--heft/tree/main/03-babel
