### ISSUE TITLE
[eslint-plugin-packlets] Misconfigured package.json not working under PnP strict mode

### ISSUE THREAD

**Issue by sargunv** [microsoft/rushstack#2518]
## Summary

`@rushstack/eslint-plugin-packlets` requires `@typescript-eslint/experimental-utils` at runtime, but only declared a `devDependency` on it instead of `dependency`. This generally works under node modules because other packages will import `experimental-utils`, but in stricter linking strategies like PnP this causes the plugin to fail.

```
~/Source/rushstack-repro(pnp-strict-no-patch) » yarn lint   

Oops! Something went wrong! :(

ESLint: 7.21.0

Error: Failed to load plugin '@rushstack/eslint-plugin-packlets' declared in 'packages/sandbox/package.json » @sargunv/eslint-config/mixins/packlets': @rushstack/eslint-plugin-packlets tried to access @typescript-eslint/experimental-utils, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @typescript-eslint/experimental-utils (via "@typescript-eslint/experimental-utils")
Required by: @rushstack/eslint-plugin-packlets@virtual:26ec5f5a292f7c6726752c2fef51ad1676125f932d835ee26f4165b263410dea52e13f52047f09831f56e1782eb469f65b17bc4124be26e0b6eb0fce0efbd0b8#npm:0.2.0 (via /Users/sargunv/Source/rushstack-repro/.yarn/$$virtual/@rushstack-eslint-plugin-packlets-virtual-4b33fc2c40/0/cache/@rushstack-eslint-plugin-packlets-npm-0.2.0-fef37538f6-f53289cc72.zip/node_modules/@rushstack/eslint-plugin-packlets/lib/)
```

## Repro steps

1. Start a new project and run `yarn set version berry`
2. Install eslint and configure it to use the packlets plugin
3. Try linting a source file; it'll fail with the error above
4. Now switch to `pnpMode: loose` in `.yarnrc.yml`
5. Try linting a source file, it works but logs an import warning
6. Switch back to `pnpMode: strict` and set `packageExtensions`:

```yml
packageExtensions:
  "@rushstack/eslint-plugin-packlets@*":
    dependencies:
      "@typescript-eslint/experimental-utils": "*"
```

7. Try linting again, it works!

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/eslint-plugin-packets` version? | v0.2.0 |
| Operating system? | macOS |
| Would you consider contributing a PR? | yes |
| TypeScript compiler version? | N/A |
| Node.js version (`node -v`)? | v14.15.1 |

**Comment by octogonz** [comment]
Does ESLint work with Yarn Plug'n'Play (without the patch and without a shared config)? The `@rushstack/eslint-patch` patch reuses ESLint's proprietary module resolver, by [overriding](https://github.com/microsoft/rushstack/blob/bfd34fa1893631a06bb836f6b77edc0e59c093b2/stack/eslint-patch/src/modern-module-resolution.ts#L126) the folder that it resolves relative to.

**Comment by sargunv** [comment]
[Yes it does](https://yarnpkg.com/features/pnp#native-support), but will get back to you with a proper repro repo tomorrow.

**Comment by sargunv** [comment]
Okay, here's the repro: https://github.com/sargunv/rushstack-repro

You'll see a number of branches:
* `pnp-strict` the basic repro, `yarn install && yarn lint` fails
* `pnp-strict-no-patch` still fails
* `pnp-loose` and `pnp-loose-no-patch` use `pnpMode: loose` and they work but log an import warning
* `pnp-strict-fixed` forces `@rushstack/eslint-plugin-packlets` to declare a `peerDependency` on `@typescript-eslint/experimental-utils` and it works

You're right, turns out the issue is a misconfigured `package.json` in `@rushstack/eslint-plugin-packlets`, not an issue in `@rushstack/eslint-patch`. PR incoming to fix it.

I'll go ahead and update the OP to reflect this.
