### ISSUE TITLE
[rush] TypeError: colors.red is not a function

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#2526]
## Summary

Certain Rush operations fail because `colors` is not imported correctly.

## Repro steps

1. Set `RUSH_PREVIEW_VERSION` to an invalid string, for example:
   ```
   set RUSH_PREVIEW_VERSION=4.4.4.4.4.
   ```

2. Invoke `rush install`

```
C:\Users\Owner\AppData\Roaming\nvm\v14.15.4\node_modules\@microsoft\rush\lib\start.js:53
        console.error(colors.red(`Invalid value for RUSH_PREVIEW_VERSION environment variable: "${previewVersion}"`));
                             ^

TypeError: colors.red is not a function
    at Object.<anonymous> (C:\Users\Owner\AppData\Roaming\nvm\v14.15.4\node_modules\@microsoft\rush\lib\start.js:53:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

This is just one example.  Various code paths hit this error.

## Details

Recently the **tsconfig.json** file enabled `esModuleInterop=true` which is "recommended" by the TypeScript group.

However this causes the compiler to accept incorrect imports that will fail at runtime:

https://github.com/microsoft/rushstack/blob/c4d6540bb7a0dabb6715247ab5545329dbff2e34/apps/rush/src/start.ts#L21

The above import should say `import colors from 'colors';`.  The error is only reported when/if the code path actually tries to call `colors.red()`.

## Thoughts

This is an absolutely insidious flaw of  `esModuleInterop=true`.  Is there some way we can make the toolchain catch these mistakes?  Maybe an ESLint rule?

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.40.6 |
| `rushVersion` from rush.json? | 5.40.6 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | confirmed on Windows / Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 12.17.0 |

**Comment by iclanton** [comment]
This has been published in Rush 5.40.7.
