### ISSUE TITLE
[heft] Typescript version is not picked up by heft declared in local package.json

### ISSUE THREAD

**Issue by Claudiazhaoya** [microsoft/rushstack#2537]
## Summary

I was trying to use typescript 3.7.x to do the heft build in our internal-repo but heft doesn't pick up the correct typescript version I declared in package.json and keeps using typescript 3.9.9. 
## Repro steps

  **Expected result:** 
Heft should pick up the typescript version declared in local package.json.
  **Actual result:** 
Heft keeps using its default typescript version 3.9.9.
## Details

This line of code guarantees that it will keep recursing through extends until it reaches the final one. And only then does it look for TypeScript. 
https://github.com/microsoft/rushstack/blob/master/apps/heft/src/utilities/TaskPackageResolver.ts#L196

According to the docs, it should check for TypeScript first before iterating down the extends.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
This is fixed in Heft 0.25.0
