### ISSUE TITLE
[rush] Broken peer dependency error when installing @microsoft/rush-lib

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#2547]
## Summary

The latest Rush release has a broken peer dependency.  This was originally reported by @boardend in https://github.com/microsoft/rushstack/issues/2393#issuecomment-796800750

## Repro steps

```
$ mkdir repro
$ cd repro
$ npm init
$ npm install @microsoft/rush-lib@5.42.0
```

  **Expected result:** A clean install.

  **Actual result:**
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN react-native-get-random-values@1.6.0 requires a peer of react-native@>=0.56 but none is installed. You must install peer dependencies yourself.
```

This is a hard error with `--strict-peer-dependencies`.

## Details

This is a regression in Rush 5.42.0

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |5.42.0 |
| Operating system? | Windows / Mac / Linux  |
| Node.js version (`node -v`)? | 12.20.1 |

**Comment by sachinjoseph** [comment]
Hmmm

```powershell
PS> md t
PS> cd t
PS> pnpm install @microsoft/rush-lib@5.42.0 --strict-peer-dependencies
```

![image](https://user-images.githubusercontent.com/6994498/110856702-d665b280-826c-11eb-88f2-835591f3d8cc.png)

**Comment by sachinjoseph** [comment]
@D4N14L and I did some digging:

![image](https://user-images.githubusercontent.com/6994498/110859285-10848380-8270-11eb-8b40-6efcb3c71183.png)

**Comment by D4N14L** [comment]
Yes this appears to be an upstream package issue, and has been for some time. I think for now if you don't want this to impact Rush then the AWS cache functionality needs to be removed while the upstream package dependency graph is fixed either to pass the peer dep all the way up to the consumer of `@aws-sdk/client-s3`, or to satisfy the peer dep.

**Comment by octogonz** [comment]
`react-native` is a completely unreasonable dependency.  It is 131MB.

Can we at the very least revert the NPM dist tag to Rush 5.41.0 to prevent people from installing 5.42.0?

**Comment by octogonz** [comment]
This `awsCredentialsProvider()` call is the only part of the feature that relies on the AWS SDK.


https://github.com/microsoft/rushstack/blob/5aabcae1617868afc583f60a5c4ef5a1d8a55dff/apps/rush-lib/src/logic/buildCache/AmazonS3BuildCacheProvider.ts#L107-L116

I'm going to make a PR to disable this logic, since it's better than reverting the feature entirely.

Maybe @raihle can help us find a way to perform equivalent functionality without a peer dependency on the entire React Native framework.   The peer dependency is not actually needed by this code path BTW.  But it is breaking our installs as shown above, so we need to eliminate it.

**Comment by octogonz** [comment]
Here's a PR:  https://github.com/microsoft/rushstack/pull/2550

**Comment by octogonz** [comment]
Rush 5.42.1 has been published with the temporary fix.  Hopefully @iclanton and @raihle can figure out a better long term solution.

**Comment by octogonz** [comment]
This PR did not work because `@aws-sdk/client-s3` has the same peer dependency. :'(

**Comment by octogonz** [comment]
While we sort this out, I have temporarily rewound the NPM disttag so that `latest` is 5.41.0.

(Amazon -- how does a cloud SDK have a dependency on React Native?!)

**Comment by octogonz** [comment]
We were wondering how this got past our CI build with [--strict-peer-dependencies](https://github.com/microsoft/rushstack/blob/250d7b40d9d811fc20a9c25a5f87abc60e70e9f7/rush.json#L65) enabled. Turns it the PR included a workaround to delete the dependency locally:

https://github.com/microsoft/rushstack/blob/250d7b40d9d811fc20a9c25a5f87abc60e70e9f7/common/config/rush/pnpmfile.js#L29-L43

**Comment by octogonz** [comment]
Here is the upstream issue: https://github.com/aws/aws-sdk-js-v3/issues/2051

**Comment by raihle** [comment]
My bad on this, I expected the pnpmfile hack to disable the peer dependency transitively, but in retrospect that's of course not possible.

V2 of the AWS SDK is huge by itself and even the earliest versions of V3 include this dependency.

Would a fork of the AWS SDK with this dependency removed be acceptable as a workaround?
