### ISSUE TITLE
[heft] [feature-request] Possibility to (optionally) remove front-end build tooling?

### ISSUE THREAD

**Issue by prescience-data** [microsoft/rushstack#2548]
## Summary

Certainly not an urgent concern, but I have moved all my Node projects to `Rush` which will never require any of the front-end build tooling like `webpack`, `node-sass`, `postcss` and so on.

Additionally, I haven't fully looked into what the `Jest` components of `Heft` do yet, but the tests are another one that seems like an easy win to strip given many people are using alternate testing frameworks. 

For the sake of efficiency & reducing unnecessary dependency compatibility issues, it would be great to one day have the option to use a version of `Heft` that is intended solely for CLI / server-type applications. 😁💭

### Possible solution:
A thinner version of `@rushstack/heft`, ie: `@rushstack/heft-base` / `@rushstack/heft-lite` _(or some similar nomenclature that fits the Rush style guide)_ which the "full" `Heft` extends on.

https://github.com/microsoft/rushstack/tree/master/apps/heft

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | Current |
| Would you consider contributing a PR? | Yes, with some deeper study of the Heft package required. | 
| Node.js version (`node -v`)? | 14+ |

**Comment by octogonz** [comment]
Heft's plugin-based architecture was designed to support this.  Initially everything was rolled together purely as a convenience.  Jest and Webpack are the biggest dependencies, so it's likely that at least those plugins will get extracted into their own packages somewhat soon.

CC @iclanton

**Comment by iclanton** [comment]
Yeah we've been talking about doing that. We could probably initially create two plugin packages: one for the browser-targeting plugins (webpack, sass, etc) and one for Jest. That probably actually wouldn't be too hard.

Any opinions on the package names?

**Comment by dmichon-msft** [comment]
We could borrow the Babel naming convention:
@rushstack/heft-core
@rushstack/heft-preset-web (shorthand for @rushstack/heft-plugin-sass and @rushstack/heft-plugin-webpack)
@rushstack/heft-plugin-jest

Though it might make sense to separate SASS and Webpack, since the latter is sometimes used to target Node, though esbuild seems be gaining favor in that space.

**Comment by prescience-data** [comment]
@dmichon-msft 
ESBuild is incredible, the speed is absolutely absurd! I currently have it jury-rigged to make ESBuild run for the final packaging, but it can also do "just" TypeScript builds but with the speed of multithreading, so it would be absolutely nuts how fast `heft` would run even on full `rush rebuild` calls if there was an optional plugin for that (to swap out `tsc` for)

**Comment by prescience-data** [comment]
@iclanton 
As you mentioned the "official" Heft plugins potentially being abstracted out _(ie "browser", "jest", etc)_, given [Folio](https://github.com/microsoft/folio
) is another Microsoft product it would be cool to see an official Heft package for it one day as well for people working with fixtures-based testing!  🕺

https://github.com/microsoft/folio

**Comment by Niek** [comment]
This is relevant again now that Node 16 is out. The package `node-sass` doesn't work with Node 16 yet (see https://github.com/sass/node-sass/pull/3090) so heft doesn't work on Node 16 yet. See also the previous issue in relation to Node 15 support: https://github.com/microsoft/rushstack/issues/2490

**Comment by prescience-data** [comment]
Yeah will be nice to roll to the new LTS (16) and off 14

**Comment by jonasb** [comment]
Another vote for breaking moving out at least sass into a separate (optional) plugin. 

I'm running on Apple Silicon (M1) and prefer to use ARM binaries for Node. There is only official Node support for Node 16+ and even if `node-sass` supports Node 16+ in `node-sass@6`, it [doesn't support Apple silicon](https://github.com/sass/node-sass/issues/3033) resulting in this error "Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Node.js 16.x"

I assume there's no official way of disabling the sass functionality?

**Comment by jonasb** [comment]
@prescience-data Heft 0.35 is released now which extracts Sass to a separate plugin. Does it cover this feature request?

**Comment by GongT** [comment]
good news: this is resolved 🎉

**Comment by octogonz** [comment]
@gongt thanks for pointing that out!
