### ISSUE TITLE
[rush] envrionment variable RUSH_TEMP_FOLDER did not work

### ISSUE THREAD

**Issue by WanderWang** [microsoft/rushstack#2566]
## Summary

envrionment variable ```RUSH_TEMP_FOLDER``` did not work

I use rush with my gitlab-ci pipeline . 
Gitlab-ci pipeline will  prepare a clean environment when triggered , and gitlab-ci 's cache is slowly ( becuase of too many files in ```common/temp``` need to be cached )
So I want to use ```RUSH_TEMP_FOLDER``` and setup it to a global store instead of use gitlab-ci 's cache
But it failed 

## Repro steps

1.  edit ```~/.bashrc```  ,add ```RUSH_TEMP_FOLDER=/home/gitlab-runner/rush-cache```
2.  execute ```source ~/.bashrc```
3.  execute ```rush update```

  **Expected result:** 

```common/temp``` should be empty and ```/home/gitlab-runner/rush-cache``` should be used

  **Actual result:** 
rush still use ```common/temp```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.40.7 |
| `rushVersion` from rush.json? | 5.40.7 |
| `useWorkspaces` from rush.json? | no |
| Operating system? | Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 14.16.0 |

**Comment by octogonz** [comment]
In [this chat](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/how.20improve.20gitlab-runner.20cost.20time/near/231582004) I confirmed that the problem does not repro for 5.11.3 (the most recent CHANGELOG referencing this feature), but it does repro for Rush 5.40.7.

Thus, this is a somewhat recent regression.

**Comment by octogonz** [comment]
> **Actual result:** rush still use `common/temp`

Here's what I tried:
1. I used Windows OS
2. Clone https://github.com/microsoft/rushstack  which has `useWorkspaces=true` in **rush.json**
3. Set `RUSH_TEMP_FOLDER` = "C:\Example"
4. Run `rush install`

It makes `C:\Example` and writes a bunch of files there, then prints an error: 
```
The shrinkwrap file is out of date. You need to run "rush update".
```

If I run `rush update`, then it says `Running "pnpm install" in C:\Example`  and we get:
```
ERROR: Internal Error: Cannot find shrinkwrap entry using importer key for workspace project:
```

@D4N14L Is `RUSH_TEMP_FOLDER` expected to work with PNPM workspaces at all? 

(Are you not using this feature?  Seems like your group originally introduced it in PR https://github.com/microsoft/rushstack/pull/585)

**Comment by octogonz** [comment]
> I confirmed that the problem does not repro for 5.11.3 (the most recent CHANGELOG referencing this feature), but it does repro for Rush 5.40.7.

Correction:  I'm pretty sure that the difference here was merely that `useWorkspace=false` at that time, not the Rush version.

For example, the https://tsdoc.org/ Rush repo has `useWorkspaces=false`, and I was successfully able to install/build it using the latest Rush 5.42.3 and PNPM 5.18.8, with `RUSH_TEMP_FOLDER`.  And I confirmed that no files were written under `common/temp`.

Based on a chat with @D4N14L, the `RUSH_TEMP_FOLDER` seems to be fundamentally incompatible with PNPM workspaces.  We should prevent people from using it.

**Comment by octogonz** [comment]
@WanderWang for your original problem, our recommended solution is therefore:
1. Configure GitLab to NOT cache `common/temp`
2. Instead use `RUSH_PNPM_STORE_PATH` to cache only the PNPM store folder.

This is what Microsoft is doing, and it should accomplish your goal of reducing your `rush install` times.

**Comment by WanderWang** [comment]
```RUSH_PNPM_STORE_PATH``` still not work  :-(
```bash
Checking out 23465219 as master...
Skipping Git submodules setup
$ echo $RUSH_PNPM_STORE_PATH
/home/gitlab-runner/rush-cache
$ rush install --to server


Rush Multi-Project Build Tool 5.40.7 - https://rushjs.io
Node.js version is 14.16.0 (LTS)


Starting "rush install"

Validating package manager shrinkwrap file.

Trying to acquire lock for pnpm-5.13.6
Acquired lock for pnpm-5.13.6
Found pnpm version 5.13.6 in /home/gitlab-runner/.rush/node-v14.16.0/pnpm-5.13.6

Symlinking "/home/gitlab-runner/builds/820b29cf/0/ads/web-client/common/temp/pnpm-local"
  --> "/home/gitlab-runner/.rush/node-v14.16.0/pnpm-5.13.6"

Using the default variant for installation.
Copying /home/gitlab-runner/builds/820b29cf/0/ads/web-client/common/config/rush/.npmrc --> /home/gitlab-runner/builds/820b29cf/0/ads/web-client/common/temp/.npmrc
Updating /home/gitlab-runner/builds/820b29cf/0/ads/web-client/common/temp/pnpmfile.js

Updating workspace files in /home/gitlab-runner/builds/820b29cf/0/ads/web-client/common/temp
Finished creating workspace (0.13 seconds)


Running "pnpm install" in /home/gitlab-runner/builds/820b29cf/0/ads/web-client/common/temp

Scope: 2 of 5 workspace projects
Using hooks from: /home/gitlab-runner/builds/820b29cf/0/ads/web-client/common/temp/pnpmfile.js
readPackage hook is declared. Manifests of dependencies might get overridden
Progress: resolved 1, reused 0, downloaded 0, added 0
# reduce unnecessary logs 
Progress: resolved 1155, reused 0, downloaded 1153, added 0
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/gitlab-runner/builds/820b29cf/0/ads/web-client/common/temp/pnpm-store/v3
```

**Comment by WanderWang** [comment]
```useWorkspace``` has been set to ```true```

**Comment by D4N14L** [comment]
@WanderWang are you sure that you are setting the environment variable correctly? Ex. `export RUSH_PNPM_STORE_PATH=<path>`? It appears you may just be setting a local bash var. I'm able to confirm that the latest version of Rush behaves as expected when this env var is set.

On another note, the block of `RUSH_TEMP_FOLDER` in workspace installs is in.

**Comment by WanderWang** [comment]
> @WanderWang are you sure that you are setting the environment variable correctly? Ex. `export RUSH_PNPM_STORE_PATH=<path>`? It appears you may just be setting a local bash var. I'm able to confirm that the latest version of Rush behaves as expected when this env var is set.
> 
> On another note, the block of `RUSH_TEMP_FOLDER` in workspace installs is in.

@D4N14L  u r right ,   thank u !

@octogonz , ```RUSH_PNPM_STORE_PATH ``` works well , u can close this issue
