### ISSUE TITLE
[eslint-plugin-packlets] Linting TypeError with typescript version >=4.2.0

### ISSUE THREAD

**Issue by klonowicki** [microsoft/rushstack#2591]
## Summary

I'm getting a typescript error from eslint-plugin-packlets while linting after upgrading TypeScript version to any equal or above 4.2.0
Error contents: 
`TypeError: program.getRefFileMap is not a function`
It's from DependencyAnalizer file from checkEntryPointForCircularImport function.
Eslint exits with error code 2.

## Repro steps

1. Upgrade TypeScript version from 4.1.3 to 4.2.3
2. Run 'eslint' script

## Details

eslint script: eslint 'packages/*/{src,tests}/**/*.{js,ts,tsx}' '**/*.json' 'cypress/**/*.{js,ts,tsx}' --fix && stylelint --fix 'packages/**/*.scss'

"@typescript-eslint/eslint-plugin": "^4.14.1",
"@typescript-eslint/parser": "^4.14.1",
"eslint": "^7.15.0",

An Error occurs also when upgrading above packages to the newest ones.

"webpack": "^5.17.0",

.eslintrc.json

> 
{
    "extends": ["../../.eslintrc.json", "plugin:@rushstack/eslint-plugin-packlets/recommended"],
    "parserOptions": {
        "ecmaVersion": 2020,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        },
        "project": ["./tsconfig.json"],
        "tsconfigRootDir": "./packages/client"
    },
    "ignorePatterns": ["*.json"],
    "rules": {
        "@rushstack/packlets/mechanics": "error"
    }
}
> 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/eslint-plugin-packlets` version? | 0.2.0 |
| Operating system? | Windows |
| Would you consider contributing a PR? |  No |
| TypeScript compiler version? |  >=4.2.0  |
| Node.js version (`node -v`)? |  14.16.0  |

**Comment by iclanton** [comment]
IS the issue just that the `typescript-eslint` project doesn't have support for TS 4.2 yet? @octogonz, have you tried upgrading any of your projects to 4.2 and seen this issue?

**Comment by octogonz** [comment]
@iclanton  The problem is that `eslint-plugin-packlets` calls an internal API:

https://github.com/microsoft/rushstack/blob/a13865bef9a20dab28c044be3504c7326bfe94b1/stack/eslint-plugin-packlets/src/DependencyAnalyzer.ts#L179

And that API doesn't exist in TS 4.2.  Lemme investigate it real quick.

**Comment by octogonz** [comment]
It was removed in https://github.com/microsoft/TypeScript/pull/40011

**Comment by octogonz** [comment]
Seems like `Program.getFileProcessingDiagnostics()` or `Program.getFileIncludeReasons()` might be a suitable replacement.

**Comment by octogonz** [comment]
`Program.getFileIncludeReasons()` works. Lemme see if I can make a PR.

**Comment by octogonz** [comment]
Here is a PR: https://github.com/microsoft/rushstack/issues/2591

**Comment by octogonz** [comment]
> 
> 
> @iclanton The problem is that `eslint-plugin-packlets` calls an internal API:
> 
> https://github.com/microsoft/rushstack/blob/a13865bef9a20dab28c044be3504c7326bfe94b1/stack/eslint-plugin-packlets/src/DependencyAnalyzer.ts#L179
> 
> And that API doesn't exist in TS 4.2. Lemme investigate it real quick.

@sheetalkamat Maybe the compiler could provide a public supported version of this API?  There doesn't seem to be an easy way to implement this analysis without relying on the internal API.

**Comment by octogonz** [comment]
This fix was released with `@rushstack/eslint-plugin-packlets` version 0.2.2
