### ISSUE TITLE
[rush] Rush reports "Internal Error" after upgrading to PNPM 6

### ISSUE THREAD

**Issue by prescience-data** [microsoft/rushstack#2601]
## Summary

Running `rush update` with `"pnpmVersion": "6.0.1"` results in `ERROR: Internal Error: Cannot find installed dependency <pkg>` when linking.

 

## Repro steps

1. Update `rush.json` to use `"pnpmVersion": "6.0.1"`
2. Run `rush purge && rush update`
3. Rush installs dependencies
4. When attempting to link first package encounters `ERROR: Internal Error: Cannot find installed dependency <first-dependency-of-first-local-package>`
 

  **Expected result:** 

A completed `rush update` linking.

  **Actual result:** 
```text
ERROR: Internal Error: Cannot find installed dependency "@rushstack/eslint-config" in
"D:\Dev\<pkg>\common\temp\node_modules\.pnpm\local\D%3A%2FDev%2F<pkg>%2Fcommon%2Ftemp%2Fprojects%2F<local-pkg>.tgz\node_modules"
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

## Details

The issue is occurring because the directory referenced in the error above is now using `+` as a seperator instead of `%3A`  `:` and `%2F`  `/`

See: https://github.com/pnpm/pnpm/releases/tag/v6.0.1

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.43.0 |
| `rushVersion` from rush.json? | 5.43.0 |
| `useWorkspaces` from rush.json? | false |
| Operating system? |  Windows  |
| Would you consider contributing a PR? | Yes, if required |
| Node.js version (`node -v`)? | v14.16.0 |

**Comment by Niek** [comment]
Same issue here

**Comment by smolinari** [comment]
[I reported this issue in the Rush Zulip chat](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/Linking.20projects.20-.3E.20cannot.20find.20deps.20error) and was asked to look at another chat thread. It asks to set `useWorkspaces` to true in `rush.json`. I did that then did a `rush update --full --purge` and the update was successful. 

Scott

**Comment by prescience-data** [comment]
Awesome! Thanks for that - 

I wasn't sure what risks the `useWorkspaces: true` setting incurred as it was flagged as `experimental` but that _"pnpm workspaces is the future"_ statement gives the confidence to enable it and solve the problem. 

Thanks again!

**Comment by octogonz** [comment]
I am reopening this issue.  Even if there are workarounds, it's not okay for Rush to be reporting `Internal Error` when upgrading PNPM.  

- The underlying incompatibility needs to be fixed
- Or at the very least, Rush should report an error saying PNPM 6 is not supported without `useWorkspaces=true`

@iclanton @D4N14L

**Comment by octogonz** [comment]
👉 Issue https://github.com/microsoft/rushstack/issues/2542 is tracking a different issue (unrelated to PNPM 6) that produces the same error message.
