### ISSUE TITLE
[rush] does not link dependencies' dependencies to projects

### ISSUE THREAD

**Issue by ziofat** [microsoft/rushstack#2619]
As v5.44.0, `rush update` seems broken. It does not link node modules depended by packages dependencies.

**Comment by octogonz** [comment]
@ziofat Can you provide some repro steps?

I just created PR https://github.com/microsoft/rushstack/pull/2621 to upgrade the Rush Stack repro, and it seems to be building without any problems.

**Comment by ziofat** [comment]
I created a [repo](https://github.com/ziofat/rush-dependencies) which is created by `rush init`. I am trying to create a documentation website using docz in `apps/docz`.

This package depends on `docz` which depends on `gatsby`. When I run `rush build`, it emit an error:

```
'gatsby' is not recognized as an internal or external command,
operable program or batch file.
```

The same thing happens to Docusaurus as well, it emits: 

```
Module not found: Can't resolve '@svgr/webpack' in 'D:\workspace\opensource\rush-dependencies\apps\docusaurus'./src/components/HomepageFeatures.js
Module not found: Can't resolve '@svgr/webpack' in 'D:\workspace\opensource\rush-dependencies\apps\docusaurus'./src/components/HomepageFeatures.js
Module not found: Can't resolve '@svgr/webpack' in 'D:\workspace\opensource\rush-dependencies\apps\docusaurus'./docs/tutorial-basics/markdown-features.mdx
Module not found: Can't resolve 'url-loader' in 'D:\workspace\opensource\rush-dependencies\apps\docusaurus\docs\tutorial-basics'./docs/tutorial-extras/translate-your-site.md
Module not found: Can't resolve 'url-loader' in 'D:\workspace\opensource\rush-dependencies\apps\docusaurus\docs\tutorial-extras'./docs/tutorial-extras/manage-docs-versions.md
Module not found: Can't resolve 'url-loader' in 'D:\workspace\opensource\rush-dependencies\apps\docusaurus\docs\tutorial-extras'
```

I have includes build logs in the demo repo.

**Comment by ziofat** [comment]
By the way, this may not be 5.44.0 related because it can be reproduced on my other linux machine which runs 5.42.4.

**Comment by ziofat** [comment]
Well, I can get how Phantom dependencies related to docz issue, docz tool directly running gatyby in project directory which makes a phantom dependency. But why docusaurus failed since it is using webpack to do some building work where those modules are not being used directly by my project?

**Comment by octogonz** [comment]
>  I thought we used to have a "dangerously flatten node_modules" option, but I can't find it. 

@iclanton PNPM offers a `--shamefully-flatten` option.  A while ago I tried to make a PR to expose it via Rush but it turned out to have nontrivial incompatibilites with Rush's installation model. 

However with `useWorkspaces=true` in **rush.json**, the situation may be different.   (@D4N14L?)  Maybe we can support it now.  Someone should investigate it.

**Comment by octogonz** [comment]
BTW another easy workaround for phantom dependencies is to use **pnpmfile.js** to add the missing dependency.

**Comment by D4N14L** [comment]
> > However with `useWorkspaces=true` in **rush.json**, the situation may be different.   (@D4N14L?)  Maybe we can support it now.  Someone should investigate it.

Yes, this should be the case that this can be supported in workspaces mode since everything is linked by PNPM in-place.

**Comment by ziofat** [comment]
> BTW an easy workaround for phantom dependencies is to use **pnpmfile.js** to add the missing dependency.

Seems pnpmfile.js is used to change dependencies' package.json? How can I use this to resolve docz's issue? I think docz has correct dependencies declaration since it puts `gastby` in `dependencies`. If I was a maintainer of docz I have no clue to fix this.

**Comment by dmichon-msft** [comment]
If need be you can configure advanced options for pnpm in your `.npmrc` file: https://pnpm.io/npmrc
