### ISSUE TITLE
[rush] Running "Rush Script" in githooks conflicts with rush publish

### ISSUE THREAD

**Issue by liyikun** [microsoft/rushstack#2637]
## Summary

Following the official documentation will trigger an “Another Rush command is already running in this repository.”

## Repro steps
First follow the steps
https://rushjs.io/pages/maintainer/enabling_prettier/

In this step, i had set prettier command.

Second follow the steps
https://rushjs.io/pages/maintainer/publishing/

In this step, I tried to run "rush publish -a  -b  master  -p" .

![image](https://user-images.githubusercontent.com/15144040/115844493-76108600-a452-11eb-97c5-aee84ba1948c.png)

## Details

It is recommended to add "safeForSimultaneousRushProcesses" related introduction in the Installing Enabling Prettier chapter，It took me several hours to troubleshoot the problem.

### pre script
  ```
  "commands": [
    {
      "name": "prettier",
      "commandKind": "global",
      "summary": "Used by the pre-commit Git hook. This command invokes Prettier to reformat staged changes.",

      "autoinstallerName": "rush-prettier",

      // This will invoke common/autoinstallers/rush-prettier/node_modules/.bin/pretty-quick
      "shellCommand": "pretty-quick --staged"
    }
```
### next
```
  "commands": [
    {
        ....pre,
        // if you running command is "rush publish -b  targetBranch", you need  to set this value.
        "safeForSimultaneousRushProcesses": true
    }
```

**Comment by iclanton** [comment]
Yeah, `safeForSimultaneousRushProcesses` should be set to `true` for prettier. That's what we have [in this repo](https://github.com/microsoft/rushstack/blob/master/common/config/rush/command-line.json#L164). I'll make a PR to update the docs. Thanks for catching that!

**Comment by iclanton** [comment]
https://github.com/microsoft/rushjs.io-website/pull/88/files
