### ISSUE TITLE
[rush] Feature Request - Support rush build -t reviewCategory

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/rushstack#2639]
## Summary

Rush build has an option `--to-version-policy` e.g. `rush build -t "my-project"`

It would be great if we could also specificy a `reviewCategory` here instead of a project name

## Details

In rush json you may have:
```json
{
  "projects": [
    {
      "packageName": "storybook",
      "projectFolder": "packages/storybook",
      "reviewCategory": "tools"
    },
  ]
}
```

In this case I am looking to be able to do an equivalent of `rush build -t tools` and it would be build all projects with reviewCategory as tools (and all their dependency projects)

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? | 5.40.7 |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
The original design of review categories was to ensure licenses were appropriate for how projects were released from a repo. There was a suggestion (https://github.com/microsoft/rushstack/issues/1241) to generalize review categories into project "tags," which sounds like it would accomplish the same thing, but in a more flexible way.

**Comment by JamesBurnside** [comment]
Oh nice, yeah this issue encapsulates what I'm looking for, closing this.
