### ISSUE TITLE
[rush] Build Cache: split apart RUSH_BUILD_CACHE_WRITE_CREDENTIAL

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/rushstack#2642]
## Summary

If you choose to enable the build cache feature but you want to require credentials for read access (e.g.: you have created an Azure storage account and disabled public access), the feature is not quite useable yet.

In particular, if you desire a CI setup as follows:

 - PR Build: developer PR-builds read (but don't write) the cache
 - CI Build: CI build does not read or write from the cache (forcing it to run all builds and unit tests to watch for regressions)
 - Cache Update Build: a separate job triggers on merges and runs a read-and-write build

There's no way to create a "read but don't write" CI job, because the only way to provide credentials via env vars also assumes that writing should be enabled.

## Details

Suggestion: eliminate `RUSH_BUILD_CACHE_WRITE_CREDENTIAL` and replace it with:

 * `RUSH_BUILD_CACHE_CREDENTIAL` -- if provided, overrides whatever lives in the rush-user cache
 * `RUSH_BUILD_WRITE_ENABLED` -- if set to the string value `true` or `false`, overrides the value provided in `build-cache.json`.
 
This allows pretty much any CI system (Azure, Jenkins, Actions, etc.) to specify the behavior they want for each job, without having to modify the build scripts or steps.  I also think this is a little more intuitive, as each environment variable is the override for exactly one field in the config file.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.43.0
| `rushVersion` from rush.json? | 5.43.0
| `useWorkspaces` from rush.json? | true
| Operating system? | Mac
| Would you consider contributing a PR? | Yes
| Node.js version (`node -v`)? | 12.17.0

**Comment by iclanton** [comment]
I think I like this design. @octogonz - you had opinions on the naming of this variable, what are your thoughts?

@elliot-nelson, would you be interested in raising a PR for this?

**Comment by octogonz** [comment]
>* `RUSH_BUILD_WRITE_ENABLED` -- if set to the string value `true` or `false`, overrides the value provided in `build-cache.json`.

When `ts-command-line` flag parameters are mapped to environment variables, they use `0` or `1` instead of `true` or `false`:
https://github.com/microsoft/rushstack/blob/4aa649c4fb8d43465a52a5ed5be09015e129fa25/libraries/ts-command-line/src/parameters/CommandLineFlagParameter.ts#L45-L55

(I forget why, but I think it was to avoid worrying about character case.)

**Comment by octogonz** [comment]
What if a CI job wants to disable the build cache entirely?  Is it cool for them to use the ` --disable-build-cache` CLI parameter for every command?  Or would it make sense to provide an environment variable for that as well?  I'm asking because we'd want the names to make sense together.  Something like `RUSH_BUILD_CACHE_ENABLED=0`.

We could enable that easily here:
https://github.com/microsoft/rushstack/blob/a13865bef9a20dab28c044be3504c7326bfe94b1/apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts#L313-L316

**Comment by elliot-nelson** [comment]
> What if a CI job wants to disable the build cache entirely? Is it cool for them to use the ` --disable-build-cache` CLI parameter for every command?

I'm trying to avoid having to use `--disable-build-cache`, because you don't necessarily have control over the scripts you are running in your pipeline.  (If your `azure-pipeline.yaml` is running `rush build`, then of course it's easy to add extra flags; but if it's running `scripts/rush-build-all.sh`, it might not even be taking arguments.)  With an env var, you always know you can set it at the top of a pipeline (or even on the machine running the command!) and have it be respected.

That hadn't occurred to me but now that I see it, it seems almost necessary.

If you've _intentionally_ made your Azure Storage Account private, and you have some jobs that you don't want to use the cache on, right now you can set `RUSH_BUILD_CACHE_WRITE_CREDENTIAL` to nothing, but then you'll still get a bunch of warnings about failed attempts to read the cache in your CI logs.  Setting an env var `RUSH_BUILD_CACHE_ENABLED=0` would avoid all those warnings (and any worry that people might think those warnings need to be fixed).

**Comment by iclanton** [comment]
My recommendations would be `RUSH_BUILD_CACHE_CREDENTIAL`, `RUSH_BUILD_CACHE_WRITE_ALLOWED` (for consistency with the `build-cache.json` config file), and  `RUSH_BUILD_CACHE_DISABLED` (because it'll default to false, and I'd think you would want to have to proactively disable the build cache).

**Comment by elliot-nelson** [comment]
It sounds like those last two vars do work slightly differently then (can be noted in eventual documentation).

For `RUSH_BUILD_CACHE_DISABLED`, it has no meaning unless set to true.  It is one of three ways to disable the build cache (command line flag, env var, and rush-project config).  If _any_ of these are true, the cache is disabled; false or missing ones are ignored.

Whereas for `RUSH_BUILD_CACHE_WRITE_ALLOWED`, if it exists and is 1 or 0, that is considered an override of the false or true setting in the build cache config.

**Comment by elliot-nelson** [comment]
Fixed by #2674.
