### ISSUE TITLE
[rush] An unrecognized file "pnpmfile.js" was found in the Rush config folder after updating the Rush to 5.45.1

### ISSUE THREAD

**Issue by slavafomin** [microsoft/rushstack#2644]
Hello!

After updating the Rush from `5.45.0` to `5.45.1` I'm starting to get the following error message:
`An unrecognized file "pnpmfile.js" was found in the Rush config folder`.

I'm using pnpm `6.2.1`.

There is no information regarding this behavior in recent changelogs of both Rush and pnpm. Also, considering that this happens in the patch-release of Rush I think it could be qualified as a bug.

**Comment by iclanton** [comment]
PNPM 6 renamed this file to `.pnpmfile.cjs`.

**Comment by slavafomin** [comment]
Oh, that's why. Thanks )

I would suggest to create a console notification for such case, this will help other users to discover this fact much more easily.

**Comment by tmeindle** [comment]
Thank you, this thread was very helpful for correctly setting up a new monorepo using pnpm 6.2.5.

**Comment by dietergeerts** [comment]
This is stated as closed, but I can still see the wrong filename being used in the official docs: https://rushjs.io/pages/configs/pnpmfile_js/, which is confusing and results to errors like this.
