### ISSUE TITLE
[rush] rush install always complain shrinkwrap is not up to date

### ISSUE THREAD

**Issue by chengcyber** [microsoft/rushstack#2656]
## Summary

rush install always complain `The shrinkwrap file is out of date. You need to run "rush update".` even after rush update

## Repro steps

1. add a `.pnpmfile.cjs` (pnpm v6, i think pnpm v5 should be same)
2. rush update, pnpm-lock.yaml is updated
3. rush install, failed with error

## Details

in `.pnpmfile.cjs`, some dependencies' version are settled down to specified version.

such as `typescript` stick into `4.2.3` version

After a little dig in codebase, I see this commit https://github.com/microsoft/rushstack/commit/18d9a27a3abfe8f96ed9fbac1fa29088e270bb82 change the validation logic.

Currently, `!foundDependency || foundDependency.version !== importerVersionSpecifier` will always be false if a version changed via `pnpmfile`.

e.g.

a package declare in package.json

```
"dependencies": {
  "typescript": "~4.2.3"
}
```

then `foundDependency.version` should be equal to `~4.2.3`, it comes from rushProject.packageJsonEditor, which comes from `package.json`

while, `importerVersionSpecifier` should be equal to `4.2.3`, it comes from pnpm, and pnpmfile set the typescript version to `4.2.3`

So, this kind of situation leads to `~4.2.3` will never equals to `4.2.3`

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.45.5 |
| `rushVersion` from rush.json? | 5.45.5  |
| `useWorkspaces` from rush.json? |  true  |
| Operating system? | Mac   |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? | 14.15.4 |

**Comment by octogonz** [comment]
Here is a PR: https://github.com/microsoft/rushstack/pull/2659

**Comment by chengcyber** [comment]
> Ack. This is an issue with the new validation logic. Generally I would say you should avoid using pnpmfile to rewrite local packages... however there's no mechanism to determine if a package is local or not in pnpmfile. I'll get a fix out soon that will run pnpmfile against the local package.json and use the result to validate.

actually, I found https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/src/logic/deploy/PnpmfileConfiguration.ts when reporting another issue https://github.com/microsoft/rushstack/issues/2657. Maybe this `PnpmfileConfiguration` 's `transform` method can handle this situtaion?

**Comment by LPegasus** [comment]
When using `pnpm workspace`, if `rush install` skip to check the `shrinkwrap` by itself, instead, use `pnpm install --frozen-lockfile` to ensure lockfile is up to date, is that more reasonable？For installation is only depends on `pnpm`.

**Comment by D4N14L** [comment]
@LPegasus I had this thought as well. However, removing the validation would mean that we could no longer skip installs/skip calling the package manager if the install state is already up-to-date. PNPM itself will still spend time performing it's own, more lengthy validation when `install` is run, so we provide this feature to avoid spending unnecessary time performing installs that are not required.

**Comment by chengcyber** [comment]
> @LPegasus I had this thought as well. However, removing the validation would mean that we could no longer skip installs/skip calling the package manager if the install state is already up-to-date. PNPM itself will still spend time performing it's own, more lengthy validation when `install` is run, so we provide this feature to avoid spending unnecessary time performing installs that are not required.

Does it a better idea that this skip install feature should be supported by pnpm natively? such as improving resolution speed. It seems to me there is no way to cache resolution step. while resolution takes a lot of time in rush + pnpm situation.

**Comment by D4N14L** [comment]
PNPM performs a full lockfile validation where Rush only performs a project-level lockfile validation. In this sense, Rush is using a shortcut to speed up the 'time-to-skip', not worsen it, so I do still see value in this feature. Additionally, removing it would likely mean removing it for other package managers since we would want a common code path for all package managers.

Either way, I will have a fix for this today that I would appreciate you testing once it is linked here :)
