### ISSUE TITLE
[api-extractor] errors when used with a tsconfig which includes `noPropertyAccessFromIndexSignature`

### ISSUE THREAD

**Issue by chriskrycho** [microsoft/rushstack#2658]
## Summary

I'm trying to get API Extractor working on a new library, and am using [`noPropertyAccessFromIndexSignature`](https://www.typescriptlang.org/tsconfig/#noPropertyAccessFromIndexSignature) from TS 4.2. API Extractor errors, treating it as an unknown compiler option:

## Repro steps

1. Run `tsc --init` in a project
2. Set `"noPropertyAccessFromIndexSignature": true` in `tsconfig.json`
3. Invoke `api-extractor run --local --verbose` 

  **Expected result:** It should run!

  **Actual result:** It doesn't!

  ```sh
  $ api-extractor run --local --verbose

  api-extractor 7.14.0  - https://api-extractor.com/

  Using configuration from ./config/api-extractor.json

  ERROR: Error parsing tsconfig.json content: Unknown compiler option 'noPropertyAccessFromIndexSignature'.
  ```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? | 7.14.0 |
| Operating system? | Mac |
| API Extractor scenario? | any! |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | 4.2.4 |
| Node.js version (`node -v`)? | 14.16.1 |

**Comment by octogonz** [comment]
Looks like we just need to upgrade the compiler engine for API Extractor.

**Comment by octogonz** [comment]
Here is a PR: https://github.com/microsoft/rushstack/issues/2658

**Comment by octogonz** [comment]
@chriskrycho Please try API Extractor 7.15.0

**Comment by chriskrycho** [comment]
Awesome, thank you! I figured that’s all it was, and am looking at the PR so if I hit this sort of thing in the future I’ll just be able to open an issue. I’ll give this a whirl tomorrow and make sure it’s fixed.
