### ISSUE TITLE
[rush] rush build fails under bash

### ISSUE THREAD

**Issue by benkaiser** [microsoft/rushstack#2679]
## Summary

When running `rush build`, the build fails indeterministicly (at different projects) with the same error:

```
C:\Users\username\.rush\node-v12.22.1\rush-5.45.5\node_modules\@rushstack\node-core-library\lib\FileWriter.js:43
            throw new Error(`Cannot write to file, file descriptor has already been released.`);
            ^

Error: Cannot write to file, file descriptor has already been released.
    at FileWriter.write (C:\Users\username\.rush\node-v12.22.1\rush-5.45.5\node_modules\@rushstack\node-core-library\lib\FileWriter.js:43:19)
    at Socket.<anonymous> (C:\Users\username\.rush\node-v12.22.1\rush-5.45.5\node_modules\@microsoft\rush-lib\lib\utilities\TarExecutable.js:99:62)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

After initial evaluation, this seems to only reproduce when running inside git bash on Windows. Running inside CMD/Powershell does not produce this error.
It is a recent regression, git bash has been working up until maybe 2 weeks ago.

## Repro steps

For Microsoft employees, clone odsp-web, run a `rush install && rush build` inside git bash on Windows.

  **Expected result:** 

Expected a clean build.

  **Actual result:** 

Build fails with the above mentioned filewriter error.

## Details

Seems to be specific to running under git bash, not sure about what other specifics may trigger the issue.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.46.1 |
| `rushVersion` from rush.json? | 5.45.5 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Windows |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 12.22.1 |

**Comment by BPapp-MS** [comment]
I reproduced locally and pulled the build-cache-tar.log file from the .rush/temp/ directory inside of one of the failing packages and this is what it said:

Start time: Thu May 06 2021 13:01:47 GMT-0700 (Pacific Daylight Time)
Invoking "C:\Program Files\Git\usr\bin\tar.exe -x -f D:\2nd-o-w\common\temp\build-cache\@rushstack+hashed-folder-copy-plugin_fb3b2c9c8b5aac9b8624c14746eb41715b4cf583"

======= BEGIN PROCESS OUTPUT =======
[stderr] /usr/bin/tar: Cannot connect to rushstack+hashed-folder-copy-plugin_fb3b2c9c8b5aac9b8624c14746eb41715b4cf583: resolve failed
======== END PROCESS OUTPUT ========

Exited with code "128"

**Comment by benkaiser** [comment]
So it turns out Windows ships with a version of `bsdtar`, but git bash has it's own set of utilities that take precedence, and one of them is `gnutar`. Both of these have the exact same name (`tar.exe`), so a simple solution for me was to rename the git one to `gnutar`:
`C:\Program Files\Git\usr\bin\tar` -> `C:\Program Files\Git\usr\bin\gnutar`

Then rush builds worked fine when processing tar files for me.
