### ISSUE TITLE
[rush] useWorkspaces: true does not generate pnpm-workspace.yaml

### ISSUE THREAD

**Issue by NicolasDuran** [microsoft/rushstack#2688]
## Summary

In the rush.json we can find the following entry:

```
/**
     * If true, then `rush install` will use the PNPM workspaces feature to perform the
     * install.
     *
     * This feature uses PNPM to perform the entire monorepo install. When using workspaces, Rush will
     * generate a "pnpm-workspace.yaml" file referencing all local projects to install. Rush will
     * also generate a "pnpmfile.js" which is used to provide preferred versions support. When install
     * is run, this pnpmfile will be used to replace dependency version ranges with a smaller subset
     * of the original range. If the preferred version is not fully a subset of the original version
     * range, it will be left as-is. After this, the pnpmfile.js provided in the repository (if one
     * exists) will be called to further modify package dependencies.
     *
     * This option is experimental. The default value is false.
     */
    "useWorkspaces": true **// I uncommented this line**
```
The text says: "_Rush will generate a "pnpm-workspace.yaml" file referencing all local projects to install_"
but running `rush install`, `rush install -p`, `rush update` or `rush update -p` doesnt generate the "pnpm-workspace.yaml" file.

## Repro steps

I created this repository https://github.com/NicolasDuran/rush-debug so you can easily validate what I explained the the Summary section

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.46.1 |
| `rushVersion` from rush.json? | "5.46.1 |
| `useWorkspaces` from rush.json? | true |
| Operating system? |  Linux  |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v15.14.0 |

**Comment by iclanton** [comment]
Yeah it gets generated under `common/temp`, which is the folder in which the actual installation happens.
