### ISSUE TITLE
[rush] Improve heft-config-file to cache promises instead of return values

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/rushstack#2691]
## Summary

I notice that the `ConfigurationFile` loader in `heft-config-file` is designed to have various cache layers, but they all cache _finished outputs_.  That means in a context like rush, where you may have 5-8 parallel in-process invocations of the `ConfigurationFile`, that the full stack actually executes several times before you finally put something in the cache.

(By full stack, I mean "check if FILE exists", "check if RIG FILE exists", "read FILE or RIG FILE", etc. -- you might have all 3 file system operations execute for 5 parallel executions, resulting in 15 file operations.)

If these cache layers cached _promises_ for objects (and set them earlier), instead of the 5 initial parallel executions all reading the same file from the file system, only 1 would read the file system and the other 4 would wait for the same promise.  (You might end up moving the cache 1 layer higher in the methods within the class as well, depending on behavior.)

## Repro steps

Not particularly visible until PR https://github.com/microsoft/rushstack/pull/2643 merges.  You can check out this branch and build with `rush build -v` to see that the first N projects all do the full "check, check rig, read file" logic for all the project configuration files they are loading.  Once the first N projects finish and the next parallel ones load up, you start hitting the cache entries and the rest of the projects are "silent" (no more verbose logging because config file loads immediately hit cache entries).

## Details

Dropping this into an issue before a PR because ConfigurationFile is a little complicated, it has multiple entry points, and I'd want to make sure I don't break any uses of it with this change.  Open to any input from people familiar with `ConfigurationFile`.

**Comment by iclanton** [comment]
This would be a great improvement. Would you be interested in raising a PR?

Yeah `ConfigurationFile` is a little complicated, but I don't think the change to preemptively cache the promise before execution would be too difficult. I wrote that package initially, so I'm happy to review.

**Comment by dmichon-msft** [comment]
I was looking at performance in this area earlier today, and didn't get to this precise side of the problem, but did notice that it'd be useful to be able to override or prepopulate the file existence checks. When we're loading the rush-project.json files from PackageChangeAnalyzer, for example, we already have, in a Map, a full enumeration of every checked-in file in the repository, which is *much* faster to check against than file system operations.

**Comment by elliot-nelson** [comment]
Merged!
