### ISSUE TITLE
[rush] Support PNPM "overrides" field in package.json

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#2698]
## Summary

PR https://github.com/microsoft/rushstack/pull/1360 enabled support for Yarn `resolutions`.

Turns out that PNPM has this same feature, but called [overrides](https://pnpm.io/package_json#pnpmoverrides).

We should:
1. Confirm whether it works properly with Rush; if not, get it working
2. Recommend to use it instead of **pnpmfile.js** (because config data is preferable to executable code).  The **pnpmfile.js**  feature would still be supported for advanced problems.

**Comment by iclanton** [comment]
Sounds like a good idea. Let's do it!

**Comment by iclanton** [comment]
@D4N14L says it should just work in Workspaces.

**Comment by dev-end** [comment]
Hello @iclanton  and @D4N14L  can you point to a link or an example where this could be supported by Workspaces?

**Comment by D4N14L** [comment]
Have you tried using it and it just doesn't work? If so, it's possible that it's not working because the overrides need to be specified in the root project, which in the case of Rush is generated in `common/temp`. This is what happened in a separate issue (#3293). Support would likely need to be added to Rush in some way, though I don't personally have the bandwidth to implement this.

**Comment by and0p** [comment]
Worth noting that it's not just overrides, but the rest of the pnpm root-level configs on that page (the linked issue is for `peerDependencyRules`).

Also, `common/temp/package.json` is wiped and reset with most relevant `rush` commands, so it can't be kept there. Not to mention the generated `.gitignore` excludes that from version control.

Would throwing something into `rush.json` work? Or would this be too bloated?

```
"pnpmOptions": {
    // ...
    "overrides": {
      "foo": "^1.0.0",
      "quux": "npm:@myorg/quux@^1.0.0",
      "bar@^2.1.0": "3.0.0",
      "qar@1>zoo": "2"
    },
    "peerDependencyRules": {
      "ignoreMissing": ["react"]
    }
}
```

You'd probably want to disallow `engines` since we already have `pnpmVersion` in `rush.json`.

**Comment by NickSeagull** [comment]
Any update on this?

**Comment by gabrielpioto** [comment]
I think this is already covered by [this line](https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/src/logic/installManager/InstallHelpers.ts#L44) of code and it was released in [version 5.79](https://github.com/microsoft/rushstack/releases/tag/%40rushstack%2Frush-sdk_v5.79.0)

**Comment by antoine-coulon** [comment]
I tested with `5.79.0` and it seems like it still does not take into account the `pnpm.overrides` section. Am I missing something? Would be happy to send a PR if there is a fix to do

**Comment by antoine-coulon** [comment]
I think it's an important feature to implement because having to override some transitive dependencies for security or feature things is quite common (unfortunately). @iclanton @octogonz let me know if you guys have no bandwidth

**Comment by octogonz** [comment]
> I think this is already covered by [this line](https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/src/logic/installManager/InstallHelpers.ts#L44) of code using `globalOverrides` and it was released in [version 5.79](https://github.com/microsoft/rushstack/releases/tag/%40rushstack%2Frush-sdk_v5.79.0)

Yes, we already fixed this.  The full docs are in [common/config/rush/pnpm-config.json](https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/assets/rush-init/common/config/rush/pnpm-config.json).

@antoine-coulon Can you provide a more detailed repro?  Otherwise I think we should close #2698 as already "fixed".

**Comment by antoine-coulon** [comment]
> > I think this is already covered by [this line](https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/src/logic/installManager/InstallHelpers.ts#L44) of code using `globalOverrides` and it was released in [version 5.79](https://github.com/microsoft/rushstack/releases/tag/%40rushstack%2Frush-sdk_v5.79.0)
> 
> Yes, we already fixed this. The full docs are in [common/config/rush/pnpm-config.json](https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/assets/rush-init/common/config/rush/pnpm-config.json).
> 
> @antoine-coulon Can you provide a more detailed repro? Otherwise I think we should close #2698 as already "fixed".

Thanks @octogonz for sharing the newly introduced `pnpm-config.json` I wasn't aware of. Is it planned to add this file in the [config file reference](https://rushjs.io/pages/advanced/config_files/)?

Consequently I just added the `pnpm-config.json` with the following config:

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/pnpm-config.schema.json",
  "useWorkspaces": true,
  "strictPeerDependencies": true,
  "pnpmStore": "local",
  "preventManualShrinkwrapChanges": true,
  "globalOverrides": {
    "moment": "2.29.4"
  }
}
```

When doing a `rush update`, it effectively adds the `pnpm.overrides` property in the `common/temp/package.json` as [stated by this change mentioned here](https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/src/logic/installManager/InstallHelpers.ts#L44):

```json
"pnpm": {
    "overrides": {
      "moment": "2.29.4"
    }
  }
```

However it seems that there is no impact on the pnpm lockfile _itself_ (`common/config/rush/pnpm-lock.yaml`), it seems like nothing is updated afterwards. Moreover I noticed that when I manually delete the lockfile and then I run `rush update` once again it seems to work, the newly created lockfile effectively includes the `overrides` property resulting in a dependency tree update in the lockfile:

```yaml
overrides:
  moment: 2.29.4

/somewhere-in-the-tree:
      moment: 2.29.4
```

Am I missing something in order for the pnpm `overrides` prop to be reflected in the dependency tree?

**Comment by octogonz** [comment]
@chengcyber Is this the expected behavior?

**Comment by chengcyber** [comment]
> @chengcyber Is this the expected behavior?

One guess is running "rush update --full" or "rush update --recheck" is needed after any modification of "pnpm-config.json". Kind of similar as running "rush update --full" is needed after changing pnpmfile.
___

Hi @antoine-coulon , you can try to run "rush update --recheck" or "rush update --full" after changing pnpm-config.json. If the issue still happens, could you kindly give me a minimal reproduce repo? This will be a great help to check this issue for you.

**Comment by octogonz** [comment]
Closing this issue since the problem seems to be solved now.
