### ISSUE TITLE
[heft] heft build --watch does not emit additionalModuleKindsToEmit from typescript.json

### ISSUE THREAD

**Issue by ksjogo** [microsoft/rushstack#2704]
## Summary

heft build does honor the additionalModuleKindsToEmit within the config/typescript.json.
heft build --watch doesn't emit the second (or further) target.
Issue #2141 exhibited the same behaviour but seemed to have been resolved, so this might be a regression.

## Repro steps

Add a typescript.json with additionalModuleKindsToEmit set.

  **Expected result:** 

heft build --watch does emit all configured moduleKinds.

  **Actual result:** 

heft build --watch only emits the default module kind from the tsconfig.json.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.30.5 |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v14.17.0 |

**Comment by iclanton** [comment]
Can you provide a repro? It's working when I try `heft build --watch` in [`heft-webpack4-everything-test`](https://github.com/microsoft/rushstack/tree/master/build-tests/heft-webpack4-everything-test).



https://user-images.githubusercontent.com/5010588/119057871-21ddc080-b982-11eb-9ee0-252eb4e818a5.mp4

**Comment by ksjogo** [comment]
I had a further look, the problem seems to be that I had:
```
	"additionalModuleKindsToEmit": [
		{
			/**
			 * (Required) Must be one of "commonjs", "amd", "umd", "system", "es2015", "esnext"
			 */
			"moduleKind": "commonjs",
			/**
			 * (Required) The name of the folder where the output will be written.
			 */
			"outFolderName": "lib/cjs"
		}
	],
```
With `lib` being the default emit folder, so cjs being a subfolder of it.
In that case updates aren't reflected.
Changing that to `lib-commonjs` i.e. making it a sibling instead of a child folder fixes the issues.
I didn't look further why the folder location is an issue though.

**Comment by iclanton** [comment]
I'm not particularly surprised putting one output folder inside another doesn't work. We should probably check for that and emit an error.
