### ISSUE TITLE
[api-extractor] Support TypeScript 4.3 `noImplicitOverride`

### ISSUE THREAD

**Issue by Shinigami92** [microsoft/rushstack#2715]
## Summary

Use new compile flag `noImplicitOverride`

## Repro steps

  **Expected result:** 

https://github.com/vitejs/vite/pull/3557 should be green/pass 🟢

  **Actual result:** 

It fails with `ERROR: Error parsing tsconfig.json content: Unknown compiler option 'noImplicitOverride'.` 🔴  
https://github.com/vitejs/vite/runs/2679263210#step:8:41

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? | 7.15.2 |
| Operating system? | Windows / Mac / Linux |
| API Extractor scenario? |  ? |
| Would you consider contributing a PR? | No |
| TypeScript compiler version? | 4.3.2 |
| Node.js version (`node -v`)? | v15.6.0 |

**Comment by apepper** [comment]
`api-extractor` currently does not support TypeScript 4.3, but only 4.2:

https://github.com/microsoft/rushstack/blob/1dffadf18b4ed9c12899360689a735f42d31361b/apps/api-extractor/package.json#L48

It would be great if all of TypeScript 4.3 would be supported.

**Comment by apepper** [comment]
`api-extractor` version `7.16.0` or newer support `typescript` `4.3` (see https://github.com/microsoft/rushstack/commit/c35c186e37b03097091984462304a9a89a726898).

This issue can be closed.
