### ISSUE TITLE
[rush] Give ability to set StdioSummarizer options for displaying omitted lines

### ISSUE THREAD

**Issue by ziofat** [microsoft/rushstack#2716]
## Summary

If output lines are more than 20 lines, only first 10 lines and last 10 lines will be displayed.
This is OK on local machine since we can directly access to package.build.log. But it is not convenient if runs on CI. 

## Repro steps

A typical situation is lint. We have a `rush lint` command to execute eslint on each package and allowing warning for success build. However if there is an error, the error message may be skipped and it is hard on CI to know where is the actual error.

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.42.4 |
| `rushVersion` from rush.json? | 5.42.4 |
| `useWorkspaces` from rush.json? | false |
| Operating system? | Linux for CI |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 12.19.0 |

**Comment by octogonz** [comment]
@ziofat  We recommend to use `rush build --verbose` (or `rush lint --verbose`) in a CI job.  This will display the complete log output.  It also shows a nice 20-line summary at the end, but then you can scroll upwards in the log to see the details.

Here is a real world example: https://dev.azure.com/RushStack/GitHubProjects/_build/results?buildId=6534&view=logs&j=1e6c3048-b351-5ff2-32a8-22f53db46e9d&t=30e6b2b3-1237-577b-c598-4e1350274b57

Does that solve your problem?

**Comment by ziofat** [comment]
Yes, `--verbose` do solve my problem. How can I forget that.

**Comment by ziofat** [comment]
I am going to leave this issue open because it is still nice to have ability to customize leading and trailing lines. Feel free to close this if you have other ideas.

**Comment by iclanton** [comment]
I think the best option is to always use `--verbose` on CI. IMO this would be something that's maybe a little too esoteric to be able to configure.

Maybe it could go in the `~/.rush-user/settings.json` file? @octogonz, thoughts on that?

**Comment by octogonz** [comment]
> | Question | Answer |
> | -------- | -------- |
> | Would you consider contributing a PR? | No |

I'm open-minded about it if somebody volunteered to make a PR.

Otherwise I feel like we should close this issue, because there are too many other work items with arguably higher priority.
