### ISSUE TITLE
[rush] How not to publish a package but still want to lock its version?

### ISSUE THREAD

**Issue by ziofat** [microsoft/rushstack#2735]
## Summary

As the [document](https://rushjs.io/pages/commands/rush_publish/) states, `--include-all` will publish all packages with `shouldPublish`=true **OR** with a specified version policy.

However in fact, to have a version policy may not mean to make it public. I have an app monorepo for document site and I want it to have same version with my lib. The version in `package.json` is also used in generating the document site.

## Repro steps

When I want to publish some packages, I ran the following commands:

```sh
rush version --bump
rush publish --include-all --publish --tag next --version-policy [myLockStepVersionPolicyName] --target-branch develop
```

  **Expected result:** 
Publish normally.

  **Actual result:** 
It give me an error of trying to publish my document site.
```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@***%2f*** - Not found
npm ERR! 404 
npm ERR! 404  '@***/***@1.0.0-alpha.9' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.42.4 |
| `rushVersion` from rush.json? | 5.42.4 |
| `useWorkspaces` from rush.json? | false |
| Operating system? | Mac |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 12.19.0 |

**Comment by ziofat** [comment]
OK, I will make a mini repo for this.

It is not related to ownership in npm. I just don't want to publish this package because it is an app not a lib. But I still want it to have same version with my published app.

**Comment by dsanders1234** [comment]
We have the same issue.  We have a "storybook package" under packages that we would like to have the same version as the rest of the packages, but there is no need to publish the storybook package.  The package.json for storybook has private: true set, and setting the version policy and allowPublish to false does not work (as per the documentation).

**Comment by ziofat** [comment]
I don't think it is necessary to provide a repo. The behavior is by design and located at here:

https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/src/api/RushConfigurationProject.ts#L331

For me, I just have a package is private and I want it to have same version with other packages. It is a document site and it do need to use the `version` in package.json for demonstration purpose.

There is no reason to publish this website as a npm package, but `--include-all` will try to publish it even its `shouldPublish` is false.
