### ISSUE TITLE
[heft] In a project without tests, but with a Jest config, heft test prints a confusing error message.

### ISSUE THREAD

**Issue by iclanton** [microsoft/rushstack#2758]
## Summary

If you run `heft test` with a project that has a Jest config, but doesn't have tests, Heft prints an error that looks like:

```
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In E:\code\odsp-web4\sp-client\tools\run-after-build-plugin
  2 files checked.
  testMatch: E:/code/something/src/**/*.test.{ts,tsx} - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 2 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
```

However, the correct parameter in Heft is `--pass-with-no-tests`. Heft should intercept this error and print a more correct error message.

## Repro steps

Delete the tests in a Heft project in this repo and run `heft test`.

  **Expected result:**

A Heft error message that mentions the right parameter.

  **Actual result:** 

A Jest error message saying:

```
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In E:\code\odsp-web4\sp-client\tools\run-after-build-plugin
  2 files checked.
  testMatch: E:/code/something/src/**/*.test.{ts,tsx} - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 2 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.33.0 |
| Operating system? | Any |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | Any |

**Comment by iclanton** [comment]
@D4N14L, would you take a look at this?

**Comment by octogonz** [comment]
This is the same issue as https://github.com/microsoft/rushstack/issues/2759.

Closing this one, since the other one has more investigation details.
