### ISSUE TITLE
[rush] add rush why command 

### ISSUE THREAD

**Issue by m1heng** [microsoft/rushstack#2766]
## Summary

`why` command is provided both by yarn and pnpm, but in a rush project, extra arguments are needed when using them. 
Like `pnpm why xxx -r  -C common/temp`.
Maybe Rush itself can provide a `rush why` command for better efficiency. 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? | YES after discussion |
| Node.js version (`node -v`)? |  |

**Comment by ycaptain** [comment]
+1

**Comment by leeight** [comment]
+10086

**Comment by iclanton** [comment]
As @octogonz mentioned, we have a work item tracking this (https://github.com/microsoft/rushstack/issues/2347), but we haven't had time to schedule that work yet. We'd of course welcome the help if someone else wants to take a crack at adding that functionality.

**Comment by octogonz** [comment]
🚀The new `rush-pnpm` command is released with  `@microsoft/rush` 5.74.0.  

To use it:  Besides upgrading `rushVersion` in your **rush.json**, you need to add the `rush-pnpm` shell command by doing `npm install --global @microsoft/rush`.

**Comment by olivierlacan** [comment]
@octogonz While `rush-pnpm` is available it still fails silently when `rush-pnpm why <package>` is used. 

Is `why` still just a stub? https://github.com/microsoft/rushstack/blob/d39f3fd5e6f2d5130072eb770c626dca23dda42f/libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts#L329-L331
