### ISSUE TITLE
[api-extractor] Trimmed member from exported namespace still exported by namespace in rollup

### ISSUE THREAD

**Issue by SchoofsKelvin** [microsoft/rushstack#2791]
## Summary
A namespace can export a member that gets trimmed away. If that namespace then gets exported, it still tries to export the trimmed member when generating the rollup.

## Repro steps

Demo code:
```ts
// index.ts
import * as ns from './ns';
export { ns };

// ns.ts
/** @public */
export const PUBLIC = 'PUBLIC';

/** @internal */
export const INTERNAL = 'INTERNAL';
```

**Expected result:**
```ts
/** @public */
declare const PUBLIC = "PUBLIC";

declare namespace ns {
  export {
    PUBLIC
  }
}
export { ns }
```

**Actual result:**
```ts
/** @public */
declare const PUBLIC = "PUBLIC";

declare namespace ns {
  export {
    PUBLIC,
    INTERNAL
  }
}
export { ns }
```

As can be seen, while the declaration of `INTERNAL` is stripped, the namespace still tries to export it.

## Details

Probably related to the recent `import * as __ from __` feature (#1029/#1796) and maybe #1664?.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? | 1.17.1 |
| Operating system? | Windows |
| API Extractor scenario? | rollups (.d.ts) |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | 4.3.5 |
| Node.js version (`node -v`)? | 14.16.0 |

**Comment by j-ulrich** [comment]
I am experiencing the same issue with version 7.19.4.

> @microsoft/api-extractor version? | 1.17.1

I guess there is something wrong because this version does not exist. :D
