### ISSUE TITLE
[api-extractor] Internal Error: indentDocComment cannot be nested

### ISSUE THREAD

**Issue by alan-agius4** [microsoft/rushstack#2797]
## Summary
 7.18.0 caused a regressions, where when using DTS rollup and a declaration has nested comments it errors out with an `internal Error: indentDocComment cannot be nested` error.

## Repro steps
Example of input that caused the above mentioned exception. 
```ts
/**
 * Foo Desc
 */
 export const foo = (o: {
  /**
   * Bar desc
   */
  bar: any;
 }) => { };
```

  **Expected result:** No exception

  **Actual result:** 
```
Error: Internal Error: indentDocComment cannot be nested
You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? |  7.18.0 |
| Operating system? | Mac | 
| API Extractor scenario? | rollups |
| Would you consider contributing a PR? |  Yes|
| TypeScript compiler version? | 4.3.2  | 
| Node.js version (`node -v`)? | 14.17.1 |

**Comment by MSNev** [comment]
Also hitting this with 7.18.0 😢 currently rolling back to 7.17.1 to unblock our release

**Comment by octogonz** [comment]
I bet it is a regression from PR https://github.com/microsoft/rushstack/pull/2796

Lemme investigate.

**Comment by octogonz** [comment]
PR: https://github.com/microsoft/rushstack/pull/2801

**Comment by octogonz** [comment]
@alan-agius4 @MSNev please try API Extractor 7.18.1 and confirm that it's fixed.

**Comment by MSNev** [comment]
Yes the builds are no longer failing.

**Comment by alan-agius4** [comment]
@octogonz, thanks for the quick turn around. Confirmed that the issue is now solved.
