### ISSUE TITLE
[rush] build-cache ignores allowWarningsInSuccessfulBuild

### ISSUE THREAD

**Issue by relm923** [microsoft/rushstack#2803]
## Summary

The new [build-cache](https://rushjs.io/pages/maintainer/build_cache/) system does not write to the cache when the command writes to STDERR even when `allowWarningsInSuccessfulBuild: true` is used in the command config.

This is easiest to see when running `rush test` and using `jest` since Jest regularly writes to STDERR (https://github.com/facebook/jest/issues/5064). But will occur with any command that writes to STDERR

I would expect the build-cache logic to respect the `allowWarningsInSuccessfulBuild` so we can still take advantage of caching even when third parties use STDERR incorrectly.

## Repro steps

Add global command that triggers something to write to STDERR
```json

// command-line.json
{
  "name": "test",
  "commandKind": "bulk",
  "summary": "This command invokes Jest to test apps.",
  "safeForSimultaneousRushProcesses": true,
  "allowWarningsInSuccessfulBuild": true,
  "incremental": true,
  "enableParallelism": true
},

// package.json
"scripts": {
  "test": "jest"
},
```

  **Expected result:** 
1. Run command `rush test`. No cache hits - all tests run (printing warnings) and cache is updated
2. Run command `rush test` again. All cache hits  - no tests run

  **Actual result:** 
1. Run command `rush test`. No cache hits - all tests run (printing warnings) and cache is **NOT** updated
2. Run command `rush test` again. No cache hits - all tests run (printing warnings) and cache is **NOT** updated

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.47.0 |
| `rushVersion` from rush.json? | 5.47.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v16.3.0 |

**Comment by relm923** [comment]
I'm not very familiar with this logic but it seems like https://github.com/microsoft/rushstack/blob/78aa5aded8051d9f38e8cf0d1513f20707edc54a/apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts#L315 needs to updated to respect `allowWarningsInSuccessfulBuild`

**Comment by octogonz** [comment]
> I would expect the build-cache logic to respect the `allowWarningsInSuccessfulBuild` so we can still take advantage of caching even when third parties use STDERR incorrectly.

Agreed, this seems like a bug.

@iclanton

**Comment by Measy** [comment]
It seems related https://github.com/microsoft/rushstack/issues/1402

**Comment by relm923** [comment]
@octogonz @iclanton any update on this?

I'm happy to help contribute a fix but will likely need some guidance getting started

**Comment by F3n67u** [comment]
You can try this `if` also pass when `allowWarningsInSuccessfulBuild & status === TaskStatus.SuccessWithWarning` is `true`.

https://github.com/microsoft/rushstack/blob/78aa5aded8051d9f38e8cf0d1513f20707edc54a/apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts#L327

**Comment by F3n67u** [comment]
I have encountered the same issue.

**Comment by octogonz** [comment]
> I'm happy to help contribute a fix but will likely need some guidance getting started

That would be great!  If you have questions about the approach, [#contributor-helpline](https://rushstack.zulipchat.com/#narrow/stream/279883-contributor-helpline) is the quickest way to get unblocked.

**Comment by relm923** [comment]
@octogonz took a stab at a PR (#2835) let me know what you think
