### ISSUE TITLE
[heft] Migrate heft-webpack5-plugin to use webpack-dev-server@4.0.x

### ISSUE THREAD

**Issue by bartvandenende-wm** [microsoft/rushstack#2818]
## Summary

`heft-webpack5-plugin` binds to `webpack-dev-server` [3.11.x](https://github.com/microsoft/rushstack/blob/master/heft-plugins/heft-webpack5-plugin/package.json#L23webpack-dev-server). It looks like 3.11.x currently only provides basic compatibility with webpack 5.0, as open issues are only being addressed in version 4.x.x. 

This ticket is a request to consider to update the dependency of `webpack-dev-server` in `heft-webpack5-plugin` from `@3.11.x` to `@4.0.x` which provides official webpack 5 compatibility. 

As 4.x.x. includes [breaking changes](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md) and just hit the RC.0 status an alternative could be to 'loosen' the semver binding of webpack-dev-server to allow major version overrides on a project/rig basis.

## Repro steps

An example of a failure case of `webpack-dev-server` [3.11.x] is to handle es5 targets properly with HMR:
1. use a web-application sample project
2. in the webpack config set `target: ['web', 'es5']`
3. notice that HMR is not working

Reference:
https://github.com/webpack/webpack-dev-server/issues/2961

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | ^0.34.7 |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v12.17.0 |

**Comment by bartvandenende-wm** [comment]
it looks like `@types/webpack-dev-server` are not yet available for 4.x so this likely would be blocking the transition, there is some push for back-porting the fixes to 3.x but no clarity on that either per https://github.com/webpack/webpack-dev-server/pull/3271

**Comment by iclanton** [comment]
The missing typings might not be a huge issue, unless the API changed in nontrivial ways. Do you know if it changed? Is it enough to just bump the dependency version?

**Comment by bartvandenende-wm** [comment]
@iclanton looks like there where some breaking changes, below a migration guide:
https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.mdtThough I'm not sure if it impacts the plugin

The stable version just got release 2 days ago, but no type updates yet from DefinitelyTyped

**Comment by bartvandenende-wm** [comment]
this issue is solved
