### ISSUE TITLE
[heft] Upgrade Jest dependency

### ISSUE THREAD

**Issue by jessekrubin** [microsoft/rushstack#2825]
Would be nice if heft could see and use a locally installed version of jest on a per-package basis, or if I could set the jest version from a rig spec.

**Comment by iclanton** [comment]
Our integration with Jest is somewhat deep, but this may be possible. We'll have to do some investigation to ensure that the Jest APIs that we use are compatible.

**Comment by D4N14L** [comment]
@iclanton agreed. One example is that we monkey-patch Jest to have a greater timeout in [here](https://github.com/microsoft/rushstack/blob/master/heft-plugins/heft-jest-plugin/src/jestWorkerPatch.ts). If Jest were to change anything in the file being patched, it's possible that it would break our patch. Additionally, @octogonz and I spoke on this topic recently, and he expressed his preference to keep the plugin bound to a specific version of Jest (though, the version could use bumping to something more recent, given that we're still on 25).

Thoughts?

**Comment by jessekrubin** [comment]
@D4N14L I would love if jest got bumped. Something about jest 25 is painfully slow on my machine (which is beefy). Jest 26/27 are both much faster. Also would appreciate any thoughts/suggestions.

**Comment by octogonz** [comment]
> use a locally installed version of jest on a per-package basis

This isn't something we can support easily IMO.

>  I would love if jest got bumped. 

This is long overdue. A number of people have given good justifications for upgrading Jest.  We need to prioritize this.  (If someone from the community wants to help out, that would be awesome.)

**Comment by jessekrubin** [comment]
@octogonz i use quite a bit of heft. Lmk what is the min stuff I gotta do to push a pr through.

**Comment by jessekrubin** [comment]
@octogonz Why would using a locally installed jest be hard?

ps: When not using heft+jest I don’t use tsjest I just compile everything and run jest on my built stuff
pps: heft being tied to a particular version of jest defeats the purpose of heft plugins and the heft jest plug-in (imo - lmk if/how I am wrong)
