### ISSUE TITLE
[rush] Corrupted build cache entries produce wrong (incomplete) builds

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/rushstack#2827]
## Summary

I recently had a situation where I was building normally, with build cache enabled locally.  I started seeing several projects generate the following error:

```console
"tar" exited with code 1 while attempting to restore cache entry. Rush will attempt to extract from the cache entry with a JavaScript implementation of tar. See "[[path]]/.rush/temp/build-cache-tar.log" for logs from the tar process.
```

The log contains the following information:

```console
Start time: Mon Jul 26 2021 11:49:13 GMT-0400 (Eastern Daylight Time)
Invoking "/usr/bin/tar -x -m -f /[[path]]/common/temp/build-cache/4ab89cf5bc634f3196593aba1f209e3d32f9b072"

======= BEGIN PROCESS OUTPUT =======
[stderr] lib/styles/fonts/[[filename]].ttf: truncated gzip input
[stderr] tar: Error exit delayed from previous errors.
======== END PROCESS OUTPUT ========
```

Even though rush is building successfully with this warning, the tar file is indeed corrupted... only half of the built JavaScript files are present in the `lib/` folder.  It seems to me that the JavaScript implementation of `tar` is ignoring the fact that the archive is incomplete.

## Repro steps

Still TBD.  It's very unclear how the _original_ corrupted cache entries were created.  It might be possible to intentionally create a truncated archive file to test with.

I think the ideal situation here would be a harder error for a corrupted cache entry; or even better, automatic deletion followed by a normal build to repopulate the cache.

## Details

I have initially tried to see if rush was just incorrectly throwing away warnings, by trying the following out in a separate console:

```javascript
let tarStream = require('tar').extract({})
tarStream.on('warn', console.error);
tarStream.on('drain', console.log);
tarStream.write(require('fs').readFileSync('/[[path]]/temp/build-cache/4ab89cf5bc634f3196593aba1f209e3d32f9b072'))
```

This test was unsuccessful... it extracted all the files it could from the archive, without producing any kind of warning, just like rush does.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.48.0 |
| `rushVersion` from rush.json? | 5.48.0 |
| `useWorkspaces` from rush.json? | yes |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes, although this may not be a rush problem (it may be a `tar` module problem) |
| Node.js version (`node -v`)? | 12.17.0 |

**Comment by octogonz** [comment]
> automatic deletion followed by a normal build to repopulate the cache.

+1 for this.  A hard error would permanently break a build agent that preserves cache between runs.

**Comment by octogonz** [comment]
> Yes, although this may not be a rush problem (it may be a tar module problem)

This seems like Rush's responsibility, even if  it's not Rush's problem.

**Comment by iclanton** [comment]
Agreed with @octogonz. We may need to look into another JS implementation of TAR.

**Comment by octogonz** [comment]
> 
> Agreed with @octogonz. We may need to look into another JS implementation of TAR.

Yes, but just so everybody is clear: Issue #2827 is tracking @elliot-nelson's suggestion to delete the invalid cache entry when corruption is detected, rather than silently ignoring the problem.  This should be an easy fix, and does not require researching tar implementations.

**Comment by elliot-nelson** [comment]
> > Agreed with @octogonz. We may need to look into another JS implementation of TAR.
> 
> Yes, but just so everybody is clear: Issue #2827 is tracking @elliot-nelson's suggestion to delete the invalid cache entry when corruption is detected, rather than silently ignoring the problem. This should be an easy fix, and does not require researching tar implementations.

Today, we try to untar with `tar` and then we use the JS implementation.  _If_ `tar` exists and prints out an error message, then we could add some code to look for a specific string and delete the invalid cache entry.  But, if `tar` is not installed or can't be run for some reason, then today there doesn't seem to be any way to know that the file is corrupted (since the whole problem is that the JS tar library right now is not detecting it).
