### ISSUE TITLE
[rush] after my Node.js version changed,rush still throw a version-unmatched error.

### ISSUE THREAD

**Issue by YuFengDing** [microsoft/rushstack#2847]
## Summary

Once my Nodejs version is v15.6 and i got an nodeSupportedVersionRange error,and then i use nvm to change my Nodejs version to v14.17.4,it comes to the same

## Repro steps

use a over-ranged node version,and then run rush commands.

change node version and repeat

  **Expected result:** success

  **Actual result:** still error

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.50.0  |
| `rushVersion` from rush.json? | 5.50.0  |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Mac  |
| Would you consider contributing a PR? |  Yes  |
| Node.js version (`node -v`)? | v14.17.4 |

**Comment by iclanton** [comment]
What is the value of the `nodeSupportedVersionRange` in your repo's `rush.json`?

**Comment by YuFengDing** [comment]
> What is the value of the `nodeSupportedVersionRange` in your repo's `rush.json`?

">=12.13.0 <13.0.0 || >=14.15.0 <15.0.0"

rebooting takes effect lol...it seems hit cache somewhere...
