### ISSUE TITLE
[eslint-config] 

### ISSUE THREAD

**Issue by jqueryandphp** [microsoft/rushstack#2850]
.eslintrc的配置

{
  "extends": "next"
}
![1628649029844](https://user-images.githubusercontent.com/37691340/128960692-9bd67fe5-6075-4505-b25c-17e59c212ccd.jpg)
![1628649067625](https://user-images.githubusercontent.com/37691340/128960699-062263f8-a1d1-4ae8-b954-1240e7dab27e.jpg)

**Comment by iclanton** [comment]
I'm not sure what the issue is based on the information you've provided, but take a look at the `.eslintrc.js` files we use in this repo:


```JS
// This is a workaround for https://github.com/eslint/eslint/issues/3458
require('@rushstack/eslint-config/patch/modern-module-resolution');

module.exports = {
  extends: [
    '@rushstack/eslint-config/profile/node-trusted-tool',
    '@rushstack/eslint-config/mixins/friendly-locals'
  ],
  parserOptions: { tsconfigRootDir: __dirname }
};
```

Doing something similar may solve your problem.
