### ISSUE TITLE
[rush] heft typescript plugin fails when using typescript 4.4.2

### ISSUE THREAD

**Issue by thekorn** [microsoft/rushstack#2878]
## Summary

when I try to build any project which is using heft and typescript 4.4.2 I get:

```

==[ FAILURE: 1 project ]=======================================================

--[ FAILURE: packlets-tutorial ]-----------------------------[ 0.46 seconds ]--

Error: directoryExists is not a function


Projects failed to build.
```

## Repro steps

Reproducing it is as simple as checking out this modified version of the rushstack sample repository, which has
* all projects disabled but the packlets tutorial
* updated all dependencies in the packlets tutorial to the most recent ones, esp typescript to 4.4.2

relevant fork + branch: https://github.com/thekorn/rushstack-samples/tree/reproducer-typescript-4.4.2

## Details

as a workaround, using an older version of typescript, like 4.3.5 works just fine

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.52.0 |
| `rushVersion` from rush.json? | 5.52.0 |
| `useWorkspaces` from rush.json? |  |
| Operating system? | Linux and verfified with WSL2 on windows as well |
| Would you consider contributing a PR? | Yes, if i get some Idea how to do that :) |
| Node.js version (`node -v`)? | v14.17.4 |

**Comment by D4N14L** [comment]
Looks like a regression here: https://github.com/microsoft/rushstack/blob/c17f2138732bfa380d23fde42ad64c88e794bebb/apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts#L1049

**Comment by D4N14L** [comment]
More accurately, a regression here (thanks @dmichon-msft): https://github.com/microsoft/rushstack/blob/c17f2138732bfa380d23fde42ad64c88e794bebb/apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts#L979

**Comment by ricklove** [comment]
Verified this is also broken in native windows (non wsl2).
