### ISSUE TITLE
[api-documenter] Table structure is broken with multiple-line comments

### ISSUE THREAD

**Issue by ocavue** [microsoft/rushstack#2950]
## Summary

When I have a function with [multiple-line comment](https://github.com/issueset/api-documenter-issue/blob/b8ebddd4855c9019cdd099a5e6ae8b7524befc08/src/index.ts#L8-L18), the markdown table generated by `api-documenter` is [broken](https://github.com/issueset/api-documenter-issue/blob/master/docs/api-documenter-issue.md). 

## Repro steps

https://github.com/issueset/api-documenter-issue/ 

Run `pnpm install; pnpm build` to generate the markdown document.

  **Expected result:** The markdown content in `docs/api-documenter-issue.md` is correct.

  **Actual result:** The markdown content in `docs/api-documenter-issue.md` is broken.

## Details

I can fix this manually by adding `@remarks` in the comment. But I'm wondering if there was a way to generate a simpler document without table structure so that we won't have this kind of issues.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-documenter` version? | 7.13.60 |
| Operating system? | Mac |
| Documentation target? | Markdown |
| Would you consider contributing a PR? | Yes if someone tells me how to do it |
| TypeScript compiler version? | 4.3 |
| Node.js version (`node -v`)? | v16.9.1 |

**Comment by phryneas** [comment]
What are your thoughts on emitting tables as HTML into the Markdown output? HTML is valid in Markdown after all.
