### ISSUE TITLE
[eslint-config] documentation gives bad path for mixin

### ISSUE THREAD

**Issue by clouedoc** [microsoft/rushstack#2997]
![image](https://user-images.githubusercontent.com/13921610/139658352-646051c8-ed23-40fe-80e0-34367410cd2c.png)

```diff
- @rushstack/eslint-config/profile/mixins/friendly-locals
+ @rushstack/eslint-config/mixins/friendly-locals
```

See: https://yarnpkg.com/package/@rushstack/eslint-config

Thanks for the excellent project.

**Comment by clouedoc** [comment]
I might be wrong, let me check...

**Comment by clouedoc** [comment]
I'm right 😄

**Comment by D4N14L** [comment]
Good catch! I'll update this. Thanks @clouedoc
