### ISSUE TITLE
npm audit violation with rushstack

### ISSUE THREAD

**Issue by LiangMingChen** [microsoft/rushstack#3018]
=== npm audit security report ===
                                 Manual Review
             Some vulnerabilities require your attention to resolve
          Visit https://go.npm.me/audit-guide for additional guidance
  Moderate        Inefficient Regular Expression Complexity in validator.js
  Package         validator
  Patched in      >=13.7.0
  Dependency of   @microsoft/api-documenter [dev]
  Path            @microsoft/api-documenter > @rushstack/node-core-library >
                  z-schema > validator
  More info       https://github.com/advisories/GHSA-qgmg-gppg-76g5
  Moderate        Inefficient Regular Expression Complexity in validator.js
  Package         validator
  Patched in      >=13.7.0
  Dependency of   @microsoft/api-documenter [dev]
  Path            @microsoft/api-documenter > @microsoft/api-extractor-model >
                  @rushstack/node-core-library > z-schema > validator
  More info       https://github.com/advisories/GHSA-qgmg-gppg-76g5

Any idea on how to address this?

**Comment by kaiyoma** [comment]
I just ran into this as well. `@rushstack/node-core-library` is pulling in a pretty old version of `z-schema` (~3.18.3), which in turn is pulling in a really old version of `validator` (^8.0.0), which has an audit issue.

`z-schema` is up to 5.0.2 now, which pulls in the most recent version of `validator`.  Even in the master branch, `@rushstack/node-core-library` is still using a really old dependency:

https://github.com/microsoft/rushstack/blob/master/libraries/node-core-library/package.json#L25

**Comment by elisei-timofte** [comment]
+1

**Comment by mamaremere** [comment]
I confirm the dependency issue described here.

`apps/rush-lib` and `libraries/node-core-library` should depend on an updated `z-schema` (version 5.0.2) which would in turn depend on a safe version of validator (version 13.7.0)

**Comment by iclanton** [comment]
`z-schema` has been updated, and the updated packages have been released.
