### ISSUE TITLE
[rush]  rush add -p package2 package2 package3

### ISSUE THREAD

**Issue by jiangtao** [microsoft/rushstack#3037]
## 👉 STEP 1

Now, `rush add` command can only add one package after using it. I think it is a better way which support multiple packages like

```bash
rush add -p package2 package2 package3
rush add -p package2 package2 package3 --dev
```

## STEP2

`rush add` cannot add with args `--peer`. It is ugly to add peerDependency package.

I think it is a good way of add package args the same as  npm install  or yarn install.

**Comment by iclanton** [comment]
Try running `rush add -p package2 -p package3`

It'd be easy enough to add support for a `--peer` flag. Would you be willing to raise a PR to add support for this?

**Comment by jiangtao** [comment]
> 

Work well~ Thank you. I wll raise a pr to add support for a --peer flag

**Comment by elliot-nelson** [comment]
Closing this ticket -- support for multiple packages has already been added, and support for `--peer` is tracked by #1456.
