### ISSUE TITLE
[rush] How is the Intellisense performance on Rush compared to NX?

### ISSUE THREAD

**Issue by anthonyma94** [microsoft/rushstack#3038]
I apologize if this is the wrong place for this discussion, mods please remove this if need be.

I'm currently using a NX monorepo. It works well for the most part, but there are some things I don't like, namely how it forces you to use its build tools and only has support for a handful of frameworks. The biggest gripe with me is that its Intellisense support is subpar at best. It breaks if you're trying to autocomplete something from a different library, unless you manually type in the import statement first. I want to switch to Rush, but I'm wondering if Rush will have the same problems with Intellisense?

**Comment by dmichon-msft** [comment]
The Intellisense behavior will be entirely dependent on how your tsconfig files are defined. Rush expresses no opinion on the matter.

**Comment by iclanton** [comment]
>It breaks if you're trying to autocomplete something from a different library, unless you manually type in the import statement first.

That works fine for me in our repos using `pnpm` with workspaces. VSCode will just add the `import` statement.
