### ISSUE TITLE
[rush] ERR code ENEEDAUTH while publish public packages to NPM by using "rush publish -p"

### ISSUE THREAD

**Issue by ArthurIvanov** [microsoft/rushstack#3042]
Hey! I'm testing Rush and plan to use it for my component library.
For testing I was follow maintainer tutorial, after set all things I try to publish my packages to my NPM account.
After first try I've got this error:
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`

Steps which I did:
Make changes in library.
rush build
git add .
git commit -m "update"
rush change
rush publish -p

I've got an error.

I check if I logged in by typing "npm whoami" - I've got my login info.

After some googling I decide to try get access to NPM via token:
FIrst I place token directly in .npmrc which are in "common/config/rush"
Same error

I'm using Mac so I try to  place token in ~./.npmrc file, also I export it from my .zshrc file as well
Same error

My project .npmrc looks like this:
registry.npmjs.org/:_authToken=${NPM_TOKEN}
always-auth=false

Projects in rush.json looks like this:
{
      "packageName": "my-controls",
      "projectFolder": "libraries/my-controls",
      "reviewCategory": "production",
      shouldPublish: true
    },
    {
      "packageName": "my-toolchain",
      "projectFolder": "tools/my-toolchain",
      "reviewCategory": "tools",
      shouldPublish: true
    }

Do I miss something?
Thanks in advance

**Comment by iclanton** [comment]
Do you have a `common/config/rush/.npmrc-publish` in your project? Can you try setting your auth token in the `NPM_TOKEN` env variable?
