### ISSUE TITLE
[rush] Exception hit rule of nodeSupportedVersionRange in rush.json

### ISSUE THREAD

**Issue by FanShiDe** [microsoft/rushstack#3046]
## Summary

When i run `rush build` with `node-v16.13.0`, I got one error about `nodeSupportedVersionRange`

```shell
rush build
```

here is my `nodeSupportedVersionRange` in `rush.json`

```json
"nodeSupportedVersionRange": ">=12.13.0 <13.0.0 || >=14.15.0 <=16.3.0",
```

the error
![image](https://user-images.githubusercontent.com/21983486/144081197-2d4d9983-b530-4fba-9296-36aa3ed8a9e7.png)

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.47.0 |
| `rushVersion` from rush.json? | 5.47.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Linux |
| Node.js version (`node -v`)? | 16.3.0 |

**Comment by iclanton** [comment]
Your range specifies `<= 16.3.0`, not `<= 16.13.0`. You'll need to update your range to **1**3.
