### ISSUE TITLE
[rush] Request for bump type even if the policy is lockedVersion but no nextBump is specified

### ISSUE THREAD

**Issue by isc30** [microsoft/rushstack#3047]
# Implementation Status (done)

## for `rush change`
- [x] change version policy schemas
- [x] change version policy to not do anything if `nextBump` is undefined
- [x] update version policy tests
- [x] ensure that a change request prompts for proper options and the changefile contains the proper type

## for `rush publish -a`
- [x] iterate over the changes and detect the proper `ChangeType` for each policy
- [x] bump all the affected projects from the policies to the new version
- [x] update the `version-policies.json` file with the new version

## unit tests
- [ ] fix cyclic dependency test error
- [ ] add tests to cover new functionality

# Original Issue

Hi, I'm trying to automatically bump versions with `rush publish -a` based on the change files and its only working for `individualVersion` policies:

https://github.com/microsoft/rushstack/blob/f1be436784102d6a617f79ea5d01792be90d689c/apps/rush-lib/src/cli/actions/ChangeAction.ts#L504

## Use case:

I have a repository with the following projects:

- `@ui/core` (no dependencies, policy UI)
- `@ui/components` (depends on `@ui/core`, policy UI)
- `@data/core` (no dependencies, policy DATA)
- `@data/react` (depends on `@data/core`, policy DATA)
- `widgets` (depends on all `data` and `ui` packages, policy WIDGETS)

With the following policies:

```json
{
    "definitionName": "lockStepVersion",
    "policyName": "UI",
    "version": "0.1100.0",
    "nextBump": "prerelease"
  },
  {
    "definitionName": "lockStepVersion",
    "policyName": "DATA",
    "version": "0.1200.0",
    "nextBump": "prerelease"
  },
  {
    "definitionName": "lockStepVersion",
    "policyName": "WIDGETS",
    "version": "0.1300.0",
    "nextBump": "prerelease"
  }
```

## Proposal

My proposal is to make the `nextBump` field optional for `lockedVersion` policies and **if the policy doesn't have a locked version prompt for the bump type**.

This way we achieve being able to maintain a locked version for a package set but still get the benefits of using change files, changelogs and automatic version bumps from rush.

version-policies.json
```diff
{
    "definitionName": "lockStepVersion",
    "policyName": "UI",
    "version": "0.1100.0",
-   "nextBump": "prerelease"
  },
  {
    "definitionName": "lockStepVersion",
    "policyName": "DATA",
    "version": "0.1200.0",
-   "nextBump": "prerelease"
  },
  {
    "definitionName": "lockStepVersion",
    "policyName": "WIDGETS",
    "version": "0.1300.0",
-   "nextBump": "prerelease"
  }
```

ChangeActions.ts
```diff
if (versionPolicy) {
    if (versionPolicy.definitionName === VersionPolicyDefinitionName.lockStepVersion
+       && versionPolicy.nextBump !== undefined) {
-       // No need to ask for bump types if project is lockstep versioned.
+       // No need to ask for bump types if project is lockstep versioned with a fixed nextBump.
        bumpOptions = {};
    } else if (versionPolicy.definitionName === VersionPolicyDefinitionName.individualVersion) {
        const individualPolicy: IndividualVersionPolicy = versionPolicy as IndividualVersionPolicy;
        if (individualPolicy.lockedMajor !== undefined) {
        delete bumpOptions[ChangeType[ChangeType.major]];
        }
    }
}
```

I would be happy to open a PR to get this ready as its blocking our release process, please point me in the right direction.
Thanks

**Comment by iclanton** [comment]
I think this is a reasonable design, although I don't know if there will be any gotchyas. If you're interested in raising a PR, I'd say go for it and we can play with the behavior and make sure it doesn't break any other scenarios.

**Comment by isc30** [comment]
After the change it seems like when running `rush publish -a` it only bumps the version in the changed project instead of the version in the policy. I'm guessing we need to also extend the `LockStepVersionPolicy` class to handle this scenario

**Comment by isc30** [comment]
Hey, I did the change and I'm going down a rabbithole while trying to make it works properly with `rush publish -a`.
My branch is here: https://github.com/isc30/rushstack/pull/1/files

I did the change to the schemas and `rush change` tooling and all of that is working fine. Now, I need to change the logic for `rush publish -a` so it detects that a project (or multiple) have a change and have a lockStepVersion policy without a `nextBump` so it tries to calculate the biggest ChangeType for each policy (done) and then apply it to every other affected project.

inside `PublishUtilities.ts` there is a `findChangeRequests` function but it doesn't seem like I can modify the `version-policies.json` file from there and the same for `VersionPolicy.ts` where I can't read the change files to bump properly.

Any ideas?

**Comment by isc30** [comment]
The list of things that need to happen when publishing a new version are:
- detect all the changes
- based on the changes and the changed project policies, bump the policies
- bump all the projects affected by the policy changes
- bump all the projects following the policy versions (when not individualVersion)

**Comment by isc30** [comment]
Update:
Managed to update the `version-policies.json` file accordingly, I will be cleaning up the code a bit and submitting a PR.
Then, if you are happy with the design/implementation I can write some tests and get it merged!

**Comment by isc30** [comment]
Update:
The implementation is complete and working in my test repository. I'm encountering some unit tests that fail regarding cyclic dependencies, I need some help with that please 😄

**Comment by isc30** [comment]
please refer to the PR for the latest updates https://github.com/microsoft/rushstack/pull/3059
