### ISSUE TITLE
[rush] Vulnerability in validator-8.2.0.tgz, which is consumed by @microsoft/rush 5.57.1

### ISSUE THREAD

**Issue by Sherry-Lee** [microsoft/rushstack#3092]
## Repro steps

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
This is fixed in Rush `5.58.0`
