### ISSUE TITLE
[rush] Feature request: "rush rm" command

### ISSUE THREAD

**Issue by kiprobinsonknack** [microsoft/rushstack#3099]
## Summary
Requesting a `rush rm` / `rush remove` command, analogous to `npm rm` and `pnpm rm` that developers are familiar with. This would do the opposite of `rush add`.

## Details
Currently, to remove a dependency, I need to manually remove it from `package.json`, then run `rush install` or `rush update`. It would be nice if there was one command which automated this.

Plus, I'm a little averse to this method of removing packages because it is _not_ how you did it with npm--in npm, if you didn't use `npm rm`, the package would still be present under node_modules on your local system which might lead to errors that don't show up until it hits a build server. Something similar could happen in Rush if I forget to run `rush install` or `rush update`.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.57.1 |
| `rushVersion` from rush.json? | 5.57.1 |
| `useWorkspaces` from rush.json? | false |
| Operating system? | Mac |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 14.18.1 |

**Comment by chrispaterson** [comment]
I agree!  I can't believe this doesn't exist...

**Comment by elliot-nelson** [comment]
Closing - requested functionality added in #3588. 🎉
