### ISSUE TITLE
[rush] [build-cache] Override cache provider in `rush-project.json`

### ISSUE THREAD

**Issue by Faithfinder** [microsoft/rushstack#3100]
## Summary

I would like to be able to cache some projects locally, but not in the cloud

## Details

Specific example: one of our packages is just [`prisma-client`](https://www.prisma.io/docs/reference/api-reference/command-reference#generate).
We treat `prisma.schema` as the source file, and `prisma generate` as the build command.

However, the library is not portable, `generate` produces different results on different machines [(builds some binaries depending on the OS)](https://www.prisma.io/docs/reference/api-reference/command-reference#generate).

So, caching in the cloud wouldn't be strictly safe. However, local cache would be perfectly fine.
In case of the prisma client the build times are negligible, so just disabling the build cache isn't a huge deal, but I bet there are similar cases around.

**Comment by iclanton** [comment]
It'd probably be better to be able to mark certain projects (via `rush-project.json`) as local-cache-only, or the cache keys could contain the OS name.

Either would probably be fairly straightforward to implement.

**Comment by iclanton** [comment]
I added an `[os]` token (https://github.com/microsoft/rushstack/pull/4545) to the cache name parameter. If you want to only include the OS in certain projects, you can include the `OS` env var in the `dependsOnEnvVars` property in the operation setting in a project's `rush-project.json` file.
