### ISSUE TITLE
[rush] Git version requirements are a bit high?

### ISSUE THREAD

**Issue by Faithfinder** [microsoft/rushstack#3109]
So, I'm working on my company's build pipeline right now, and I've noticed one unfortunate thing - official docker `node` images, which I think are most likely to be used with `rush`, all have git version `2.11` installed rather than anything later. After some digging you can also use `node:x-buster` images which contain git `2.20`.
Since `rush` wants `2.30`, I'd need to install it into the image manually, and with images based on Debian rather than Ubuntu it's not a straightforward process (I think I need to build from source? Maybe I'll find a simpler way, but it doesn't google easily).

While I understand that it's not entirely rush's problem, I do wonder if minimal version _really_ needs to be that high?

**Comment by chengcyber** [comment]
Share my changes to Dockerfile, hopes it help

```
# install git 2.32.0
RUN apt-get purge -y git && apt-get update \
    && apt-get install -y libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev asciidoc xmlto docbook2x \
    && wget https://github.com/git/git/archive/v2.32.0.tar.gz \
    && tar zxvf v2.32.0.tar.gz \
    && cd git-2.32.0 \
    && make configure \
    && ./configure --prefix=/usr \
    && make all \
    && sudo make install
```

**Comment by Faithfinder** [comment]
Thanks! That helps _me_ indeed, but the question is sorta philosophical.

**Comment by chengcyber** [comment]
Agreed. Either document or environment compatibility checker should be improved.

**Comment by dmichon-msft** [comment]
We can probably get away with reverting the dependency on git 2.30 now that we are calling `git merge-base` manually, we'll just need to remove the `--merge-base` flag from the `git diff-index` call and document that the caller is responsible for calling `git merge-base` first or else they may get undesired behavior.

**Comment by Faithfinder** [comment]
There's also a question of "How far back can we go" - unless it's 2.20, or, even better, 2.11 - not much point in doing it. 2.25 would be no better than 2.30

**Comment by matthiasg** [comment]
2.25 is at least in standard `apt install git`.

Is there documentation somewhere why this change was made and what the merge-base command (when run manually) is protecting from ?
