### ISSUE TITLE
[rush] Is there some way to control version of a Phantom dependencies

### ISSUE THREAD

**Issue by ISFhr** [microsoft/rushstack#3118]
## Summary
My monorepo project add vue@2 & vue@3. I  use vuepress@1.8.2 in a project, when run rush build command, it returns an error:
![image](https://user-images.githubusercontent.com/30992121/147627370-ae486d4f-2200-46f9-a018-21d95fab378a.png)

This is temp/node_modules/.pnpm
![image](https://user-images.githubusercontent.com/30992121/147627449-b0eb8acc-ffd4-415b-bbba-adb4f49cc296.png)

## Repro steps

  **Expected result:**: vue-server-render@2.6.14 will required the same version of vue

  **Actual result:**: vue-server-render@2.6.14 required vue@3.2.20

## Details
In vuepress, it has a depencency named **vue-server-render**, and in **vue-server-render** source code , I found that it required **vue** which is a phantom dependencies, code like this in **vue-server-render/index.js**:
![image](https://user-images.githubusercontent.com/30992121/147627638-9432ea9b-2e7f-4b14-83a2-b69d08b58530.png)
and **vue-server-render's** package.json is:
![image](https://user-images.githubusercontent.com/30992121/147627697-5c66d97e-5f1d-4927-bd45-db4c25525ddd.png)
(actually here need introduced **vue** from developer's project)

So how can I assign a fixed version of vue in a project when use vuepress? And maybe I really need a soluation of this case：How to assign a fixed version of a dependence in a rush project to ensure the whole dependence (include dependence of dependence) in this project will use this fixed version.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by dmichon-msft** [comment]
The general solution is to use pnpmfile or the pnpm/yarn resolutions feature(s) to add the missing dependency to the package.

**Comment by iclanton** [comment]
You can try adding tweaks in [`common/config/rush/common-versions.json`](https://rushjs.io/pages/configs/common-versions_json/), but @dmichon-msft is probably right that the best way to handle this is by adding some logic into `pnpmfile` to make the phantom dependency explicit.

PNPM also has added some options to `package.json` to control dependencies-of-dependencies. Take a look at the PNPM documentation for that.
