### ISSUE TITLE
[heft] jest-build-transform does not support sources outside of `/src`

### ISSUE THREAD

**Issue by MichaelSitter** [microsoft/rushstack#3128]
## Summary

jest-build-transform does not support sources outside of `/src`, looks like its enforced here:

https://github.com/microsoft/rushstack/blob/master/heft-plugins/heft-jest-plugin/src/transformers/BuildTransformer.ts#L353

I'm unclear why this limitation is enforced by the plugin, so I don't know if this is a feature or a bug. Is there a reason why `src` is checked this way?

## Repro steps

My rush package is structured with the sources all living under the `/modules` directory instead of `/src`. Note that if the `/src` directory doesn't exist the runner will fail before it even detects the project specs. This is b/c the `roots` config from `@rushstack/heft-jest-plugin/includes/jest-shared.config.json` gets merged, instead of overridden.

```
{
  "extends": "@rushstack/heft-jest-plugin/includes/jest-shared.config.json",
  "clearMocks": true,
  "testMatch": ["<rootDir>/modules/**/*.test.[jt]s?(x)"],
  "roots": ["<rootDir>/modules"],
  "setupFiles": ["./testEnv.js"],
  "testEnvironment": "jest-environment-node"
}
```

  **Expected result:** 

Should run jest tests for any specs which match the jest config.

  **Actual result:** 

```
 FAIL  modules/auth/__tests__/middleware.test.ts
  ● Test suite failed to run

    jest-build-transform: The input path is not under the "src" folder:
    /Users/michaelsitter/xxxxxxx/modules/auth/__tests__/middleware.test.ts

      at BuildTransformer.process (../../common/temp/node_modules/.pnpm/@rushstack+heft-jest-plugin@0.2.0_@rushstack+heft@0.44.0/node_modules/@rushstack/heft-jest-plugin/src/transformers/BuildTransformer.ts:388:13)
      at ScriptTransformer.transformSource (../../common/temp/node_modules/.pnpm/@jest+transform@27.4.2/node_modules/@jest/transform/build/ScriptTransformer.js:620:31)
      at ScriptTransformer._transformAndBuildScript (../../common/temp/node_modules/.pnpm/@jest+transform@27.4.2/node_modules/@jest/transform/build/ScriptTransformer.js:766:40)
      at ScriptTransformer.transform (../../common/temp/node_modules/.pnpm/@jest+transform@27.4.2/node_modules/@jest/transform/build/ScriptTransformer.js:823:19)
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 5.56.0
| Operating system? | Mac
| Would you consider contributing a PR? | Yes
| Node.js version (`node -v`)? | v14.17.5

**Comment by MichaelSitter** [comment]
Just wondering if I can get some direction as to wether this is a bug or a feature enhancement. I'm happy to carve out some time to make a contribution, it's just not clear from the plugin documentation if this is intended to work like this.

**Comment by ErikMikkelson** [comment]
My company has worked with a modified version of the plugin for six months with this change.  We wanted to have a separate "deploy" folder for all our cdk code.  It requires changes in 3 places in BuildTransform.ts and then you can use jestOptions.roots.

**Comment by FullStackSteve** [comment]
> My company has worked with a modified version of the plugin for six months with this change. We wanted to have a separate "deploy" folder for all our cdk code. It requires changes in 3 places in BuildTransform.ts and then you can use jestOptions.roots.

@ErikMikkelson would it be possible to share the steps required to create a modified plugin?

**Comment by FullStackSteve** [comment]
So it looks like we can do a quick fix if we:

- Rename our project's src file path from `./packages/<project-name>/src/*` to `./packages/<project-name>/module/*`
- Update tsconfig.json from `src` instead of `module`:
  ```
  {
    "$schema": "http://json.schemastore.org/tsconfig",
  
    "compilerOptions": {
      "baseUrl": "./module",
      "rootDir": "./module"
      // ...
    },
    "include": ["module/**/*"],
  }
  ```
- Update the `@rushstack/heft-jest-plugin/includes/jest-shared.config.json`  from `src` to `module`:
  ```
  {
    // THIS SHARED JEST CONFIGURATION FILE IS INTENDED TO BE REFERENCED BY THE JEST CONFIGURATION IN
    // CONSUMING PACKAGE AND REQUIRES PRESET-RELATIVE MODULE RESOLUTION TO BE ENABLED. IF YOU HAVE
    // DISABLED THIS FEATURE YOU MUST CREATE YOUR OWN JEST CONFIGURATION
  
    // By default, don't hide console output
    "silent": false,
  
    // In order for HeftJestReporter to receive console.log() events, we must set verbose=false
    "verbose": false,
  
    // If mocks are not cleared between tests, it opens the door to accidental reliance on
    // ordering of tests or describe blocks, eventually resulting in intermittent failures.
    //
    // We suggest this setting for any heft project (in a monorepo or not).
    "clearMocks": true,
  
    // "Adding '<rootDir>/src' here enables src/__mocks__ to be used for mocking Node.js system modules
    "roots": ["<rootDir>/module"],
  
    "testURL": "http://localhost/",
  
    "testMatch": ["<rootDir>/src/**/*.test.{ts,tsx}"],
    "testPathIgnorePatterns": ["/node_modules/"],
  
    // Code coverage tracking is disabled by default; set this to true to enable it
    "collectCoverage": true,
  
    "coverageDirectory": "<rootDir>/temp/coverage",
  
    "collectCoverageFrom": [
      "src/**/*.{ts,tsx}",
      "!src/**/*.d.ts",
      "!src/**/*.test.{ts,tsx}",
      "!src/**/test/**",
      "!src/**/__tests__/**",
      "!src/**/__fixtures__/**",
      "!src/**/__mocks__/**"
    ],
    "coveragePathIgnorePatterns": ["/node_modules/"],
  
    "transformIgnorePatterns": [],
  
    // jest-identity-mock-transform returns a proxy for exported key/value pairs, where Webpack would return a module
    // jest-string-mock-transform returns the filename, where Webpack would return a URL
    // When using the heft-jest-plugin, these will be replaced with the resolved module location
    "transform": {
      "\\.(ts|tsx)$": "@rushstack/heft-jest-plugin/lib/exports/jest-build-transform.js",
  
      "\\.(css|sass|scss)$": "@rushstack/heft-jest-plugin/lib/exports/jest-identity-mock-transform.js",
  
      "\\.(aac|eot|gif|jpeg|jpg|m4a|mp3|mp4|oga|otf|png|svg|ttf|wav|webm|webp|woff|woff2)$": "@rushstack/heft-jest-plugin/lib/exports/jest-string-mock-transform.js"
    },
  
    // The modulePathIgnorePatterns below accepts these sorts of paths:
    //   - <rootDir>/src
    //   - <rootDir>/src/file.ts
    // ...and ignores anything else under <rootDir>
    "modulePathIgnorePatterns": [],
  
    // Prefer .cjs to .js to catch explicit commonjs output. Optimize for local files, which will be .ts or .tsx
    "moduleFileExtensions": ["ts", "tsx", "cjs", "js", "json", "node"],
  
    // When using the heft-jest-plugin, these will be replaced with the resolved module location
    "setupFiles": ["@rushstack/heft-jest-plugin/lib/exports/jest-global-setup.js"],
  
    // When using the heft-jest-plugin, these will be replaced with the resolved module location
    "resolver": "@rushstack/heft-jest-plugin/lib/exports/jest-improved-resolver.js",
    "testEnvironment": "node",
    "coverageProvider": "v8",
    "moduleDirectories": ["node_modules", "module"]
  }
  ```
  
Potentially the issue seems to be something to do with the hardcoded `src` in the `heft-jest` plugin, when using non-relative import paths that are conflicting with `mongodb` SDK's folder structure?

**Comment by MichaelSitter** [comment]
@FullStackSteve afaik I linked to the line you'd need to modify to support other paths in the issue report. I was hoping someone from the maintainer team would comment if this was an intentional choice or just a limitation of the current implementation.

**Comment by ErikMikkelson** [comment]
@FullStackSteve https://gist.github.com/ErikMikkelson/1ba9d39e46d4479364a3b52d7aad9627

**Comment by elliot-nelson** [comment]
FWIW, I think the current implementation is just a safety precaution. Commonly, for web-based outputs, you'll configure typescript to compile `/src` to `/lib` and `/lib-commonjs` (`/lib` will contain your ESM output, `/lib-commonjs` will contain a second copy emitted as CommonJS).

If you have _multiple_ source root folders set up, you would want to make sure that they get mapped to identical subpaths within both of those output folders, and that they wouldn't conflict with each other (e.g. `src/index.ts` and `modules/index.ts`, if both are inputs).

It looks like your solution is to treat the `<rootDir>` as the build root, so you'd have `/lib/src`, `/lib/modules`, `/lib-commonjs/src`, `/lib-commonjs/modules`, etc. -- this still seems pretty safe to me, although you might need to also adjust your webpack etc. config to compensate.

**Comment by D4N14L** [comment]
This issue seems to be superseded by the changes made to `@rushstack/heft-jest-plugin` by @dmichon-msft in our move to the updated version of Heft, so I'm closing this out. Please re-open if this is still an issue.
