### ISSUE TITLE
[rush] plugin custom command throw error in rush@5.59.2

### ISSUE THREAD

**Issue by chengcyber** [microsoft/rushstack#3155]
## Summary

In rush@5.59.2, the logic of default build/rebuild commands is moved to `CommandLineConfiguration`, which is used by pluginManager as well. This leads to always duplicate `build/rebuild` when apply command line json from plugin.

![image](https://user-images.githubusercontent.com/16147702/149462295-a12d4b20-9a5b-4929-83df-b51998791b87.png)

## Repro steps

1. Configuration a rush plugin with custom command-line.json
2. run rush cli, such as rush update
3. rush prints warnings

  **Expected result:** 

  **Actual result:** 

## Details

Solution might be make `CommandLineConfiguration` to insert default build/rebuild command definitions explicitly.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? | 5.92.2 |
| `useWorkspaces` from rush.json? | true |
| Operating system? |  |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14 |

**Comment by octogonz** [comment]
This is fixed in the latest release 5.61.1.  5.60.0 introduces a breaking change for the build cache, so we have backported this fix as 5.60.1 and 5.59.3.
