### ISSUE TITLE
[rush] Error: git hash-object exited with status 128

### ISSUE THREAD

**Issue by prescience-data** [microsoft/rushstack#3163]
## Summary

When running `rush build` I'm encountering the following error:
```
Error calculating the state of the repo. (inner error: Error: git hash-object exited with status 128: fatal: could not open 'libraries/*****/src/****.ts' for reading: No such file or directory
). Continuing without diffing files.
```
This results in a full rebuild each time `rush build` is called.

## Repro steps

Unfortunately specific repro steps are a bit thin given I'm not sure which exact recent change caused the issue. 
I do know it only started occurring after a recent Rush version update.

1. Set **Rush** to version `5.59.2` and **pnpm** to `6.25.1`
2. Run `rush build`

  **Expected result:**  
Cached build to occur.

  **Actual result:**
Upon first package (whichever it is) receive WARN error:
```
Error calculating the state of the repo. (inner error: Error: git hash-object exited with status 128: fatal: could not open 'libraries/*****/src/****.ts' for reading: No such file or directory
). Continuing without diffing files.
```

## Details

Root cause:
https://github.com/microsoft/rushstack/blob/3a872ed093aaa4a56d19b4b0a96cc44ab88f3e40/libraries/package-deps-hash/src/getRepoState.ts#L222-L225

Similar historic issues:
https://github.com/microsoft/rushstack/issues/2007
https://github.com/microsoft/rushstack/pull/2033 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.59.2 |
| `rushVersion` from rush.json? | 5.59.2 |
| `useWorkspaces` from rush.json? | true |
| Operating system? |  Windows  |
| Would you consider contributing a PR? | Yes   |
| Node.js version (`node -v`)? | 16.13.0 |

**Comment by D4N14L** [comment]
I've seen this myself locally as well, this looks like a bug.

**Comment by dmichon-msft** [comment]
If the file is staged it shouldn't even get passed to `git hash-object`, so this is definitely a bug.

**Comment by Luxcium** [comment]
I got `Analyzing repo state... Error calculating the state of the repo. (inner error: Error: git hash-object exited with status 128: fatal: Unable to hash servers/api/
). Continuing without diffing files.`

What should I do to work around that ??? 

it is part of my tree:

```json
  "projects": [
    {
      "packageName": "api-server",
      "projectFolder": "servers/api",
      "tags": ["servers"]
    }
  ]
```
