### ISSUE TITLE
[rush] allowWarningsInSuccessfulBuild stopped working in v5.59.0

### ISSUE THREAD

**Issue by gesiu** [microsoft/rushstack#3165]
## Summary

In `command-line.json`, the following config allows a successful build when a test writes to stderr:

````
{
      "commandKind": "bulk",
      "name": "test",
      "summary": "Tests each of the projects",
      "description": "Tests each of the projects",
      "enableParallelism": false,
      "allowWarningsInSuccessfulBuild": true
    }
````

When upgrading from 5.58.0 to 5.59.0, the build fails.

## Repro steps

https://github.com/gesiu/rush-warnings

````
npm install
npm run test
````

Expected: Succeeds with return code 0

Actual:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rush-warnings@1.0.0 test: `node common/scripts/install-run-rush.js test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rush-warnings@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

This succeeds if the rush version is reverted to 5.58.0 in
https://github.com/gesiu/rush-warnings/blob/main/rush.json

## Details

[This commit](https://github.com/microsoft/rushstack/commit/5d61c402b13e7d08129bd6b29296cb9ef96f3d79)  translates bulk commands to phased commands. Phased commands don't support allowWarningsInSuccessfulBuild, so that parameter has no effect anymore.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | N/A |
| `rushVersion` from rush.json? | 5.58.0 works; 5.59.0+ doesn't work |
| `useWorkspaces` from rush.json? | No |
| Operating system? | Windows |
| Would you consider contributing a PR? | Not at this time |
| Node.js version (`node -v`)? | 14.16.1 |

**Comment by isc30** [comment]
facing the same issue, please this is a critical bug

**Comment by isc30** [comment]
@iclanton

**Comment by brycepolly** [comment]
Just ran into this also with jest testing, downgrading for now
