### ISSUE TITLE
[rush] rush update --full reported beta version as available major upgrade

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/rushstack#3167]
## Summary
[In our repo](https://github.com/Azure/azure-sdk-for-js/issues/19607) we check available major version upgrades using the following steps

![image](https://user-images.githubusercontent.com/7583839/150008999-da68f780-324c-4949-a7aa-0c820eb01057.png)

For some package, the available major version upgrades only had beta releases, no stable versions yet.  Maybe it's better to not report them as available major upgrades until a stable version has been released?

For example, when the above issue was logged, fast-xml-parser 4.0.0 stable version hadn't been published.

  **Expected result:** 
available major upgrades that only have beta releases so far are not reported

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.55.1 |
| `rushVersion` from rush.json? | 5.55.1 |
| `useWorkspaces` from rush.json? | not using this option |
| Operating system? | All |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 14.15.1 |

**Comment by iclanton** [comment]
Related to https://github.com/microsoft/rushstack/issues/3169, this isn't a Rush feature. Rather, this is implemented by some packages' `postInstall` scripts and by some package managers.
