### ISSUE TITLE
[rush] some package has major version upgrade available but not reported by rush

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/rushstack#3169]
## Summary

we use the following steps in our repo to find out available major version upgrades

![image](https://user-images.githubusercontent.com/7583839/150008999-da68f780-324c-4949-a7aa-0c820eb01057.png)

[Recently we found that](https://github.com/azure/azure-sdk-for-js/issues/19880#issuecomment-1015890412) while rush found an available upgrade v7.0.0 for `@types/concurrently`, it didn't report an upgrade that is available to the main library package `concurrently`.  The two at least are used together in one package (dev-tool) that is managed by rush.

This was tested on commit 6faa0c8ce28049eb337ac3c9790ecd72324929c7 of https://github.com/azure/azure-sdk-for-js

  **Expected result:** 
Rush reports that an upgrade of v7.0.0 is available to the main library package `concurrently`

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 1.55.1 |
| `rushVersion` from rush.json? | 1.55.1 |
| `useWorkspaces` from rush.json? | not using this option |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? | 16.13.1 |

**Comment by iclanton** [comment]
It looks like you're using a very old version of Rush. Notification about new versions isn't a Rush feature, but it is a feature of some package managers, and some packages have `postInstall` scripts that report when a new version is available.

I recommend that you look into how the package reports new versions and/or what the package manager that you're using is expected to do.
