### ISSUE TITLE
[rush] transient S3 errors updating build cache causes CI to fail

### ISSUE THREAD

**Issue by UberMouse** [microsoft/rushstack#3198]
## Summary

Somewhat frequently we get issues in our CI jobs during the phase that compiles dependencies. We make use of the S3 cloud caching functionality and sometimes (I haven't been able to work out specifically why, it seems to happen sometimes when there is little activity on the bucket) that compile step will fail because one of the packages fails to upload to S3 with the error

```
Error uploading cache entry to S3: Error: Amazon S3 responded with status code 503 (Slow Down)

Unable to set cloud cache entry.
```

Rerunning the job always fixes it. Ideally Rush would try and re-upload the cache entry itself automatically (or with a flag if required), a delay before retrying seems sensible.

Alternatively, a flag to not make this error fail the compile step would be fine too.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.59.2 |
| `rushVersion` from rush.json? | 5.59.2 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14.17.5 |

**Comment by iclanton** [comment]
It'd be straightforward enough to add some retry logic to the S3 plugin. Would you be willing to put that together?

**Comment by UberMouse** [comment]
Sure I can give it a go as time permits at work :) Mind pointing me at the right place?

**Comment by iclanton** [comment]
This is where the S3 cache provider performs the upload: https://github.com/microsoft/rushstack/blob/4acef65db819ab65e7026c51526fc1942c8279b5/rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3BuildCacheProvider.ts#L137-L147

And this is where the HTTP request happens: https://github.com/microsoft/rushstack/blob/4acef65db819ab65e7026c51526fc1942c8279b5/rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts#L87

**Comment by ricsam** [comment]
Hi, I'll work on this today. 

**Feature 1:** add retry logic
**Feature 2:** cli_flag/config_var/env_var to suppress cache write/read errors

I'll start with adding the retry logic, **Feature 1**:

Cache options proposal:

```jsonc
// send maximum of 2 requests in total
// takes about 2 seconds to fail
"retryCacheRequest": {
  "retries": 1,
  "waitDuration": 2,
  "exponential": false,
}
```

```jsonc
// same as above, waitDuration defaults to 2, exponential defaults to false
"retryCacheRequest": {
  "retries": 1
}
```


```jsonc
// send maximum of 3 requests in total
// takes about 20 seconds to fail
"retryCacheRequest": {
  "retries": 2,
  "waitDuration": 10,
  "exponential": false,
}
```

```jsonc
// send maximum of 3 requests in total
// takes about 110 seconds to fail (10^1 + 10^2)
"retryCacheRequest": {
  "retries": 2,
  "waitDuration": 10,
  "exponential": true,
}
```

```jsonc
// same as "retryCacheRequest": null or "retryCacheRequest": {} i.e. retries are diabled
"retryCacheRequest": {
  "retries": 0
}
```
