### ISSUE TITLE
[rush] --prerelease-name bumps the packages making semver incompatible with prerelease versions

### ISSUE THREAD

**Issue by isc30** [microsoft/rushstack#3201]
`--prerelease-name` is increasing the semver with a patch before adding the prerelease and it breaks selectors like `^1.0.0` where a prerelease version `1.0.1-something` isn't assignable to it

**Comment by iclanton** [comment]
Would you be willing to put together a fix?

**Comment by isc30** [comment]
yes absolutely, i have a few things on my list that i would want to contribute and this is one of them (after the automatic version for lockstepversionpolicy)

**Comment by isc30** [comment]
actually, it seems to be a bug because `--include-all` doesn't work at all when mixed with `--prerelease-name`. Also `--prerelease-name` is increasing the semver with a patch before adding the prerelease and it breaks selectors like `^1.0.0` that isn't assignable to `1.0.1-something`

**Comment by isc30** [comment]
just realized that --sufix doesn't bump the versions, no need for this
