### ISSUE TITLE
[rush] For local-only cache provider, writeAllowed should default set be true.

### ISSUE THREAD

**Issue by leeight** [microsoft/rushstack#3226]
## Repro steps

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by leeight** [comment]
https://github.com/microsoft/rushstack/issues/3227

**Comment by dmichon-msft** [comment]
Resolved in #3227
