### ISSUE TITLE
[rush] bug: prerelease name not in git tag

### ISSUE THREAD

**Issue by ethan-burrell** [microsoft/rushstack#3239]
## Summary

This is pretty much the same error as #3222. The issue now is happening at another part in the publish script. Now it is happening after `npm publish` runs.

```
npm notice === Tarball Contents === 
[Redacted]
npm notice === Tarball Details === 
npm notice name:          <packageName>          
npm notice version:       <version>-<prereleaseName>
npm notice package size:  108.6 kB                                
npm notice unpacked size: 509.1 kB                                
npm notice shasum:        <sha>
npm notice integrity:     <sha>
npm notice total files:   329                                     
npm notice 
fatal: tag '<packageName>_v<version>' already exists
```

## Repro steps

Running this command:
`rush publish --apply --publish --tag beta --prerelease-name beta`

In this case there has already been a publish done for the feature, so the git repo has the tag not including the `pre-release` name.

  **Expected result:** 

This should not error out, and use the git tag with the prerelease name in it

  **Actual result:**

Exit 128

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 1.22.5  |
| `rushVersion` from rush.json? | 5.62.3 |
| `useWorkspaces` from rush.json? | true  |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 12.18.2 |

**Comment by D4N14L** [comment]
@ethan-burrell it seems like you have a good handle on this issue. Would you be willing to contribute another fix for this? CC @pgonzal
