### ISSUE TITLE
[rush] Rush is having install/update issues for the @okta/okta-auth-js package

### ISSUE THREAD

**Issue by miguel-a-calles-mba** [microsoft/rushstack#3260]
## Summary

I get an error when running `rush update` or `rush install` for a folder that is using the `@okta/okta-auth-js` package.

I was not having an issue when I was simply doing an `npm install` but now that I'm trying to add rush into my repo it fails with the error below.

```
ERROR: The dependency "@typescript/lib-dom" needed by "webcrypto-core" was not found in the common folder -- do you need to run "rush install"?
```

## Repro steps

- Create a folder with its own package.json file by using the `npm init -y` command.
- Install the package with `npm i @okta/okta-auth-js` within that folder.
- Add the folder to the `rush.json` file.
- Run `rush update` and see the error.

  **Expected result:** 

No errors.

  **Actual result:** 

```
ERROR: The dependency "@typescript/lib-dom" needed by "webcrypto-core" was not found in the common folder -- do you need to run "rush install"?
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.62.4 |
| `rushVersion` from rush.json? | 5.62.4 |
| `useWorkspaces` from rush.json? | Not there |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14.18.1 |

**Comment by miguel-a-calles-mba** [comment]
I think I may have found the issue. I submitted a PR for the affected npm package.

https://github.com/PeculiarVentures/webcrypto-core/pull/48

**Comment by iclanton** [comment]
Don't run `npm install` (or `npm i`) in folders in a Rush repo. Run `rush add --package <packageName>` or manually add the dependency to the project's `package.json` and run `rush update`.

Looks like the root of the issue was an incorrectly specified peer dependency, though.
