### ISSUE TITLE
[rush] rush change always gives me No changes were detected

### ISSUE THREAD

**Issue by shakogegia** [microsoft/rushstack#3261]
I just set up a new project with rush and whenever I run `rush change` it always returns

```
No changes were detected to relevant packages on this branch. Nothing to do.
```

Am I missing something?

P.S 
forgive me if I opened issue incorrectly, I could not find solution for this anywhere

**Comment by iclanton** [comment]
Did you configure projects for publishing? You need to either set the `shouldPublish` field to `true` for the project in `rush.json` (see docs here: https://rushjs.io/pages/maintainer/publishing/#1-track-changes), or configure version policies (see docs here: https://rushjs.io/pages/maintainer/publishing/#3-version-policy).

`rush change` diffs against the branch configured in the `repository` settings of `rush.json` (https://rushjs.io/pages/maintainer/recommended_settings/#repositoryurl), or, that isn't configured, against `origin/master` (will be updated to `origin/main` in Rush 6, but this will be a breaking change) by default. You need to have committed changes inside project folders for `rush change` to detect any changes.

**Comment by TGTGamer** [comment]
I've replicated this issue, please find the configuration I use here: https://github.com/Resnovas/Eventiva/blob/master/rush.json

I have tried having the changes staged, and unstaged. Do we need to commit them locally without pushing or something?

I'm feeling like I'm missing something obvious

![image](https://user-images.githubusercontent.com/11413796/157727405-c9a58603-828a-4473-bbda-80ad9b7037f9.png)

**Comment by dmichon-msft** [comment]
Slight correction, `rush change`, contrary to what the warning says, will detect changes that are merely staged, they do not need to be committed.

**Comment by dmichon-msft** [comment]
Committing locally and not pushing should work; staging should be sufficient, however (as of a few months ago Rush uses `git diff-index` to compute the list of changed files).

**Comment by iclanton** [comment]
Yes, you do need to commit changes to trigger change detection.

**Comment by elliot-nelson** [comment]
Just to confirm, if a project is set up for publishing, you should see changes via `rush change` if the changes are just added to the index (you don't need to commit them).

The linked issue also hopefully fixes any submodule-related hashing issues -- please open a new ticket if you run into additional problems with rush change!
