### ISSUE TITLE
[api-extractor] Exposing whether a method/type parameter is optional

### ISSUE THREAD

**Issue by zelliott** [microsoft/rushstack#3266]
## Motivation

It's useful to know whether a method or type parameter is optional. Examples:

```
export function foo(x?: boolean): void {

}

// Generated .d.ts changes `x = true` to `x?: boolean`.
export function bar(x = true): void {

}

export function baz<X = {}>() {

}
```

This information is currently not exposed in the `.api.json` doc model for a method/type parameter.

## Proposal

We will add a new property to the `Parameter` and `TypeParameter` classes in `api-extractor-model` called `isOptional` that indicates whether or not they are optional. Notably, these classes will not use the `ApiOptionalMixin` because they do not extend the `ApiItem` base class. For more context, please see https://rushstack.zulipchat.com/#narrow/stream/262521-api-extractor/topic/Optional.20parameters.

## Open questions

- [x] Does the `isOptional` property also make sense for `TypeParameter`s? Example: `function foo<X = {}>() {}`. **Yes.**

**Comment by octogonz** [comment]
> * Does the `isOptional` property also make sense for `TypeParameter`s? 

Yes, I think so.

**Comment by zelliott** [comment]
Okay, updated the issue accordingly.

**Comment by zelliott** [comment]
@octogonz If a `TypeParameter` has a default type (e.g. `function foo<X = number>() {}`), then it is optional. The `defaultTypeTokenRange` is already present in the API doc model. So, presumably, a user of api-extractor-model (aka api-documenter) can already document whether a `TypeParameter` is optional, we don't need to store any additional information in the API doc model. But should we?

**Comment by octogonz** [comment]
Good observation. 👍

IFF means that the `.api.json` file doesn't need a new field.  What would be useful is to implement the `isOptional` property in the TypeScript class, since many people will not be aware of this fact, and might not realize they can implement `isOptional`.

Also, we could still update API Documenter to render the `isOptional` state consistently with the other things that can be optional.
