### ISSUE TITLE
[rush] Build Cache feature is broken in rush@5.63.0

### ISSUE THREAD

**Issue by chengcyber** [microsoft/rushstack#3287]
## Summary

It seems `rush@5.63.0` build cache is totally broken...

## Repro steps

Use rushstack repo

update rush.json to use `"rushVersion": "5.63.0",`

remove the build-cache folder at `common/temp/build-cache`

run `rush build --to rush-lib -v`

and run again.

**Expected result:** 

the second time of `rush build` hit caches.

**Actual result:** 

every projects are logging `This project was not found in the build cache.`, which means local build cache is broken now.

Ideally, local build cache should present under `common/temp/build-cache` but nothing now.

___

When you switch back to `  "rushVersion": "5.62.4",`, everything is fine.
  

## Details

It feels like `Successfully set cache entry.` is not logging. So, it might be related with incorrect value of the `isCacheWriteAllowed` property of `ShellOperationRunner`.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.62.2 |
| `rushVersion` from rush.json? | 5.63.0 |
| `useWorkspaces` from rush.json? |  |
| Operating system? | MacOS |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by dmichon-msft** [comment]
Default value of `isCacheWriteAllowed` in `ShellOperationRunner` needs to change from `false` to `true`. Will have a PR out shortly.
