### ISSUE TITLE
[rush] (pnpm) Ignoring peer dependency

### ISSUE THREAD

**Issue by anantoghosh** [microsoft/rushstack#3293]
## Summary
For example when I install `@emotion/react` which has a optional peer dependency on `@babel/core`. We are not installing `@babel/core` as it not required for our build.

I tried to ignore it by setting in the projects's package.json
```
"pnpm": {
  "peerDependencyRules": {
    "ignoreMissing": [
      "@babel/core"
    ]
  }
}
```
[as recommended by pnpm](https://github.com/pnpm/pnpm/discussions/3536#discussioncomment-2010684), but that does not seem to work within a rush repo. It works normally in a pnpm project just fine.

This prevents our projects from using strict peer dependencies, as it throws an error. Furthermore, it makes the rush update output quite verbose and full of warnings.
## Repro steps

https://github.com/anantoghosh/rush-peer

![image](https://user-images.githubusercontent.com/12339068/159893344-6175237f-ccb6-4c8c-bb7a-e5c97e3dbd97.png)

## Details

Current workaround is to install all the optional peers as well, but that may lead to unintended effects under certain cases.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.62.2 |
| `rushVersion` from rush.json? | 5.63.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Windows |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v16.13.2 |
| pnpm | v6.32.3 |

**Comment by D4N14L** [comment]
We just run PNPM install when performing `rush install`, so I'm unsure why this wouldn't be working for you. Our own modifications on top of this are limited to `.pnpmfile.cjs` and generate a workspace file. Have you tried doing this with a vanilla PNPM workspace?

**Comment by anantoghosh** [comment]
@D4N14L thank you for your input, it helped me with further investigation. It turns out in a pnpm workspace, the `pnpm` key must be specified in the root `package.json`.
https://github.com/pnpm/pnpm/issues/4306#issuecomment-1054884310. Since rush keeps the root `package.json` internal, is there any way we would specify it?

**Comment by elliot-nelson** [comment]
This configuration option is now officially supported in Rush 5.79+ in the pnpm-config file:
