### ISSUE TITLE
[rush] build cache not working if package to be cached has "common" as its folder name

### ISSUE THREAD

**Issue by towfiles** [microsoft/rushstack#3319]
## Summary
Build cache not working if package to be cached has "common" as its folder name

- Create a monorepo package and name the folder name "common", then also the package name as @xxx/common
- Configure the rush-project.json and also build cache
- The cache build doesnt seem to be create or even build-cache folder generated

## Repro steps

  **Expected result:** Cache should be generated even if package folder name contains "common"

  **Actual result:** No Cache is generated for packages with folder name common

## Details
Explained here:
https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/rush.20build.20cache.20issues

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | Yes |
| `rushVersion` from rush.json? | 5.62.4 |
| `useWorkspaces` from rush.json? | No |
| Operating system? | Mac |
| Node.js version (`node -v`)? | v12.22.4 |

**Comment by iclanton** [comment]
I'm trying to get a repro for this, but it's working as expected for me. I put together a repro repo here: https://github.com/iclanton/rush-common-repro

Can you confirm I'm doing what you did? Can you get this issue to reproduce there?

I am trying this on Windows right now. I can try it on a mac at the office tomorrow.

**Comment by towfiles** [comment]
I wasn't able to reproduce this issue on another repo and the common package/folder started building when i setup cloud caching
