### ISSUE TITLE
[rush] set public-hoist-pattern but vs code not detect?

### ISSUE THREAD

**Issue by leohxj** [microsoft/rushstack#3324]
I have some sub packages whose has phantom dependencies, as usually I will can `public-hoist-pattern` rules to use it in my apps. 

I update `common/config/rush/.npmrc` , add the public-hoist-pattern rules then run `rush update`, the `common/temp/node_modules` have the modules who has been hoisted.

BUT, vs code does't detect those modules, it still "cannot find module or its corresponding type declarations".

PS: as workaround, I manually  add those modules as a dependency to project's package.json.

**Comment by dmichon-msft** [comment]
Even with public-host-pattern, since the node_modules directory is not in the root of the repository, the modules are only resolvable from within external dependencies. If a project depends on them directly, they need to be declared in package.json.

**Comment by leohxj** [comment]
> Even with public-host-pattern, since the node_modules directory is not in the root of the repository, the modules are only resolvable from within external dependencies. If a project depends on them directly, they need to be declared in package.json.

Thanks, I have to manually add phantom dependencies in package.json now.
