### ISSUE TITLE
[api-extractor] API Extractor should report a better error if it attempts to analyze `.ts` files instead of `.d.ts` files.

### ISSUE THREAD

**Issue by zelliott** [microsoft/rushstack#3328]
## Summary

From Zulip chat:

> I just spent some time debugging an error in AE where the root cause was AE attempting to analyze .ts files. I think this is due to the TS compiler engine preferring .ts files over .d.ts files (https://github.com/microsoft/rushstack/issues/1310). I'm wondering if it's feasible for AE to simply throw an InternalError of some kind if it "realizes" it's analyzing .ts files? That might make these types of errors easier for developers to debug.

## Details

According to @octogonz:

> Yes, this is a common problem. Reporting an error/warning would probably a void a lot of support requests. :-)
> `--diagnostics` already prints the list of file paths, so checking for `.ts` should be pretty simple.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? | Latest |
| Operating system? | All |
| API Extractor scenario? | All |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | Latest |
| Node.js version (`node -v`)? | Latest |

**Comment by sedghi** [comment]
I had this problem and it appeared that I was using a class def as type, posting here for anyone looking for an answer. Below the `StackViewport` is a class def not a type def. 

![image](https://user-images.githubusercontent.com/7490180/171917484-bd2e51f4-9cad-4e19-944a-afe3712daf94.png)

**Comment by zelliott** [comment]
This should be closed as https://github.com/microsoft/rushstack/pull/3341 is merged.
