### ISSUE TITLE
[eslint-patch] warning from vite bundling as cannot determine if CJS or ESM

### ISSUE THREAD

**Issue by tom-fletcher** [microsoft/rushstack#3343]
## Summary

When the Vite tool is being used in a package, it performs automatic dependency discovery during builds. During this process it attempts to determine whether each package in the project is CommonJS or ESM. As this is automatic for all the project dependencies, it discovers `eslint-patch` (even though it will not included in the final build).

Vite outputs the following warning during bundling:

```
@rushstack/eslint-patch doesn't appear to be written in CJS, but also doesn't appear to be a
valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point).
Please contact the package author to fix.
```

## Problem

The entry point for `eslint-patch` throws an error to explain the package does not have a default entry point. However there is nothing in this code that identifies it as CommonJS, causing Vite to output the warning.

## Fix

Adding a blank export provides sufficient information for Vite to determine this is CommonJS, and the warning is no longer output. The intended error will still be thrown if the package is directly imported.

## PR

PR will be submitted.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/eslint-patch` version? | 1.1.2 |
| Would you consider contributing a PR? | Yes |

**Comment by dmichon-msft** [comment]
Strictly speaking the particular module is 100% valid ESM and valid CommonJS at the same time. That warning is rather poorly worded, since it really means "is not forced to be interpreted by Node as an ES module".

**Comment by tom-fletcher** [comment]
I agree, and it's probably a bit of an edge case as the whole module is really valid CommonJS.

That said, the warning is annoying as it outputs at build time, but goes away and everything plays nicely together again with the addition of the blank export in #3344.
