### ISSUE TITLE
[rush] Build caching randomly outputs warning saying there are no S3 credentials configured

### ISSUE THREAD

**Issue by UberMouse** [microsoft/rushstack#3347]
## Summary

Updated to Rush v5.66.0 yesterday after seeing that the fix for retrying failed S3 cache uploads was released (happy to see that get fixed :partying_face:) and that has solved our problems with some CI runs failing due to issues around that.

However, now I'm randomly getting a warning about missing S3 credentials when running `rush build` locally. From looking at the code that error is only logged when there are no S3 credentials retrieved and the response is related to credential errors.

Except this only happens sometimes, which means my configured S3 credentials are fine. It will affect maybe one or two package builds out of the 40ish packages that we build during `rush build`.

## Repro steps

1. run `rush build`

  **Expected result:** All packages build with no warning output

  **Actual result:** _Sometimes_ one or two of the builds emit the warning "No credentials found and received a 403 response code from the cloud storage. Maybe run rush update-cloud-credentials or set the RUSH_BUILD_CACHE_CREDENTIAL env"

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.66.0 |
| `rushVersion` from rush.json? | 5.66.0 |
| `useWorkspaces` from rush.json? |  true |
| Operating system? | Linux |
| Node.js version (`node -v`)? | v14.17.5 |

**Comment by UberMouse** [comment]
Just had a thought. If there is no asset at that path in the S3 CDN bucket then S3 returns a 403 code, not a 404 code.

So I'm wondering if a cache miss is logging that message by mistake?

**Comment by iclanton** [comment]
>Just had a thought. If there is no asset at that path in the S3 CDN bucket then S3 returns a 403 code, not a 404 code.

Is that true even if you have valid credentials? I admittedly don't have much experience with S3.

**Comment by UberMouse** [comment]
Ah yes, you are correct. I was just thinking about unauthenticated requests, those get 403 since the files are what specifically have public permissions if you allow unauthenticated access. Attempting to copy a non-existent file out of our Rush CI caching bucket with aws-cli results in a 404.

So that kills my only thought as to what might be happening here :thinking: 

It's definitely inconsistent, except for the times it's consistent. What I mean by that is, 
1. it doesn't affect the same packages consistently
2. but I have gotten it into a state where running `rush build`, getting the warning printed for a package, ctrl+c, run build again, warning reliably appears
3. but later that package no longer gives the warning

Which is what lead me to believe it might be related to cache misses. Sorry I can't provide better info at this stage, I haven't been able to figure out a pattern to the warnings.

**Comment by UberMouse** [comment]
Hmm. I'm wondering if my s3 credentials were not actually configured correctly and it was just non-obvious that was the problem. Since they were configured correctly previously and I haven't touched them since then. But that problem was being masked by locally cached builds or something. I'm not sure. Would explain why once a package started emitting that warning, killing the build before it finished would cause it emit the warning again next build, since it hadn't writen the result to the build cache.

Anyway, I've re-run `rush update-cloud-credentials` just in case and I will close the issue if the warning doesn't crop up again.

**Comment by UberMouse** [comment]
Now that a few days have passed I think that warning was accurate. I guess my caching just wasn't working before the Rush update and I never noticed 🤷 

The warning is a bit of an odd experience because it appears and goes away "randomly", at least it feels random. And you get messages about the build being successfully restored from cache. But that means the local cache. So it wasn't obvious the warning was correct.

Not sure if it's feasible with the way it's architected, but IMO a much better warning would be one emitted by `rush build` when you have remote build caching configured, but you don't have cloud credentials configured. That way it is reliable since every invocation will get it, instead of appearing randomly and disappearing randomly.

**Comment by calbearox** [comment]
Ok
________________________________
