### ISSUE TITLE
[rush] Add `allowedProjectTags` and project `tags` to schema

### ISSUE THREAD

**Issue by MrLowkos** [microsoft/rushstack#3355]
## Summary

In my `rush.json`, `allowedProjectTags` and project `tag` are flagged as "Property is not allowed".
These keys seem to be missing from the schema [https://developer.microsoft.com/json-schemas/rush/v5/rush.schema.json](https://developer.microsoft.com/json-schemas/rush/v5/rush.schema.json)

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.66.2 |
| `rushVersion` from rush.json? | 5.66.2 |
| `useWorkspaces` from rush.json? | yes |
| Operating system? | Windows |
| Would you consider contributing a PR? | Maybe |
| Node.js version (`node -v`)? | 16.14.2 |

**Comment by iclanton** [comment]
I updated the schemas a few days ago with https://github.com/microsoft/json-schemas/pull/85. I thought deployment of that repo was pretty quick, but I'll try to follow up on Monday.

**Comment by elliot-nelson** [comment]
Closing -- issue fixed.
