### ISSUE TITLE
[rush] How to configure different config file in different env?

### ISSUE THREAD

**Issue by jiangtao** [microsoft/rushstack#3371]
In many cases, we often distinguish between different environments, such as local, cicd, etc. How to configure different rush.json to fit this situation. . Can Rush support specifying different environment configurations？ For example:
- `rush install --config rush.json`
- `rush config rush.dev.json`
- More env files,  sush as `rush.local.json`, `rush.test.json`, `rush.prod.json` 
- Support `rush.config.js` like `.babelrc.js`, developers can change the config file in runtime env. 

## Repro steps

  **Expected result:** 

Rush does not support dynamic configuration of rush.json

  **Actual result:** 

Any of the following dynamic configuration options are expected to be supported.

- `rush install --config rush.json`
- `rush config rush.dev.json`
- More env files,  sush as `rush.local.json`, `rush.test.json`, `rush.prod.json` 
- Support `rush.config.js` like `.babelrc.js`, developers can change the config file in runtime env. 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | Y |
| `rushVersion` from rush.json? | 5.56.0 |
| `useWorkspaces` from rush.json? | Y |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14.17.3 |

**Comment by iclanton** [comment]
Can you give some more information about what you'd like to be different between the environments? `rush.json` contains configuration that generally should stay the same across all environments.

**Comment by jiangtao** [comment]
> Can you give some more information about what you'd like to be different between the environments? `rush.json` contains configuration that generally should stay the same across all environments.

Any of the following dynamic configuration options are expected to be supported.

- `rush install --config rush.json`
- `rush config rush.dev.json`
- More env files,  sush as `rush.local.json`, `rush.test.json`, `rush.prod.json` 
- Support `rush.config.js` like `.babelrc.js`, developers can change the config file in runtime env.

**Comment by elliot-nelson** [comment]
As described, this is a change we are unlikely to make, because `rush.json` is intended to be a coherent source of truth for the contents and configuration of the monorepo. _Individual_ projects in the repo, like applications and services, might have some concept of environments like test and production, but the source code itself does not.

(If there's a specific setting in `rush.json` that you think should be parameterized, let me know, it might be something we could open as a more narrow feature request.)
