### ISSUE TITLE
[rush] Rush Build doesn't consider --max-old-space-size

### ISSUE THREAD

**Issue by davidabap** [microsoft/rushstack#3379]
## Summary
As I my understanding, Rush Build perform the `npm run build` on each app based on the dependency and it should have the same behavior when explicit execute `npm run build` under the app. This issue can be reproduced in the https://github.com/microsoft/rush-example since our real project have the similar usage.

## Repro steps
1. Clone the rush-example repo and change the rushVersion to **5.67.0**.
2. Add new config(**node-options=--max-old-space-size=20**) in your _$HOME_/.npmrc 
3. Run `rush update` and `rush build` under the project, all passed.
4. `cd tools/my-toolchain` and Run `npm run build`, it failed due to memory leak.

![image](https://user-images.githubusercontent.com/25033055/165879862-5132fadf-b5bd-4473-8e99-6651d70a05b9.png)

  **Expected result:** 
Rush Build should have the same result when manually trigger `npm run build` under the app, then the rush build can managed by the `--max-old-space-size`

  **Actual result:** 
Rush Build doesn't consider --max-old-space-size if the build script direct invoke the bin, but I find the  --max-old-space-size will be consider during Rush Build if your build sciprt write like `"build": "npm run something"`

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.67.0 |
| `rushVersion` from rush.json? | 5.67.0 |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  Mac |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? | 16.13.1 |

**Comment by dmichon-msft** [comment]
The environment variable `NODE_OPTIONS` gets propagated, so you can set the `--max-old-space-size=4096` (or whatever) value there, or else the other recommended path is to write it directly in the `package.json` `scripts` value, e.g. `"build": "node --max-old-space-size=4096 path/to/script.js"`.

Rush as configured only interacts with `.npmrc` for the purposes of running package installation, and not during execution. There are a number of behaviors of `npm run` that are not copied by the Rush execution logic, such as setting environment variables from `package.json` or from the CLI parser.
