### ISSUE TITLE
[rush] Customize "node version not supported" message

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/rushstack#3405]
## Summary

Rush will print an error if you use a node version that is not supported (defined in your `rush.json`) file.

If this message were customizable, you could add additional information for your developers.  For example, if part of your standard monorepo setup is installing NVM, you could add a blurb at the bottom of the message:

```console
> rush list


Rush Multi-Project Build Tool 5.67.0 - https://rushjs.io
Node.js version is 14.18.1 (LTS

ERROR: Your dev environment is running Node.js version v14.18.1 which does not meet the requirements for building this repository.  (The rush.json configuration requires
nodeSupportedVersionRange=">=14.19.0 <15.0.0 || >=16.13.0 <17.0.0")

To fix this issue, run:

    nvm install 14.19.0
    nvm alias default 14.19.0
```

## Details

The current message is defined at https://github.com/microsoft/rushstack/blob/69f2d97f3d150ae736e5bef2f16f5a8d854baa35/libraries/rush-lib/src/api/RushConfiguration.ts#L535.

The message is not a fixed string, so perhaps the "customization" should just be an additional message at the end and not wholesale replacement.  Or, perhaps, the message by default could be a string with interpolated data, e.g.:

```json
{
    "nodeVersionUnsupportedMessage": "Your dev environment is running Node.js version {{current_version}} which does not meet the requirements for building this repository.  (The rush.json configuration requires nodeSupportedVersionRange=\"{{supported_version}}\")"
}
```

(I don't recall us using interpolated strings like this anywhere in Rush, but I have seen it in other tools.)

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.67.0 |
| `rushVersion` from rush.json? | 5.67.0 |
| `useWorkspaces` from rush.json? | yes |
| Operating system? | macos |
| Would you consider contributing a PR? | yes |
| Node.js version (`node -v`)? | 14.18.0 |

**Comment by ahalf-yuan** [comment]
The customized message seems to make it user-friendly. But how does the 'customization ' part work? 
configure it in the `rush.json` file?

**Comment by robertf224** [comment]
+1 on this, snippet from our README below

### Upgrading Node
Occasionally we'll need to update the version of Node we use.  You'll know you're on the wrong version when Rush gives you an error like:
```
ERROR: Your dev environment is running Node.js version vX.X.X which does not meet the requirements for building this repository.
```

When you need to upgrade, run the following:
```bash
nvm install 16.13.0
nvm alias default 16.13.0
# You need to re-install rush for this version of Node
npm install -g @microsoft/rush
rush purge
rush install
```
