### ISSUE TITLE
[heft] heft-sass-plugin TypingsGenerator API use deprecated

### ISSUE THREAD

**Issue by halfnibble** [microsoft/rushstack#3417]
## Summary

Update heft-sass-plugin to use `globsToIgnore` instead of `filesToIgnore`
https://github.com/microsoft/rushstack/blob/main/heft-plugins/heft-sass-plugin/src/SassTypingsGenerator.ts#L105

## Repro steps

1. Install latest heft-sass-plugin.
2. Configure settings: `"excludeFiles"` in sass.json
3. Run.

Generates error:
```
Error: The filesToIgnore option is no longer supported. Please use globsToIgnore instead.
 ELIFECYCLE  Command failed with exit code 1.
```

  **Expected result:** No error generated

  **Actual result:** Above error generated

## Details
Maybe update the build test to test all config options. 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.42.4 |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 12.22.1 |

**Comment by iclanton** [comment]
Oops. @halfnibble - would you mind putting together a fix?

**Comment by halfnibble** [comment]
Sure thing. I will try to get something up for review today.

**Comment by aliatsis** [comment]
@halfnibble @iclanton My team ran into this recently and it's blocking our upgrade to the latest version of rush.
Was there any attempt at a solution here yet?

**Comment by gerwolfe** [comment]
@halfnibble @iclanton This is a blocker for upgrading to the latest version of rush. Any movement on a solution?

**Comment by octogonz** [comment]
Reading this issue, I'm not sure I understand what is being proposed. Could you give a realistic example of a case where the plugin doesn't work, and what is the proposed change in behavior (or new setting)? Thanks!

**Comment by halfnibble** [comment]
I think this config options needs to be updated to use the new `globsToIgnore` config settings:
https://github.com/microsoft/rushstack/blob/main/heft-plugins/heft-sass-plugin/src/SassProcessor.ts#L134C7-L134C20

Here is the new setting:
https://github.com/microsoft/rushstack/blob/main/libraries/typings-generator/src/TypingsGenerator.ts#L26

I would provide a PR, but my current employer requires preauthorization for contributing to open source. :(

**Comment by octogonz** [comment]
Thanks @iclanton for fixing this in PR #4240!
