### ISSUE TITLE
[rush] "rush update" retries when there are unmet peer dependencies

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/rushstack#3420]
## Summary

If you run `rush update` and you cannot complete the install due to unmet peer dependencies, Rush keeps "retrying" the pnpm install even though there is no chance it will work again. This behavior is a little confusing.

## Repro steps

Try adding a package to a project in the monorepo that has a peer dependency.  For example:

```console
$ rush add -p @aws-sdk/lib-storage
.
.
.
.
Progress: resolved 1639, reused 1637, downloaded 2, added 2, done
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

../../acme/dynamite
└─┬ @aws-sdk/lib-storage
  └── ✕ missing peer @aws-sdk/abort-controller@^3.0.0
Peer dependencies that should be installed:
  @aws-sdk/abort-controller@^3.0.0

The command failed:
pnpm install --store pnpm-store --no-prefer-frozen-lockfile --strict-peer-dependencies --recursive --link-workspace-packages false
ERROR: Error: The command failed with exit code 1

Trying again (attempt #2)...
```

## Details

It would be nice if certain errors (like unmet peer dependencies) would cause rush update to fail immediately, instead of being treated like a transient error.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.67.0 |
| `rushVersion` from rush.json? | 5.67.0 |
| `useWorkspaces` from rush.json? | Y |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14 |

**Comment by iclanton** [comment]
Yeah that would be useful. I'm pretty sure Rush retries installation if the package manager exits with any nonzero exit code. Do you know if PNPM exits with something special for unmet peers? If it doesn't, we'll have to detect this by looking at its console output.

**Comment by elliot-nelson** [comment]
Unfortunately it looks like it doesn't:

```console
❯ pnpm install --strict-peer-dependencies @aws-sdk/lib-storage
...
dependencies:
+ @aws-sdk/lib-storage 3.88.0

 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @aws-sdk/lib-storage
  ├── ✕ missing peer @aws-sdk/abort-controller@^3.0.0
  └── ✕ missing peer @aws-sdk/client-s3@^3.0.0
Peer dependencies that should be installed:
  @aws-sdk/abort-controller@^3.0.0  @aws-sdk/client-s3@^3.0.0         

Progress: resolved 12, reused 12, downloaded 0, added 0

~/dev/test-23
❯ echo $?
1
```

(Although, this might be something we could request from pnpm, I've always liked error-specific exit codes.)

**Comment by elliot-nelson** [comment]
In https://github.com/pnpm/pnpm/issues/4747#issuecomment-1128765790, Zoltan mentioned:

> I am not sure what type of error could be fixed by retrying. pnpm already retries in those cases.

The code that does this is https://github.com/microsoft/rushstack/blob/c7aef037ee57dbb0892b2882c9d8404cc51ce0fc/libraries/rush-lib/src/logic/installManager/RushInstallManager.ts#L503, which is agnostic (npm vs yarn vs pnpm).  So, it's _possible_ that we never really intended to "retry" pnpm install commands at all?

I'm curious what pnpm error code we believe would be intermittent/retryable.

**Comment by elliot-nelson** [comment]
Fixed by https://github.com/microsoft/rushstack/pull/3495 -- since the default max retries is 1, unless the maintainers have configured the retries higher, only a single rush update pass should happen.
