### ISSUE TITLE
[rush] build-cache local-only no cache folder generated

### ISSUE THREAD

**Issue by Humb3l** [microsoft/rushstack#3456]
Hey,
I'm trying to cache my builds with the rush build cache. I configured the build-cache.json and the rush-project.json, but he never generates the cache folder after building my libs (```rush build ```).

The build-cache.json looks like the following:
```
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/build-cache.schema.json",
  "buildCacheEnabled": true,
  "cacheProvider": "local-only",
```
<project>/config/rush-project.json:
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/rush-project.schema.json",
  "operationSettings": [  // formerly phaseOptions
    {
      "operationName": "build",
      "disableBuildCacheForOperation": false,
      "outputFolderNames": ["dist"]
    }
  ]
}
```
## Repro steps

1. Setup a Project with rush 
2. create a project within
3. enable build caching
4. create a rush-project.json "<project>/config/rush-project.json"
5. Run the ```rush build```command two times (```rush rebuild``` does not work either ) 

  **Expected result:** There is a cache folder within ```common/temp```
  **Actual result:** There is no cache folder

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.69 |
| `rushVersion` from rush.json? | 5.69 |
| `useWorkspaces` from rush.json? | yes |
| Operating system? | Mac |
| Node.js version (`node -v`)? | 16.14.2 |

**Comment by iclanton** [comment]
>\4. create a rush-project.json "/config/rush-project.json"

Is that file under the project folder, or under the repo root?

**Comment by Humb3l** [comment]
Could someone recreate this issue? I still couldn't fix this :/

**Comment by dlannoye** [comment]
I was seeing something similar on rush v5.63, but just updated to v5.74 and I am now seeing the local-only caching work as expected.

**Comment by Humb3l** [comment]
@dlannoye It worked thanks :).
