### ISSUE TITLE
[rush] LockFile does not handle two processes locking in same millisecond

### ISSUE THREAD

**Issue by benjamind** [microsoft/rushstack#3475]
## Summary

If you try and acquire a LockFile from two processes within the same millisecond, then both processes acquire a dirty lock as they see each others lockfiles as stale.

## Repro steps

Will file PR with test case.

## Details

In [this block](https://github.com/microsoft/rushstack/blob/main/libraries/node-core-library/src/LockFile.ts#L339) we do not test for the case of `smallestBirthTimeMs === otherBirthtimeMs` which causes both processes to acquire valid dirty locks.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  5.55.0 |
| `rushVersion` from rush.json? | 5.55.0 |
| `useWorkspaces` from rush.json? | yes |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 16 |

**Comment by octogonz** [comment]
🚀 Published as Rush  5.77.1
