### ISSUE TITLE
[rush] rush auto hoist some packages 

### ISSUE THREAD

**Issue by sanmmm** [microsoft/rushstack#3535]
## Summary
Normally all packages should be installed into **common/temp/node_modules/.pnpm/,** but now some packages were installed or symlinked into **common/temp/node_modules**. This caused some phantom dependency issues. Is it a rush problem or pnpm problem ?

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.75.0 |
| `rushVersion` from rush.json? | 5.52.0 |
| `useWorkspaces` from rush.json? | no |
| Operating system? | Windows |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v14.17.5 |

**Comment by dmichon-msft** [comment]
Packages in common/temp/node_modules come from the `public-hoist-pattern` setting in .npmrc (which as a default non-empty value)
Packages in common/temp/node_modules/.pnpm/node_modules come from the `hoist-pattern` setting in .npmrc (which defaults to `*`)
See https://pnpm.io/npmrc#dependency-hoisting-settings

**Comment by iclanton** [comment]
We should probably update our templates.

**Comment by octogonz** [comment]
This is superseded by https://github.com/microsoft/rushstack/issues/3542
