### ISSUE TITLE
[eslint-config] Need update for dependencies of eslint-config

### ISSUE THREAD

**Issue by paperbackdragon** [microsoft/rushstack#3550]
## Summary
In my project we're using TypeScript 4.7.4 and also using the `@rushstack/eslint-config` package, but when I run linting, I get this warning:

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.7.0

YOUR TYPESCRIPT VERSION: 4.7.4

Please only submit bug reports when using the officially supported version.

=============
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/eslint-config` version? | 2.6.2 |
| Operating system? | Windows |
| Would you consider contributing a PR? | No |
| TypeScript compiler version? | 4.7.4 |
| Node.js version (`node -v`)? | 16.9.1 |

**Comment by iclanton** [comment]
Looks like we just need to pull TS 4.7 into this repo and fix up warnings and issues.

**Comment by BPapp-MS** [comment]
PR to update is here: https://github.com/microsoft/rushstack/pull/3565
