### ISSUE TITLE
[rush] proposal. Re-focus back on yarn or npm (without losing focus on PNPM)

### ISSUE THREAD

**Issue by Jabher** [microsoft/rushstack#3551]
PNPM is great project but for developers in Russia or Belarus it is a significant risk to use it: https://news.ycombinator.com/item?id=30921103.

I totally understand the author and feel bad about everything happening, but I have team members who are working from this 2 countries (and other CIS countries) for various reasons - from issues with getting international passport after being forced to serve years ago (and forced into getting so-called secrecy form, which bans you from leaving the country for 10+ years) to parents who require medical attention, so people can only leave country knowing they will make their parents die slowly, as no one will take care of them (as they literally fight for medical supplies every week or two, driving all around the town in search of deficit drugs).

I'm big fan of Rush (which is significantly ahead all other solutions) but PNPM is risk for our team now, and yarn/npm solutions are problematic to use due to multiple minor bugs in everyday use, so I honestly have no idea what to do - migrate to lerna/nx/turporepo, and write ton of replacement code on our own? Wait for something else to happen and resolve the case? No idea. Just very sad - not about rush itself, of course.

**Comment by iclanton** [comment]
I'm certainly not opposed. We pivoted away from keeping NPM because of an increasing set of bugs that we weren't able to work around, and neither NPM nor Yarn (without Yarn PnP) supported the same level of strict dependency sandboxing that PNPM supports. We haven't looked into either in a few years, so NPM's stability may have improved, but if it hasn't, it'd be probably more worthwhile to focus on Yarn.

@Jabher - Would you/your team be interested in working on this?

**Comment by octogonz** [comment]
Isn't it only the PNPM website that is blocked? The notice seems to indicate that developers can still install the package from `npmjs.com` and it should still function correctly. Also, the website content is stored on GitHub.

**Comment by Jabher** [comment]
> I'm certainly not opposed. We pivoted away from keeping NPM because of an increasing set of bugs that we weren't able to work around, and neither NPM nor Yarn (without Yarn PnP) supported the same level of strict dependency sandboxing that PNPM supports. We haven't looked into either in a few years, so NPM's stability may have improved, but if it hasn't, it'd be probably more worthwhile to focus on Yarn.
> 
> @Jabher - Would you/your team be interested in working on this?

I personally would be happy to contribute again (if I have a time) but sadly I'm afraid I will not be able to contribute in full.

However, my team has limited capacity :(

> Isn't it only the PNPM website that is blocked? The notice seems to indicate that developers can still install the package from npmjs.com and it should still function correctly. Also, the website content is stored on GitHub.

This is correct ATM but at march there was a lot of cases like this https://portswigger.net/daily-swig/npm-maintainer-targets-russian-users-with-data-wiping-protestware. So in terms of risk management even version-lock is not an option - as long as there is no security audit on that version. 

However, Zoltan (author of PNPM) is discussing about NPM registry lock in terms of not "this is not we want" or "this will break ton of things" but "we have no control on that". https://twitter.com/ZoltanKochan/status/1498310500836380683

For me it sounds like "if we will find more ways to make issues to russian IPs we will probably apply them too" so that's a risk - even for ones who already left the country, as they are sometimes using private or public VPNs to access gov-services - even simply for getting documents for other residency

**Comment by octogonz** [comment]
I understand your concerns. But we must consider Zoltan's actual words/actions, versus what he *didn't* say or *hypothetically* might do. Sometimes politics can be difficult to separate from our work life. Individuals are free to express their perspectives and opinions, but as a community, Rush's focus is on solving technology problems. They are:

- **Ability to use PNPM within a blocked IP network:**  As of today, PNPM can be installed without a VPN. It functions correctly. It is possible to access the documentation via GitHub.
- **Better Rush support for Yarn/NPM package managers:** I agree with Ian that Yarn is better aligned with Rush's requirements, however it would be great to improve support for both. This is not a priority for the corporate monorepos that are operated by the Rush maintainers, but we would be happy to work with anyone who wants to make those improvements.

There's already an existing GitHub issue tracking better NPM support: [#886](https://t.co/SJJJdyWVjO)

And a couple issues for improving Yarn support: [#1553](https://t.co/FWkIVKnTj1) and [#1748](https://t.co/Yhmci6gjRf)

So maybe the concrete technical aspects of this request are already being tracked sufficiently?

**Comment by Jabher** [comment]
You are right about trackers, thank you.

Zero offence is intended, just risk management - that's why I came with this issue.

**Comment by octogonz** [comment]
Thanks for understanding. It's a difficult situation. 🙁
