### ISSUE TITLE
[rush] @microsoft/rush install failed

### ISSUE THREAD

**Issue by cccRaim** [microsoft/rushstack#3556]
## Repro steps

  **Expected result:** 
install success

  **Actual result:** 
install failed

## Details

When I use `npm i -g @microsoft/rush`, got install error.
```bash
npm WARN deprecated read-package-tree@5.1.6: The functionality that this package provided is now in @npmcli/arborist
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @rushstack/rush-amazon-s3-build-cache-plugin@5.75.0-pr3481.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@microsoft/rush-lib'
npm ERR! notarget
```

maybe package update is missing?
## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? | Mac |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 14.19.3 |

**Comment by octogonz** [comment]
Thanks for reporting this! The dist tag was incorrectly assigned by a publishing job. We're working on fixing it.

**Comment by octogonz** [comment]
✅ Confirmed that it is fixed now

**Comment by cccRaim** [comment]
@octogonz 
Hey, I think the key point is dependence chain.  
`@microsoft/rush`@
5.75.0-pr3481.0 -> `@microsoft/rush-lib`@5.75.0-pr3481.0 -> `@rushstack/rush-azure-storage-build-cache-plugin`@
5.75.0-pr3481.0.
I check the (versions)[https://www.npmjs.com/package/@rushstack/rush-azure-storage-build-cache-plugin], there is no `
5.75.0-pr3481.0` in `@rushstack/rush-azure-storage-build-cache-plugin`.
The error is still exist.

**Comment by cccRaim** [comment]
The version is rollback now, solved.
