### ISSUE TITLE
[api-extractor] extends tokens don't include closing `>` for generic types

### ISSUE THREAD

**Issue by suneettipirneni** [microsoft/rushstack#3561]
## Summary

When using api-extractor whenever a class that extends a generic IE `class A extends B<SomeGeneric>`. The spanned tokens of the extend type will result in the string `B<SomeGeneric`. The full generic parameter including the closing bracket should be included.

## Repro steps

An example of a reproduction is available on the rush stack documentation site for [IPrecompileSubstage](https://api.rushstack.io/pages/heft.iprecompilesubstage/#iprecompilesubstage-interface).

  **Expected result:** 

Extends type excerpt should be `IBuildSubstage<BuildSubstageHooksBase>`

  **Actual result:** 

Extends type is `IBuildSubstage<BuildSubstageHooksBase`

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? | 7.28.6 |
| Operating system? | Mac |
| API Extractor scenario? |  |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | 4.7.4 |
| Node.js version (`node -v`)? | 16.13.2 |

**Comment by octogonz** [comment]
CC @zelliott @mrshllstock

Could this be a regression from the recent work in #3317 and 3354 ?

**Comment by zelliott** [comment]
Yep, I think probably #3317.

**Comment by octogonz** [comment]
@suneettipirneni Does your issue repro with `@microsoft/api-extractor` 7.20.0?

**Comment by zelliott** [comment]
I should have a PR out fixing this hopefully tomorrow.

**Comment by suneettipirneni** [comment]
> > Yep, I think probably #3317.
> 
> @suneettipirneni Does your issue repro with `@microsoft/api-extractor` 7.20.0?

@octogonz No, it seems to work as expected on version 7.20.0.
