### ISSUE TITLE
[rush] Update to pnpm latest version 

### ISSUE THREAD

**Issue by TheLarkInn** [microsoft/rushstack#3567]
## Summary
Currently we are running pnpm 6.29.1 inside rushstack. We should update to the latest version (v7.8.0) of .pnpm to take advantage of new features, bugfixes, and performance enhancements. https://github.com/pnpm/pnpm/releases/tag/v7.0.0.

The more people using it, the more we can report back any bugs or peculiarities to @zkochan and friends at pnpm anyways. 

Considerations: it looks that Node 12 is not supported in latest pnpm so we can't default it to customers but we can use it on the repo ourselves.

**Comment by iclanton** [comment]
It may be time to drop official support for Node 12.

**Comment by octogonz** [comment]
Before upgrading, we ideally should first make the Rush PR that sets `ignore-compatibility-db=true`.  (See 
https://github.com/pnpm/pnpm/issues/5132 for details)

**Comment by octogonz** [comment]
Here's the PR: https://github.com/microsoft/rushstack/pull/3575
