### ISSUE TITLE
[load-themed-styles] Error in function shouldUseCssText 

### ISSUE THREAD

**Issue by olemp** [microsoft/rushstack#359]
There's a error in @microsoft\load-themed-styles.

The function `shouldUseCssText()` is used to determine wether `registerStyles()` or `registerStylesIE()` is used to register styles. According to `shouldUseCssText()`, `registerStylesIE()` should be used for IE 9 and below, but it also kicks in for IE 10 and IE 11 (which default to document mode IE 10).

Could `shouldUseCssText()` be written in another way?

**Comment by iclanton** [comment]
@dzearing - can you take a look at this?

**Comment by dzearing** [comment]
@jijizz This may be an optimization we could make. We really don't support IE10 or below any more, so removing this code would probably both speed up the registration and reduce bundle size.

**Comment by iclanton** [comment]
This issue is stale at this point. Closing. If this is still a problem, please open a new issue.
