### ISSUE TITLE
[rush] incorrect Node.js version detection

### ISSUE THREAD

**Issue by gomain** [microsoft/rushstack#3613]
## Summary

Any rush command fails, because of node.js version validation.
```bash
$ node --version
v14.20.0

$ rush --debug update


Rush Multi-Project Build Tool 5.56.0 - https://rushjs.io
Node.js version is 16.16.0 (LTS)



ERROR: Your dev environment is running Node.js version v16.16.0 which does not meet the requirements for building this repository.  (The rush.json configuration requires nodeSupportedVersionRange=">=12.13.0 <13.0.0 || >=14.15.0 <15.0.0")
```

## Repro steps

Using Nixos:

1. Enter a nix-shell where nodejs is v16.16.0.
2. Then enter another nix-shell where nodejs is v14.20.0
3. Run any rush command.

## Details

Rush is not detecting nodejs verison by actually running `node --version`.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  5.76.1 |
| `rushVersion` from rush.json? | 5.56.0 |
| `useWorkspaces` from rush.json? | Yes |
| Operating system? | Linux:Nixos |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 16.16.0 then 14.20.0 |

**Comment by iclanton** [comment]
How is Rush installed globally? What is the contents of the file at the path that gets printed when you run `which rush`?

My suspicion is that the bin script for Rush is pointing at a different version of Node.

**Comment by gomain** [comment]
Rush is globally installed via `nix-shell` & `node2nix`.  At the time of running `node2nix`, node version is specified (as 16). This somehow constraints the node versions when spawned by `rush`. Regardless of the node version available in the user's shell.

**Comment by ekawatani** [comment]
I'm also getting this. In my case, I used `[devbox](https://www.jetpack.io/devbox/)` to create a development shell which specifies node and rush to be globally installed in the shell.

In my config for devbox, I initially specified the latest version of node, but it was not compatible, so I re-created the shell with older version of node, but it's still pointing to the wrong node version.

**Comment by ekawatani** [comment]
@iclanton When I do `which rush`, I get this:

> /home/eigo/projects/<my-user-name>/bloqs/.devbox/nix/profile/default/bin/rush

**Comment by gomain** [comment]
nix ensures runtime dependencies. executable node packages (such as rush) executables aren't plain scripts run by the node available at the shell, but a node specified by its derivative. this is particularly true when derivatives were generated via node2nix. you could install rush without installing node and it will still run. this is not a bug. you need tobe explicit of what you want.

**Comment by ekawatani** [comment]
@gomain  Got it. That's a good point. I'm still fairly new to nix, but I understand what you mean.

@iclanton  I suppose this ticket can be closed since it's not a problem with rush.
