### ISSUE TITLE
[api-documenter] Links between packages are not rendered

### ISSUE THREAD

**Issue by sranka** [microsoft/rushstack#3624]
## Summary
Having JSON files generated from monorepo packages, when I run `api-documenter`, the markdown output does not contain a lot of links between these monorepo packages.

## Repro steps

```bash
git clone git@github.com:influxdata/influxdb-client-js.git
cd influxdb-client-js
yarn
yarn workspaces run apidoc:extract
yarn api-documenter markdown -i docs -o docs/dist
```
The generated markdown files are now missing a lot of links between monorepo packages, For example, open `docs/dist/influxdb-client-apis.authorizationsapi._constructor_.md`, it contains:

|  Parameter | Type | Description |
|  --- | --- | --- |
|  influxDB | InfluxDB | an instance that knows how to communicate with InfluxDB server |

**Expected result:** 

The `InfluxDB` type should be a link.

**Actual result:** 

The `InfluxDB` type is not a link. The associated api-extractor input file `docs/influxdb-client-apis.api.json` contains a reference
```json
                {
                  "kind": "Reference",
                  "text": "InfluxDB",
                  "canonicalReference": "@influxdata/influxdb-client!~InfluxDB:class"
                }
```

`@influxdata/influxdb-client!~InfluxDB:class` is not present in `docs/influxdb-client.api.json` but `@influxdata/influxdb-client!InfluxDB:class` is!

## Details

There are 1376 occurrences of the same pattern in the `influxdb-client-js` project. I created a script that repairs these references https://github.com/influxdata/influxdb-client-js/pull/567 , changing `!~` to `!` in a reference is a workaround ... all links are then rendered properly in the markdown files.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? |  7.29.3 |
| `@microsoft/api-documenter` version? | 7.19.5 |
| Operating system? | Linux |
| Documentation target? | Markdown |
| Would you consider contributing a PR? | I does not seem simple to me, YES after an advice |
| TypeScript compiler version? | 4.7 and 4.8 |
| Node.js version (`node -v`)? | 14, 16 - does not matter |

**Comment by sranka** [comment]
It is fixed since `@microsoft/api-extractor:7.31.0`.

**Comment by zelliott** [comment]
@sranka Can we close this issue then?

**Comment by sranka** [comment]
I double-checked it.
