### ISSUE TITLE
[rushstack-repo] Open github discussion(s) boards

### ISSUE THREAD

**Issue by jessekrubin** [microsoft/rushstack#3632]
I quite like github discussion(s) as they're like github issues but don't clog up the gh issues.

I think rushstack and rush-users would gain a lot from having a place to openly ponder/discuss/pontificate on rush et al.

**Comment by iclanton** [comment]
We generally use Zulip (https://rushstack.zulipchat.com/) for general discussions. Check that out?

**Comment by jessekrubin** [comment]
@iclanton I have and I regularly bother @octogonz on there, and I think that I have even messaged you saying something along the lines of "what up clanton!?"

**My 2 cents:** I like github discussions and I think it makes sense to have discussions open seeing as one of the best rushstack resources is the rushstack repo itself. food for thought!
