### ISSUE TITLE
[rush] Allow having root level defined pnpm workspaces (as in `${REPO_ROOT}/pnpm-lock.yaml`)

### ISSUE THREAD

**Issue by jessekrubin** [microsoft/rushstack#3633]
I 100% understand why rush hides things away in `comon/temp` but is it really necessary if I have all my deps checked by `rush check`? and if I am using pnpm?

Allowing for this (specifically with pnpm) would be a huge boon for people to consider using rush who are already using pnpm as well as for people using rush who are not using pnpm.

I also think this would be a nicer way of using rush + pnpm (I think `rush pnpm` is quite nice and handy but absolutely not ergonomic)

**Comment by iclanton** [comment]
Rush does a bunch of minor fixups on pnpm behind the scenes, which is the motivation for abstracting pnpm's operations away. This also allows a repo maintainer to specify the pnpm version in `rush.json`, allowing users of the repo to only need to globally install one tool (Rush).

`rush-pnpm` is intentionally designed around those considerations and to be an advanced feature that most developers in a repo shouldn't need to use. If Rush allowed manual management of the workspace by a repo maintainer, Rush would lose some important contextual information like the set of external dependencies for each project (which is used in the build cache state tracking).

Manual management of the pnpm workspace makes sense for small teams of more advanced users, but one of Rush's goals is to put rails on the tools to ensure consistent behavior for large teams of developers.

**Comment by jessekrubin** [comment]
@iclanton Thanks for all the info and your detailed response!

What kinds of fix ups are you talking about? I ask as just bc I am quite curious.

**Comment by iclanton** [comment]
At this point, there are no longer any manual tweaks to the pnpm lockfile, but we do generate a custom pnpmfile (here https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/src/logic/pnpm/PnpmfileShim.ts) that is driven by generated JSON files.

**Comment by jessekrubin** [comment]
so does that mean that root-level pnpm lock or workspaces files are a no go?
