### ISSUE TITLE
[rush] Travis CI is sadly not what it was before maybe it should be removed

### ISSUE THREAD

**Issue by Luxcium** [microsoft/rushstack#3646]
## Summary

I suggest that you remove the [Travis CI](https://travis-ci.com/) config file as it is now an expensive product that cost 69$ per month or more...

> January 7, 2021 · Many open-source projects are still using Travis and open-source maintainers are notoriously overworked. Time spent migrating builds is time not spent on other things. Large well-maintained projects will likely quickly transition but for many smaller projects, an abrupt change in a service they depend on is a huge challenge.
― Adam Gordon Bell https://earthly.dev/blog/migrating-from-travis/

## Details

I also opened an [issue (#99)](https://github.com/microsoft/rushstack-websites/issues/99) with the `rushstack-websites` so that it could maybe give examples with other services:

> _Your documentation examples could show how to use Azure DevOps Services CI/CD or other third parties examples, some are suggested by Adam Gordon Bell in the [blog link](https://earthly.dev/blog/migrating-from-travis/) above..._

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.79.0  |
| `rushVersion` from rush.json? | 5.78.1  |
| `useWorkspaces` from rush.json? | true |
| Operating system? | GNU/Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 16.17.1 |

**Comment by iclanton** [comment]
If Travis isn't free for OSS anymore, I agree it should be removed.

We should perhaps replace it with a config file for GitHub Actions.

**Comment by octogonz** [comment]
I agree 👍

**Comment by Luxcium** [comment]
Later in the future maybe add an option to choose between [Azure DevOps](https://azure.microsoft.com/en-us/products/devops/?nav=min)  and [GitHub Actions](https://github.com/features/actions) as both will remain consistent and will not end up like @travis-ci (I am pretty sure you could get a sponsorship LoL)...
