### ISSUE TITLE
[rush] Unable to initiate working in rushstack repo (using "rush update")

### ISSUE THREAD

**Issue by Luxcium** [microsoft/rushstack#3658]
# I feel pretty doomed 

I am trying my best to quickly learn how to use that stack and it seems that I am falling into a deep rabbit hole... I do not really know if my complaints are valuable for you I want it to work for me but at the same time, I want to bring constructive pieces of information about my experience. I hope I did not overlook something obvious as I have opened a few _complaints_ :sweat_smile: _issues_ in the last 2 days.

## Summary
I am getting an error message despite apparently following what it is asked in the error message:
![Screenshot_000001_20220927_213420](https://user-images.githubusercontent.com/42672814/192667325-0f6ac1da-c689-43d2-bce9-e82a18dd7ddc.png)

```log  
❯ git config --local user.name "Benjamin Vincent Kasapoglu"
git config --local user.email "luxcium@neb401.com"
rush update


Rush Multi-Project Build Tool 5.76.1 - https://rushjs.io
Node.js version is 16.17.1 (LTS)


Starting "rush update"

Checking Git policy for this repository.

Hey there!  To keep things tidy, this repo asks you to submit your Git commits using an email like this pattern:

    [^@]+@users\.noreply\.github\.com

...but yours is configured like this:

    Benjamin Vincent Kasapoglu <luxcium@neb401.com>

To fix it, you can use commands like this:

    git config --local user.name "Mr. Example"
    git config --local user.email "example@users.noreply.github.com"

Aborting, so you can go fix your settings.  (Or use --bypass-policy to skip.)
```

## Repro steps

After `gh repo clone microsoft/rushstack; cd rushstack`
did `rush update`

with: 
`git config --get --local user.email`
> ❯ luxcium@neb401.com

`git config --get --local user.name`
> ❯ Benjamin Vincent Kasapoglu

  **Expected result:** 

Starting "rush update"

  **Actual result:** 

Aborting, so [ I ] can go fix [ my ] settings.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.79.0  |
| `rushVersion` from rush.json? | 5.78.1  |
| `useWorkspaces` from rush.json? | true |
| Operating system? | GNU/Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 16.17.1 |

**Comment by iclanton** [comment]
The error message is saying that your email doesn't match the expected pattern (which is `[^@]+@users\.noreply\.github\.com`). If you run `git config --local user.email "luxcium@users.noreply.github.com"` inside the repo, the issue will be resolved.

This repo (https://github.com/microsoft/rushstack) requires that users use their GitHub username pseudo-emails to avoid someone accidentally making a commit and including their personal or work email in the Git history. See docs here: https://rushjs.io/pages/maintainer/setup_policies/#allowedemailregexps-avoiding-private-e-mail-addresses

**Comment by Luxcium** [comment]
oh oops, thanks (I was reading without my eyes sorry)...
