### ISSUE TITLE
[heft] upgrade or add jest 28/29 plugins

### ISSUE THREAD

**Issue by jessekrubin** [microsoft/rushstack#3665]
I usually don't question the pace of the rush repo but at the same time I am irked (might be irrational) by my heft-jest-plugin projects using jest 27.

Now that jest is on v29 I think we (I consider myself a rusher now (even if ya don't)) should aim to not be behind more than one major release. 

_PS: on a semi related note I should really find the time to PR in my tap and vitest heft plugins which (for me and my team) seem to work p well (just gotta clean them up (a bunch)). My team is often using a hybrid version of the heft jest plugin and my messy vitest plugin._

PPS/PSS: I really dislike jest but heft + jest is 🔥 so hats off to everyone involved.

**Comment by iclanton** [comment]
Sounds like a good idea. We'll need to look through the breaking changes both to the runtime and the APIs, but hopefully that won't be too complicated.

**Comment by tomi-bigpi** [comment]
Are there any updates or available timelines regarding updated Jest support? We're running into more and more ESM-only modules which is causing lots of additional workaround work for us to keep tests running as our app evolves.
