### ISSUE TITLE
[rush] `rush pnpm why`  is not implimented/broken. `rush pnpm why` is a feature I would like and think (really know) would be super easy to add/fix

### ISSUE THREAD

**Issue by jessekrubin** [microsoft/rushstack#3700]
Lots o rush repos get big (b/c rush kicks ass and lets you actually write more code instead of ripping your hair out over config files), so I would like to be able to figure out the dep-why of a dep without having to go to the `common/temp` dir and doing `pnpm why -r DEPNAME`; this would be a huge HUGE feature imo. food for thought.

**Comment by dmichon-msft** [comment]
`rush-pnpm why -r DEPNAME`
