### ISSUE TITLE
[lockfile-explorer] Design Note: REST API for file explorer

### ISSUE THREAD

**Issue by william2958** [microsoft/rushstack#3703]
As the client application lockfile-explorer-web does not have access to the file system of the user, and by extension the rush project this cli is working in, the server-side component of the lockfile-explorer will need to provide an API that enables lockfile-explorer-web to query and navigate the directory that this CLI is being run in.

Below is a proposed interface for when the lockfile-explorer is launched in a rush workspace:

GET `localhost:8091/api/lockfile`
Returns a parsed JSON object of the lockfile that is found in `common/config/rush/pnpm-lock.yaml`

GET `localhost:8091/api/pnpmfile`
Returns the raw text of of the `.pnpmfile.cjs` found in the `common/config/rush/.pnpmfile.cjs` file

GET `localhost:8091/api/package-spec?project=@scope/project-a`
Returns the transformed package.json (by the cjs file) for the project specified in the parameters.

GET `localhost:8091/api/package-json?project=@scope/project-a`
Returns the package.json file for the specified project in the rush workspace

GET `localhost:8091/api/projects`
Returns a list of rush projects in the rush workspace in the form:
```
[
  {
    name: "project-a",
    projectFolder: "apps/project-a",
    reviewCategory: "tests"
  },
  ...
]
```
With which the lockfile-explorer-web can further use with the other endpoints above to query more information, such as their respective package.json files or parsed package.json files.

**Comment by octogonz** [comment]
Closing since this is now implemented. 👍
