### ISSUE TITLE
[rush] Proposal: Support custom fields in change files

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/rushstack#3707]
## Summary

As a monorepo maintainer, I would like to:

1. Have the `rush change` tool prompt developers with additional questions, that I can define in Rush configuration.
2. Save the answers to these questions in my monorepo's change files.
3. Save these answers permanently in the `CHANGELOG.json` when change files are consumed.

With this feature, I can ensure metadata about changes is available to other monorepo tooling that I might build. For example: I might want to ask developers what JIRA ticket is involved, and then later, I can scrape the CHANGELOG for structured data about recent tickets, instead of scraping git commit logs.

## Details

I would like to be able to specify (something like) the following in my `rush.json`:

```jsonc
{
  /* Additional, optional configuration options for change files */
  "changes": {
    /* A new, optional array of custom fields */
    "customFields": [
      {
        /* the value that will be saved in the customFields dictionary */
        "name": "jiraTicket",

        /* the message to prompt the user with in rush change */
        "prompt": "Enter JIRA ticket (or N/A):",

        /* an optional regex that the answer must match to be valid */
        "regex": "^(ACM|XSO|PEO)-\d+$|^N/A$",

        /* an optional, customized message if validation fails. defaults to something generic */
        "errorMessage": "Enter the JIRA ticket for this work, or N/A to opt out."

        /* a default value to use if user just presses ENTER. if not specified, this prompt is
            required (the user must provide a value). you can set a default of `null`, if desired,
            which will leave the field out of the customFields dictionary if user does not enter
            a value. */
        // "default": ""

        /* a list of choices the user can select, similar to the existing major/minor/patch prompt.
            not compatible with `regex` option. */
        // "choices": {
        //   [
        //     { "display": "text", "value": "text" }
        //   ]
        // }
      }
    ]
  }
}
```

If I were to provide the above configuration, running `rush change` will consume this config and insert my additional prompts into the `ChangeCommand#_promptForcomments` routine:

```console
@acme/web-portal
? Describe changes, or ENTER if no changes: Users can now choose Forgot Password
? Select the type of change: patch - for changes that do not affect compatibility, e.g. fixing a bug
? Enter JIRA ticket (or N/A): ACM-1209
```

Finally, this data will be saved in the generated change file:

```json
{
  "changes": [
    {
      "comment": "Users can now choose Forgot Password",
      "type": "patch",
      "packageName": "@acme/web-portal",
      "customFields": {
        "jiraTicket": "ACM-1209"
      }
    }
  ],
  "packageName": "@acme/web-portal"
}
```

(The schema for `customFields` is a `Record<string, string>` with no additional requirements -- Rush should not assume these fields exist, and any custom tooling you write should probably not assume they exist either.)

## Alternative proposals

It's very possible, as a monorepo maintainer, that my requirements for a new prompt won't be satisfied by the above list.  Why not?

   - What if I want custom logic that parses my most recent git commit, and if it looks like there's a JIRA ticket in there, it defaults the JIRA prompt. This is a fair bit of javascript I can't shove into config.
   - What if I want `"acm-1209"` to automatically be converted to `"ACM-1209"` (uppercased).
   - What if I want some projects to require the new prompt and others not to.

If any of these are true, I really need to write my own logic. This would be possible if instead we added a rush plugin extension point -- a new `rushSession.registerBeforeRushChangePrompt()` and `rushSession.registerAfterRushChangePrompt()` would take a factory that returns an `IRushChangePrompt` instance; this instance accepts a `(packageName: string, prompt: inquirer.PromptModule, changeInfo: IChangeInfo)` signature and then can take whatever action it chooses (showing prompts, not showing prompts, etc.).

These plugins could accept an IChangeInfo and return a modified IChangeInfo, so they'd have relatively broad powers -- they could add `customFields`, like above, but also rewrite comments or add/remove additional comments. At the end, after all prompts are done, the set of output files are validated via `ChangeFiles.validate` so the basic laws of change files would still need to be kept.

I also like this idea, although it maybe needs a little polishing to be ready for implementation.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
Doing this with a plugin hook is probably the best way to go.

@octogonz - we were talking about working on a design doc for a redesigned versioning/publishing. Did you have a chance to write down any thoughts.

**Comment by elliot-nelson** [comment]
Thanks Ian, I am going to close this for now in favor of #3725.
