### ISSUE TITLE
[rush] Design: transitioning from conventional commits to change files

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/rushstack#3708]
## Summary

In some organizations, there may be an existing strong bias towards _conventional commits_, before they explore monorepos.

Conventional commits are not suitable for a monorepo, and don't meet the baseline requirements for change tracking: a _description_ and _bump level_ of each change, on a _per-project_ basis. However, it's hard work to change course on an already-moving ship, and developers will cling to conventional commits until they are truly familiar with change files.

I have some suggestions on how we could make it easier.

### PROPOSAL 1: Decode most recent git commit

If I have just committed `fix: Don't show error page`, and then I remember to run `rush change`, if it automatically defaults my message to `Don't show error page` and my bump level to `patch`, I don't feel quite as bad about the double-bookkeeping I'm doing.

### PROPOSAL 2: Encode message as a conventional commit

If I run `rush change --commit`, using the brand-new "commit my message" feature in rush change, don't default to the message `rush change` for the resulting git commit -- encode my change as a conventional commit.

For example, if I run `rush change --commit` and enter the message `Don't show error page` with bump level `patch`, rush change should automatically commit with message `fix: Don't show error page`. (If there are multiple projects touched, commit with a multi-line message with projects sorted alphabetically.)

## Goals

The user experience I am working towards is one where I could reasonably add a new git executable, `git-change`, to developer's workflows. `git-changes` = `rush change --commit`, so that:

```
cd myproject
git add .
git changes

# ^
# It's going to prompt me for each project I touched, ask me about my modifications and bump levels,
# and then commit it all using actual conventional commits.
```

```
cd myproject
git add .
git commit -m "chore: do some stuff"

# oops... forgot...
git changes

# ^
# It's going to prompt me for each project I touched, ask me about my modifications and bump levels,
# and then commit it all using a new commit. each prompt will default to "do some stuff" with
# bump level "none".
```

With this workflow, where `git changes` replaces `git commit` in the monorepo, we can pitch that we aren't trying to _replace conventional commits with change files_, we merely want to provide _structured_ conventional commits, by having a tool that validates their inputs, instead of relying on user-formatted text. Some of the initial friction is reduced while developers are getting used to the idea of change files, visible in the pull requests.

## Next steps?

Open to any feedback on above. Both encoding and decoding conventional commits requires a little bit of logic and guesswork, since they are a lossy representation of changes in a monorepo; maybe we could tuck this behavior behind an experimental flag.

Another option would be to have _all of this_ behavior handled by a plugin, perhaps like a plugin described in https://github.com/microsoft/rushstack/issues/3707. The plugin interface would need to be a bit more evolved, though, because I'm not just adding brand new prompts; I'd need to provide defaults for prompts that don't have them, change the logic for generating commit message, and etc. These new features would make for a potentially complicated plugin interface.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? | yes |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
This seems useful. I'd be interested in seeing a draft implementation.

@octogonz - I'm sure you have some ideas here too.

**Comment by elliot-nelson** [comment]
Thanks Ian, I am going to close this for now in favor of #3725.
