### ISSUE TITLE
[heft] heft-sass-plugin use deprecated node-sass

### ISSUE THREAD

**Issue by csobj** [microsoft/rushstack#3716]
## Summary
node-sass is deprecated and no additional sass feature will come.

## Details

node-sass (and libsass) used by heft-sass-plugin has been deprecated and is not compatible with the new css or sass feature. The same kind of PR https://github.com/microsoft/rushstack/issues/1666 was resolved before, but it seems that the code using node-sass is restored when refactoring the rushstack-legacy.

There are 3 sass implementation available for now.

- node-sass: Deprecated. many sass features still are available but nothing new will come.
- dart-sass(sass): It's known as having some performance overhead because it is pure javascript version converted from dart-sass. If the changing log I'd saw is correct one, rushstack-legacy was choose node-sass because of performance issue. the compilation performance might be critical especially for large scaled codebase. so this decision should be respected also.
- sass-embedded: This is javascript wrapper around a native dart executable. Because of it depends Dart, It will be much faster especially for large sass compilations generally, but also have relatively limited platform supports which can install Dart runtime. (Windows, MacOS and Linux)

sass-embedded seems suitable for most users but none of options are perfect.

So maybe giving configurable option is the simpliest and ideal.
Or, We can provide `heft-dart-sass-plugin` or `heft-sass-embedded-plugin` like we did for webpack5.

**Related**
- `Sass plugin should allow to configure the sass transpiler.` https://github.com/microsoft/rushstack/issues/2732 by @halfnibble
- `Adds sass implementation option on heft-sass-plugin` [chat room] by @csobj

[chat room]: https://rushstack.zulipchat.com/#narrow/stream/262522-heft/topic/Adds.20sass.20implementation.20option.20on.20heft-sass-plugin

**Comment by TheLarkInn** [comment]
I agree that the scalability issue with `dart-sass` could be an eventual problem but I believe having the option for `sass-embedded` is a good plug-n-play solution here.

**Comment by iclanton** [comment]
Closing because @csobj did the work to upgrade us to dart-sass in https://github.com/microsoft/rushstack/pull/3717
