### ISSUE TITLE
[rush] What is the recommended way of installing a rush project (which has a cli) globally?

### ISSUE THREAD

**Issue by jessekrubin** [microsoft/rushstack#3720]
I have a small cli app that I would like to install globally. I have faked it for now with an alias.

I am wondering if the rush team has any suggestions for how I should install a rush-project globally? is this possible? I would rather not do a rush-deploy for such a small cli.

**Comment by iclanton** [comment]
Your tool has dependencies on other projects inside your repo, and you don't want to publish those libraries as well? You could list all of those as devDependencies and then webpack all of your local code and mark external dependencies as externals in your webpack config. You'd have to make sure all runtime dependencies are listed in your tool project.

**Comment by jessekrubin** [comment]
Thanks Clayton! 

Ooof. Sounds like I may have to docker it. Cli has native deps that are separate rush projects.
