### ISSUE TITLE
[heft] [feature-request] Expose `findRushJson()` function

### ISSUE THREAD

**Issue by prescience-data** [microsoft/rushstack#3723]
## Summary

In some development tooling packages, we often need to locate the monorepo root directory.

The [findRushJson()](https://github.com/microsoft/rushstack/blob/e35d0671f34d62beff72ef18634c26b99dd0bedf/apps/heft/src/utilities/RushUtilities.ts#L32) utility function achieves this neatly, but is not exported from the main `@rushstack/heft` package.

Currently it can be imported from:

```typescript
import { findRushJsonFolder } from "@rushstack/heft/lib/utilities/RushUtilities"
```
But this seems messy / easy to interpret as "not-intended", so would be awesome to see it exposed at the main `heft` package level!

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.48.7 |
| Operating system? | All |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 18.x.x |

**Comment by D4N14L** [comment]
You should use @microsoft/rush-lib or @microsoft/rush-sdk to access this API. It can be found here: https://github.com/microsoft/rushstack/blob/7968688f988f571554a4cb8953e0e334dba9a2dc/libraries/rush-lib/src/api/RushConfiguration.ts#L693
