### ISSUE TITLE
[heft] Build does not recognize "references" of tsconfig

### ISSUE THREAD

**Issue by StarFishing** [microsoft/rushstack#3755]
---------------------------------------------------------------------->
i can not run `heft build` in my repo

## i have tsconfig.json like below
```
{
  "references": [
    {
      "path": "./tsconfig.config.json"
    }
  ]
}
```
tsconfig.config.json
```
{
  "$schema": "http://json.schemastore.org/tsconfig",

  "compilerOptions": {
    "outDir": "lib",
    "rootDirs": ["src/"],

    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "sourceMap": true,
    "declarationMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strict": true,
    "esModuleInterop": true,
    "types": ["heft-jest", "node"],

    "module": "commonjs",
    "target": "es2017",
    "lib": ["es2017"],
    "composite": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "lib"]
}

```

## Repro steps

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version |0.48.8|
| Operating system? | <Mac  |
| Would you consider contributing a PR?|  No|  
| Node.js version (`node -v`)|v16.17.0|

**Comment by iclanton** [comment]
You need to set the `buildProjectReferences` option in `config/typescript.json` to `true`. Note that if you're using a rig, you'll want your `config/typescript.json` to look like this:

```JSON
{
  "extends": "<rig-package-name>/profiles/<profile-name (or default)>/config/typescript.json",
  "buildProjectReferences": true
}
```

**Comment by StarFishing** [comment]
> 

This doesn't seem to solve my problem. If I use extends, there is no problem with my problem in using references to refer to the scenario of the configuration file.
