### ISSUE TITLE
[api-extractor] Presentation-ready data from API model?

### ISSUE THREAD

**Issue by donmccurdy** [microsoft/rushstack#3772]
## Summary

I'm interested in using the output of API Extractor (i.e. the API model) to generate documentation, but I'd like to handle the rendering myself. The main thing this requires — I think — is a serialization of the API model that is: (1) type safe, (2) compact, (3) distilled down to just the relevant information for a particular class/interface/enum. For example inherited members and their descriptions need to be resolved for child classes, TSDoc tags need to be parsed, and text may be translated or localized. It doesn't seem like the API model is meant to provide that (can't extract the JSON for a specific class and have enough info to display), and I'm expecting I'll need to define my own encoding instead. You can see where I've gotten in experiments so far:

- https://github.com/donmccurdy/greendoc/blob/main/packages/parse/src/types.ts
- https://github.com/donmccurdy/greendoc/blob/main/packages/parse/src/Encoder.ts

From there it's straightforward enough to render the API model with [framework of choice]:

- https://github.com/donmccurdy/greendoc/blob/main/packages/svelte/src/lib/Class.svelte

My question is — does this seem like a reasonable general approach? Do you see anything I'm missing about API Extractor or related projects that would either (a) solve this in a better way, or (b) create problems for me later? I'd like to support integrations for rendering the API model into larger websites built with different frameworks, not just generating static HTML, and API Extractor has been a really helpful foundation for that. Thanks!

## Details

Cross-posted from chat:

- [zulip > #api-extractor > Presentation-ready data from API model?](https://rushstack.zulipchat.com/#narrow/stream/262521-api-extractor/topic/Presentation-ready.20data.20from.20API.20model.3F)
 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? | N/A |
| Operating system? | N/A |
| API Extractor scenario? | docs (.api.json) |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | N/A |
| Node.js version (`node -v`)? | N/A |

**Comment by octogonz** [comment]
I replied to your [Zulip thread](https://rushstack.zulipchat.com/#narrow/stream/262521-api-extractor/topic/Presentation-ready.20data.20from.20API.20model.3F/near/311296885).
