### ISSUE TITLE
[eslint-config]  invoke ESLint separately for each project folder ，but my eslint is not work,why?

### ISSUE THREAD

**Issue by ghost** [microsoft/rushstack#3794]

**Comment by Mr-GaoYu** [comment]
![image](https://user-images.githubusercontent.com/67352005/204785350-5c8dfd41-7d21-4db2-870f-3cb89ee3fa1e.png)
![image](https://user-images.githubusercontent.com/67352005/204785399-4212162b-ab5b-4284-885d-a3039272f440.png)
![image](https://user-images.githubusercontent.com/67352005/204785474-622ece39-1f1e-4683-80b5-388a784d689f.png)

**Comment by elliot-nelson** [comment]
It sounds like you're saying, you've customized the eslint config for your specific project, but the linting doesn't seem to be respecting that.

One thing to check is whether this is a VSCode integration issue, or an eslint issue. If you're using Heft for building, run `heft build` in your project to invoke the linting (or run `eslint` directly in your folder if not). Does this produce the error you expect?

**Comment by iclanton** [comment]
This issue has gotten stale at this point. If this is still a problem, please open a new issue with a repro link.
