### ISSUE TITLE
[rush] rush change -v on shallow checkout is confusing 

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/rushstack#3805]
## Summary

By default, GitHub Actions performs a shallow clone (fetch depth1).

This means it is easy to get caught by an error when running rush change -v in a new pipeline. However, the error message is confusing and doesn't clearly indicate that the fetch depth could be the issue.

## Repro steps

Run rush change -v in a shallow clone.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
What is the error? I guess if there is a Git error during any `rush change` operation, we could look at the fetch depth and then present a more useful error message. Would you be interested in putting that together?

**Comment by elliot-nelson** [comment]
Fixed by #3668 - at the time we didn't have this update, I think it is now much more direct!
