### ISSUE TITLE
[webpack5-module-minifier-plugin] @types/estree is not properly declared as a dependency

### ISSUE THREAD

**Issue by TheLarkInn** [microsoft/rushstack#3844]
## Summary
When you attempt to use this plugin, it fails with TypeScript errors: 

```bash
[typescript] Error: common/temp/node_modules/.pnpm/@rushstack+webpack5-module-minifier-plugin@5.1.40_ryeedturos24uuwfujlvq35jyu/node_modules/@rushstack/webpack5-module-minifier-plugin/dist/webpack5-module-minifier-plugin.d.ts:3:30 - (TS2307) Cannot find module 'estree' or its corresponding type declarations.
```

This is because `@types/estree` is being used in the `@public` interfaces for the plugin, however not declared as a peerDependency/dependency. 

## Repro steps
Use plugin, get TypeScript errors. 

  **Expected result:** 
No TypeScript errors, plugin works.
  **Actual result:** 
TypeScript errors, can't compile with TypeScript.

**Comment by iclanton** [comment]
Want to raise a quick PR to fix this?

**Comment by TheLarkInn** [comment]
Yup just created it to have something to tie the PR to.

**Comment by iclanton** [comment]
It should probably be an optional peerDependency

**Comment by iclanton** [comment]
Or a regular dependency

**Comment by TheLarkInn** [comment]
I can just make a regular dep

**Comment by Faithfinder** [comment]
Sorry about random questions from a passerby, but when does it make sense to make a  `@types` package regular dependency? I thought since types don't exist at runtime, they're always a dev dependency

**Comment by TheLarkInn** [comment]
> Sorry about random questions from a passerby, but when does it make sense to make a `@types` package regular dependency? I thought since types don't exist at runtime, they're always a dev dependency

This exact scenario 😄. For me to even _use_ this plugin, I need the types available when I install it.
