### ISSUE TITLE
might be a potiential issue for eslint-patch

### ISSUE THREAD

**Issue by shc261392** [microsoft/rushstack#3847]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@rushstack/eslint-patch@1.2.0` for the project I'm working on.

Patching the line of code could avoid an exception happens when running `prettier-eslint`. The details and the suggestion to patch this line of code are in this issue https://github.com/idahogurl/vs-code-prettier-eslint/issues/72#issuecomment-1247516987.

Since I'm unfamiliar with the `rushstack/eslint-patch` codebase, I'm not sure if the patch is good for the project. I just want to hightlight that the patch solves an issue that people encountered when using projects that depends on `eslint-patch`.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js b/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js
index a163313..da8acba 100644
--- a/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js
+++ b/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js
@@ -207,7 +207,7 @@ if (!ConfigArrayFactory.__patched) {
                 ModuleResolver.resolve = function (moduleName, relativeToPath) {
                     try {
                         // resolve using ctx.filePath instead of relativeToPath
-                        return originalResolve.call(this, moduleName, ctx.filePath);
+                        return originalResolve.call(this, moduleName, ctx.filePath || relativeToPath);
                     }
                     catch (e) {
                         if (isModuleResolutionError(e)) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by elliot-nelson** [comment]
Thanks for the report! I'll take a look at this.

Note that, if you're on the latest version of Rush, you can use `rush-pnpm patch` instead of `patch-package`. The advantage is that the patches show up in `common/` and are automatically tracked by rush install / rush update (with patch-package it's a bit hairy because Rush doesn't know about the patch, so additions or changes to patches won't correctly trigger rush install and could have confusing behavior).
