### ISSUE TITLE
[rush] Add install-run-rush-pnpm.js script

### ISSUE THREAD

**Issue by stekycz** [microsoft/rushstack#3851]
## Summary

I want to run specific commands using PNPM as the package manager for Rush.js, such as `rush-pnpm audit`, in a continuous integration (CI) environment or any other automated way. To do this, I would like to add a script to [the existing ones](https://github.com/microsoft/rushstack/tree/main/libraries/rush-lib/src/scripts) to execute these commands. I think it should be a simple script similar to `install-run-rushx.js`, as the logic is already there.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.86.0 |
| `rushVersion` from rush.json? | 5.86.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14.21.1 |

**Comment by iclanton** [comment]
Seems useful. Would you be mind putting this together?

**Comment by stekycz** [comment]
@iclanton I have just created the PR
