### ISSUE TITLE
[package-deps-hash] Reenable flakey tests that were temporarily disabled

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#3913]
## Summary

The `main` branch is failing to build due to Jest tests in [package-deps-hash/src/test/getRepoDeps.test.ts](https://github.com/microsoft/rushstack/blob/main/libraries/package-deps-hash/src/test/getRepoDeps.test.ts).

When I tried to debug it, the tests sometimes passed and sometimes failed.  I believe this test is invoking the `git` command line to analyze the working directory, which is maybe the source of the trouble. (?)  

I have temporarily disabled the tests to unblock the build (PR #3914).

The affected code was most recently modified by PR #3756 in November.

## Details

Example build failure: [ADO 10507](https://dev.azure.com/RushStack/GitHubProjects/_build/results?buildId=10507&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=0db80ebc-3da9-5105-8df1-43c3063dee76)

Example log message:

1. In the CI job, it failed with a wrong Jest snapshot
```
  ● getRepoStateAsync › can parse committed files

    expect(received).toMatchSnapshot()

    Snapshot name: `getRepoStateAsync can parse committed files 1`

    - Snapshot  - 8
    + Received  + 1

    - Object {
  ...13 lines omitted...
      32 | }
      33 |
      34 | describe(getRepoRoot.name, () => {

      at checkSnapshot (src/test/getRepoDeps.test.ts:31:27)
      at Object.<anonymous> (src/test/getRepoDeps.test.ts:91:5)
```

2. When I ran `heft test -u` locally, I got this `undefined` key error:
```
    TypeError: Cannot read properties of undefined (reading 'startsWith')

      19 |   const relevantResults: Record<string, string> = {};
      20 |   for (const [key, hash] of results) {
    > 21 |     if (key.startsWith(TEST_PREFIX)) {
         |             ^
      22 |       const partialKey: string = key.slice(TEST_PREFIX.length);
      23 |       for (const filter of FILTERS) {
      24 |         if (partialKey.startsWith(filter)) {

      at checkSnapshot (src/test/getRepoDeps.test.ts:21:13)
      at Object.<anonymous> (src/test/getRepoDeps.test.ts:91:5)
```

3. A different time, `heft test -u --production` succeeded.

4. Another time, `heft test -u --production` succeeded but produced significant diffs for the snapshots. 🤷‍♂️
 
 @dmichon-msft @iclanton

**Comment by dmichon-msft** [comment]
Issue here seems to be related to invoking `git status` while other projects are building. Namely it only repros if running the tests as part of `rush test` rather than running the project in isolation.

**Comment by octogonz** [comment]
Thanks for fixing this!
