### ISSUE TITLE
[heft] Project using heft which depends on another project using heft causes test failures

### ISSUE THREAD

**Issue by 21echoes** [microsoft/rushstack#3922]
## Summary

If I have two projects in a Rush monorepo both using `heft` (and `heft-web-rig`) with default settings, and one project depends on the other project, then the downstream project always fails `heft test`.

## Repro steps

Minimal reproduction repository here: https://github.com/21echoes/rush-heft-jest-repro

1. Make two projects A and B in a rush repo
2. Have them both use vanilla `heft` with `heft-web-rig` (`library` profile)
3. Have B depend on A
5. Run `rush build` to run an initial build (note: this succeeds)
6. Run `rushx test` in B's folder

  **Expected result:** Tests can run

  **Actual result:** Syntax error due to A's output format

```
FAIL (undefined) src/__tests__/index.test.ts (duration: 0.000s, 0 passed, 0 failed)
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /<>/rush-heft-jest-repro/libraries/a/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export var helloWorld = function (name) {
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { helloWorld } from '@my-repo/a';
        | ^
      2 |
      3 | export const helloHelloWorld = (name = 'World'): string => {
      4 | 	return `Hello ${helloWorld(name)}!`;

      at Runtime.createScriptFromCode (../../common/temp/node_modules/.pnpm/jest-runtime@27.5.1/node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/index.ts:1:1)
```

## Details

Project A outputs two formats: ESM (in `lib`) and CommonJS (in `lib-commonjs`). By default, B can and should use ESM, which provides types and other benefits. But `heft-jest` of course uses `jest`, which does not support ESM, so it fails on encountering ESM syntax. Trying to switch A's `main` export to `lib-commonjs` fails, because `heft` does not compile CommonJS with type information, causing builds of B to fail when they cannot find the types

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | Latest (0.49.1) |
| Operating system? | confirmed on Mac and Linux |
| Would you consider contributing a PR? | If I knew how to fix it! |
| Node.js version (`node -v`)? | 16.19.0 |

**Comment by iclanton** [comment]
>Trying to switch A's `main` export to `lib-commonjs` fails, because `heft` does not compile CommonJS with type information, causing builds of B to fail when they cannot find the types

This is the correct solution for the case where you aren't using deep imports. You need to make sure you have the `module`, `main`, and `typings` fields set in `package.json`, pointing to the commonjs, esm, and declarations entrypoints respectively.

If you are using deep imports, you need to add a block that looks like this in your `config/jest.config.json` file:

```
...
  "moduleNameMapper": {
    "<packagename>/lib/(.*)$": "<packageName>/lib-commonjs/$1"
  }
```

This line is telling Jest that any path that it encounters that looks like `<your-package>/lib/<some-path>` should get redirected to `<your-package>/lib-commonjs/<some-path>`.

This should probably get documented better.

**Comment by 21echoes** [comment]
Wonderful! I was hoping it was something this simple. For posterity, here are the settings that made it work (for my non-deep-import case):
```
  "main": "lib-commonjs/index.js",
  "module": "lib/index.js",
  "types": "lib/index.d.ts",
```

**Comment by iclanton** [comment]
Glad you're unblocked!
