### ISSUE TITLE
[rush] how to `rush change` on not published projects

### ISSUE THREAD

**Issue by gomain** [microsoft/rushstack#3929]
## Summary

`rush change` does not detect, and so does not prompt to generate change files, for _new_ projects. I.e. the projects don't exist on the `--target-branch`. This is sort of unintuitive. It makes the implication that: "Coming in to existence does not count as a change."

## Details

This is sort of a special case of change. It does not affect bumping of versions, i.e. the initial version is the _bumped_ version. The workflow could skip the change-type selection and record type as the special type `'init'`.

It does, and should, affect generation of CHANGELOG files.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.79.0 |
| `rushVersion` from rush.json? | 5.79.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | linux-nixos |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v16.18.1 |

**Comment by elliot-nelson** [comment]
In my testing, I didn't find this to be true, my steps were as follows:

1. Create new project `sandbox/abc`
2. Add to `rush.json` with `"shouldPublish": true`
3. Stage (git add) my changes
4. Run `rush change`
5. I was then prompted for change description for project `abc`

I am wondering if one of two things may havehappened:

 - You did not `git add` or `git commit` your changes before running `rush change` (this requirement exists for both new and existing projects, rush change doesn't consider unstaged changes).
 - Your new project did not enable publishing (shouldPublish: true), so it wasn't eligible for change tracking.

**Comment by gomain** [comment]
@elliot-nelson Thank you, I missed the "'shouldPublish" thing.

Could you suggest the workflow for tracking changes on projects/packages that are not (even decided) to be published yet. New projects can be in their infancy state for quite a while and I would want to maintain change logs of pre-published versions. I know this is not exactly is the purpose of CHANGELOG, but for the benefit of internal contributors.

**Comment by iclanton** [comment]
Rush doesn't support tracking changes in projects that aren't published, but if that's an important scenario for you, I'd encourage you to suggest it in this issue https://github.com/microsoft/rushstack/issues/3934
