### ISSUE TITLE
[node-core-library] Moving @types/node to an optional peerDependency causes errors if the version doesn't match

### ISSUE THREAD

**Issue by mikeharder** [microsoft/rushstack#3946]
## Summary
`@types/node` was moved to an optional peerDependency in https://github.com/microsoft/rushstack/pull/3937.  This caused `rush update --full` in our monorepo to fail with the following errors:

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

├─┬ @rush-temp/abort-controller
│ └─┬ @microsoft/api-extractor
│   └─┬ @microsoft/api-extractor-model
│     └─┬ @rushstack/node-core-library
│       └── ✕ unmet peer @types/node@^12.20.24: found 14.18.36
└─┬ @rush-temp/schema-registry-avro
  └─┬ @microsoft/api-extractor
    └─┬ @microsoft/api-extractor-model
      └─┬ @rushstack/node-core-library
        └── ✕ unmet peer @types/node@^12.20.24: found 16.18.11
```

The peer dependency range was upgraded from `^12.20.24` to `^14.18.36` in https://github.com/microsoft/rushstack/pull/3928, but this doesn't change the core issue, since the packages are still incompatible with `@types/node@^16` and `@types/node@^18`.

`pnpm` does not issue warnings/errors for missing optional peer dependencies, but it does issue a warning/error for peer dependencies that a present but a non-matching version.  I'm not sure if this is by design or a bug in `pnpm`, and I've filed https://github.com/pnpm/pnpm/issues/6013 to find out.

If this is by design in `pnpm`, I think Rush should either:

1. Remove `@types/node` as an optional peerDependency
2. Expand the range of allowed versions, from `^14.18.36` to something like `^14.18.36 || ^16.18.11 || ^18.11.18`, to allow all the current Node LTS versions.

## Repro steps

`pnpm add @rushstack/node-core-library@3.55.0 @types/node@16.18.11`

  **Expected result:** 
No warnings or errors.

  **Actual result:** 
```
dependencies:
+ @rushstack/node-core-library 3.55.0
+ @types/node 16.18.11 (18.11.18 is available)

 WARN  Issues with peer dependencies found
.
└─┬ @rushstack/node-core-library 3.55.0
  └── ✕ unmet peer @types/node@^14.18.36: found 16.18.11
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| Package name: | @rushstack/node-core-library |
| Package version? | 3.55.0 |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v18.13.0 |

**Comment by AlexAegis** [comment]
I came here to report this too. It affects `vite` users too as a popular type definition generator uses it:

```sh
...
  └─┬ vite-plugin-dts 1.7.2
    └─┬ @microsoft/api-extractor 7.34.2
      └─┬ @microsoft/api-extractor-model 7.26.2
        └─┬ @rushstack/node-core-library 3.55.0
          └── ✕ unmet peer @types/node@^14.18.36: found 18.11.18
```

**Comment by mikeharder** [comment]
The pnpm maintainer confirmed this is expected behavior.

**Comment by octogonz** [comment]
An experiment from [Zulip: Unmet peer dependencies in @rushstack/node-core-library](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/Unmet.20peer.20dependencies.20in.20.40rushstack.2Fnode-core-library/near/325049326):

https://github.com/microsoft/rush-example/pull/19
