### ISSUE TITLE
[rush] The "rush test" command is undocumented

### ISSUE THREAD

**Issue by pvarga-dni** [microsoft/rushstack#3981]
## Summary

> What were you trying to accomplish?

Run tests 

> What action did you perform that ran into trouble?

Looked at the documentation

> What went wrong?

Found no documentation for the `rush test` command at https://rushjs.io/pages/commands/rush_test/

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.90.0 |
| `rushVersion` from rush.json? | 5.88.2 |
| `useWorkspaces` from rush.json? | `useWorkspaces` not present in `rush.json` |
| Operating system? | Unix |
| Would you consider contributing a PR? | Maybe |
| Node.js version (`node -v`)? | 16.15.0 (old version, I know...) |

**Comment by iclanton** [comment]
`rush test` actually isn't a built-in command. The Rushstack repo, and many other repos, have a [`rush test` custom command](https://github.com/microsoft/rushstack/blob/main/common/config/rush/command-line.json#L20-L27) configured in `common/config/rush/command-line.json`. In this repo, the `rush test` command is a phased command that first runs a project's build (specified as a command in the `_phase:build` `package.json` script) and then runs the project's tests (specified as a command in the `_phase:test` `package.json` script). This is useful for increasing parallelism, but this isn't the only way to configure a `rush test` command.

See docs here on custom commands (https://rushjs.io/pages/maintainer/custom_commands/) and here on phased builds (https://rushjs.io/pages/maintainer/phased_builds/).
