### ISSUE TITLE
[heft] WebpackConfigurationLoader lacks support for .cjs file extensions

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/rushstack#3988]
## Summary
While working to update a rush monorepo to ESM I hit an issue when attempting to update webpack config files to leverage a `.cjs` file extension. For "reasons", we'd prefer to not refactor the entire webpack config system away from require, etc...and instead just append the appropriate file extension.

It seems that [this file](https://github.com/microsoft/rushstack/blob/84ad0baf6f1308549e6ebc031f0cf38a4e46d27b/heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts#L27) has hardcoded strings for valid file names which look specifically for `.js` files.

## Repro steps
I can't share the repository, but initializing the minimum rush repo with support for ESM (module resolution of `nodenext` or `Node16`, file extensions on all import/exports, packages with `"type": "module"`. Configure webpack with a .cjs extension.

## Details
This is currently blocking our migration, so while I think a broader feature for more configuration here might be helpful, ideally this could come in with a quick fix as not being able to use a `.cjs` file extension for webpack is quite prescriptive and "buggy".  

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? | 5.78.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | all |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 16.18.0 |

**Comment by TheLarkInn** [comment]
@iclanton: @chrisdholt suggested this might be our culprit:

https://github.com/microsoft/rushstack/blob/84ad0baf6f1308549e6ebc031f0cf38a4e46d27b/heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts#L27

We could unblock this with a new heft config option, _or_ just try and use autodetect heuristics for more file formats.

**Comment by iclanton** [comment]
It would be easy enough to just check for a set of well-known filenames, and then probably error if multiple are encountered.

@chrisdholt - Would you be willing to put that together?

**Comment by TheLarkInn** [comment]
> It would be easy enough to just check for a set of well-known filenames, and then probably error if multiple are encountered.
> 
> @chrisdholt - Would you be willing to put that together?

If we introduce a config option for the plugin which can override the default config and dev config name, then this could allow scenarios like running multiple configs w/ multiple heft-webpack-plugins!
