### ISSUE TITLE
[rush] Prevent redownloading dependencies after failed update

### ISSUE THREAD

**Issue by xixixao** [microsoft/rushstack#3996]
## Summary

When I try to install a new dependency, but it fails because I'm missing a peer dependency, the pnpm store gets nuked. This means next time I try all packages get redownloaded. This is maddening, as it takes a while to download all packages.

Can we prevent having to redownload all the packages?

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.86.0 |
| `rushVersion` from rush.json? | 5.86.0 |
| `useWorkspaces` from rush.json? | unset |
| Operating system? | Mac |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 16.15.1 |

**Comment by dmichon-msft** [comment]
If you set the environment variable `RUSH_PNPM_STORE_PATH` (see https://rushjs.io/pages/configs/environment_vars/#rush_pnpm_store_path), to somewhere outside of your repository, you can both share it across git repos and also prevent it from being cleared as part of the local cleanup.

**Comment by iclanton** [comment]
The fix has been published as Rush `5.93.2`.
