### ISSUE TITLE
[rush] Build cache in Github actions

### ISSUE THREAD

**Issue by gigara** [microsoft/rushstack#4001]
I've created a new rush cache plugin to save/restore the build cache in Github actions. This can be used in Github actions instead of azure-blob and amazon-s3.
https://www.npmjs.com/package/@gigara/rush-github-action-build-cache-plugin

**Comment by iclanton** [comment]
Very cool! We should make use of that in this repo.

Would you be interested in having your plugin listed in on https://rushjs.io/pages/maintainer/using_rush_plugins/#third-party-plugins?

**Comment by gigara** [comment]
Yes. Please add it to the list.

**Comment by iclanton** [comment]
Your docs should probably mention that you need to set `"cacheProvider"` to `"github-action-build-cache"` in `common/config/rush/build-cache.json`.

**Comment by iclanton** [comment]
There's an issue with local builds. You need to have [`isCacheWriteAllowed`](https://github.com/gigara/rush-github-action-build-cache-plugin/blob/main/src/AbstractGithubCacheProvider.ts#L30-L32) only return `true` if it's in CI mode. You should probably also check for the other environment variables that your action sets.

Your action should probably not do any other repo setup other than for caching (i.e. - it shouldn't set up pnpm or run `rush install`)

**Comment by gigara** [comment]
Updated

**Comment by gigara** [comment]
Created a PR in rushstack-websites: https://github.com/microsoft/rushstack-websites/pull/131

**Comment by iclanton** [comment]
@gigara - Looks like there's one other minor issue: your plugin only works specifically with the `build` command. Can you remove the `associatedCommands` property from the manifest so the plugin is applied to all build-like commands (like this repo's `rush test` command)?

**Comment by gigara** [comment]
@iclanton Done. Please update to 1.0.5
