### ISSUE TITLE
Non-determinism in rush install

### ISSUE THREAD

**Issue by benkeen** [microsoft/rushstack#4014]
Hey! We have a pnpm-rush monorepo in a corporate env with our own registry that houses copies of the packages from npm. Typically there's a bit of a lag between when a new package version is published publicly on npm and when we get it in our registry. Bit of a pain, but doesn't happen often and we've been working around it.

Yesterday however, our pipelines all started failing when a new version of `@babel/generator` was published on npm. That's the puzzling bit. Our pnpm lock file should lock everything down, correct? We hadn't changed it, but suddenly something was requiring that new version.

This occurred for some people locally (rush update) and on the CI (scripts/install-run-rush.sh). Once the package had propagated to our registry the problem went away, but we're left wondering where's the non-determinism here? Looks like perhaps it's at the very first phase where it installs the right Rush version. Screenshot below.

![Screenshot 2023-03-15 at 1 20 36 PM](https://user-images.githubusercontent.com/512116/225433022-4e8bb603-9a9e-4b0e-934c-2309489e6a54.png)

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | No |
| `rushVersion` from rush.json? | 5.88.0 |
| `useWorkspaces` from rush.json? | No |
| Operating system? | mac, unix |
| Would you consider contributing a PR? | N/A |
| Node.js version (`node -v`)? | 16.17.0 |

**Comment by benkeen** [comment]
So it _is_ the Rush installation step. Installing @microsoft/rush@5.88.0 which older than @babel/generator@7.21.3 causes that babel version to be installed. This is kind of a worry since it may break any of our internal pipelines/local devs at any point. 

Odd, but this seems like an instance where the package should be committed with the lockfile just so it'd be fully deterministic for consumers. But of course that would raise other issues. 

Any suggestions?

**Comment by dmichon-msft** [comment]
There is an environment variable `INSTALL_RUN_RUSH_LOCKFILE_PATH` that can be set on CI, pointing to the package-lock.json produced by a prior invocation of `install-run-rush.js`. The recommended way to use this is when upgrading the target version of Rush in your repository, run `install-run-rush.js`, then copy `common/temp/install-run/@microsoft+rush@${rushVersion}/package-lock.json` to somewhere in your repository and commit it. In your pipelines point `INSTALL_RUN_RUSH_LOCKFILE_PATH` at that committed file.

Incidentally it will also measurably improve the performance of installing Rush.

**Comment by benkeen** [comment]
Ooh you gem. Brilliant, thanks so much!
