### ISSUE TITLE
[rush] ERROR: version.includes is not a function 

### ISSUE THREAD

**Issue by Bingjiling** [microsoft/rushstack#4047]
## Summary
Rush update throw `ERROR: version.includes is not a function` when field "nodeSupportedVersionRange" is set with one major version. e.g. `"nodeSupportedVersionRange": ">=18.0.0 <19.0.0"`

## Repro steps

1. Create new repo with rush init 
2. Set `"nodeSupportedVersionRange": ">=18.0.0 <19.0.0"` in rush.json
3. Add a new dependency in any project
4. Run `rush update` 

  **Expected result:** 
Rush update success without error

  **Actual result:** 
ERROR: version.includes is not a function

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by dmichon-msft** [comment]
Would you mind running `rush --debug update`? It'll print the full stack trace of the issue.

**Comment by Bingjiling** [comment]
We found the root cause, it's pnpm v8 being specified in rush.json. Thank you for the response!
