### ISSUE TITLE
[heft] cannot upgrade heft-web-rig to 0.14.9

### ISSUE THREAD

**Issue by kamontat** [microsoft/rushstack#4053]
## Summary

Upgrading heft-web-rig to version 0.14.9 failed due to version inconsistency between dependency and peer dependency: webpack in heft-webpack5-plugin.

dep: https://github.com/microsoft/rushstack/blob/fb9e5ff047799e5edc42ea6e8e83e9f870bf730c/heft-plugins/heft-webpack5-plugin/package.json#L33
Peer dep: https://github.com/microsoft/rushstack/blob/fb9e5ff047799e5edc42ea6e8e83e9f870bf730c/heft-plugins/heft-webpack5-plugin/package.json#L22

## Repro steps

1. Install or upgrade heft-web-rig to version 0.14.9
2. Failed with error: unmet peer webpack@~5.75.0

  **Expected result:** able to install new version

  **Actual result:** error

## Details

https://github.com/kc-workspace/kcws-js/actions/runs/4648509747/jobs/8226245408

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? |  |
| Operating system? | Linux |
| Package manager | Pnpm |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 18.15.0 |

**Comment by TheLarkInn** [comment]
Nice catch. I will fix this.
