### ISSUE TITLE
[rush] EPERM attempting to read build log for build cache

### ISSUE THREAD

**Issue by dmichon-msft** [microsoft/rushstack#4102]
## Summary
Rush sometimes encounters an EPERM when attempting to copy the build log for a project into the rush-temp folder.

## Repro steps
On Windows, running a build with phased builds experiment disabled (i.e. only vanilla Bulk command) can get into a state where when Rush attempts to copy the Project build log into the rush-temp folder, the stat call encounters EPERM.

It might require that the log file already exists from a previous run, not clear.

## Details
Examination of the code and control flow indicates that the file being copied is currently held open for writing by the Rush process, since it attempts to write the results of setting the cache entry into the log file that it is attempting to copy into the build cache entry.

Most likely this should be updated to have the log that contains information about cache read/write and the log that contains the results of the shell command be completely separate files, only the latter of which gets written into the build cache entry.

FYI @chengcyber 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.97.1 |
| `rushVersion` from rush.json? | 5.97.1 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Windows |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 16.20.0 |

**Comment by chengcyber** [comment]
Sorry for the late reply. I am kind of busy this week... Anyway, let me see how to improve this part of logic. Hopefully i will take a look this week.

**Comment by chengcyber** [comment]
Hi @dmichon-msft , after checking the code, i wonder wether it's the right direction to do the following steps:

1/ Add a property in `ITerminalChunk`

**libraries/terminal/src/ITerminalChunk.ts**

```ts
interface ITerminalChunk {
    kind: TerminalChunkKind;
    text: string;

    meta?: Record<string, unknown>;
}
```

NOTE: The idea behind this meta object is the fact that `Terminal` is a separate package from rush-lib and it should only be designed to target common use case.  So, it's not a good thing to add `isXXXLog` as a predefined meta info.

2/ Update the `CollatedTerminalProvider` to

**libraries/rush-lib/src/utilities/CollatedTerminalProvider.ts**

```ts
  public write(data: string, severity: TerminalProviderSeverity): void {
    switch (severity) {
      case TerminalProviderSeverity.log:
      case TerminalProviderSeverity.verbose: {
        this._collatedTerminal.writeChunk({ 
          text: data,
          kind: TerminalChunkKind.Stdout,
          meta: { source: 'runner' }     // <--- mark the log comes from Runner(ShellOperationRunner)
        });
        break;
      }
     // ... other code
```

3/ Update transformer

3.1/ If we want to persist the log in a separate log file, then updating a new logWriter in `ProjectLogWritable`

**libraries/rush-lib/src/logic/operations/ProjectLogWritable.ts**

```ts
  protected onWriteChunk(chunk: ITerminalChunk): void {
    if (chunk.meta?.source === 'runner') {
       // write to the new file, maybe called "runner.log"
    }
    // other code
  }

```

Or, 3.2/ If we don't want to persist the log for build cache, we can also add a splitter transformer and route the logs for build cache to discardTransform.

```
    //                             +--> quietModeTransform? --> collatedWriter
    //                             |
    // normalizeNewlineTransform --1--> stderrLineTransform --2--> removeColorsTransform --3--> projectLogWritable
    //                                                        |                                                                                                 |
    //                                                        +--> stdioSummarizer                                                            +--> discardTransform

```

Any thoughts are welcome!

**Comment by dmichon-msft** [comment]
@chengcyber I'm pretty sure we just want to create two separate Terminal instances, one that writes to the console and the log file for the child process, and one that writes to the console and (optionally) an outer log file for the cache subsystem. The first terminal will have the underlying file closed before we copy the file into the build cache, while the latter will run both before and after the child process.
