### ISSUE TITLE
INFORMATION REQUEST: [rush-amazon-s3-build-cache-plugin] Does build-cache with AWS S3 Support InstanceRoles

### ISSUE THREAD

**Issue by jkerrigan-chwy** [microsoft/rushstack#4115]
Asked for this information in the zulip chat, did not receive an answer so asking here:

## Summary
Interested in finding out if I need to specify Access/SecretKey for AWS S3 usage with build-cache or if it will be able to work if I run without specifying creds on a server that has an IAM role attached to it.

**Comment by john-u** [comment]
I considered looking into using the AWS SDK to do support [STS assume role](https://docs.aws.amazon.com/IAM/latest/UserGuide/example_sts_AssumeRole_section.html) and providing the role via configuration. I saw a couple issues with this though.
- Many existing CI platform AWS plugins are designed to setup auth once for an entire build session or group of jobs/steps, not assuming creds per job/step. In this case, Rush would be assuming a "session" with AWS IAM which seems a little heavy handed.
- Most of the CI plugins that I checked already export credentials to the build environment that are picked up by numerous different tools (AWS SDK, CLI, etc.). For example, here is [Jenkins withAWS](https://github.com/jenkinsci/pipeline-aws-plugin/blob/693f49f51bda7a8738060eba2e90da8b7033c645/src/main/java/de/taimos/pipeline/aws/WithAWSStep.java#L399) exporting these vars and here is [GitHub actions configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials/blob/375a690dc0af3921541e5f427167f333d7e85f67/index.js#L145). Both of these assume being called before or wrapping any functionality that requires the auth (such as a Rush build).

I opened a PR that checks for those env vars and uses them if set. I figured this would be easier to maintain and more flexible for different use cases.
