### ISSUE TITLE
[rush] cached builds shouldn't include cache analysis in cached logs

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/rushstack#4117]
## Summary

When using the rush build cache, it caches a bit too much of the build log output. It ought to only cache the _actual_ build output, not the cache analysis output. This gets confusing because the cached log output includes _multiple_ sections of cache analysis logging when it gets a cache hit, including _always_ ending in "This project was not found in the build cache", even when it restored from the build cache, because any cached build always came from a case where it wasn't in the cache!

## Repro steps

1. Setup a rush repo with cloud build caching enabled
2. Run the build with cloud cache write enabled
3. Run the build again with `--verbose`

  **Expected result:** 
I expect the build output to report the _current_ cache analysis info, not the cache analysis from the cached build run. E.g. something like this:
```
==[ @myscope/mypackage ]=====================================[ N of M ]==

This project was not found in the local build cache. Querying the cloud build cache.
Wrote cache entry to "/home/circleci/project/common/temp/build-cache/ab1bf358c00dcda4e7787d6d7c977c5a625d5d48".
Build cache hit.
Clearing cached folders: dist
Successfully restored output from the build cache.

Invoking: npm run build
...
"@myscope/mypackage" was restored from the build cache.
```

  **Actual result:** 
It emits the current cache analysis, _and_ the cache analysis from the time the build actually ran:
```
==[ @myscope/mypackage ]=====================================[ N of M ]==

This project was not found in the local build cache. Querying the cloud build cache.
Wrote cache entry to "/home/circleci/project/common/temp/build-cache/ab1bf358c00dcda4e7787d6d7c977c5a625d5d48".
Build cache hit.
Clearing cached folders: dist
Successfully restored output from the build cache.

Restoring cached log file at /home/circleci/project/libs/mypackage/.rush/temp/operation/build/all.log
This project was not found in the local build cache. Querying the cloud build cache.
This project was not found in the build cache.
Invoking: npm run build 
...
"@myscope/mypackage" was restored from the build cache.
```

## Details

Make the cache analysis output go direct to stdout, skipping whatever cache capture system is in place?

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.97.1 |
| `rushVersion` from rush.json? | 5.97.1 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes, if I can get some pointers for where to start |
| Node.js version (`node -v`)? | 16.20.0 |

**Comment by dmichon-msft** [comment]
Related #4102 , which deals with some errors that result from caching the log file that is actively being written to by the caching process.
