### ISSUE TITLE
[rush] --impacted-by behaviour with phased commands

### ISSUE THREAD

**Issue by UberMouse** [microsoft/rushstack#4118]
How does `--impacted-by` interact with phased commands? I'm trying to use `--impacted-by` with a phased command and it's certainly not working and I'm trying to understand if I'm doing something wrong or if I've encountered a bug

## Summary

Have `phasedCommands` set to true in `experiments.json`
Have defined a series of phases as such

phaseA

phaseB
  depends on upstream phaseA

phaseC
  depends on self phaseB

So to run `phaseC` for a given package we need to have run `phaseB` on the same package, and `phaseA` on any upstream packages before `phaseC` will be able to succeed

If I run `rush phaseC` I see that `phaseA` is correctly run for the projects upstream of any project currently executing `phaseC` as I would expect. However, if I instead run `rush phaseC --impacted-by git:master` to run `phaseC` for any projects affected by changes since master I do _not_ see `phaseA` run for the correct packages. Instead I see it start on `phaseB` for a package, which then fails because the upstream packages of that package have not had `phaseA` run.

Which means the command fails. Instead I would have to run `rush phaseA` before hand, without `--impacted-by`, to satisfy the phase requirements of `phaseB`. With `rush phaseA --impacted-by git:master` I see the same problem where it doesn't run `phaseA` for all the projects upstreams that are impacted by changes since branching off master.

Is this the intended behaviour? If so, is there some correct way to achieve what I'm after? Because as it stands it doesn't seem possible

## Details

The repo also has incremental builds and the build cache enabled. For extra background the phases are actually
phaseA: build
phaseB: build storybook
phaseC: submit storybook to [Chromatic](https://www.chromatic.com) for testing

And `phaseB` is failing because a package in the monorepo it depends on hasn't been built yet, despite being an upstream dependency of the package.

I've attached our [command-line.json here](https://gist.github.com/UberMouse/c18b4d22c0b92b58aea861e830a714e4) if it's useful

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.93.1 |
| `rushVersion` from rush.json? | 5.93.1 |
| `useWorkspaces` from rush.json? | this is default enabled now isn't it?|
| Operating system? | Ubuntu |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 18.16.0 |

**Comment by UberMouse** [comment]
Hmm I now see this line in the docs, so this is working as intended?

>In these situations the --impacted-by parameter can be handy: It means "Select only those projects that might be broken by a change to B, and trust me that their dependencies are in a usable state."

Meaning it's not possible to safely select a subset of projects to run a specific phase on?

**Comment by iclanton** [comment]
That behavior doesn't seem right to me either. @dmichon-msft?

**Comment by dmichon-msft** [comment]
Currently, the various selection parameters only select _projects_, not phases. So what happens when you specify `--impacted-by X` is that Rush evaluates that to X and all projects that declare a direct or indirect dependency on X, then run all phases defined in the command on said projects.

There is no mechanism in the command line as it currently exists to run all operations (project*phase tuples) that are impacted by a specific operation in the full graph, mainly because there is currently no way to precisely specify an operation via the command line, only a project.

**Comment by dmichon-msft** [comment]
Note that if you want to ensure that the necessary dependencies are run, you want to use `--from`, not `--impacted-by`.

**Comment by iclanton** [comment]
>Could you expand out a specific example with some names of projects and phases, their dependency relationship, and what command you expect to do what?

If you take a look at their [`command-line.json`](https://gist.github.com/UberMouse/c18b4d22c0b92b58aea861e830a714e4), it looks like they have three relevant phases:

- `_phase:build` (depends on upstream `_phase:build`)
- `_phase:build-storybook` (depends on self `_phase:build`)
- `_phase:chromatic` (depends on self `_phase:build-storybook`)

And they have three commands:

- `rush build`, which runs `_phase:build`
- `rush build-storybook`, which runs `_phase:build-storybook` (and, therefore runs `_phase:build` the self and upstream projects)
- `rush chromatic`, which runs `_phase:chromatic` (and, therefore runs `_phase:build-storybook` and `_phase:build` the self project and `_phase:build` on the upstream projects)

Sounds like what's happening is running `rush chromatic --impacted-by git:master` only runs `_phase:build-storybook` and then `_phase:chromatic` and not `_phase:build` (@UberMouse - correct me if this isn't right).

This also sounds like unexpected behavior to me. If `--impacted-by` selects projects, it seems like it should still expand the phases for the selected projects. It seems like `--impacted-by` should be the same as `--from <project that changed> --from <other project that changed>` and not `--only <project that changed> --only <other project that changed>`.

**Comment by dmichon-msft** [comment]
Per the behavior change in #3754, the sequence of operations that happen when executing `rush chromatic --impacted-by git:master`:
1. Evaluate `git:master` to determine the set of projects that contain source code changes since `master` (staged and committed only)
1. Evaluate the `--impacted-by` expansion to the projects selected in (1), recursively adding consuming projects.
1. Select the exact set of phases in the definition of the `chromatic` command, which is `["_phase:chromatic"]`
1. For each project selected by (2) and each phase selected by (3), add the corresponding operation and all of its dependencies to the build graph. If the dependency's project or phase is not in scope, mark it as "skipped".
1. Select all operations in (4) that either have a project that corresponds to a project in the `changedProjects` set
1. Expand the set in (5) to include all consumers of such operations
1. Mark all operations in the graph produced by (4) that are not in the set in (6) as skipped.

Based on this logic, if you have 3 projects:
A depends on B depends on C
then running `rush chromatic --impacted-by B` should select:
`B (_phase:chromatic)`, `C (_phase:chromatic)`
then expand to:
`B (_phase:chromatic)`, `C (_phase:chromatic)`, `B (_phase:build-storybook)`, `C (_phase:build-storybook)`, `B (_phase:build)`, `C (_phase:build)`

Does this match what you are seeing?

**Comment by UberMouse** [comment]
>Sounds like what's happening is running rush chromatic --impacted-by git:master only runs _phase:build-storybook and then _phase:chromatic and not _phase:build (@UberMouse - correct me if this isn't right).

That is correct. If I start with a blank slate (no packages built, just `rush install` run) then the very first package containing a chromatic phase that executes fails to complete the build-storybook phase because it requires an upstream package to have been built first, which rush isn't selecting.

> Based on this logic, if you have 3 projects:
> A depends on B depends on C
> then running rush chromatic --impacted-by B should select:
> B (_phase:chromatic), C (_phase:chromatic)
> then expand to:
> B (_phase:chromatic), C (_phase:chromatic), B (_phase:build-storybook), C (_phase:build-storybook), B (_phase:build), C (_phase:build)
> 
> Does this match what you are seeing?

I think so. If I choose our base UI package which everything else containing a storybook depends on by going `rush chromatic --impacted-by <base-ui-package>` then it seems to select the correct phases for all downstream packages and ignore anything upstream.

If I do `rush chromatic --from <base-ui-package>` it looks like it both selects all downstream packages (same as --impacted-by) but it also does the right thing for upstream packages (correctly builds the packages the <base-ui-package> depends on). 

Now that I read the selecting projects docs closer I realize I misunderstood what it was saying, I thought you had to use `--impacted-by` to use the `git:` selector but that's just the example I looked at. So to achieve the correct behaviour here, I can just use `rush chromatic --from git:origin/master` instead and it will select all the packages + dependent phases correctly.

Though I just tested that and `--from` doesn't select the specified package itself, so my assumption is that `rush chromatic --from git:origin/master` will run the chromatic phases for all packages that depend on the packages with source code changes, but not chromatic for the packages that actually had the source code changes? But it would run their build phases because the downstream packages require that to satisfy their build-storybook phase?

So not quite what I'm after. However, I'm not really clear on whether this would actually end up running anything differently than an unfiltered `rush chromatic` assuming the build cache is functioning. Since with the build cache it will cache the phase results and skip them until it encounters a package with changes that cause a cache miss and then all phases downstream of that won't try and access the cache?

Am I correct in my assumptions?

**Comment by dmichon-msft** [comment]
> Though I just tested that and `--from` doesn't select the specified package itself, so my assumption is that `rush chromatic --from git:origin/master` will run the chromatic phases for all packages that depend on the packages with source code changes, but not chromatic for the packages that actually had the source code changes? But it would run their build phases because the downstream packages require that to satisfy their build-storybook phase?

The specification for the `--from` parameter is that it performs the expansion that `--impacted-by` does, and then for each project in the new selection, applies the effects of the `--to` operator (i.e. include all dependencies).

So in the simple case with:
A depends on B depends on C (I wrote this wrong earlier; the previous comment assumed C depends on B depends on A)

`--to B` selects B, C
`--impacted-by B` selects A, B
`--from B` selects A, B, C

**Comment by UberMouse** [comment]
Ok yep I think I looked at the build output wrong because running it again I see the project listed in `--from` is also built. So `rush chromatic --from git:origin/master` should give me the results I want then. Thanks :pray: 

>However, I'm not really clear on whether this would actually end up running anything differently than an unfiltered rush chromatic assuming the build cache is functioning. Since with the build cache it will cache the phase results and skip them until it encounters a package with changes that cause a cache miss and then all phases downstream of that won't try and access the cache?

Can you expand on whether this is true or whether my understanding of this is incorrect?

**Comment by UberMouse** [comment]
Anyway, I think this issue can be closed now. `--from git:` is what I was actually after, I just misread the docs. And it sounds like `--impacted-by` is working as intended even if it's a bit of an odd interaction with phased commands. Thanks for the help 🙏

**Comment by dmichon-msft** [comment]
> So not quite what I'm after. However, I'm not really clear on whether this would actually end up running anything differently than an unfiltered `rush chromatic` assuming the build cache is functioning. Since with the build cache it will cache the phase results and skip them until it encounters a package with changes that cause a cache miss and then all phases downstream of that won't try and access the cache?

The only time you will get a difference between `--from` and not filtering at all is if your repository contains disjoint subtrees. Specifying `--from` on any project in a subtree will invoke the entire subtree.
