### ISSUE TITLE
[rush] There was an error in rush build and I didn't know how to fix it

### ISSUE THREAD

**Issue by MsBeiBei** [microsoft/rushstack#4199]
I have configured four projects in rush.json, each project has a build command written in the script of package.json.
demo https://github.com/MsBeiBei/ANADI.git

    project1   @anadi/types

    "scripts": {
        "build": ""
      }

    project2   @anadi/glm

    "scripts": {
        "build": ""
      }

    project3   @anadi/copyright

    "scripts": {
        "build": "tsc"
      }

    project4   @anadi/tsconfig

    "scripts": {
        "build": ""
      }

When I execute rush build in the root directory, an error is thrown as follows.
![image](https://github.com/microsoft/rushstack/assets/133855318/67c75621-9d61-4ac3-a7ea-5ec528060cf1)

My desired outcome is that project3 can be compiled normally by tsc. But I don't know how to solve it. Can someone help me?

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.100.0 |
| `rushVersion` from rush.json? |  5.100.0 |
| `useWorkspaces` from rush.json? | pnpm 8.6.2 |
| Operating system? | Windows |
| Would you consider contributing a PR? | NO |
| Node.js version (`node -v`)? | 18.16.0 |

**Comment by iclanton** [comment]
A fix has been released in Rush `5.100.1`.
