### ISSUE TITLE
[rush] Delegate git hook files do not pass arguments through

### ISSUE THREAD

**Issue by egmacke** [microsoft/rushstack#4200]
## Summary

We use custom git hooks to check contents of commit messages in a `pre-commit` hook.

Since upgrading to rush 5.100.0 these hooks have stopped working.

The issue seems to be that the new delegate git hook scripts (that were added in 5.100.0) invoke the hooks defined in the `common/git-hooks/` folder, but do not pass any of the git args through.

This is a problem because for the hooks we use, we need access to the temporary commit message file which is passed in as a command line arg to the hook scripts (which we access using $1)

## Repro steps

Define a `pre-commit` hook which reads the commit message file as passed in via `$1`

`$1` does not evaluate to anything as it's not passed through.

Example:

`common/git-hooks/pre-commit`
```
#!/bin/bash

echo "Commit footer text" >> $1
```

This should append the `Commit footer text` to the end of the commit message.

Actual result is an error `$1: ambiguous redirect`

## Details

I believe the fix is just to pass through all args in the delegate scripts.

This can be achieved using `$@` so ` "$SCRIPT_IMPLEMENTATION_PATH"` becomes ` "$SCRIPT_IMPLEMENTATION_PATH" $@`

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  5.100.0 |
| `rushVersion` from rush.json? | 5.100.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Linux (via WSL) |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 18.15.0 |

**Comment by iclanton** [comment]
The fix has been released in Rush `5.100.1`.
