### ISSUE TITLE
[rush] Using --to does not filter correctly when using pnpm v8

### ISSUE THREAD

**Issue by Pipo93** [microsoft/rushstack#4218]
## Summary

We're running project based installs and builds in our monorepo using the `--to <project>` argument. 
After upgrading to pnpm version 8.6.2, rush doesn't seem to apply this properly. It recognizes the scope of projects (e.g. `Scope: 4 of 42 workspace projects`) but then it installs the packages for all the projects and executes for example also postinstall scripts for applications which have no dependency to the application we want to install.

With pnpm v7 this was working properly.

## Repro steps

Running `node ./common/scripts/install-run-rush.js install --to <application>` 

  **Expected result:** 
Rush does not execute install and postinstall for projects which are independent.

  **Actual result:** 
All the projects are installed and postinstall scripts executed 

## Details

I guess something in pnpm has changed in v8 which breaks the `--to` argument.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.100.1 |
| `rushVersion` from rush.json? | 5.100.1 |
| `useWorkspaces` from rush.json? | true |
| Operating system? |  Mac / Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 16.14.2 |

**Comment by iclanton** [comment]
@dmichon-msft - Would you take a look at this?

There isn't an obvious change between 7 and 8 in the filtering docs: https://pnpm.io/filtering

**Comment by Pipo93** [comment]
I found this issue on pnpm side: https://github.com/pnpm/pnpm/issues/6300

This might be the root cause

**Comment by matthieu-foucault** [comment]
> I found this issue on pnpm side: [pnpm/pnpm#6300](https://github.com/pnpm/pnpm/issues/6300)
> 
> This might be the root cause

FYI the root cause issue was fixed and release in pnpm v9. I was experiencing the issue with the `--to` filter and pnpm v8. Upgrading to v9 fixed it (pnpm v9.12.3, rush v5.140.1).

**Comment by iclanton** [comment]
Looks like this is no longer an issue at this point.
