### ISSUE TITLE
[heft] Dev server broken by "File extension for signature expected to be dts"

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#4224]
## Summary

After upgrading to the latest Heft+TypeScript, I now occasionally get this error in the `heft start` dev server:

```
[build:typescript] File change detected. Starting incremental compilation...
[build:typescript] Error: Debug Failure. False expression: File extension for signature expected to be dts: Got:: C:/Git/my-repo/my-app/lib/ui/misc/App.d.ts.map
```

After this error is reported, the dev server will continue serving the old build. So you can spend several minutes debugging a "problem" that ultimately turns out be that you're debugging an outdated build.

Killing and restarting `heft start` fixes the problem.

## Repro steps

I haven't been able to determiner repro steps yet.  

@iclanton said he encountered the same issue recently.

## Details

This error message is an assertion failure in the `typescript` package:

[typescript/src/compiler/builderState.ts](https://github.com/microsoft/TypeScript/blob/88cb76d314a93937ce8d9543114ccbad993be6d1/src/compiler/builderState.ts#L414)
```ts
    export function computeDtsSignature(
        programOfThisState: Program,
        sourceFile: SourceFile,
        cancellationToken: CancellationToken | undefined,
        host: HostForComputeHash,
        onNewSignature: (signature: string, sourceFiles: readonly SourceFile[]) => void,
    ) {
        programOfThisState.emit(
            sourceFile,
            (fileName, text, _writeByteOrderMark, _onError, sourceFiles, data) => {
                Debug.assert(isDeclarationFileName(fileName), `File extension for signature expected to be dts: Got:: ${fileName}`);
                onNewSignature(computeSignatureWithDiagnostics(
```

So it seems that `heft-typescript-plugin` is sometimes passing an incorrect file extension to the compiler. (?)

Why does the Heft dev server never recover however? In addition to fixing the root cause, maybe we could also make Heft's dev server more robust.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.55.2 |
| `typescript` version? | 5.0.4 |
| Operating system? |Windows  |
| Node.js version (`node -v`)? | v16.15.1 |

**Comment by Faithfinder** [comment]
I also don't have a repro, but it happened to me fairly consistently. I also don't think it's heft 51 related, as the branch I've experienced it on is on 0.50.5.

(Might have happened for a while, as we don't often use heft watch mode, and use rush's `watchForChanges` from `command-line.json` instead)

**Comment by octogonz** [comment]
🚀  This was fixed in `@rushstack/heft-typescript-plugin` `0.2.16`

@Faithfinder
