### ISSUE TITLE
[rush] Error installing npm -g @microsoft/rush on github action host

### ISSUE THREAD

**Issue by eduarevalo** [microsoft/rushstack#4239]
## Summary

The following error appears when installing rush globally on nodejs 16
<img width="982" alt="image" src="https://github.com/microsoft/rushstack/assets/20518796/31eecf8b-f7d6-49e2-9444-eafcc032f010">
## Repro steps

  **Expected result:** 
Unable to install rush

  **Actual result:** 
rush fully operational

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by octogonz** [comment]
The `@rushstack/rush-azure-storage-build-cache-plugin` package version appears to have been published correctly:

https://www.npmjs.com/package/@rushstack/rush-azure-storage-build-cache-plugin/v/5.100.1

I just ran `npm install -g @microsoft/rush` on my laptop and it completed successfully.

What's in your `.npmrc`? Maybe you are using a private NPM registry whose cache is missing this version?

**Comment by eduarevalo** [comment]
Seems to be a temporary problem. It took more than an hour to get resolved. Closing now
