### ISSUE TITLE
[rush] WSL2 + node 18 = cli startup is slow

### ISSUE THREAD

**Issue by isc30** [microsoft/rushstack#4244]
## Summary

CLI startup time is non existent with node 16 (quick) but when switching to node 18 (via nvm) it takes around 10s to show the initial "Rush Multi-Project Build Tool 5.100.1..."

## Repro steps

- WSL2
- node 18
- run `rush` in the CLI
- see how there is no output for around 10s

  **Expected result:** its instantaneous like node 16

  **Actual result:** there is no output for around 10s

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.100.1 |
| Node.js version (`node -v`)? | ^18 |

**Comment by isc30** [comment]
https://github.com/microsoft/rushstack/assets/10807051/66c36126-6fd9-4821-adfb-a6547446bc8b

https://github.com/microsoft/rushstack/assets/10807051/b9774bc8-1497-4b27-8b12-d3cd9ed1c338

**Comment by iclanton** [comment]
Is your globally-installed Rush binary for Node 18 installed in WSL's filesystem, or is it coming from the Windows filesystem?

**Comment by isc30** [comment]
The binary is the one coming doing "npm I -g @mcrosoft/rush"

**Comment by dmichon-msft** [comment]
I can't repro this locally; I get 0.5s boot time with WSL2, Node 18, rush 5.100.1.

Run:
> `which rush`
Should give a result like `/home/some-username/.nvm/versions/node/v18.17.0/bin/rush`
Then pass that as:
> `node --cpu-prof /home/some-username/.nvm/versions/node/v18.17.0/bin/rush`
The pull up the trace in https://speedscope.app (or other tool) and see if you can identify where its spending the time? You're welcome to upload said .cpuprofile file as well.

**Comment by isc30** [comment]
oh, my fault. The `which rush` made me realize that, for some reason, the PATH of windows had priority over the WSL2's nvm.

I fixed that and it seems to be working well, thanks a lot!
