### ISSUE TITLE
[lockfile-explorer] Lockfile v6 support

### ISSUE THREAD

**Issue by Faithfinder** [microsoft/rushstack#4254]
Self-explanatory. Doesn't seem to be there right now.

**Comment by iclanton** [comment]
@william2958 - Want to take a look?

**Comment by Faithfinder** [comment]
Just tried it, and it doesn't seem to work correctly? I know we have doppelgangers, and the "Selected entry" looks wrong
![image](https://github.com/microsoft/rushstack/assets/25051063/90510490-d56a-4965-85f8-b1fce4be9c19)
