### ISSUE TITLE
[rush] install-run.js assumes that registry returns versions in ascending order

### ISSUE THREAD

**Issue by raihle** [microsoft/rushstack#4256]
## Summary

I'm using _install-run.js_ to install and run some developer tools:

`node ./common/scripts/install-run.js the-package@^1 the-command`

Rush installs _a_ 1.x.x version, but not the latest available one (1.1.1, despite version 1.2.1 being published).

This seems to be because our registry (JFrog Artifactory) returns the versions "out of order" when queried with for example `pnpm view`. The installed version (1.1.1) is the last one in the result.

## Repro steps

(Using JFrog Artifactory or another registry that doesn't sort package versions)

* `node common/scripts/install-run.js react@^18 zzz`

  **Expected result:** Rush should always installs the last version returned by the registry (currently 18.2.0) and then crash (because there is no bin-script named zzz)

  **Actual result:** Rush installs React version 18.1.0

## Details

As mentioned, this seems to be because our registry is returning unsorted versions. Rush simply selects the last version returned by the registry, which is not always the highest version.

I'm not sure if this is a bug in Rush or in Artifactory. The public NPM registry seems to sort its package versions when queried, but is that reliable behavior? Perhaps it should be fixed in NPM or PNPM (whatever Rush is using to make this query)? But sorting the versions seems like a simple enough fix that it could be worth doing in Rush.

The reason for using `@^1` in the first place is that I want the latest 1.x.x version, but...
* `@1` and `@1.x` will give me the latest compatible version _at the time_, and then never check for newer versions until common/temp/install-run is emptied
* `@latest` won't necessarily be a compatible version and has the same issue with cache
* `@*` or no selector won't necessarily be a compatible version, _and_ have the same issue of selecting the "last returned" version, not the highest version

Of course resolving versions like this means that builds are not necessarily reproducible. That's alright in this case because the commands do not run in CI, they are developer convenience tools for generating new packages, serving build output locally, etc..

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.100.2 |
| `rushVersion` from rush.json? | 5.100.2 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 20.5.0 |

**Comment by raihle** [comment]
Actually, it gets worse - using a query like `react@^18.2` will fail even though 18.2.0 exists, because the format of `npm view ... version` is different depending on the number of matching versions. If there are multiple, it returns the format Rush expects (a list of `<package name>@<version> '<version>'`). If there is only one, it returns _just_ the version number. Unlike the above, this is easy to reproduce with the global registry.

The log output:

> Error: Unable to resolve version ^18.2 of package react: Error: Invalid npm output 18.2.0

**Comment by iclanton** [comment]
I think it's a good idea for the `install-run` script to just go ahead and sort versions. If you wouldn't mind putting together a fix for this, it'd be very appreciated.

The other issue sounds like it should be easy enough to handle as well. With some quick experimentation, it looks like if you run `npm view --json <package>@<version> versions`, it will return a more consistent format. For example:

```
$ npm view --json react@^18.2 version
"18.2.0"
$ npm view --json react@^18 version
[
  "18.0.0",
  "18.1.0",
  "18.2.0"
]
```

So then we could coalesce that result with something like:

```TypeScript
const parsedVersionOutput: string | string[] = JSON.parse(npmViewVersionOutput);
const versions: string[] = Array.isArray(parsedVersionOutput) ? parsedVersionOutput : [parsedVersionOutput];
```

**Comment by raihle** [comment]
@iclanton Done!
