### ISSUE TITLE
[rush] parsePnpmDependencyKey doesn't handle `/typescript@5.1.6` format

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/rushstack#4274]
## Summary

we use the following npm alias in dependency list

```
   "@_ts/min": "npm:typescript@~4.2.4",
   "@_ts/max": "npm:typescript@latest",
```

in v6 of pnpm-lock file, the dependencyKey format changed from `/typescript/5.1.6` to `/typescript@5.1.6`.  However, `parsePnpmDependencyKey()` doesn't handle the new format properly, which leads to the error

>ERROR: Cannot parse PNPM shrinkwrap version specifier: "/typescript@5.1.6" for "@_ts/max"

maybe the regex need to be updated? 

https://github.com/microsoft/rushstack/blob/c40569e8e10b652baf3e89f48eea24d2aff2e533/libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts#L166

## Repro steps

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? | 5.101.0 |
| `useWorkspaces` from rush.json? | false |
| Operating system? |  |
| Would you consider contributing a PR? | better leave this to devs who are more familar with this code |
| Node.js version (`node -v`)? | v16.20.1 |

**Comment by iclanton** [comment]
@jeremymeng - give the fix in this PR a try? https://github.com/microsoft/rushstack/pull/4281

**Comment by jeremymeng** [comment]
@iclanton @dmichon-msft thanks for the quick fix! Yes the latest addressed the issue.

though we hit another issue afterwards https://github.com/microsoft/rushstack/issues/4283
