### ISSUE TITLE
[rush] Version command bumps all versions regardless of change files

### ISSUE THREAD

**Issue by CodeMedic42** [microsoft/rushstack#4279]
## Summary

I ran "rush change" and got logs for 6/8 projects. However when I run "rush version --bump" the versions for all 8 projects get updated. I was expecting just the 6 with change logs to get updated.

## Repro steps

Clone/Download my repo (You should be able to see it)
https://github.com/CodeMedic42/reform

run "rush version --bump"

  **Expected result:**

The versions for the web-unit, web-unit-jest are not changed because the code for those two projects were not modified. Also no change files for these two project were not created after running "rush change". 

  **Actual result:**

The versions for the web-unit, web-unit-jest are updated when they should not be since their code was not modified.

## Detail

Here is my repo
https://github.com/CodeMedic42/reform

I checked the change logs in. The same one which were generated by the "rush change"

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
5.97.0
| `rushVersion` from rush.json? |  |
5.97.0
| `useWorkspaces` from rush.json? |  |
Not defined, so defaulted to false?
| Operating system? |  |
Mac 11.4
| Would you consider contributing a PR? |  |
Depends on how confident I am on the code
| Node.js version (`node -v`)? |  |
16.15.0

**Comment by iclanton** [comment]
You're using lockstepped version policies (https://github.com/CodeMedic42/reform/blob/main/common/config/rush/version-policies.json#L12-L29), which bump all packages that the policy is applied to, regardless of whether the individual packages have changes or not. See docs [here](https://rushjs.io/pages/maintainer/publishing/#two-types-of-version-policies).

If you only want to bump a single version policy, you can pass the `--version-policy NAME` argument to `rush version`, but it sounds like you probably want to be using individual versioning, given that you didn't expect the unchanged packages to be bumped.

**Comment by CodeMedic42** [comment]
Thank you for replying, however I am concerned that a nuance of my question is not as clear as I would like it.

As you pointed out I have three version policies, each set to "lockStepVersion"
https://github.com/CodeMedic42/reform/blob/main/common/config/rush/version-policies.json#L12-L29

I also have changes in 6 of my 8 projects. Those 6 projects belong to 2 of the 3 version policies. The other 2, which did not change and have no dependency to the other 6, belong to their own policy.
https://github.com/CodeMedic42/reform/tree/main/common/changes/%40reformjs
https://github.com/CodeMedic42/reform/blob/main/rush.json

My expectation is that since the two projects who belong to their own policy and did not change and have no dependency on anything that did change, should not have their version number updated.

For a bit of a visual breakdown ...

As an example of the dependency of my projects A, B, C, D, E

A depends on B
B depends on C
D depends on E

A belongs to policy X
B belongs to policy X
C belongs to policy Y
D belongs to policy Z
E belongs to policy Z

C is changed which creates changes and change logs for A, B, C which affect policies X and Y.

However I am getting version changes for all projects even though by all accounts D and E are autonomous which is not what I was expecting.

If I am expecting too much that is fine, I just want to make sure I am clear and did not miss anything.
