### ISSUE TITLE
[heft] storybook plugin provides no way to skip webpack build when doing a static build

### ISSUE THREAD

**Issue by UberMouse** [microsoft/rushstack#4289]
## Summary

The heft storybook plugin automatically cancels the webpack plugins from running when it's run with `--serve`, but it does not do this if you omit `--serve` because you want to do a static build. Not sure if there's some reason I'm not aware of that needs it to operate this way, but it doesn't work for our setup. 

I've patched the package locally to move the webpack plugin cancellation outside of the serveMode check to resolve this for us in the meantime

## Repro steps

1. Have heft phases defined where the webpack plugin and storybook plugin are in the same phase
2. run `heft <phase> --storybook --serve` and see that the webpack plugin compilation gets cancelled
3. run `heft <phase> --storybook` and see that both the webpack and storybook builds happen in parallel

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.58.0 |
| `@rushstack/heft-storybook-plugin` version? | 0.3.23 |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v18.17.1 |

**Comment by iclanton** [comment]
Seems reasonable. We'd be happy to accept a PR fixing this.

**Comment by UberMouse** [comment]
My intention is to just change these code blocks here https://github.com/microsoft/rushstack/blob/f90983d70fadd19d88aef752489f90588bdb762c/heft-plugins/heft-storybook-plugin/src/StorybookPlugin.ts#L151-L173

And move lines 158/170 down one line out of the `if` statement so the plugin always cancels the webpack plugin.

I can do that when I get some time.
