### ISSUE TITLE
[rush] git stash will restore deleted config file

### ISSUE THREAD

**Issue by lili2012** [microsoft/rushstack#4295]
I want to run `npx react-scripts eject` and it prompts 

> `config` already exists in your app folder. We cannot continue as you would lose all the changes in that file or directory. Please move or delete it (maybe make a copy for backup) and run this command again.

So I delete config folder and run  `npx react-scripts eject` and it prompts

> This git repository has untracked files or uncommitted changes:

I git stash the removed config folder but after git stash it shows again. It takes me to origin I can't run `npx react-scripts eject`

How could I run `npx react-scripts eject` or suppress  config folder auto generation?

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.100.1 
| `rushVersion` from rush.json? | 5.100.1
| `useWorkspaces` from rush.json? | no
| Operating system? | Windows 
| Would you consider contributing a PR? |  No 
| Node.js version (`node -v`)? | v18.14.1

**Comment by iclanton** [comment]
This is an issue with `react-scripts`, not with Rush. If you have a `config/rig.json` or a `config/rush-project.json` file in your project, you'll probably want to keep those around after ejecting.

You can commit deletion of that folder, run your eject script, commit those changes, and then revert that deletion commit.
