### ISSUE TITLE
[rush] ensureConsistentVersions flag leads to issues with npm aliases

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/rushstack#4298]
## Summary
One of our dependencies has a dependency on `@swc/helpers`. Since version 0.4.36 of `@swc/helpers`, the dependency "legacy-swc-helpers": "npm:@swc/helpers@=0.4.14" was added.
When `ensureConsistentVersions` flag set to `true` in `rush.json` and npm aliases are used in dependency list, an error with shrinkwrap file is shown during Linking step for `rush update` command.
![image](https://github.com/microsoft/rushstack/assets/98852890/b2483ac1-ece2-42a4-bd11-9d6dbc503bf3)

## Repro steps
[Demo repository link](https://github.com/vhuseinova-msft/fluentui-components-swc-helpers-demo)

Steps to reproduce:
- download the demo app
- navigate to the demo app folder
- run `rush update`

  **Expected result:** 
`rush update` can be run without errors when `ensureConsistentVersions` flag set to `true` in `rush.json`

  **Actual result:** Error is shown:
![image](https://github.com/microsoft/rushstack/assets/98852890/b2483ac1-ece2-42a4-bd11-9d6dbc503bf3)

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.100.1 |
| `rushVersion` from rush.json? | 5.100.1 |
| `useWorkspaces` from rush.json? | false |
| Operating system? | Mac |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? |  |

**Comment by iclanton** [comment]
This was fixed in Rush `5.102.0` (see changelog here: https://github.com/microsoft/rushstack/blob/main/apps/rush/CHANGELOG.md#51020). I just tried updating your repro repo and `rush install` completed successfully (after a `rush update` to refresh `common/scripts`).
