### ISSUE TITLE
[rush] allow `echo noop` to be interpreted as empty build/npm script

### ISSUE THREAD

**Issue by jessekrubin** [microsoft/rushstack#4326]
Allow rush to interpret something like `"build": "echo noop",` as an empty/no-work build script

## Summary

Often I run scripts in my rush-repo using pnpm instead of rushx (habit), but pnpm (as well as the other package managers) doesn’t/don’t like when you have an empty string npm-script, it would be nice if there was a standard "noop" build script aside from an emtpy string.

**Comment by iclanton** [comment]
You could write a plugin that does this, but I'm not sure we'd build this into Rush directly.

It looks like npm handles this without issue, but pnpm and yarn return a 1 exit code. If you do choose to put together a plugin, we could feature it on https://rushjs.io/pages/maintainer/using_rush_plugins/#third-party-plugins.
