### ISSUE TITLE
[rush] Install failing with latest version

### ISSUE THREAD

**Issue by nason** [microsoft/rushstack#4347]
## Summary

Installing rush from npm is giving an error:

```
❯ npm install --global @microsoft/rush                                             
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @rushstack/rush-amazon-s3-build-cache-plugin@5.107.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

## Repro steps

1. Run `npm install --global @microsoft/rush`

  **Expected result:** 

Rush is installed

  **Actual result:** 

Rush is not installed

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.100.1|
| `rushVersion` from rush.json? | 5.100.1 |
| `useWorkspaces` from rush.json? | null |
| Operating system? | Mac, happening in GitHub Actions Linux Runner too |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 18.17.0 |

**Comment by AndrewCudworthAB** [comment]
Seems like a bad update was published

https://www.npmjs.com/package/@microsoft/rush?activeTab=versions
![image](https://github.com/microsoft/rushstack/assets/101130611/46cfe242-0884-400a-aa4f-5b9e18c2f00f)

**Comment by rahmatputrawiranata** [comment]
is it already solve ?

**Comment by fahmifan** [comment]
hapends on my end too

**Comment by samueldominguez** [comment]
Also failing to install here `No matching version found for @rushstack/rush-amazon-s3-build-cache-plugin@5.107.3`

**Comment by iclanton** [comment]
This is fixed now. Looks like you all hit this during a brief period when Rush 5.107.3 was not fully published.
