### ISSUE TITLE
[heft] `ERR_ILLEGAL_CONSTRUCTOR` when running `heft clean`

### ISSUE THREAD

**Issue by Niek** [microsoft/rushstack#4351]
See below:

```bash
❯ node -v
v20.7.0
❯ npx heft clean
TypeError [ERR_ILLEGAL_CONSTRUCTOR]: Illegal constructor
```

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | v0.61.0 |
| Operating system? | macOS |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v20.7.0 |

**Comment by iclanton** [comment]
The Heft package's full name is `@rushstack/heft`.

If you already have Heft installed locally (i.e. - this is actually running our Heft), can you provide a stacktrace?
