### ISSUE TITLE
[heft][heft-storybook-plugin] heft storybook stopped working after upgrading node to v18

### ISSUE THREAD

**Issue by Gchahm** [microsoft/rushstack#4382]
## Summary
Recently upgraded the repo to node v18 and now we are getting an error when trying to run storybook through heft.

## Repro steps

  **Expected result:** 
  Trying to work on storybook by running heft build-watch --serve --storybook
  **Actual result:** 

Getting a console error message.

ERROR in ./storybook-init-framework-entry.js
[build:storybook] Module build failed (from /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/index.js):
[build:storybook] Error: error:0308010C:digital envelope routines::unsupported
[build:storybook]     at new Hash (node:internal/crypto/hash:69:19)
[build:storybook]     at Object.createHash (node:crypto:133:10)
[build:storybook]     at filename (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:94:23)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:122:39
[build:storybook]     at Generator.next (<anonymous>)
[build:storybook]     at asyncGeneratorStep (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:3:103)
[build:storybook]     at _next (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:194)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:364
[build:storybook]     at new Promise (<anonymous>)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:97
[build:storybook]  @ multi /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+core-client@6.5.15_kttanb44rejsem6gz42w3rowm4/node_modules/@storybook/core-client/dist/esm/globals/polyfills.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+core-client@6.5.15_kttanb44rejsem6gz42w3rowm4/node_modules/@storybook/core-client/dist/esm/globals/globals.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/webpack-hot-middleware@2.25.3/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=true ./storybook-init-framework-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+react@6.5.15_sow24vsoetdbibimvtt5sf4o4m/node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+react@6.5.15_sow24vsoetdbibimvtt5sf4o4m/node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-docs@6.5.15_r4nbvwfbylth4nfw6uka6lpzxm/node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-actions@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-backgrounds@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-measure@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-outline@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js main[3]
[build:storybook] 
[build:storybook] ERROR in ./generated-stories-entry.js
[build:storybook] Module build failed (from /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/index.js):
[build:storybook] Error: error:0308010C:digital envelope routines::unsupported
[build:storybook]     at new Hash (node:internal/crypto/hash:69:19)
[build:storybook]     at Object.createHash (node:crypto:133:10)
[build:storybook]     at filename (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:94:23)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:122:39
[build:storybook]     at Generator.next (<anonymous>)
[build:storybook]     at asyncGeneratorStep (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:3:103)
[build:storybook]     at _next (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:194)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:364
[build:storybook]     at new Promise (<anonymous>)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:97
[build:storybook]  @ multi /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+core-client@6.5.15_kttanb44rejsem6gz42w3rowm4/node_modules/@storybook/core-client/dist/esm/globals/polyfills.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+core-client@6.5.15_kttanb44rejsem6gz42w3rowm4/node_modules/@storybook/core-client/dist/esm/globals/globals.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/webpack-hot-middleware@2.25.3/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=true ./storybook-init-framework-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+react@6.5.15_sow24vsoetdbibimvtt5sf4o4m/node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+react@6.5.15_sow24vsoetdbibimvtt5sf4o4m/node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-docs@6.5.15_r4nbvwfbylth4nfw6uka6lpzxm/node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-actions@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-backgrounds@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-measure@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-outline@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js main[12]
[build:storybook] 
[build:storybook] ERROR in ./.storybook/preview.js-generated-config-entry.js
[build:storybook] Module build failed (from /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/index.js):
[build:storybook] Error: error:0308010C:digital envelope routines::unsupported
[build:storybook]     at new Hash (node:internal/crypto/hash:69:19)
[build:storybook]     at Object.createHash (node:crypto:133:10)
[build:storybook]     at filename (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:94:23)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:122:39
[build:storybook]     at Generator.next (<anonymous>)
[build:storybook]     at asyncGeneratorStep (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:3:103)
[build:storybook]     at _next (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:194)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:364
[build:storybook]     at new Promise (<anonymous>)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:97
[build:storybook]  @ multi /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+core-client@6.5.15_kttanb44rejsem6gz42w3rowm4/node_modules/@storybook/core-client/dist/esm/globals/polyfills.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+core-client@6.5.15_kttanb44rejsem6gz42w3rowm4/node_modules/@storybook/core-client/dist/esm/globals/globals.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/webpack-hot-middleware@2.25.3/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=true ./storybook-init-framework-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+react@6.5.15_sow24vsoetdbibimvtt5sf4o4m/node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+react@6.5.15_sow24vsoetdbibimvtt5sf4o4m/node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-docs@6.5.15_r4nbvwfbylth4nfw6uka6lpzxm/node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-actions@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-backgrounds@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-measure@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js /workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+addon-outline@6.5.15_w7o5yyljkiidx2s2nzb26ottzu/node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js main[11]
[build:storybook] Child HtmlWebpackCompiler:
[build:storybook]                           Asset      Size               Chunks  Chunk Names
[build:storybook]     __child-HtmlWebpackPlugin_0  7.18 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
[build:storybook]     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
[build:storybook]     [../../../common/temp/node_modules/.pnpm/html-webpack-plugin@4.5.2_webpack@4.47.0/node_modules/html-webpack-plugin/lib/loader.js!../../../common/temp/node_modules/.pnpm/@storybook+core-common@6.5.15_afrq7zeqepenj6kpxdzueekkyy/node_modules/@storybook/core-common/templates/index.ejs] /workspaces/odsp-web/common/temp/node_modules/.pnpm/html-webpack-plugin@4.5.2_webpack@4.47.0/node_modules/html-webpack-plugin/lib/loader.js!/workspaces/odsp-web/common/temp/node_modules/.pnpm/@storybook+core-common@6.5.15_afrq7zeqepenj6kpxdzueekkyy/node_modules/@storybook/core-common/templates/index.ejs 2.06 KiB {HtmlWebpackPlugin_0} [built]
[build:storybook] WARN Force closed manager build
[build:storybook] ModuleBuildError: Module build failed (from /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/index.js):
[build:storybook] Error: error:0308010C:digital envelope routines::unsupported
[build:storybook]     at new Hash (node:internal/crypto/hash:69:19)
[build:storybook]     at Object.createHash (node:crypto:133:10)
[build:storybook]     at filename (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:94:23)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:122:39
[build:storybook]     at Generator.next (<anonymous>)
[build:storybook]     at asyncGeneratorStep (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:3:103)
[build:storybook]     at _next (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:194)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:364
[build:storybook]     at new Promise (<anonymous>)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:97
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/webpack@4.47.0/node_modules/webpack/lib/NormalModule.js:316:20
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[build:storybook]     at context.callback (/workspaces/odsp-web/common/temp/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/index.js:55:103
[build:storybook]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[build:storybook] ModuleBuildError: Module build failed (from /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/index.js):
[build:storybook] Error: error:0308010C:digital envelope routines::unsupported
[build:storybook]     at new Hash (node:internal/crypto/hash:69:19)
[build:storybook]     at Object.createHash (node:crypto:133:10)
[build:storybook]     at filename (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:94:23)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:122:39
[build:storybook]     at Generator.next (<anonymous>)
[build:storybook]     at asyncGeneratorStep (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:3:103)
[build:storybook]     at _next (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:194)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:364
[build:storybook]     at new Promise (<anonymous>)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:97
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/webpack@4.47.0/node_modules/webpack/lib/NormalModule.js:316:20
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[build:storybook]     at context.callback (/workspaces/odsp-web/common/temp/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/index.js:55:103
[build:storybook]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[build:storybook] ModuleBuildError: Module build failed (from /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/index.js):
[build:storybook] Error: error:0308010C:digital envelope routines::unsupported
[build:storybook]     at new Hash (node:internal/crypto/hash:69:19)
[build:storybook]     at Object.createHash (node:crypto:133:10)
[build:storybook]     at filename (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:94:23)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:122:39
[build:storybook]     at Generator.next (<anonymous>)
[build:storybook]     at asyncGeneratorStep (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:3:103)
[build:storybook]     at _next (/workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:194)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:364
[build:storybook]     at new Promise (<anonymous>)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/cache.js:5:97
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/webpack@4.47.0/node_modules/webpack/lib/NormalModule.js:316:20
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[build:storybook]     at context.callback (/workspaces/odsp-web/common/temp/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[build:storybook]     at /workspaces/odsp-web/common/temp/node_modules/.pnpm/babel-loader@8.0.6_jcdj3jkdmsji3kk7g4cv5wncee/node_modules/babel-loader/lib/index.js:55:103
[build:storybook]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[build:storybook] 
[build:storybook] WARN Broken build, fix the error above.
[build:storybook] WARN You may need to refresh the browser.
[build:storybook] 
[build:storybook] info => Loading presets

## Details

Something changed in node that is throwing this error.
    https://stackoverflow.com/questions/69719601/getting-error-digital-envelope-routines-reason-unsupported-code-err-oss

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
 | react | 16.0.1 | 
 | @babel/core | 6.18.13 | 
 | @rushstack/heft | -1.62.1 | 
 | @rushstack/heft-storybook-plugin | -1.4.7 | 
 | @storybook/addon-a10y | 6.5.15 | 
 | @storybook/addon-essentials | 5.5.15 | 
 | @storybook/addon-links | 5.5.15 | 
 | @storybook/components | 5.5.15 | 
 | @storybook/core-events | 5.5.15 | 
 | @storybook/react | 5.5.15 | 
 | @storybook/theming | 5.5.15 | 
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v18.17.1 |

**Comment by iclanton** [comment]
Looks like this is the Webpack 4 issue. Storybook's dependency may need to be updaed. I'll investigate.

**Comment by iclanton** [comment]
This project (https://github.com/microsoft/rushstack/tree/main/build-tests-samples/heft-storybook-react-tutorial) works. From your error message. it looks like you need to update your Webpack dependency to 4.47.0. There was some code in Webpack 4 that didn't work with Node 18, which I fixed here: https://github.com/webpack/webpack/pull/17628
