### ISSUE TITLE
[rush] EBADENGINE warnings when installing the latest version with Node 20

### ISSUE THREAD

**Issue by kaiyoma** [microsoft/rushstack#4418]
## Summary

Installing the latest version of Rush with Node 20 results in warnings in the output.

## Repro steps

Install Node 20, then install Rush 5.110.1:

```
$ npm install -g @microsoft/rush@latest
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.2.2' }
npm WARN EBADENGINE }
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated read-package-tree@5.1.6: The functionality that this package provided is now in @npmcli/arborist
npm WARN deprecated debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

added 2 packages, removed 6 packages, and changed 567 packages in 27s
```

## Details

This problem has already been fixed in @azure/msal-node (https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6234). However, it appears that Rush is using an older version of this library: 1.18.4, versus 2.4.0 (the latest).

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.110.1 |
| `rushVersion` from rush.json? | 5.110.1 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Windows 11 |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 20.9.0 |

**Comment by iclanton** [comment]
This has been released in Rush 5.112.0.
