### ISSUE TITLE
[rush] Properly support current LTS node version

### ISSUE THREAD

**Issue by emlynmac** [microsoft/rushstack#4440]
## Summary
NodeJS 20 is LTS now, but rush still complains:

`Your version of Node.js (20.5.0) is not a Long-Term Support (LTS) release. These versions frequently have bugs. Please consider installing a stable release.`

## Repro steps
Use NodeJS 20.x and run rush.

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? | 5.112.1 |
| `useWorkspaces` from rush.json? | |
| Operating system? | Mac/Linux |

| Node.js version (`node -v`)? | 20.x|

**Comment by iclanton** [comment]
Node `20.5.0` isn't actually a LTS release. The first release of Node 20 that is LTS is `20.9.0`. To get rid of that warning, upgrade to `20.9.0`.
