### ISSUE TITLE
[rush] Regression: folderToCopy creates subfolder in deploy folder

### ISSUE THREAD

**Issue by nlochschmidt** [microsoft/rushstack#4444]
## Summary

In rush version 5.107.4 the `folderToCopy` option in `deploy.json` works as [documented](https://rushjs.io/pages/configs/deploy_json/) and places the files in the referenced folder top-level into `common/deploy`. From version 5.108.0 onwards however a subfolder gets created in `common/deploy`.

## Repro steps

1. Create a `deploy.json` with a `folderToCopy` pointing to a folder with some files
2. Run `rush deploy --overwrite` in version 5.107.4 and check `common/deploy` to see the files top-level
3. Switch to any version from 5.108.0 to 5.112.1
4. Run `rush deploy --overwrite` again and check `common/deploy` to see the files now inside of a folder with the name of the source folder

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.112.1 |
| `rushVersion` from rush.json? | 5.112.1 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 18.18.4 |

**Comment by iclanton** [comment]
Fixed in Rush `5.112.2`.
