### ISSUE TITLE
[rush] rush version bump type - `preminor` behavior not replicable

### ISSUE THREAD

**Issue by anmolshres98** [microsoft/rushstack#4445]
Hi, I believe the `preminor` flag is useful and should not have been removed. Our recent upgrade to rush version 5.100.x is failing since `preminor` is not an option anymore. We have been using the `preminor` flag from the cli by running `rush version --override-bump preminor --version-policy ... --bump --override-prelease-id dev`. This would change the version to the next minor version-dev.0. For example, if the current version is 3.1.5 it would set the version to 3.2.0-dev.0. 

This behavior cannot be replicated with the `prerelease` flag. It seems that rush assumes the next release version would be a patch release instead of a minor release when using that flag. Specifically, if prerelease flag is used, in the above example, the version goes from 3.1.5 to 3.1.6-dev.0. This is not the same effect as `preminor` and not what we want to do.

Is there a way to replicate the effect of `preminor` as I have mentioned in my example?

**Comment by iclanton** [comment]
This was removed by https://github.com/microsoft/rushstack/pull/4157. We should partially revert that PR.

**Comment by iclanton** [comment]
Fixed in Rush `5.112.2`.
