### ISSUE TITLE
[rush] rush init without `common/scripts` folder.

### ISSUE THREAD

**Issue by leohxj** [microsoft/rushstack#4474]
I run `rush init` in a new project, learning from [Setting up a new repo | Rush](https://rushjs.io/pages/maintainer/setup_new_repo/)

## Summary
The generate Rush's config files does not include `common/scripts`,  but in the section [Enabling CI builds | Rush](https://rushjs.io/pages/maintainer/enabling_ci_builds/), it say " All Rush repos come with a script common/scripts/install-run-rush.js".

## Repro steps

  **Expected result:** 
- Here is a folder called `common/scripts` and it containers some files like: [rush-example/common/scripts at main · microsoft/rush-example](https://github.com/microsoft/rush-example/tree/main/common/scripts)

  **Actual result:** 
- no `common/scripts` folders and its files.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | Y |
| `rushVersion` from rush.json? | 5.112.2 |
| `useWorkspaces` from rush.json? | N |
| Operating system? | Mac |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v18.19.0 |

**Comment by leohxj** [comment]
got it, need run `rush install` or `rush update`.

**Comment by iclanton** [comment]
Yeah, that folder gets updated when you run `rush update`.
