### ISSUE TITLE
[rush] Rush build will incorrectly save the information output during the project build process to the error.log file

### ISSUE THREAD

**Issue by hx-dl** [microsoft/rushstack#4488]
## Repro steps

  **Expected result:** The result of executing rush build is consistent with the result of executing rushx build under projectFolder

  **Actual result:** When executing rushx build under projectFolder, only the build.log file will exist and no error.log file will be generated. However, when executing with rush build --to projectName, both error.log and build.log files will be generated

## Details
<img width="1144" alt="image" src="https://github.com/microsoft/rushstack/assets/36653037/e15b161c-b592-4e02-9d4a-0fd1631d175c">
<img width="561" alt="image" src="https://github.com/microsoft/rushstack/assets/36653037/a7aaaa5c-e268-431b-ac01-3a6262633b87">
<img width="745" alt="image" src="https://github.com/microsoft/rushstack/assets/36653037/4bc34496-f9cc-4291-be06-e54339572a2d">

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.112.2 |
| `rushVersion` from rush.json? | 5.112.2 |
| `useWorkspaces` from rush.json? | true |
| Operating system? |  Mac  |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v16.20.2 |

**Comment by iclanton** [comment]
It looks like your tool is writing to STDERR, which is treated as error output in Rush bulk commands. You can override this behavior in `command-line.json` by setting the `allowWarningsInSuccessfulBuild` option to `true` for your command, but keep in mind that this will ignore everything that writes to STDERR and will only fail builds if the process exits with a nonzero exit code.
