### ISSUE TITLE
[api-extractor-model] Broken link

### ISSUE THREAD

**Issue by matthias-ccri** [microsoft/rushstack#4519]
There's a broken link in the readme of the @microsoft/api-extractor-model package

https://github.com/microsoft/rushstack/blob/083a8e08b2921f5dcb9839447113fde43f38f44f/libraries/api-extractor-model/README.md#L7

> API documentation for this package: https://rushstack.io/pages/api/api-extractor-model/

![image](https://github.com/microsoft/rushstack/assets/18034092/99b733f1-1888-4fea-b3da-c8627819dcd7)

**Comment by iclanton** [comment]
Fixed by https://github.com/microsoft/rushstack/pull/4520
