### ISSUE TITLE
[eslint-patch]  Upgrade to ESLint 9

### ISSUE THREAD

**Issue by Nixie24** [microsoft/rushstack#4635]
ESLint v9.0.0 is [released](https://eslint.org/blog/2024/04/eslint-v9.0.0-released) 🎉

It would be awesome to have official ESLint 9 support. 🙂

**Comment by iclanton** [comment]
I'm pretty sure there are a bunch of breaking changes in ESLint 9, so this may take some effort. If someone wants to take that on, we'd happily take it. For now, it'll be a lower priority for our team.

**Comment by kirill-konshin** [comment]
Even with recent fixup https://eslint.org/blog/2024/05/eslint-compatibility-utilities/ it fails:

```
Oops! Something went wrong! :(

ESLint: 9.2.0

Error: Failed to patch ESLint because the calling module was not recognized.
If you are using a newer ESLint version that may be unsupported, please create a GitHub issue:
https://github.com/microsoft/rushstack/issues
    at Object.<anonymous> (/xxx/node_modules/@rushstack/eslint-patch/lib/_patch-base.js:165:19)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/xxx/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js:11:23)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
```

Just in case this helps...

The fixup works with configs (actual objects returned from config), and eslint-patch is usually called inside config. It might be useful to just disable some functionality if ESLint 9 is detected...

**Comment by kirill-konshin** [comment]
Thanks @nzakas for prompt response and fix. I assume we now have to wait for release and propagation to other packages like Next.js rules set?

**Comment by D4N14L** [comment]
@kirill-konshin yes. Publish is manually triggered. You can either choose to wait for the next publish, or you can request a publish from one of the senior maintainers.

**Comment by DmitryMarkov** [comment]
> Even with recent fixup https://eslint.org/blog/2024/05/eslint-compatibility-utilities/ it fails:

Same for me

**Comment by kirill-konshin** [comment]
@D4N14L was it published? I'm getting the same error https://github.com/microsoft/rushstack/issues/4965#issuecomment-2447809752 but with shareable config.

**Comment by D4N14L** [comment]
@kirill-konshin yes it is published, though I don't know if support for shareable configs requires any additional work. Could you share a repro?

**Comment by kirill-konshin** [comment]
@D4N14L sure, here you go: https://stackblitz.com/edit/stackblitz-starters-zxpfgk?file=eslint.config.mjs,package.json

It does not reproduce there directly, but if you download a zip and run

```
$ yarn set version berry
$ yarn lint
```

Then it will fail.

The problem is interference with newer Yarn it seems. Also I purposely made it a monorepo.

**Comment by kirill-konshin** [comment]
@D4N14L any chances to have this fixed? Can I help?

**Comment by D4N14L** [comment]
@kirill-konshin to be honest I don't think I'll be able to look any time soon. If you can create a fix or investigate a fix, that would be appreciated.

**Comment by kirill-konshin** [comment]
@D4N14L I don't really think I can, since the error originates from the module resolution patch and Yarn's `nodeLinker: node-modules` config.

BUT! On a positive side, I've just tested my custom config with Yarn's `nodeLinker: pnpm` (not `pnp`!) and it magically worked just fine.

So in addition to my reproduction scenario before, I can reliably say it works well with Yarn 1 and Yarn 2+ with `nodeLinker: node-modules`.

**Comment by D4N14L** [comment]
@kirill-konshin nice! So then seems possibly an issue with pnp compatibility in ESLint instead of anything that we have done. Glad to hear :)

**Comment by kirill-konshin** [comment]
> [@kirill-konshin](https://github.com/kirill-konshin) nice! So then seems possibly an issue with pnp compatibility in ESLint instead of anything that we have done. Glad to hear :)

Not PNP but original `node-modules` linker...

**Comment by D4N14L** [comment]
Ah interesting. Then possibly an issue with shadow dependencies given that PNPM brings more dependency correctness with its algorithm

**Comment by kirill-konshin** [comment]
@D4N14L looks like something changed over time and I can no longer reproduce this. Works like charm.
