### ISSUE TITLE
[rush] The source code address for the 'rush build' command.

### ISSUE THREAD

**Issue by tianmagongyue** [microsoft/rushstack#4663]
When I read the Rush's code, I've been unable to find the logic for the 'rush build' command in this directory 'libraries/rush-lib/src/cli/actions/'. I hope for someone can point me in the right direction as to where I can find the code for 'rush build'.

**Comment by iclanton** [comment]
Unless custom `build` and/or `rebuild` commands are specified in `common/config/rush/command-line.json`, the default commands are initialized here: https://github.com/microsoft/rushstack/blob/129a6cf1cb3dd27497b5b32b9ffc8171ee2a9c17/libraries/rush-lib/src/api/CommandLineConfiguration.ts#L449-L480

`rush build` ends up being initialized as an instance of a [`PhasedScriptAction`](https://github.com/microsoft/rushstack/blob/main/libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts)
