### ISSUE TITLE
[eslint-bulk] eslint-bulk-suppressions-test fails to build

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#4691]
## Summary

I was able to reproduce this error locally.  The output looks like:

```
-- Running eslint-bulk-suppressions for eslint@8.57.0 in client --
STDOUT:

STDERR:
@rushstack/eslint-bulk: Error finding patch path: Command failed: C:\Program Files\nodejs\node.exe C:/Git/rushstack/common/temp/default/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/./bin/eslint.js --stdin --config C:\Git\rushstack\build-tests\eslint-bulk-suppressions-test\client/.eslintrc.js
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.


------------------------------------------------------------------
```

It looks like a regression caused by PR ##4627
 

## Details
 

The problem is that this code is pasting strings together without proper escaping:

https://github.com/microsoft/rushstack/blob/fb711c10a4ed1560305f7ddc168f00f549a2d1ec/eslint/eslint-bulk/src/start.ts#L69-L82

On Windows, the `eslintBinCommand` string has this value: `"C:\\Program Files\\nodejs\\node.exe C:/Git/rushstack/common/temp/default/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/./bin/eslint.js"`.

@iclanton I'm not sure this is even solvable using `execSync()`.  The best known solution is `Executable.spawnSync()` (which still acknowledges that certain characters are impossible to escape on Windows).  But avoiding that dependency, we should at least use `spawnSync()` instead of `execSync()` here.

**Comment by trickpattyFH20** [comment]
@iclanton @octogonz I still see this error with a fresh install:
```
eslint-bulk suppress --all ./sites

@rushstack/eslint-bulk: Error finding patch path. Are you sure the package you are in has @rushstack/eslint-patch as a direct or indirect dependency?
```

**Comment by octogonz** [comment]
I tried the following commands:

```
cd rushstack/build-tests/eslint-bulk-suppressions-test/client

rush install && rush build -t .

npm install -g @rushstack/eslint-bulk

eslint-bulk suppress --all ./
```

It runs successfully - no problems.

This issue #4691 is already closed.  @trickpattyFH20 could you create a new GitHub issue so we can track this properly? Include clear step-by-step instructions to reproduce the error that you encountered.
