### ISSUE TITLE
[lockfile-explorer] missing dependencies for first init

### ISSUE THREAD

**Issue by harttle** [microsoft/rushstack#4705]
## Summary

I installed lockfile-explorer and run it immediately.

## Repro steps

Following docs here: https://github.com/microsoft/rushstack/tree/main/apps/lockfile-explorer

```bash
npm install -g @rushstack/lockfile-explorer
lockfile-explorer
```

The second command fails.

  **Expected result:** 

Not throw error.

  **Actual result:** 

Outputs following and exits with non-zero code.

```text
➜  tmp git:(macos) ✗ npm install -g @rushstack/lockfile-explorer


changed 178 packages in 2s
➜  tmp git:(macos) ✗ lockfile-explorer

node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '@microsoft/rush-lib/lib/api/RushConfiguration'
Require stack:
- ~/.nvm/versions/node/v18.12.1/lib/node_modules/@rushstack/lockfile-explorer/lib/init.js
- ~/.nvm/versions/node/v18.12.1/lib/node_modules/@rushstack/lockfile-explorer/lib/start.js
- ~/.nvm/versions/node/v18.12.1/lib/node_modules/@rushstack/lockfile-explorer/bin/lockfile-explorer
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/lockfile-explorer` version? | 1.4.3 |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | v18.12.1 |

**Comment by iclanton** [comment]
This was fixed by https://github.com/microsoft/rushstack/pull/4697.
