### ISSUE TITLE
[rush] Vulnerability for @azure/identity flagged by component governance

### ISSUE THREAD

**Issue by briancmpbll** [microsoft/rushstack#4785]
## Summary

When running a build in ADO with the latest rush version component governance flags https://github.com/advisories/GHSA-m5vv-6r4h-3vj9 as a moderate vulnerability which is due to @azure/identity version 4.0.1.

## Details

The nesting of this is as follows:
  @microsoft/rush-lib@5.128.1
  ├─ @rushstack/rush-azure-storage-build-cache-plugin@5.128.1
  │  ├─ @azure/identity@4.0.1

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.128.1 |
| `rushVersion` from rush.json? | 5.128.1 |
| `useWorkspaces` from rush.json? | yes |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 20.9.0 |

**Comment by octogonz** [comment]
@iclanton FYI
