### ISSUE TITLE
[rush] `rush add -p pkg@some_version --make-consistent` to update a installed old version pkg will update all projects not a subapce's projects

### ISSUE THREAD

**Issue by hhheroo** [microsoft/rushstack#4789]
## Summary

With rush(5.124.7). I'd like to update a package version to latest in a specific subapce by using `rush add -p @pkg@latest` or `rush add -p pkg@some_vesrsion`, this error occurs.
![7bd63bd2-d4e2-445d-88ef-a5c12cb7d7dc](https://github.com/microsoft/rushstack/assets/126048826/b8e617b7-f940-4c4c-a9e9-dbe11700723e)
While following the message add "--make-consistent", `rush add -p @pkg@some_version --make-consistent`, it updates all projects package.json those in different subspaces.
![image](https://github.com/microsoft/rushstack/assets/126048826/a167073c-df1d-4cb6-8408-e3680355a1ad)

## Repro steps
- open a monorepo with at least two subspaces.
- using `rush add -p pkg@new_version --make-consistent` to update a pkg's version which an old version already installed.

  **Expected result:** 

update current subspace's projects package.json.

  **Actual result:** 

update all projects package.json, those projects are used the package.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.128.0|
| `rushVersion` from rush.json? | 5.124.7 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | macOS 14.5 |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v18.20.3 |

**Comment by iclanton** [comment]
I believe this is the expected behavior for `--make-consistent`. @octogonz/@g-chao?

**Comment by octogonz** [comment]
@william2958 FYI
