### ISSUE TITLE
[rush] `rush-pnpm store prune` returns exit code 1 since 5.126.0

### ISSUE THREAD

**Issue by koen-dev** [microsoft/rushstack#4795]
## Summary

Ever since updating Rush to `5.126.0` and later the `rush-pnpm store prune` command returns exit code 1. Even though it looks to be working correctly and no further error information can be found.

## Repro steps

Reproducible repository: https://github.com/koen-dev/rush-pnpm-store-prune-bug
1. Clone the project above
2. Run `rush install` or `rush update`
3. Run `rush-pnpm store prune`
4. Run `$?` to get the exit code

  **Expected result:** Either a clearer error message or exit code 0

  **Actual result:** exit code 1

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.129.1 |
| `rushVersion` from rush.json? | 5.126.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Mac & Linux in CI |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v18.20.2 |

**Comment by iclanton** [comment]
This is fixed in Rush 5.129.2

**Comment by koen-dev** [comment]
Thanks for the quick fix @iclanton 🙌🎉
