### ISSUE TITLE
[rush] shrinkwrapIsUpToDate does not take globalOverrides into account

### ISSUE THREAD

**Issue by fzxen** [microsoft/rushstack#4820]
## Summary

After I modified the `globalOverrides` field in `common/config/rush/pnpm-config.json`, I hope rush can remind me to execute` rush update` to update lockfile. However, I didn't encounter any errors when I executed `rush install`. And lockfile also did not be updated. 

## Repro steps

1. modify the globalOverrides field in `common/config/rush/pnpm-config.json`
2. run `rush install` in workspace.

  **Expected result:** 

Rush should throw an error and remind me: _The shrinkwrap file is out of date. You need to run "rush update"_.

  **Actual result:** 

Install successfully. There are no changes about git tracked files in our repo, but the `common/temp/pnpm-lock.yaml` has indeed been updated.

Actually,  The lockfile was not updated even after I executed the `rush update`. Only after executing `rush update --recheck` will the lockfile be updated correctly. 

## Details

I guess the logic of judging whether shrinkwraps is updated does not take globalOverrides into account and not sure whether this is intentional.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.129.6 |
| `rushVersion` from rush.json? | 5.129.6 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Mac |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? | v16.20.2 |

**Comment by iclanton** [comment]
Looks like we need to ensure the `packageExtensionsChecksum` is up-to-date.

Would you be interested in contributing this fix?

**Comment by fzxen** [comment]
@iclanton OK, I will take a look at the relevant implementations in rush and try to create a PR.
