### ISSUE TITLE
rush-pnpm patch-commit not generating patch file

### ISSUE THREAD

**Issue by benkeen** [microsoft/rushstack#4827]
We make occasional use of `rush-pnpm patch [package name]` for dire situations when altering an external package is our only option. 

Perhaps I'm doing something daft, but I think the process was:
- run `rush-pnpm patch [package name]@[package version]`
- edit the file(s) in the temporary folder that's generated
- run the command that's output on the command line to complete the transaction, generate the patch file of changes and update pnpm-config.json. 

We updated to rush@5.128.5 a little while ago and this command no longer works. The command doesn't throw any errors, but no patch file is generated + the pnpm-config.json file isn't altered to add the new file. 

I did notice the command that it tells you to run has changed since our last Rush update. Now it looks like:

`rush-pnpm --subspace default patch-commit /private/var/folders/7f/h61q2x553xb63r1mnflg1jdr0000gn/T/fcf8d612d892c2aec319704efa7bc5f0` 

Pretty sure the `--subspace default` is new (?) but even without it it doesn't do anything. So not sure if that's the cause. Thanks!

**Comment by iclanton** [comment]
Sounds like this was broken by subspaces. @octogonz, can you have someone take a look?

**Comment by benkeen** [comment]
Huh, works again. Thanks @iclanton! Should've tried that.

**Comment by octogonz** [comment]
> We updated to rush@5.128.5 a little while ago and this command no longer works.

Looking at [CHANGELOG.md](https://github.com/microsoft/rushstack/blob/main/apps/rush/CHANGELOG.md#51292), there was a fix for `rush-pnpm` in 5.128.2.  But maybe your issue was actually this one:

5.129.2
- Fix an issue where the `rush pnpm ...` command always terminates with an exit code of 1.
