### ISSUE TITLE
[rush] Feature Request: Support PNPM 9

### ISSUE THREAD

**Issue by kenrick95** [microsoft/rushstack#4841]
## Summary

Rush should support [PNPM 9](https://github.com/pnpm/pnpm/releases/tag/v9.0.0), which has a breaking change on the lockfile format.

Based on the conversation in [Zulipchat](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/PNPM.209.20compatibility): 

> @jeremymeng 
> Last time I checked PNPM v9 on our repo (azure/azure-sdk-for-js) there are changes that broke PnpmShrinkwrapFile. It seems that some properties got moved around in he parsed yaml data.

When directly bumped in my company's repo, I observed that `rush update` successfully upgraded the lockfile in the temp folder (`common/temp/pnpm-lock.yaml`), but it wasn't synced back to `common/config/rush/pnpm-lock.yaml`. Not really sure why..

I tried bumping the PNPM version in in the Rushstack repo and tried to build, but seems like [pnpm-sync](https://github.com/tiktok/pnpm-sync) also needs to be modified to support PNPM 9.

## Repro steps

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.129.7 |
| `rushVersion` from rush.json? | 5.117.8 |
| `useWorkspaces` from rush.json? | Yes |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 18.20.3 |

**Comment by iclanton** [comment]
@g-chao - Would you take a look at this?

**Comment by dbartholomae** [comment]
Is this something where external PRs would be accepted?

**Comment by VasekProchazka** [comment]
Hello, what is the current status ?

**Comment by matthieu-foucault** [comment]
I just tried on our monorepo and everything seems to be working fine with pnpm v9.12.3, rush v5.140.1. 
Should I expect some issues with pnpm v9?

**Comment by iclanton** [comment]
@dbartholomae - we're happy to accept external PRs.

**Comment by dbartholomae** [comment]
I just tried updating pnpm to version 9, and it worked without additional changes (except for pnpm internal things, like the fact that pre and post hooks now are enabled by default). So there doesn't seem to be need for a PR anymore, and maybe this issue can be closed - unless anyone else still runs into trouble?

**Comment by prabirshrestha** [comment]
@dbartholomae curious if you have tried pnpm catalog feature that was introduced in v9 and if it works. https://pnpm.io/catalogs

**Comment by dbartholomae** [comment]
We don't use them, so I can't really tell

**Comment by fzxen** [comment]
@dbartholomae After upgrading to v9 and executing the `rush install/update` command, you will find that the content of the `.rush/temp/shrinkwrap-deps.json` file is incorrect. As you can see, rush is currently unable to correctly parse lockfile v9. Thus, Rush cache system doesn't work fine with pnpmv9 because rush will generate a cacheId based on the hash of `shrinkwrap-deps.json`. I have submitted a PR to fix this issue. https://github.com/microsoft/rushstack/pull/5009.

**Comment by kenrick95** [comment]
Looks like #5009 has been merged and released as `@microsoft/rush@5.146.0`. Thanks a lot @fzxen!
