### ISSUE TITLE
[rush] feature request: support pnpm's `ignoredOptionalDependencies` setting in pnpm-config.json

### ISSUE THREAD

**Issue by joelrbrandt** [microsoft/rushstack#4859]
## Summary

pnpm has an [`ignoredOptionalDependencies` setting](https://pnpm.io/package_json#pnpmignoredoptionaldependencies) that is not yet supported by rush's pnpm-config.json

I would like to use it to ignore specific optional dependencies! 😄 

## Details

My specific use case is that I rely on a package (`fabric@5.3.0`) that has an optional dependency on `canvas`. For the way I'm using fabric, I don't need canvas. Moreover, `canvas` happens to be complicated to build on ARM linux. So, rather than going through the complication of getting `canvas` to build, I want to ignore that optional dependency, because I don't actually need it for the way I am using `fabric`.

As a workaround, I can use the existing `globalNeverBuiltDependencies` feature. But this isn't great, because if I someday add another dependency that _requires_ canvas (as a regular dependency), it will be installed, but its build will be skipped and it will be really non-obvious why my code isn't working.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.131.0 |
| `rushVersion` from rush.json? | 5.131.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | all |
| Would you consider contributing a PR? | yes, but I don't know how to test for problems this change would cause |
| Node.js version (`node -v`)? | 20.15.1 |

**Comment by iclanton** [comment]
This should be pretty easy to put together. Similar to the other options in that file, adding support for this option just involves updating the schema and the `rush init` template, and reading that property from the file and setting it in the generated `/common/temp/package.json` file.

**Comment by glitchkyle** [comment]
I would like to give this a try!
