### ISSUE TITLE
[heft] Rush stack heft plugins preventing webpack security upgrades

### ISSUE THREAD

**Issue by DavidRieman** [microsoft/rushstack#4946]
## Summary
Currently there is a webpack security issue with a released fix at 5.95.0.  However, the latest released versions of the heft plugins currently, through restrictive peer dependencies, do not cleanly allow users to upgrade past 5.82.

## Repro steps
From a rush stack monorepo, try to upgrade just webpack.  That'll force the usual cascading series of work where you also have to also upgrade a series of other rush stack pieces due to restrictive versioning (for better or worse).  In the end you get a bit blocked though because none of the rush stack heft plugins accommodate trying out newer tech.  Produces error like:
```
└─┬ @rushstack/heft-webpack5-plugin 0.10.12
  └── ✕ unmet peer webpack@~5.82.1: found 5.95.0
```

## Details
There are likely workarounds ranging from bad (setting up version overrides) to worse (removing strict peer dependencies altogether).
Perhaps the most realistic solution ATM would be to test and release plugin versions which allow the latest webpack.

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.64.5 up to 0.67.2 |
| Operating system? | Windows and Mac |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v18.17.1 |

**Comment by iclanton** [comment]
Should be an easy fix, assuming there are no breaking changes in releases since 5.82.

**Comment by dmichon-msft** [comment]
Bit more complicated than expected; there were some breaking strictness changes in typings, and the way the LibManifestPlugin emitted files changed.
