### ISSUE TITLE
[rush] `deploy` command no longer copies the `node_modules/.bin`

### ISSUE THREAD

**Issue by koen-dev** [microsoft/rushstack#4961]
## Repro steps

Reproducible repository: https://github.com/koen-dev/rush-deploy-node-modules-bin-issue

### What were you trying to accomplish?

I was trying to use `rush deploy` to set up a deployment for a project, which includes scripts for database migration using the Prisma CLI.

### What action did you perform that ran into trouble?

After running `rush deploy`, I tried executing `rushx migrate` in the `common/deploy/app1` folder.

### What went wrong?

The command errored out with `'prisma' not found`, indicating that the Prisma CLI wasn't available. I noticed that the `common/deploy/app1/node_modules` directory no longer contains the `.bin` folder, which seems to be the root of the problem. This behavior differs from version `5.134.0`, where the `.bin` folder was present after deploying.

  **Expected result:** Running `rushx migrate` in the `common/deploy/app1` folder should successfully execute the Prisma migration script.

  **Actual result:** Running `rushx migrate` results in an error stating `'prisma' not found` due to the missing `.bin` folder in `common/deploy/app1/node_modules`.

## Details

It looks to be introduced in version `5.135.0` and any later version also contains the same issue.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.135.0 |
| `rushVersion` from rush.json? | 5.135.0 |
| `useWorkspaces` from pnpm-config.json? | true |
| Operating system? | Mac & Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 18.20.4 |

**Comment by Woutwo** [comment]
Yep also running into this with my projects

**Comment by iclanton** [comment]
@D4N14L - can you investigate?

**Comment by sveisvei** [comment]
This happens in node 20 as well, had to roll back to 5.134.0.

**Comment by koen-dev** [comment]
@iclanton & @D4N14L any updates on this? 😇

**Comment by D4N14L** [comment]
Not yet, planning on getting to this at some point this week. Been busy the last little bit, apologies...
