### ISSUE TITLE
[rush] v5.139.0 Breaks Incremental Build

### ISSUE THREAD

**Issue by skaldarnar** [microsoft/rushstack#5004]
## Summary

Rush v5.139.0 breaks incremental building, at least in our project setup. On and above that version, every rush build rebuilds all packages, regardless of changes on the filesystem. On v5.138.0 and below, incremental builds work as expected. We are not using the build cache.

Similar to #4394, but not quite the same.

## Repro steps

- Install version 5.138.0
- Run `rush update && rush build && rush build`, builds are cached 🙂
- Update rush.json to 5.104.0
- Run `rush update && rush build && rush build`, all packages rebuilt 🙁

## Details

We are **not** using the build cache and there are no project-specific `rush-project.json` files. 

`rush --debug build` shows `Incremental strategy: output preservation`.

This is happening on a private repo, but I'm happy to provide more information if needed.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.140.1 |
| `rushVersion` from rush.json? | 5.140.1 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Linux |
| Would you consider contributing a PR? | yes |
| Node.js version (`node -v`)? | v20.18.0 |

**Comment by dmichon-msft** [comment]
This looks to be fixed by #4993 , that just hasn't published yet.
