### ISSUE TITLE
[rush] Add support for the latest LTS version of Node (v22) to Rush repo

### ISSUE THREAD

**Issue by npetruzzelli** [microsoft/rushstack#5033]
## Summary

> We recommend the latest [LTS version](https://nodejs.org/en/download/releases/), because non-stable NodeJS releases frequently have bugs."
> 
> _source: <https://rushjs.io/pages/developer/new_developer/#prerequisites>_

The latest, current LTS version of Node is v22, but trying to use it with Rush results in the following error:

```
ERROR: Your dev environment is running Node.js version v22.2.0 which does not meet the requirements for building this
repository.  (The rush.json configuration requires nodeSupportedVersionRange=">=18.15.0 <19.0.0 || >=20.9.0 <21.0.0")
```
![Image](https://github.com/user-attachments/assets/4d5bb7be-4e08-4f8d-9c6a-1b02cfa9da32)
<https://nodejs.org/en/about/previous-releases>

## Repro steps

1. fork/clone <https://github.com/microsoft/rushstack>
2. install rush: `npm install -g @microsoft/rush`
   - make sure you have pnpm installed that is the same version or higher as the one indicated in `rush.json` . For best results, use the exact version: <https://github.com/microsoft/rushstack/blob/%40microsoft/rush_v5.144.0/rush.json#L19>
   - I am currently running `9.12.2`, but this never gets a chance to be a potential problem
3. execute `rush update` 

  **Expected result:** 
`rush update` executes without issue.

  **Actual result:** 
`rush update` failed with an error that claims Node 22 is not supported, which is contrary to the recommendation on the website.

## Details

Either it has not been tested with Node 22 or the version check script itself is out of date.

A first pass would be updating the script locally, allowing it to run with node 22 and see if test suites pass/fail and determine next steps based on the results of that.

It may be that updating `nodeSupportedVersionRange` in `rush.json` is enough.

I may be making some poor assumptions as I am new to Rush.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | `@microsoft/rush@5.144.0` |
| `rushVersion` from rush.json? | `5.143.0-pr5009.1` |
| `useWorkspaces` from rush.json? | N/A |
| Operating system? | Windows 10 |
| Would you consider contributing a PR? | Yes / if time allows |
| Node.js version (`node -v`)? | `v22.2.0` |

**Comment by iclanton** [comment]
This depends on https://github.com/microsoft/rushstack/pull/5031, as a built-in dependency of `node-fetch@2` is dropped in Node 22. Once that's in, I'll bump Rush to support Node 22.

**Comment by iclanton** [comment]
Related: https://github.com/microsoft/rushstack/issues/5008

**Comment by npetruzzelli** [comment]
@iclanton - Thank you for the swift response to this and #5034 

It is much appreciated!

This will make my life, that of my co-workers, and probably other people out there, that much better.

**Comment by iclanton** [comment]
Glad to help!
