### ISSUE TITLE
[rush] Rename "cyclicDependencyProjects" to something more intuitive

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#547]
Today, if a local Rush **project-a** refers to another local **project-b**, Rush will symlink them together only if the SemVer ranges are compatible (e.g. **project-a** asks for "^1.2.0" and project-b's version is "1.2.3").  Otherwise, Rush will print a warning and install a published package that satisfies the semver range (e.g. **project-b@1.2.1** from NPM).

In practice this works fine when you rely on "rush publish", because it automatically keeps the SemVer ranges in sync.  However, @scsewall recently had a reasonable scenario where he bumps the SemVer ranges manually, and it was confusing to end up with random errors because an old version was getting installed.

@nickpape-msft pointed out that our `cyclicDependencyProjects` feature already provides a way to explicitly opt-in to installing an external version of a local project.  So perhaps we should make this the only way to do it, and instead report an error if Rush encounters an incompatible SemVer range.  (This could be part of `rush check` or `rush install`.)

As part of this change, we could change the option name from `cyclicDependencyProjects`  to something more general like `installedDependencyProjects`.

**Comment by octogonz** [comment]
@zkochan discussed this topic recently  [on Gitter](https://gitter.im/pnpm/pnpm?at=5d2cdb3f4d750532414fd5ba):

> We need some command that will update only dependencies that are inside the workspace.
> When a workspace package references older versions of packages that are in the same workspace, I want to be able to update the deps to use the versions that are available in the repo

**Comment by bsiegel** [comment]
Related: #1385

**Comment by abirmingham** [comment]
I ran into this recently while migrating a repository to use `rush`. In my case I have `apps/a` which depends on `libraries/b@1.0.0`. `libraries/b` is unpublished and is meant to be consumed exclusively by other packages in the repository. I would like to prevent `rush` from ever attempting to fetch `libraries/b` from a registry. My understanding is that `rush` will not do so if `apps/a` specifies a semver-compatible dependency on `libraries/b`, but a non-semver-compatible dependency might be accidentally (or maliciously) introduced. Thanks!

**Comment by octogonz** [comment]
@wanderwang also encountered this today.  This is pretty easy to implement.  Hopefully someone can fix it soon!

**Comment by WanderWang** [comment]
👍

**Comment by octogonz** [comment]
When you specify `useWorkspaces=true` in **rush.json**, this disables the problematic behavior where Rush would magically determine whether to locally linked the project based on its semver range.  

The `useWorkspaces=true` behavior:
- A project is locally linked if-and-only-if the dependency range includes [the `workspace:` specifier](https://pnpm.io/6.x/workspaces#workspace-protocol-workspace) 
  Examples: `"library": "workspace:*"`,  `"library2": "workspace:^1.2.3"`
- If a dependency package exists as a project in the workspace, then Rush avoids accidents by enforcing that you MUST specify `workspace:` UNLESS you have explicitly opted out by adding the dependency to `"cyclicDependencyProjects"` in **rush.json**

This new behavior mostly resolves the original concerns of this GitHub issue.  The only remaining work is:

- Rename the `"cyclicDependencyProjects"`  setting to something more intuitive, since its purpose is now more general than self-dependencies
- Probably we should accept the old name for backwards compatibility until the next major release of Rush

**Comment by octogonz** [comment]
I've updated the issue title accordingly.

**Comment by octogonz** [comment]
@D4N14L and I chatted about this and decided to call the new setting `"decoupledLocalDependencies"`

**Comment by octogonz** [comment]
Update: TikTok will implement this.
