### ISSUE TITLE
[rush] Output is suppressed for scripts run by the "rushPostInstall" event hook

### ISSUE THREAD

**Issue by scsewall** [microsoft/rushstack#553]
scsewall @scsewall 09:30
I just got around to trying the "rushPostInstall" event hook. It worked as advertised (so thanks for the tip), but the output of whatever runs is suppressed. Is there a way to configure the output of the "rushPostInstall" scripts?

pgonzal @pgonzal 10:51
For "rush build" we have "--verbose", since in a large repo the noise is normally very distracting. I'm not sure about "rush install". If not, it would be easy to fix. How would you expect it to work?
A flag? Or simply always show the output?

scsewall @scsewall 12:12
I don't want the noise of a "--verbose" at the "rush install" level. I want the script that runs at "rushPostInstall" to decide what to output and just have that be shown or not depending on that script's options.

pgonzal @pgonzal 13:13
I guess that makes sense, given that you own this script and can make it do whatever you like. Could you open a GitHub issue (or PR)? It's probably not difficult to fix

**Comment by ksjogo** [comment]
Would be interested in this as well.

**Comment by octogonz** [comment]
Could someone propose a design for how this should work?  Should it be a `--verbose` flag?  Should it be done in a config file, separately for each hook? etc.
