### ISSUE TITLE
@microsoft/load-themed-styles 1.7.80 fails build

### ISSUE THREAD

**Issue by bengry** [microsoft/rushstack#782]
`@microsoft/load-themed-styles` version 1.7.80 contains no javascript files, making it useless, and fails build when other tools rely on it.

This can be verified by unarchiving [this zip file](https://registry.npmjs.org/@microsoft/load-themed-styles/-/load-themed-styles-1.7.80.tgz) (direct from npmjs.org) and seeing it has no `lib` nor `lib-amd` folders like previous versions.

**Comment by Vivihung** [comment]
Hit the same issue...

**Comment by pgonzal** [comment]
Thanks for reporting this.

**Comment by pgonzal** [comment]
We also published an empty version of **@microsoft/api-documenter**

**Comment by ADobin** [comment]
@microsoft/loader-load-themed-styles seems empty as well.
