### ISSUE TITLE
[rush] Policies: Enforcing same version number across projects.

### ISSUE THREAD

**Issue by MartynasZilinskas** [microsoft/rushstack#841]
[Rush mono-repo example](https://github.com/simplrjs/react-forms). The same version is used on all packages to keep usage simple. Adding a policy would simplify things.

[React](https://github.com/facebook/react) uses the same versioning convention for their packages.

**Comment by nickpape-msft** [comment]
We have just recently added this: 

https://github.com/Microsoft/web-build-tools/pull/829

This will be in the next version of Rush. For now, you can add a CI step to run `rush check` to ensure that mismatching versions aren't added.

**Comment by pgonzal** [comment]
There's a detailed example here:

https://rushjs.io/pages/maintainer/enabling_ci_builds/
