### ISSUE TITLE
[rush] Rush's node_modules structure is not resolved in vscode correctly

### ISSUE THREAD

**Issue by nfour** [microsoft/rushstack#955]
First up, I'm not sure if this is the right place for this report, but it's likely going to be relevant to the contributers here.

## Problem

My team has run into a curious issue with rush's node module structure and vscode.

When trying to auto-import node modules within a project, intellisense will not locate dependencies.

This also results in the editor's TS server crashing intermittently.

## Reproduction

Rush setups tested:
- v5.5.2 / v5.3.0
- node 6 / node 10
- vscode v1.28.2 / insiders
- with either of: npm, yarn or pnpm (all latest)

You can replicate this issue within `web-build-tools` itself. 

Open https://github.com/Microsoft/web-build-tools/blob/master/libraries/ts-command-line/src/index.ts

And type `Colors` in the top level (from the `colors` module). You shouldn't be able to resolve the symbol.

eg.

```ts

Colors

export {
  CommandLineAction,
  ICommandLineActionOptions
} from './CommandLineAction';
```

## Workaround

If you execute the below script to replace symlinks with real files:
```bash
mv node_modules node_modules_old
rsync node_modules_old/ node_modules/ -a --copy-links -v
```

Everything should work as expected.

**Comment by pgonzal** [comment]
I'm not able to repro this issue.

Which folder do you open using VS Code?  The **libraries/ts-command-line** folder?  Or the root of the repository?

When I type `Colors` it doesn't work, but I think that's expected.  Whereas if I type `import * as colors from 'colors';` and then `colors.`, the IntelliSense works fine.

**Comment by nfour** [comment]
@pgonzal 

Seems like you reproduced it nicely! Expected behaviour is that typing `Colo` should prompt an auto-import autocomplete, or an autofix bubble to add the import statement.

`Colors` is one of the exported types from that library and it shouldn't matter what directory you're in.

**Comment by zomble** [comment]
Corresponding issue in vscode. https://github.com/Microsoft/vscode/issues/63620#issue-383403610

**Comment by pgonzal** [comment]
Great, thanks!

**Comment by pgonzal** [comment]
I marked this as external for now, since it appears to be a problem with VS Code (or TypeScript?).  But we'll keep this issue open to track it.

**Comment by pgonzal** [comment]
@nfour did you try to collect a TS Server log? That might be helpful...

**Comment by nfour** [comment]
@pgonzal I recall not seeing anything in VSCode's TS Server output panel whenever I had these issues. The developer tools console also didn't show anything out of wack. Nor did trying to profile vscode.

I'll check again to be sure though.

**Comment by nfour** [comment]
I want to give an update:
- VSCode@1.33+ no longer spins noticeable CPU cycles with rush `5.5` and `pnpm` 
- Auto-import of arbitrary dependencies still does not work - however - those that are rush linked do indeed show up in import suggestions

**Comment by halfnibble** [comment]
Based off of the last comment here, I think we may need to work with the VSCode team.
https://github.com/microsoft/TypeScript/issues/28689#issue-383403610

**Comment by totomakers** [comment]
Any update for this ?

**Comment by iclanton** [comment]
This issue is stale at this point and https://github.com/microsoft/TypeScript/issues/28689#issue-383403610 is closed. If this is still a problem, please consider opening a new issue
